### ISSUE TITLE
counted_iterator comparison requirements

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#100]
`operator<(const counted_iterator<I1>&, const counted_iterator<I2>&)` is specified to require `Common<I1, I2>()`, as are operators `>`, `<=`, and `>=`; operators `==` and `!=` have no such requirement.

I think the `Common` requirements are insufficient. The true precondition for all binary operations - comparisons and difference - on `counted_iterator`s is that they refer to elements of the same sequence. Two values `i1` and `i2` of (possibly differing) types `counted_iterator<I1>` and `counted_iterator<I2>` refer to elements of the same sequence iff `next(i1.base(), i1.count())` and `next(i2.base(), i2.count())` refer to the same (possibly past-the-end) element.

In other words, given:
```
  int array[] = {0,1,2,3};
  counted_iterator<int*> a{array, 2};
  counted_iterator<int*> b{array, 3};
```
`a` and `b` have the same type. Obviously they meet the current `Common` requirements for the binary operations. Those operations are not well-defined, however, since `a` and `b` do not refer to elements of the same sequence: `a` refers to `0` in the sequence `0, 1` and `b` to `0` in the sequence `0,1,2`.

I think we need a paragraph in [counted.iter.ops] that specifies what it means for `counted_iterator`s to refer to elements of the same sequence, with an example much like the one above. It's non-obvious, necessary so we can refer to it as a precondition for the binary operations, and will hopefully reduce the number of bug reports implementers get about iterators like `a` and `b` returning crazy values from the binary operations.

I'm ambivalent right now about whether the `Common` requirements are useful, but I think they should be consistently present or absent.

**Comment by ericniebler** [comment]
> Two values `i1` and `i2` of (possibly differing) types `counted_iterator<I1>` and `counted_iterator<I2>` refer to elements of the same sequence iff `next(i1.base(), i1.count())` and `next(i2.base(), i2.count())` refer to the same (possibly past-the-end) element.

I know Sean feels this would be too strict. In your `array` example above, there wouldn't seem to be any reason *not* to be able to compare `a` and `b`. A case can be made that they *do* refer to the same sequence: `array`. Although an argument could be made either way, IMO.

The `Common` requirement is admittedly a hack to allow `counted_iterator<int*>` to be comparable with `counted_iterator<const int*>`. I'm not sure if there is a better way to express that. The lack of `Common` on `op==` and `op!=` is simply an oversight.

**Comment by CaseyCarter** [comment]
> I know Sean feels this would be too strict. In your array example above, there wouldn't seem to be any reason not to be able to compare a and b. A case can be made that they do refer to the same sequence: array. Although an argument could be made either way, IMO.

If `a` and `b` are comparable, then presumably `a` and `b + 1` are comparable as well. But then we have `a == b + 1 && *a != *(b + 1)`. Since `*` is not equality preserving, `counted_iterator` does not satisfy `Readable`.

**Comment by CaseyCarter** [comment]
> Since `*` is not equality preserving, `counted_iterator` does not satisfy `Readable`.

Correction: I've assumed here that it's well-defined to dereference both `a` and `b + 1`. This is actually a proof that comparability of `counted_iterator`s with different ends-of-sequence forbids `counted_iterator` to satisfy `ForwardIterator`.

**Comment by ericniebler** [comment]
OK, that's pretty convincing. Funny, that was my original formulation, although I hadn't done the full analysis. And I agree we need semantic constraints on the comparison operators along the lines as you suggest. Thanks.

**Comment by ericniebler** [comment]
Aside: `counted_iterator`'s `op==` and `op!=` have the `Common` requirement in the `<iterator>` synopsis but not in the body of the text. Just an oversight.
