### ISSUE TITLE
Equality preservation of begin(Range) and end(Range)

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#101]
Given a `ForwardRange` lvalue `f`, the multi-pass guarantee for `ForwardIterator` enables me to write e.g,
```
auto b = begin(f);
auto e = end(f);
distance(b, e);
sort(b, e);
reverse(b, e);
```
but the lack of equality preservation for `begin` and `end` means that I cannot equivalently write:
```
distance(f);
sort(f);
reverse(f);
```
which I find unreasonable. Certainly `ForwardRange` should require equality-preserving `begin` and `end`.

I think requiring equality-preserving `end` for `InputRange` should be uncontroversial as well. Without equality-preserving `end`, many of the range algorithms are useless. After `auto i = find(input_range, 42);`, for example, there's no way to continue processing the rest of the range after `i` or even to determine if a `42` was found. If we do not require equality-preserving `end`, algorithms that return an iterator into the range should probably require `ForwardRange` to prevent (silent) programming errors like `if (find(input_range, 42) == end(input_range)) { ... }`.

The argument is not as clear cut for `begin`: `InputRange`s whose state is stored in the range itself can trivially provide equality-preserving `begin`, `InputRange`s whose state is stored in the iterators (e.g., the straightforward implementation of `istream_range<T>` using `istream_iterator<T>`) cannot. Such an `InputRange` must be modified to store an iterator or the equivalent to return from `begin` to provide equality-preservation. Doing so would not be challenging, but it seems wasteful to permanently reserve space in the range object for state that becomes garbage after the first increment of an iterator returned from `begin`. (Requiring `begin` to preserve equality does not change the fact that `InputIterator` is single-pass; `begin` would only be well-defined before the first such iterator increment.)

In light of these considerations, I propose that `ForwardRange` should require `begin` to preserve equality, and `InputRange` should require `end` to preserve equality. I don't think there is currently sufficient motivation for equality-preserving `begin` in `InputRange`, nor for pushing the requirement for equality-preserving `end` down into `Range` itself. I also propose note explaining the subtle consequences of equality-preservation and/or the lack thereof for `begin` and `end` in the descriptions of `InputRange` and `ForwardRange`.

**Comment by ericniebler** [comment]
Agree. Somewhat surprised we don't already have such wording.

**Comment by CaseyCarter** [comment]
Thoughts on `size(SizedRange && InputRange)`? Should we only require it to be well-defined before the first increment of an iterator returned from `begin`?

**Comment by CaseyCarter** [comment]
> I propose that `ForwardRange` should require `begin` to preserve equality, and `InputRange` should require `end` to preserve equality.

As I'm writing the wording:
> Given an lvalue `t` of type `remove_reference_t<T>`, `ForwardRange<T>()` is satisfied if and only if `begin(t)` is equality-preserving.

I realize that I've created a purely semantic distinction between `ForwardRange` and "range whose `begin` returns a `ForwardIterator`." It's of course technically possible to workaround the issue with yet another opt-in or opt-out trait, but it seems silly to complicate the design to allow for ranges that have a `FooIterator` but don't satisfy `FooRange`. I prefer to simply forbid them outright by applying the semantic requirements in `Range` itself that (a) `end` must be equality preserving, and (b) `begin` must be equality preserving if it returns a `ForwardIterator`.

**Comment by ericniebler** [comment]
> forbid them outright by applying the semantic requirements in `Range` itself that (a) `end` must be equality preserving, and (b) `begin` must be equality preserving if it returns a `ForwardIterator`.

I see your point. That's fine by me.

> Thoughts on `size(SizedRange && InputRange)`? Should we only require it to be well-defined before the first increment of an iterator returned from `begin`?

Things get weird here. Merely constructing an `istream_iterator` *can* eagerly read from a stream, for instance. So just calling `begin` a bunch of times on an istream range might invalidate `size` *even without incrementing any iterators*. Perhaps we should say something along the lines that mutating an input range's iterators is potentially a mutating operation on the range itself. `Size` is made invalid by any mutating or non-equality preserving operation on the range. That feels messy to me, though. Thoughts?

**Comment by ericniebler** [comment]
> `Size` is made invalid by any mutating or non-equality preserving operation on the range.

The implication of this is that, if you're planning on calling both `begin` and `size`, you must call `size` *first*.

**Comment by CaseyCarter** [comment]
> That feels messy to me, though.
> The implication of this is that, if you're planning on calling both `begin` and `size`, you must call size *first*.

The note I have now for `Range` indicates clearly that you can only call `begin` once on an `InputRange` since it is not equality preserving and may not even be well-defined to call repeatedly. We may as well reuse those criteria and say that `begin(Range)` may invalidate `size(Range)` as well if `IteratorType<Range>` does not satisfy `ForwardIterator`.
