### ISSUE TITLE
Unimplementable requirements for advance and distance

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#107]
Describing:
```c++
template <Iterator I, Sentinel<I> S>
void advance(I& i, S bound);
```
[iterator.operations]/7 says:
> If `SizedIteratorRange<I,S>()` is satisfied, this function shall dispatch to `advance(i, bound - i)`.

Paragraph 10 similarly requires of:
```c++
template <Iterator I, Sentinel<I> S>
DifferenceType<I> advance(I& i, DifferenceType<I> n, S bound);
```
> If `SizedIteratorRange<I,S>()` is satisfied: ... Otherwise, ...

Paragraph 12 provides a similar requirement for
```c++
template <Iterator I, Sentinel<I> S>
DifferenceType<I> distance(I first, S last);
```
> If `SizedIteratorRange<I,S>()` is satisfied, returns `(last - first)`; otherwise, ...

Since it is not possible for a library implementation to determine if a set of parameters satisfies the non-syntactic requirements of a concept, these requirements are not implementable.

**Comment by CaseyCarter** [comment]
Possible solutions:
* Introduce additional overloads that require `SizedIteratorRange`:
  ```c++
SizedIteratorRange{I, S}
void advance(I& i, S bound);

SizedIteratorRange{I, S}
DifferenceType<I> advance(I& i, DifferenceType<I> n, S bound);

SizedIteratorRange{I, S}
DifferenceType<I> distance(I first, S last);
```
  and similarly for the overloads of `next` and `prev` that are specified to dispatch to `advance`, and any algorithms that may use `advance` or `distance` in their implementations.

* Prohibit `Iterator` / `Sentinel` pairs that meet the syntactic requirements of `SizedIteratorRange` but do not satisfy `SizedIteratorRange`.

**Comment by ericniebler** [comment]
> I don't think the approach is tenable for the algorithms.

I think the correct approach here is to have some text in the library introduction describing what happens when instantiating a template on a type that does not satisfy the requirements: undefined behavior. We would also need to extend this blanket wording to function templates that are specified to use concepts internally to dispatch to optimal implementations.

**Comment by CaseyCarter** [comment]
I greatly prefer a single consistent library-wide requirement for `SizedRange` and `SizedIteratorRange`. Your suggestion implies that we decide at specification time to partition the library into components that may used `SizedRange` / `SizedIteratorRange` in their implementations, and components that may not - restricting implementor freedom. We either specify the partitioning explicitly - increasing specification size and thus cognitive load on readers - or leave it implicit so users must recursively trace requirements through the standard to determine the partitioning.

I think it would save everyone time and trouble if we rename `disable_sized_range` to `disable_sized`, and require users who pass `Range`s or `Sentinel`s to the library that do not satisfy `SizedRange` / `SizedIteratorRange` bit do meet the syntactic requirements to specialize `disable_sized` to `false`.

**Comment by ericniebler** [comment]
> I think it would save everyone time and trouble if we rename `disable_sized_range` to `disable_sized`, and require users who pass `Range`s or `Sentinel`s to the library that do not satisfy `SizedRange` / `SizedIteratorRange` bit do meet the syntactic requirements to specialize `disable_sized` to `false`.

What would the definition of such a `disable_sized` trait look like?

**Comment by CaseyCarter** [comment]
The trait itself would be the same except for the name change; when we made it a pure opt-out trait it became agnostic to the type of the parameter. It's now simply a mapping from type to `bool` that defaults to `false` (which may as well be a variable template, now that I think about it). What *would* be different is the definition of `SizedIteratorRange` to allow opt-out:
```c++
template <class I, class S>
concept bool SizedIteratorRange() {
  return Sentinel<S, I>() &&
    !disable_sized<S>::value &&
    requires (const I i, const S j) {
      { i - i } -> DifferenceType<I>;
      { j - j } -> DifferenceType<I>;
      { i - j } -> DifferenceType<I>;
      { j - i } -> DifferenceType<I>;
    };
}
```
Although it seems a bit hackish that only the sentinel type participates in the determination. I'm convinced that we need a single library-wide requirement, but I'm not certain at this time exactly what that requirement should be. I need to let this gel some more.

**Comment by ericniebler** [comment]
Obviously, sized-ness is not a property of the sentinel only, but of the iterator/sentinel pair. Pressing a single trait into service for this will require a fairly contrived and confusing interface. It requires more thought.
