### ISSUE TITLE
Stable names use [child.parent] rather than [parent.child]

### ISSUE THREAD

**Issue by jwakely** [ericniebler/stl2#109]
The stable section names for new sections in the draft TS use [child.parent] e.g. [readable.iterators] and [movewritable.iterators] are children of [iterators]

The convention in the standard, and the existing sections modified in the draft TS, is [parent.child] (and [parent.child.grandchild]) e.g. [iterators] and [iterators.general], [iterator.requirements] and [iterator.requirements.general] (yes, admittedly, it is inconsistent to have [iterator.xxx] singular below [iterators] plural :-) )

Also, [tuple], with children [tuple.general], [tuple.tuple], [tuple.cnstr], [tuple.assign] etc.

And [vector], with [vector.overview], [vector.cons], [vector.capacity] etc.

**Comment by ericniebler** [comment]
In making this change consistently within the Ranges TS, I'm making it inconsistent with the current standard. See [input.iterators], which -- if we follow [parent.child] -- should be [iterators.input].
