### ISSUE TITLE
Semiregular requirement on the value passed to fill & fill_n

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#121]
The `fill` algorithms require that the value to be filled must satisfy `Semiregular`, e.g.:
```c++
template<Semiregular T, OutputIterator<T> O, Sentinel<O> S>
O fill(O first, S last, const T& value);
```
with effects specified as:
> *Effects:* `fill` assigns `value` through all the iterators in the range `[first,last)`.

It seems to me that these effects are easily achieved without requiring anything of `T`:
```c++
template<class T, OutputIterator<T> O, Sentinel<O> S>
O fill(O first, S last, const T& value) {
  while (first != last) {
    *first = value;
    ++first;
  }
  return first;
}
```
The only use of `T` is the assignment expression `*first = value` which is already constrained by `OutputIterator<O, T>` indirectly though `Writable<I, T>`. I can't imagine an implementation of this algorithm needing to default construct, assign, copy, move, or destroy a `T`. C++14 doesn't require anything of `T` beyond "The expression `value` shall be writable to the output iterator." Is there any reason we shouldn't relax `Semiregular` on these algorithms to `class`?

**Comment by ericniebler** [comment]
> Is there any reason we shouldn't relax `Semiregular` on these algorithms to `class`?

None that I can think of.
