### ISSUE TITLE
Overconstraint on binary search algorithms

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#122]
`lower_bound`, `upper_bound`, `equal_range`, and `binary_search` all require their `value` argument to satisfy `TotallyOrdered`, despite the fact that they never inspect `value` directly - they only pass it to the comparison function. Unless I'm missing something these should all be relaxed to `class T`.

**Comment by ericniebler** [comment]
Thanks, I thought I fixed this ages ago.
