### ISSUE TITLE
min, max, minmax

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#126]
I just finished implementing these, and I wrote up a wording change to (a) default the predicate arguments to `less<>` and remove the overloads without predicate arguments, and (b) relax the requirement on the element type of the overloads that return a copy to `CopyConstructible` instead of `Semiregular`. I'm convinced that (a) is good for consistency with the other algorithms, but I started doubting (b) while typing a pull request.

If the element type is `Copyable`, and copying is "cheap", an implementation can cache elements instead of iterators that denote them. This helps alias analysis a lot, resulting in improved code generation in my cursory investigation: the implementation of `min(Range)` that caches the current minimal element in a temporary is amenable to vectorization with arithmetic element types.

We have three options, as I see it:
1. Use the most relaxed requirement - `CopyConstructible` - that is sufficient for the algorithm, forbidding this optimization.
2. Use the stronger requirement - `Copyable` - so that the optimization is allowed, excluding types that are only `CopyConstructible` from the algorithm.
3. Specify both `CopyConstructible` and `Copyable` overloads for both the `initializer_list` and vanilla-`Range` overloads of `min`, `max`, and `minmax`. This neither excludes types from the algorithm nor optimizations from the implementation at the cost of specification space/time. It also keeps the user/library contract clear: your type must model `CopyConstructible`, and it most not pretend to model `Copyable`.

**Comment by ericniebler** [comment]
My preference is to require `Copyable`.

**Comment by ericniebler** [comment]
> This helps alias analysis a lot, resulting in improved code generation in my cursory investigation

BTW, this is an interesting result. Thanks for doing this analysis.

**Comment by CaseyCarter** [comment]
While I'm poking around in here, is there any reason not to have a projection argument for `min`, `max`, and `minmax`?

**Comment by CaseyCarter** [comment]
Woops, correction: the range overloads require **input** ranges, so they *must* cache elements instead of iterators and hence require `Copyable` (or crazy implementation techniques like caching in an `optional` that is reconstructed instead of assigned). Relaxing the requirement on the element type to `CopyConstructible` would require strengthening the requirement on the range to `Forward`.

**Comment by ericniebler** [comment]
> While I'm poking around in here, is there any reason not to have a projection argument for `min`, `max`, and `minmax`?

I can't think of one ... except that these functions are *so* simple, I hesitate to make them more complicated. But inconsistency with the other algorithms is a complication in and of itself, so they should probably accept projections.

FYI, the paper is already submitted for the pre-meeting mailing.

**Comment by CaseyCarter** [comment]
> But inconsistency with the other algorithms is a complication in and of itself, so they should probably accept projections.

My thought as well. For that reason I implemented projections for `min`, `max`, and `minmax` in caseycarter/cmcstl2@329e80e883139cf7ca5bd9b997aeba464aec5a93. I'll write up some wording.
