### ISSUE TITLE
Standard iterator adaptors should provide operator-> if their underlying iterator does

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#13]
Like reverse_iterator. No need for operator-> to be in the iterator concepts. There can be magic SFINAE prose to remove reverse_iterator::operator-> when it can't be easily supported.

**Comment by asutton** [comment]
Operator-> is weird... It can be a requirement imposed by an algorithm
using that notation, but it can't be part of the iterator concepts
themselves because it's conditional -- only required if the value type
is a class type.

Andrew Sutton

**Comment by ericniebler** [comment]
Allocator traits are defined in terms of randomaccessiterator to get operator->

**Comment by ericniebler** [comment]
`operator->` causes implementation complexity for iterators that return rvalues, but nothing that can't be worked around with some clever hackery. One issue is whether the concept should require the hackery. The room generally felt that no, it should not. Another question is whether the iterator adaptors should provide `operator->` when "it makes sense to," and the feeling is yes, they should. I'll come up with wording.
