### ISSUE TITLE
"is equal to v is unchanged"

### ISSUE THREAD

**Issue by jwakely** [ericniebler/stl2#133]
P0021R0 19.4.5 [concepts.lib.object.copyconstructible] p1 (1.2) has some dangling text, maybe vestigial

> — `T{v}` or `*new T{v}` is equal to `v` is unchanged.

https://github.com/ericniebler/stl2/blob/master/concepts.tex#L824

**Comment by CaseyCarter** [comment]
I was going to claim blame for this, but it was the markup update in 814126d43ec6249171a94919b73b115cb825c1d5 - I blame the project editor!

**Comment by ericniebler** [comment]
:-P
