### ISSUE TITLE
Iterator/Range Ambiguity

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#145]
Any pair of overloads that differs in a single argument such that one overload requires `FooIterator` and the other `BarRange` needs disambiguation - arrays are both (undecayed) ranges and (decayed) iterators. Arrays make better ranges than iterators due to being statically sized, so we want the range overload to be preferred.

- [x] Determine the best way to specify the disambiguation, whether it be explicitly specifying additional requirements, or an implicit blanket requirement that any such occurrences of ambiguity must be resolved in favor of the range overload when applicable.
- [x] If the decision is to explicitly specify requirements, audit the algorithms for all such occurrences.
- [x] Write wording for the chosen disambiguation solution.

**Comment by ericniebler** [comment]
I believe in my original range proposal, I called this out as a potential problem for implementors. It's certainly something I've had to work around in range v3. It can't be fixed by simply adding extra requirements. It actually requires taking iterators by forwarding reference in the places where ambiguity can occur. I would prefer some blanket wording.

**Comment by CaseyCarter** [comment]
I know you're aware if of the issue; I just fixed an occurrence in cmcstl2 and I thought we should have an action item somewhere so we don't forget to address it in the TS. I should have said "modifying the declarations so the ambiguity does not exist" instead of "additional requirements."

We also need to decide if "blanket wording" should only cover the array case or if it should be a general rule to prefer the range overload when it's viable. Nothing in the requirements precludes a user type satisfying both `Range` and `Iterator`; we need to either include or forbid such a thing deliberately.

**Comment by ericniebler** [comment]
My personal preference is to only prefer the range overload only for arrays; otherwise, it is and should be ambiguous. Anybody who designs a type that is both an iterator and a range should have their hand slapped.

**Comment by CaseyCarter** [comment]
So you're suggesting this type:
```c++
struct A {
  using value_type = A;
  using difference_type = int;
  using iterator_category = ranges::input_iterator_tag;

  A operator*() const;
  A& operator++();
  A operator++(int);

  friend bool operator==(A, A);
  friend bool operator!=(A, A);

  A begin();
  A end();
};
```
may not be well designed? ;)

**Comment by ericniebler** [comment]
Indeed, I am. I'm a killjoy, I know.
