### ISSUE TITLE
Validity of references obtained from out-of-lifetime iterators

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#156]
### Summary
By removing the requirement in C++14 [forward.iterators]/6:

> If `a` and `b` are both dereferenceable, then `a == b` if and only if `*a` and `*b` are bound to the same object.

the Ranges TS inadvertently allows "stashing" forward iterators, which notoriously break `reverse_iterator` and e.g. `return *(some_local_iterator + 4)`.

### Detailed discussion

Iterators that return a reference to a member object are known as "stashing" iterators - `istream_iterator` is the classic example. They famously do not work with `reverse_iterator`, since they violate [forward.iterators]/6:

> If `a` and `b` are both dereferenceable, then `a == b` if and only if `*a` and `*b` are bound to the same object.

3efd5da3271a6778ce54aaa0f766d4191455dec4 "various concept tweaks" committed June 1 changed this requirement in the TS to:

``` tex
If \tcode{a} and \tcode{b} are both dereferenceable, then \tcode{a == b} if and only if
\tcode{*a} is equal to \tcode{*b}.
```

So that the requirement has well-defined meaning when `*a` and `*b` are not objects. 

5578feee5e6538055e66d42e24afe559be930aa0 "Language for equality-preserving-by-default expressions" committed July 3 removed the requirement completely, since
- `*a == *b` if `a == b` is implied by the equality preservation of `*` from `Readable`, and
- `a == b` if `*a == *b` requires that a value appears at most once in any given range, which was not intended.

I believe the TS wording now allows "stashing" iterators to satisfy `Forward`, despite that many reasonable operations simply don't work with them. Iterators _denote_ elements, they must not _own_ them: the expectation is that the lifetime of denoted object elements is the lifetime of the range, _not_ the lifetime of the iterator. We need to bring back a requirement that forbids "stashing" `Forward` iterators. This should cause no hardship to TS users since `Forward` iterators can have prvalue types.

Proxy reference types make it challenging to develop a simple requirement; the straightforward "If `reference_t<I>` is a reference type, then `&*a == &*b` iff `a == b`" doesn't work. The high-level wording "If iterator values denote objects, then `a == b` iff `a` and `b` denote the same object." seems clearer to me, but I'm accustomed to thinking of iterators as either denoting objects or denoting values. I'm not sure someone coming straight to the TS from C++14 would understand. I also don't think the "If..dereferenceable" qualifier since (a) past-the-end iterators denote the same past-the-end object, and  (b) singular iterators won't be in the domain of `==` and can therefore do anything they like.

### Proposed Resolution

Add a new paragraph to section "Concept `ForwardIterator`" ([iterators.forward]) after paragraph 4:

> 5. Pointers and references obtained from a forward iterator into a range `[i, s)` must remain valid while `[i, s)` continues to denote a range.

**Comment by ericniebler** [comment]
> I believe the TS wording now allows "stashing" iterators to satisfy `Forward`, despite that many reasonable operations simply don't work with them.

Yikes!

> Proxy reference types make it challenging to develop a simple requirement

Technically, we haven't integrated the proxy paper yet. Proxy is only permissible for input iterators, where it's also OK to have a stashing iterator. But I prefer a forward-looking solution that makes forward proxy iterators OK.

> The high-level wording "If iterator values denote objects, then `a == b` iff `a` and `b` denote the same object."

Does a prvalue not denote an object then? I would be fine with this wording. When I integrate the proxy iterators paper, I'll need to specify what it means for a proxy reference to denote an object.

**Comment by CaseyCarter** [comment]
> I prefer a forward-looking solution that makes forward proxy iterators OK.

Yes, that's the intent. I should have made that explicit for readers other than you and I.

> Does a prvalue not denote an object then?

If you have to ask, the wording needs to be improved. The mental model I'm using here is that "elements" are either objects or values, but I'm now realizing that model is too weak. `vector<bool>::iterator` certainly does not "denote an object", but it does denote a value stored in memory.

What we really need to specify are requirements on the validity of references. If `[i, s)` denotes an `InputRange` and I bind a reference - proxy or otherwise - with `auto&& v = *i;`, I expect that reference to remain valid until I increment an iterator equal to `i` or somehow invalidate the range. If `[i, s)` denotes a `ForwardRange`, I expect the reference to remain valid while the range is valid.

I would like to require that "Two WeakIterators are equal iff they denote the same element," but I'm not sure that "same element" has a well-defined meaning, let alone how to specify it.

**Comment by CaseyCarter** [comment]
Maybe "elements" are notional entities that hold values but are not necessarily objects. That definition makes it clear that two iterators that denote the same element must dereference to the same value, and that modifying the value of a mutable element must be observable to other iterators that denote the same element. It doesn't forbid stashing iterators for ranges of immutable elements, though, and seems to imply that `istream_iterator` shouldn't be using a `const T&` for its reference type since copies of the same iterator don't reference the same object.

**Comment by CaseyCarter** [comment]
> seems to imply that istream_iterator shouldn't be using a const T& for its reference type since copies of the same iterator don't reference the same object

This is fixable by splitting into two requirements:
* Equal WeakIterators denote equal elements
* ForwardIterators are equal iff they denote the same element

Which is just dandy, but doesn't provide guarantees for the validity of references.

In an ideal design, reference validity would be exactly equivalent to the dereferenceability of iterator *values*, and "equal iff they denote the same element" would apply to WeakIterators. It should be valid to capture a reference to `*i` if `i` is dereferenceable, and continue to use that reference while `i`'s value remains dereferenceable. This should work:
```c++
// Pre: [in, s) denotes a range (generally implicit)
void f(InputIterator in, Sentinel<I> s) {
  if (in != s) {
    auto in2 = in;
    auto&& ref = *in2;
    in2 = {}; // no effect on the value of in
    assert(ref == *in); // never fires
    ++in; // invalidates old value of in, and therefore ref
  }
}
```
and this:
```c++
// Pre: out is dereferenceable
void g(WeakOutputIterator<int> out) {
  auto out2 = out;
  auto&& ref = *out2;
  out2 = {};
  ref = 42; // invalidates value of out, and therefore ref
}
```
if for no other reason than consistency with the intuitive notion of what "dereferenceable" means. Stashing iterators hold/own/are elements; they break the model that iterators *denote* elements. How do you suppose the committee would respond to us breaking stashing iterators completely in order to have consistent semantics?

**Comment by CaseyCarter** [comment]
I should point out the critical difference between *stashing* iterators, which when dereferenced return a reference to a member object, and *caching* iterators which when dereferenced return the value of a member object. Caching iterators fit the dereferenceability semantics perfectly, since `auto&& ref = *i;` results in a lifetime-extended temporary that is valid for the lifetime of the "reference."

The demand for stashing iterators is also much lower in the Ranges design than in that of the standard. Ranges and views provide a convenient place to store state that is heavy enough for copying to be a concern. An `istream_range`, for example, could cache the current value for its iterators, or use an adaptive design like my implementation of `repeat_view` that caches values in the iterator when they are small enough for copying not to be a concern and in the view when they are not.

**Comment by ericniebler** [comment]
> How do you suppose the committee would respond to us breaking stashing iterators completely in order to have consistent semantics?

Well, stashing iterators are already broken, unless you mean for input iterators as well as forward. I think breaking `istream_iterator` is a problem. Returning by value is a possible fix, but it incurs a perf hit. Going back to my blog post on `getline`, it means that there is no efficient range-base replacement, which is a problem. http://ericniebler.com/2013/10/13/out-parameters-vs-move-semantics/

**Comment by CaseyCarter** [comment]
Yes, I mean breaking stashing for all categories. Returning by value would obviously be undesirable when values are "big," but is at least as fast as returning by reference when values are "small." The efficient range-based replacement is something like [`istream_range`, which heuristically determines which value types are "big" or "small"](https://gist.github.com/CaseyCarter/9d00256c4042556f7284). It results in equivalent assembly in inner loops as similar code using `istream_iterator` for the simple cases I've examined.

Unless I'm missing something, and admittedly I haven't had time to investigate thoroughly, we can have consistent semantics that forbid stashing iterators without losing performance.

**Comment by ericniebler** [comment]
Should be resolved together with #226, which also needs a characterization of proxy references.

**Comment by CaseyCarter** [comment]
My dislike for stashing iterators aside, we have a fairly serious flaw in the design. We've inherited N4606 [iterator.requirements]/10:

> Destruction of an iterator may invalidate pointers and references previously obtained from that iterator.

but not the mitigating requirement from N4606 [forward.iterators]/6:

> If `a` and `b` are both dereferenceable, then `a == b` if and only if `*a` and `*b` are bound to the same object.

Without the "bound to the same object" requirement, references may be invalidated by iterator destruction. `reverse_iterator::operator*` is affected, as is anything that returns a reference obtained from a temporary iterator.

**Comment by CaseyCarter** [comment]
From #244, discussing `move_iterator::operator[]`:

> We forgot that `i[n]` should be changed to return `iter_move(i + n)`. Considering that the `op*` change was approved, I consider the corresponding change to `op[]` to be editorial/approved in principle.

It should be noted that `iter_move(i + n)` may return a reference that is no longer valid after the temporary `i + n` is destroyed; returning such a reference from `move_iterator::operator[]` is morally equivalent to returning a dangling reference from `reverse_iterator::operator*`.

**Comment by Peregring-lk** [comment]
> Iterators denote elements, they must not own them: the expectation is that the lifetime of denoted object elements is the lifetime of the range, not the lifetime of the iterator. We need to bring back a requirement that forbids "stashing" Forward iterators.

I'm right now implementing a stashing iterator for Qt, and my iterator stores a QModelIndex wrapper which overloads `operator=` to call `setData` on the `QAbstractItemModel`, because Qt models doesn't offer references to the contents of the model.

The iterator owns the wrapper, and thus it's a stashing iterator, that's true, but the lifetime of the denoted element (the Qt model position) survives to each iterator, because the "underlying sequence" is not stored on the iterator, but on the model. What the "range" stores is not the sequence, but its witnesses.

So, I agree with your first part of the sentence, the iterator shall not own the element, but not the second: a stashing iterator always owns the element. It own the `value_type` in my case, but the range of `value_type` are not the values/objects/positions you are really manipulating, which is different.

**Comment by ericniebler** [comment]
@CaseyCarter I think the language we've been beating on for #398 could help here. I think we want to say that for forward iterators, mutating the iterator shouldn't mutate references obtained from the iterator. Yes?

**Comment by ericniebler** [comment]
Proposed Resolution (suggestion):
--------------------

In section "Concept ForwardIterator" ([iterators.forward]), add:

> 4. Destruction of a forward iterator may not invalidate pointers and references previously obtained from that iterator.

**Comment by CaseyCarter** [comment]
To forbid stashing, we need to require that *modification* - including destruction - of an iterator does not invalidate pointers and references previously obtained from that iterator.

This immediately begs the question of what events *do* invalidate references and pointers obtained from a forward iterator - which is likely what we should be specifying instead. We want to tie validity to the validity of the range, something like "Pointers and references obtained from a forward iterator into a range `[i, s)` must remain valid while `[i, s)` continues to denote a range."

**Comment by CaseyCarter** [comment]
Also, if we forbid stashing, we will break `path::iterator`. Well, not "break," so much as "leave broken": `path::iterator` is all but required to stash.

**Comment by ericniebler** [comment]
> "Pointers and references obtained from a forward iterator into a range `[i, s)` must remain valid while `[i, s)` continues to denote a range."

That works for me.

**Comment by ericniebler** [comment]
> Also, if we forbid stashing, we will break `path::iterator`. Well, not "break," so much as "leave broken": `path::iterator` is all but required to stash.

Not my fault. /me points at @Beman.

**Comment by CaseyCarter** [comment]
I suppose you could avoid stashing if the representation of `path` is a container of `path`. I wonder if that's sane.

**Comment by ericniebler** [comment]
I suspect it's a hard problem or it would have been solved by now. It would be interesting to look deeper and understand what the issue is there.
