### ISSUE TITLE
Wrapping iterator/sentinel ranges with move_iterator

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#159]
In C++14, if I have a range of input iterators from which I would like an algorithm to move, I wrap the iterators in `move_iterator`:
```c++
template <class InputIterator>
void foo(InputIterator first, InputIterator last) {
  bar(make_move_iterator(first), make_move_iterator(last));
}
```

In the Ranges design, an input range is denoted by an input iterator and a sentinel:
```c++
template <InputIterator I, Sentinel<I> S>
void foo(I first, S last) {
  bar(make_move_iterator(first), ???);
}
```
What do I pass to `bar` to denote the end of the range? `make_move_iterator(next(first, last))` isn't usable if the range is single-pass. I see potential two solutions:

1. Define a `move_sentinel<S>` wrapper class that satisfies `Sentinel<move_sentinel<S>, move_iterator<I>>()` when `Sentinel<S, I>()` is satisfied. Add a `make_move_sentinel` helper function for ease-of-use. This approach maintains a clear distinction between the adapted range and the underlying range. I define `foo` as:
  ```c++
  template <InputIterator I, Sentinel<I> S>
  void foo(I first, S last) {
    bar(make_move_iterator(first), make_move_sentinel(last));
  }
 ```

2. Define `==` / `!=` overloads for `move_iterator<I>` and `Sentinel<I>` so that move iterators can use the same sentinels as their base iterators:

  ```c++
  Sentinel{S, I}
  bool operator==(const move_iterator<I>& i, const S& s) {
    return i.current_ == s;
  }
  // Define != similarly, and the symmetric overloads.
  ```

  `foo` is simpler since it passes the sentinel directly:

  ```c++
  template <InputIterator I, Sentinel<I> S>
  void foo(I first, S last) {
    bar(make_move_iterator(first), last);
  }
  ```

3. (Yes, I know I said two solutions - sue me) Ignore the problem until TS2, where the solution will be something like:

  ```c++
  template <InputIterator I, Sentinel<I> S>
  void foo(I first, S last) {
    bar(view::move(make_view(first, last));
  }
  ```

I'm inclined toward the second approach, since it can solve the problem now and involves the least effort to use and specify.

**Comment by ericniebler** [comment]
If we have these:

```c++
Sentinel{S, I}
bool operator==(const move_iterator<I>& i, const S& s);
Sentinel{S, I}
bool operator==(const S& s, const move_iterator<I>& i);
```

Then won't `i==i` be ambiguous when `i` is a `move_iterator`? There's a strange loopiness here. The `Sentinel{S,I}` check will try to use the `op==` currently begin defined. It'll fail for the first overload since it hasn't been seen yet, but for the second overload, it'll consider the first (but not the second). I dunno what the implications are. This makes me uncomfortable. Thoughts?

**Comment by CaseyCarter** [comment]
If the base iterator has an `==` operator, the `operator==(move_iterator, move_iterator)` overload is more specialized and hence selected by overload resolution for `move_iterator<I> == move_iterator<I>`. If the base iterator does not have an `==` operator, it's not an issue if these overloads are ambiguous when specialized for `move_iterator, move_iterator` because overload resolution is intended to fail.

Test code at caseycarter/cmcstl2@293743f59a1003bd55e502bfa9552463c644c1c0 demonstrates these facts.

**Comment by CaseyCarter** [comment]
> but for the second overload, it'll consider the first

...and we've already established that the first overload is not viable.

**Comment by CaseyCarter** [comment]
Implementation has led me to discover the flaw in the "just use the sentinel directly" approach: an underconstrained `op==` template on the sentinel type in test_iterators.hpp is ambiguous with the move_iterator overloads. Wrapping in a `move_sentinel` obviously averts this issue.

**Comment by ericniebler** [comment]
It was setting off my "too-clever" detector; I'm not too surprised. ;-)
