### ISSUE TITLE
Should input/output iterators be allowed to be move-only?

### ISSUE THREAD

**Issue by NicolBolas** [ericniebler/stl2#164]
I know the current suite of iterators for C++14 requires input/output iterators to have postfix `operator++`, which effectively requires the ability to copy such iterators. But having such iterators be move-only could be useful for various safety reasons.

Would it be feasible for the Ranges TS to define its input/outout iterator requirements to not require iterator copying? I know this would restrict implementations, but I'm not sure how they would be able to make use of such copies when input/output iterator copies cannot be used after one of them is incremented.

**Comment by ericniebler** [comment]
It has been brought up in committee many times. Too much code depends on the `Regular`ity of iterators to make this change feasible.
