### ISSUE TITLE
ConvertibleTo should require both implicit and explicit conversion

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#167]
Currently, `ConvertibleTo` checks only for _implicit_ convertibility (a-la `is_convertible`). It would be highly surprising for generic code for an _explicit_ conversion to fail, or to succeed but yield a different result.

### Proposed Resolution

(Also fixes #314.)

Replace the contents of [concepts.lib.corelang.convertibleto] with:

> ```c++
> template <class From, class To>
> concept bool ConvertibleTo() {
>   return is_convertible<From, To>::value &&
>     requires (From (&f)()) {
>       static_cast<To>(f());
>     };
> }
> ```
> 
> 1 Let `test` be the invented function:
> ```c++
> To test(From (&f)()) {
>   return f();
> }
> ```
> and let `f` be a function with no arguments and return type `From` such that `f()` is equality preserving. Then `ConvertibleTo<From, To>()` is satisfied if and only if:
>
> > (1.1) - `To` is not an object or reference-to-object type, or `static_cast<To>(f())` is equal to `test(f)`.
> >  (1.2) - `From` is not a reference-to-object type, or
> > > (1.2.1) - If `From` is an rvalue reference to a non `const`-qualified type, the resulting state of the object referenced by `f()` after either above expression is valid but unspecified ([lib.types.movedfrom]).
> > > (1.2.2) - Otherwise, the object referred to by `f()` is not modified by either above expression.
>
>2 There need not be any subsumption relationship between `ConvertibleTo<From, To>()`
>  and `is_convertible<From, To>::value`.

**Comment by ericniebler** [comment]
Why is it not enough to have just one concept, `ConvertibleTo`, that is satisfied only when the type is both explicitly and implicitly convertible, with identical semantics?

**Comment by CaseyCarter** [comment]
That works for everything in the TS except `Common` and `CommonReference`, which have previously required only explicit conversion.

The biggest potential issue I see is that we first have to decide what "implicitly convertible" and "explicitly convertible" mean. I've been using `is_convertible`'s definition for implicit conversion ([meta.rel]):

> 5 The predicate condition for a template specialization `is_convertible<From, To>` shall be satisfied if and only if the return expression in the following code would be well-formed, including any implicit conversions to the return type of the function:
>
> ```c++
> To test() {
>   return declval<From>();
> }
> ```

which doesn't exactly agree with the core language's definition ([conv]):

> 3 An expression `e` can be *implicitly converted* to a type `T` if and only if the declaration `T t=e;` is well-formed, for some invented temporary variable `t` (8.6).

most notably when the source and target type are both `void`.

I've been using `static_cast<To>(declval<From>())` to model explicit conversion, but functional cast notation (`To(declval<From>())`) as in the definitions of `Common` & `CommonReference` is probably more appropriate.

I suspect that we will need more variations of "convertible" for characterizing the rest of the library, at which time we may wish we had names for the "implicit" and "explicit" parts of `ConvertibleTo` so we can reuse them individually. There will be some redesign when we tackle conditionally-explicit converting constructors for wrapper types and how to discriminate between conversions that do and do not require narrowing. I'm sure there's at least one paper to write here, but not one that we want to write now.

Barring further work, I propose we define `ConvertibleTo` as:
> ```c++
> template <class From, class To>
> concept bool ConvertibleTo() {
>   return is_convertible<From, To>::value && requires(From&& from) {
>     To(std::forward<From>(from));
>   };
> }
> ```
> 
> Let `test` be the invented function:
> ```c++
> To test(From&& from) {
>   return std::forward<From>(from);
> }
> ```
> and let `E` be an expression such that `decltype(E)` is `From`. Then `ConvertibleTo<From, To>()` is satisfied if and only if:
> * `test(E)` is equality preserving
> * `To(E)` equals `test(E)`

**Comment by ericniebler** [comment]
> I suspect that we will need more variations of "convertible" for characterizing the rest of the library, at which time we may wish we had names for the "implicit" and "explicit" parts of `ConvertibleTo` so we can reuse them individually.

I suggest crossing that bridge when we come to it.

> Barring further work, I propose we define `ConvertibleTo` as:
> ```c++
> template <class From, class To>
> concept bool ConvertibleTo() {
>   return is_convertible<From, To>::value && requires(From&& from) {
>     To(std::forward<From>(from));
>   };
> }
> ```

So, `ConvertibleTo<void,void>()` is not satisfied?

How about?

```c++
template <class From, class To>
concept bool ConvertibleTo() {
  return is_convertible<From, To>::value && requires(From (&from)()) {
    To(from());
  };
}
```

**Comment by CaseyCarter** [comment]
>So, `ConvertibleTo<void,void>()` is not satisfied?

I should have stopped at `To(declval<From>())`.

**Comment by ericniebler** [comment]
Ship it!

**Comment by ericniebler** [comment]
We have decided that function-style casts are bad and lead to surprising behavior (`ConvertibleTo<int&,long&>()`). This resolution needs to be changed to a `static_cast`.

**Comment by ericniebler** [comment]
Added:

> * If `From` is `const`, an lvalue reference type, or a const rvalue reference type, neither of the expressions `static_cast<To>(f())` and `test(f)` shall modify the value of the object referred to by the expression `f()`. Otherwise, the resulting state of the object referred to by `f()` is unspecified. [ _Note:_ It must still meet the requirements of the library component that is using it. The operations listed in those requirements must work as specified whether the has been moved from or not. --_end note_ ]

@CaseyCarter for your review.

**Comment by CaseyCarter** [comment]
> EDIT: is it the case that non-modification is the default, and I only need to call out the cases where modification is permitted? If so, I can simplify this.

Expressions that appear in *requires-expressions* that have `const` operands *by default* do not modify those operands.  In the PR, that means that `static_cast<To>(f())` does not modify `f()` if `From` is `const` or a reference to `const`.

**Comment by ericniebler** [comment]
... but we have to say explicitly that `f()` is not modified if its type is a non-`const` lvalue reference?

**Comment by CaseyCarter** [comment]
`ConvertibleTo<void, void>()` needs to work. so this needs a "`To` is `void` or ..." in front.

**Comment by CaseyCarter** [comment]
> ... but we have to say explicitly that f() is not modified if its type is a non-const lvalue reference?

Yes.

**Comment by ericniebler** [comment]
Updated proposed resolution. How about now?

**Comment by CaseyCarter** [comment]
`is_convertible` accepts complete types, arrays of unknown bound, and `void`. `ConvertibleTo` should as well. How about:

`ConvertibleTo<From, To>()` is satisfied if and only if:
 * `To` is not an object or reference-to-object type, or `static_cast<To>(f())` is equal to `test(f)`.
 * `From` is not a reference-to-object type, or
   * If `From` is an rvalue reference to a `const`-qualified type, the resulting state of the object referred to by `f()` after either above expression is unspecified. [ _Note:_ It must still meet the requirements of the library component that is using it. The operations listed in those requirements must work as specified whether the object has been moved from or not. --_end note_ ].
   * Otherwise, the object referred to by `f()` is not modified by either above expression.

**Comment by ericniebler** [comment]
> If `From` is an rvalue reference to a `const`-qualified type

If `From` is an rvalue reference to a _non_-`const`-qualified type

**Comment by ericniebler** [comment]
Resolution edited to hide the subsumption relationship with the trait.

**Comment by CaseyCarter** [comment]
Resolution edited per LWG Kona feedback:

1. Use "There need not be any subsumption..." wording

2. Use "valid but unspecified" and cite C++14 [lib.types.movedfrom].
