### ISSUE TITLE
s/newtxt/added/g, s/oldtxt//g, s/oldoldtxt/removed/g

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#169]
The current draft has gotten a bit out of control with the diff markings. Before any additional changes are made, IMO we should turn all gold text blue, and purple text should be deleted or turn red as appropriate. At least in the parts that have already been reviewed.

**Comment by CaseyCarter** [comment]
We reviewed all of 24.2 (Iterator Requirements) in Jacksonville. I'm going to remove all markup from the section and perform the changes discussed with fresh markup.

Are there other portions of the document that have had review without the consequent markup updates?

**Comment by CaseyCarter** [comment]
Fixed by #213.
