### ISSUE TITLE
common_type<Iterator I, Sentinel<I>> !!!

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#17]

**Comment by ericniebler** [comment]
This seemingly good idea is actually impossible to implement AFAICT. `Sentinel<I> S` implies `EqualityComparable<I, S>`, which implies `Common<I, S>`, which requires the instantiation of `common_type` that is currently being constrained. That's recursive on all paths.

**Comment by CaseyCarter** [comment]
This is fixable. Define WeaklyEqualityComparable:
>```
template<class T, class U>
concept bool WeaklyEqualityComparable =
  EqualityComparable<T>() && EqualityComparable<U>() &&
  requires(T t, U u) {
    { t == u } -> Boolean;
    { t != u } -> Boolean;
    { u == t } -> Boolean;
    { u != t } -> Boolean;
  };
```
Given objects `t1` and `t2` of type `T` and `u1` and `u2` of type `U`, types `T` and `U` model `WeaklyEqualityComparable` if and only if:
* `(bool(t1 == u1) == bool(u1 == t1)) != false` [`==` is symmetric with respect to `T` and `U`]
* `(bool(u1 != t1) == bool(t1 != u1)) != false` [`!=` is symmetric with respect to `T` and `U`]
* `(bool(t1 != u1) == !bool(t1 == u1)) != false` [`!=` is the complement of `==`]
* `((bool(t1 == u1) && bool(t1 == t2)) == bool(t2 == u1)) != false` [`==` of `T` and `U` respects `T`'s `==`]
* `((bool(t1 == u1) && bool(u1 == u2)) == bool(t1 == u2)) != false` [`==` of `T` and `U` respects `U`'s `==`]
```
and Sentinel:
>```
template<class S, class I>
concept bool Sentinel =
  Iterator<I> &&
  Regular<S> &&
  WeaklyEqualityComparable<I, S>;
```
and the common type:
>```
template<class I, Sentinel<I> S>
struct common_type<I, S> { using type = common_iterator<I, S>; };
template<class S, class I>
  requires Sentinel<S, I>
struct common_type<S, I> { using type = common_iterator<I, S>; };
```
then `I` and `S` (and by symmetry `S` and `I`) model `EqualityComparable` by construction. This is actually true of any pair of types that model  `WeaklyEqualityComparable`: once we have cross-type `==` that respects `==` of both `T` and `U`, we can construct a common type.

Given that (a) people have been complaining about the comparison concepts requiring `Common`, and (b) you had to define WeaklyEqualityComparable non-normatively anyway for `common_iterator`, it seems we way as well make it normative and useful?

**Comment by CaseyCarter** [comment]
There's an underlying pattern here: this is the same way that `std::optional<T>` works. `std::optional<T>` is the common type of `T` and `std::nullopt`. Any sum type with an `==` that respects the `==` of the constituent types is a common type for the constituents.

**Comment by CaseyCarter** [comment]
Oh, and of course `EqualityComparable` becomes:
```
template<class T, class U>
concept bool EqualityComparable() {
  return WeaklyEqualityComparable<T, U>() &&
    Common<T, U>;
}
```
Although its meaning changes to something like "the types `T` and `U` are `WeaklyEqualityComparable` and the operators `==` and `!=` on `std::common_type<T, U>::type` are consistent with the equivalent operators applied directly on `T` and `U`."

**Comment by ericniebler** [comment]
OK, I'll take another look at the issue. I get nervous monkeying with `Common` and `EqualityComparable` since they're so fundamental, and since they have Alex's fingerprints all over them. ;-)

**Comment by CaseyCarter** [comment]
I don't buy your argument - Stepanov's algorithms take iterators of the same type. You're already a heretic ;) I started a separate issue since "Should we relax fundamental concepts?" is a very different question from "Should we define `common_iterator<I, Sentinel<I>>`?"

**Comment by ericniebler** [comment]
The reference implementation now has these:

```c++
template <Iterator I, Regular S>
  requires !_Valid<__cond, I, S> && ext::WeaklyEqualityComparable<I,S>()
struct common_type<I, S> {
  using type = common_iterator<I, S>;
};

template <Regular S, Iterator I>
  requires !_Valid<__cond, I, S> && ext::WeaklyEqualityComparable<I,S>()
struct common_type<S, I> {
  using type = common_iterator<I, S>;
};
```

**Comment by CaseyCarter** [comment]
> The reference implementation now has these

These specializations are now implemented as:

```c++
  template <class I, class S>
    requires !_Valid<__cond, I, S> && _Valid<common_iterator, I, S>
  struct common_type<I, S> {
    using type = common_iterator<I, S>;
  };

  template <class S, class I>
    requires !_Valid<__cond, I, S> && _Valid<common_iterator, I, S>
  struct common_type<S, I> {
    using type = common_iterator<I, S>;
  };
```
which (a) avoids duplication of the `common_iterator` requirements, and (b) avoids checking those requirements when `(true ? declval<I>() : declval<S>())` is valid. This is necessary to allow e.g. `common_type<T*,T*>` to work with incomplete type `T`. If we decide to specify this `common_type` partial specialization, we'll need to word it carefully.

**Comment by ericniebler** [comment]
I'm now fairly convinced that this approach is fundamentally flawed. The following code causes a recursive instantiation of `common_type<back_insert_iterator<std::vector<int>>, int>`.

```c++
#include <vector>
#include <stl2/detail/fwd.hpp>
#include <stl2/detail/iterator/concepts.hpp>

STL2_OPEN_NAMESPACE {
  template <class S, class I>
  concept bool __WeakSentinel =
    Iterator<I>() && Regular<S>() &&
    ext::WeaklyEqualityComparable<I, S>();

  template <InputIterator I, __WeakSentinel<I> S>
    requires !Same<I, S>()
  class common_iterator;

  // Not to spec: extension
  template <InputIterator I, class S>
    requires !_Valid<__cond, I, S> && __WeakSentinel<S, I>
  struct common_type<I, S> {
    using type = common_iterator<I, S>;
  };

  template <class S, InputIterator I>
    requires !_Valid<__cond, I, S> && __WeakSentinel<S, I>
  struct common_type<S, I> {
    using type = common_iterator<I, S>;
  };

  template <class Container>
  class back_insert_iterator {
  public:
    using difference_type = std::ptrdiff_t;
    using value_type = typename Container::value_type;
    constexpr back_insert_iterator() = default;

    const back_insert_iterator& operator*() const;

    const back_insert_iterator& operator++() const;

    const back_insert_iterator& operator++(int) const;

    const back_insert_iterator&
    operator=(const value_type& value) const &;
    
    const back_insert_iterator&
    operator=(value_type&& value) const &;
  };
} STL2_CLOSE_NAMESPACE

namespace stl2 = __stl2;

stl2::common_type<
  stl2::back_insert_iterator<std::vector<int>>,
  int
> u;

int main() {}
```

The trouble is that while picking the specialization of `common_type<back_insert_iterator<std::vector<int>>, int>`, an attempt is made to satisfy `InputIterator<back_insert_iterator<std::vector<int>>`. Since the reference type of `back_insert_iterator<X>` is `const back_insert_iterator<X>&`, the `Readable` concept test for `CommonReference<const back_insert_iterator<std::vector<int>>&, int&>`, which eventually re-dispatches to `common_type<back_insert_iterator<std::vector<int>>, int>`, causing a hard error.

I would very much like cmcstl2 to follow the spec and not try to define a generic `common_type<Iterator, Sentinel>` specialization. The implications are too hard to fathom.

**Comment by CaseyCarter** [comment]
Fair enough, we'll consider it a failed experiment. (Although this program compiles fine for me - `decltype(u)` has no member `type`. I speculate the check dies at `WeaklyIncrementable` for me and you have some changes in place from #137 that allow it to get to `Readable`.)

Full disclosure: I just spent a couple of hours determining that this `common_type` specialization was the root cause of this program:
```c++
struct foo;
static_assert(ranges::models::EqualityComparable<foo*>);
struct foo {};
static_assert(ranges::models::RandomAccessIterator<foo*>);
```
failing at the final `static_assert`, so I may not be completely objective when considering whether or not to excise it with fire.

**Comment by ericniebler** [comment]
...And this observation revealed the shortcoming that out `common_iterator` doesn't work for `OutputIterator`s. I'm fixing it, but it highlights the risks we take when our reference implementation diverges from the text.

**Comment by ericniebler** [comment]
> I speculate the check dies at `WeaklyIncrementable` for me and you have some changes in place from #137 that allow it to get to `Readable`.)

You speculate correctly.

**Comment by CaseyCarter** [comment]
Just checked in caseycarter/cmcstl2@4ad0986d11fd6c3e5bd716ddfb4435be24b205ac. It was an educational experiment, but this thread should now be closed.

**Comment by ericniebler** [comment]
A worthy experiment, certainly.
