### ISSUE TITLE
unique_copy and LWG2439

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#170]
The declaration of `unique_copy` is underconstrained when the iterator category of the source range is not forward. It should probably be brought into line with the resolution of [LWG2439](http://www.open-std.org/jtc1/sc22/wg21/docs/lwg-defects.html#2439).

### Proposed Resolution
Update the declarations of `unique_copy` in the synopsis of `<experimental/ranges/algorithm>`  in [algorithms.general] as follows:
```diff
 template <InputIterator I, Sentinel<I> S, WeaklyIncrementable O,
     class Proj = identity, IndirectRelation<projected<I, Proj>> R = equal_to<>>
-  requires IndirectlyCopyable<I, O>() && (ForwardIterator<I>() ||
-    ForwardIterator<O>() || IndirectlyCopyableStorable<I, O>())
+  requires IndirectlyCopyable<I, O>() &&
+    (ForwardIterator<I>() ||
+     (InputIterator<O>() && Same<value_type_t<I>, value_type_t<O>>()) ||
+     IndirectlyCopyableStorable<iterator_t<Rng>, O>())
   tagged_pair<tag::in(I), tag::out(O)>
     unique_copy(I first, S last, O result, R comp = R{}, Proj proj = Proj{});

 template <InputRange Rng, WeaklyIncrementable O, class Proj = identity,
     IndirectRelation<projected<iterator_t<Rng>, Proj>> R = equal_to<>>
   requires IndirectlyCopyable<iterator_t<Rng>, O>() &&
-    (ForwardIterator<iterator_t<Rng>>() || ForwardIterator<O>() ||
+    (ForwardIterator<iterator_t<Rng>>() ||
+     (InputIterator<O>() && Same<value_type_t<I>, value_type_t<O>>()) ||
      IndirectlyCopyableStorable<iterator_t<Rng>, O>())
   tagged_pair<tag::in(safe_iterator_t<Rng>), tag::out(O)>
     unique_copy(Rng&& rng, O result, R comp = R{}, Proj proj = Proj{});
```

**Comment by ericniebler** [comment]
Wow, I didn't think `unique_copy` could get any messier. I was wrong. :-P

**Comment by CaseyCarter** [comment]
Yeah, it's a train wreck.

**Comment by CaseyCarter** [comment]
LWG2439 seems to be overconstraining. There are three cases that need distinct implementations for input range `Rng`, output iterator `O`, projection `Proj`, and predicate `R` (all require `InputRange<Rng>() && WeaklyIncrementable<O>() && IndirectlyCopyable<I, O>()`):
1. The input range is forward: `ForwardRange<Rng>() && IndirectCallableRelation<R, projected<iterator_t<Rng>, Proj>>()`
2. The output range is input: `InputIterator<O>() && IndirectCallablePredicate<R, projected<iterator_t<Rng>, Proj>, FOO>()` where `FOO` could legitimately be either `O` or `projected<O, Proj>`, or...? This is the case where LWG2449 requires `ForwardIterator<O>() && Same<value_type_t<O>, value_type_t<iterator_t<Rng>>>()`.
3. Otherwise, we need to store a temporary value: `IndirectlyCopyableStorable<iterator_t<Rng>, O>() && IndirectCallableRelation<R, projected<iterator_t<Rng>, Proj>>()`

The issue of possibly applying the projection to the output range in case 2 needs to be addressed, and the decision to disjoin the three requirement sets into a single declaration needs to be reevaluated.

**Comment by CaseyCarter** [comment]
> This is the case where LWG2449 requires `ForwardIterator<O>() && Same<value_type_t<O>, value_type_t<iterator_t<Rng>>>()`

Forward is necessary (in Standard C++) to ensure that reference_t<O> is an lvalue so that:

(1) `*declval<O>() = *declval<iterator_t<Rng>>()` is guaranteed (via `CopyAssignable`) not to modify `*declval<iterator_t<Rng>>()`

(2) `declval<R>()(*declval<O>(), *declval<iterator_t<Rng>>())` has the same signature as 
`declval<R>()(*declval<iterator_t<Rng>>(), *declval<iterator_t<Rng>>())`, and is consequently required to be valid

The Ranges TS ensures (1) by requiring `IndirectlyCopyable<iterator_t<Rng>, O>()`, and *will* ensure (2) in `IndirectCallablePredicate` once the proxy iterator proposal is integrated, so I think the requirement on `O` for case 2 can be relaxed to `InputIterator` as I've presented it above.

**Comment by CaseyCarter** [comment]
> 2. The output range is input: `InputIterator<O>() && IndirectCallablePredicate<R, projected<iterator_t<Rng>, Proj>, FOO>()` where `FOO` could legitimately be either `O` or `projected<O, Proj>`, or...? This is the case where LWG2449 requires `ForwardIterator<O>() && Same<value_type_t<O>, value_type_t<iterator_t<Rng>>>()`.

In think the fix for case 2 is to require that the source and destination ranges have the same value type, and to apply the projection to both. Other cases can fall back to the "make a temporary" implementation.

### Potential Resolution
Update the declarations of `unique_copy` in the synopsis of `<algorithm>`  in [algorithms.general] as follows:
```diff
 template <InputIterator I, Sentinel<I> S, WeaklyIncrementable O,
     class Proj = identity, IndirectRelation<projected<I, Proj>> R = equal_to<>>
-  requires IndirectlyCopyable<I, O>() && (ForwardIterator<I>() ||
-    ForwardIterator<O>() || IndirectlyCopyableStorable<I, O>())
+  requires IndirectlyCopyable<I, O>() &&
+    (ForwardIterator<I>() ||
+     InputIterator<O>() && Same<value_type_t<I>, value_type_t<O>>() ||
+     IndirectlyCopyableStorable<iterator_t<Rng>, O>())
   tagged_pair<tag::in(I), tag::out(O)>
     unique_copy(I first, S last, O result, R comp = R{}, Proj proj = Proj{});

 template <InputRange Rng, WeaklyIncrementable O, class Proj = identity,
     IndirectRelation<projected<iterator_t<Rng>, Proj>> R = equal_to<>>
   requires IndirectlyCopyable<iterator_t<Rng>, O>() &&
-    (ForwardIterator<iterator_t<Rng>>() || ForwardIterator<O>() ||
+    (ForwardIterator<iterator_t<Rng>>() ||
+     InputIterator<O>() && Same<value_type_t<I>, value_type_t<O>>() ||
      IndirectlyCopyableStorable<iterator_t<Rng>, O>())
   tagged_pair<tag::in(safe_iterator_t<Rng>), tag::out(O)>
     unique_copy(Rng&& rng, O result, R comp = R{}, Proj proj = Proj{});
```

**Comment by ericniebler** [comment]
Looks good. I added parens around the conjunctions within disjunctions.

**Comment by huixie90** [comment]
Sorry for doing archaeology here. I am puzzled when implementing std::ranges::unique_copy. The constraint about `value_type<in> == valie_type<out> `confused me a lot and finally I got where it came from. (This PR). 

The LWG issue says to be able to call comp(*out, *in), we need to have input and output iterator to have the same value_type

but why does value_type matter here? Surely we only need reference type for this particular comparison

**Comment by var-const** [comment]
@CaseyCarter One more question related to this if you don't mind. LWG2439 required the output iterator to be a forward iterator for the second case (where value types are the same), and AFAICT, that's still the case in the latest draft. For ranges, however, the constraint uses `input_iterator` instead of `forward_iterator`. I presume this is due to some difference between `input_iterator` and `Cpp17InputIterator`?
