### ISSUE TITLE
Concepts and preconditions

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#171]
What should this program do:

``` c++
#include <experimental/ranges/concepts>

using namespace std::experimental::ranges;

template <class> int foo() { return 0; }
template <Destructible> int foo() { return 1; }

int main()
{
    struct A;
    int x = foo<A>();
    struct A {};
    x += foo<A>();
    return x;
}
```

Return 0? Return 1? Return 2? Be ill-formed? Be ill-formed NDR?

`std::is_destructible<T>` requires `T` to be complete (if it's not cv-void or an array of unknown bound). We need to determine which of the type trait preconditions should be applied to the concept definitions, and whether we should strengthen some of them to ill-formed-ness. (For the specific case given in this example program, [I prefer "ill-formed"](https://github.com/CaseyCarter/cmcstl2/commit/c328c5dd73082a7690d4558e8038508d9f247be1).)

**Comment by ericniebler** [comment]
At first blush, it seems that we should blanket require that parameters to standard Concepts be complete or CV void. It's a question for core whether *all* Concepts should get that treatment. I pulls day yes.

**Comment by ericniebler** [comment]
We already have [res.on.functions]/p2:

> 2. In particular, the effects are undefined if an incomplete type (ISO/IEC 14882:2014 §3.9) is used as a template argument when instantiating a template component or evaluating a concept, unless specifically allowed for that component.
