### ISSUE TITLE
tagged<Base...> should be implicitly constructible from Base

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#172]
`tagged<Base, Tags...>` needs to be implicitly constructible from `Base&&` when `MoveConstructible<Base>()`, and from `Base const&` when `CopyConstructible<Base>()`. (To avoid the issue in ericniebler/range-v3#324.)

Proposed Resolution
---------------------

Change the class synopsis of `tagged` in [taggedtup.tagged] as follows:

```diff
 template <class Base, TagSpecifier... Tags>
   requires sizeof...(Tags) <= tuple_size<Base>::value
 struct tagged :
   Base, TAGGET (tagged<Base, Tags...>, Ti, i)... { // see below
   using Base::Base;
   tagged() = default;
   tagged(tagged&&) = default;
   tagged(const tagged&) = default;
+  tagged(Base&&) noexcept(see below)
+    requires MoveConstructible<Base>();
+  tagged(const Base&) noexcept(see below)
+    requires CopyConstructible<Base>();
   tagged &operator=(tagged&&) = default;
   tagged &operator=(const tagged&) = default;
   [...]
```

After [taggedtup.tagged]/9, add the following:

> ```
> tagged(Base &&that) noexcept(see below )
>   requires MoveConstructible<Base>();
> ```
> 10 _Remarks:_ The expression in the `noexcept` is equivalent to:
> ```
> is_nothrow_move_constructible<Base>::value
> ```
> 11 Effects: Initializes `Base` with `std::move(that)`.
> ```
>
> tagged(const Base &that) noexcept(see below )
>   requires CopyConstructible<Base>();
> ```
> 12 _Remarks:_ The expression in the `noexcept` is equivalent to:
> ```
> is_nothrow_copy_constructible<Base>::value
> ```
> 13 Effects: Initializes `Base` with `that`.

**Comment by CaseyCarter** [comment]
`get` needs to be a customization point in order to tag non-standard types.

`tagged` needs to inject the tagged getter types "between" itself and `Base` in the inheritance hierarchy, so that tagged getter names hide (instead of ambiguate) members with the same name in `Base`. i.e., if we envision the current design as "fan inheritance":

<pre>
                Tagged
                 ^  ^
        collect--/  \---Base
        ^     ^
getter1-/ ... \-getterN
</pre>

we want to change the structure to "chain inheritance":

<pre>
Tagged
^
\-getter1
  ^
  \-getter2
    ^
   ...
    \-getterN
      ^
      \--Base
</pre>

**Comment by ericniebler** [comment]
I've proposed a fix for constructing `tagged<Base>` from `Base`. Is the problem with `get` only about supporting user-defined tag types? We can safely punt on that for now. And chain inheritance? Why should there be hiding instead of ambiguity? Seems to me that ambiguity is an acceptable result.

**Comment by CaseyCarter** [comment]
> Why should there be hiding instead of ambiguity?

Given:
```c++
template <class T, class U>
tagged_tuple<tag::in(T), tag::out(U), tag::end(int)> f() { /*...*/ }
```
Should `f().in()` always return a reference to the temporary's `T` member, or should it be allowed to break when `T` or `U` have a member function named `in`, but only on implementations that use EBO for `std::tuple`?

**Comment by CaseyCarter** [comment]
> Is the problem with `get` only about supporting user-defined tag types?

No, it's about supporting user-defined tuple-like types that define `get` function templates in their associated namespaces that are not namespace `std`.

**Comment by CaseyCarter** [comment]
> `tagged` needs to inject the tagged getter types "between" itself and `Base` in the inheritance hierarchy, so that tagged getter names hide (instead of ambiguate) members with the same name in `Base`.

This is now issue #363.

> > Is the problem with `get` only about supporting user-defined tag types?

> No, it's about supporting tagging of user-defined tuple-like types that define `get` function templates in their associated namespaces that are not namespace `std`. 

This is now issue #364.
