### ISSUE TITLE
Swappable concept and P0185 swappable traits

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#174]
...have inconsistent interfaces. Our `Swappable<T, U>` is roughly equivalent to C++17's `is_swappable_with<T, U>`, so `is_swappable<T>` - which is equivalent to `is_swappable_with<T&, T&>` - is roughly equivalent to `Swappable<T&, T&>`. There's enormous potential for confusion in this disparity.

We need to bring the concept definitions to parity with the WP traits by renaming `Swappable<T, U>` to `SwappableWith`, and defining `Swappable<T>` to be roughly equivalent to `SwappableWith<T&, T&>`:

Proposed Resolution
---------------------

(Includes the proposed resolution of #379.)

Change the definition of concept `Swappable` ([concepts.lib.corelang.swappable]) to:

``` c++
template <class T>
concept bool Swappable =
  requires(T& a, T& b) {
    ranges::swap(a, b);
  };

template <class T, class U>
concept bool SwappableWith =
  CommonReference<
    const remove_reference_t<T>&,
    const remove_reference_t<U>&> &&
  requires(T&& t, U&& u) {
    ranges::swap(std::forward<T>(t), std::forward<T>(t));
    ranges::swap(std::forward<U>(u), std::forward<U>(u));
    ranges::swap(std::forward<T>(t), std::forward<U>(u));
    ranges::swap(std::forward<U>(u), std::forward<T>(t));
  };
```

Change the definition of `Movable` ([concepts.lib.object.movable]) as follows (includes changes from [P0547R1](http://wg21.link/P0547R1)):

```diff
 template <class T>
 concept bool Movable =
   std::is_object<T>::value && // see below
   MoveConstructible<T> &&
   Assignable<T&, T> &&
-  Swappable<T&>;
+  Swappable<T>;
```

In the class synopsis of class template `tagged` ([taggedtup.tagged]/p2), make the following changes:

```diff
   tagged& operator=(U&& u) noexcept(see below );
   void swap(tagged& that) noexcept(see below )
-    requires Swappable<Base&>;
+    requires Swappable<Base>;
   friend void swap(tagged&, tagged&) noexcept(see below )
-    requires Swappable<Base&>;
+    requires Swappable<Base>;
};
```

Make the same changes to the detailed specifications of `tagged::swap` and the non-member `swap(tagged&, tagged&)` overload in [taggedtup.tagged]/p20 and p23

**Comment by ericniebler** [comment]
> We need to bring the concept definitions to parity with the WP traits by renaming `Swappable<T, U>` to `SwappableWith`, and defining `Swappable<T>` to be roughly equivalent to `SwappableWith<T&, T&>`

Not unless you also want `EqualityComparableWith`, `StrictTotallyOrderedWith`, and friends. I don't relish the idea.

**Comment by CaseyCarter** [comment]
> Not unless you also want `EqualityComparableWith`, `StrictTotallyOrderedWith`, and friends.

I don't follow - there are no concepts named `EqualityComparableWith` or `StrictTotallyOrderedWith` in the C++ WP with which to be consistent.

**Comment by ericniebler** [comment]
My point was that with `Swappable` and `SwappableWith` we set a precedent that the cross-type variant of the concept ends with `With`. Either we apply that rule consistently, or not at all.

**Comment by CaseyCarter** [comment]
Cross-type is not the key difference; the important distinction is that `is_swappable<T>` is equivalent to `is_swappable_with<T&, T&>` and therefore really means "is lvalue-swappable." `is_swappable` could easily/compatibly be made cross-type by defaulting a second type parameter:
```c++
template <class T, class U = T>
using is_swappable = is_swappable_with<T&, U&>;
```
The equivalent concept design is:
```c++
template <class T>
concept bool SwappableWith() {
  /* existing definition of Swappable<T>() */
}

template <class T, class U>
concept bool SwappableWith() {
  /* existing definition of Swappable<T, U>() */
}

template <class T>
concept bool Swappable() {
  return SwappableWith<T&>();
}

template <class T, class U>
concept bool Swappable() {
  return SwappableWith<T&, U&>();
}
```
which enables straight-forward replacement of C++17's `is_swappable<T>::value` (`is_swappable_with<T, U>::value`) with `Swappable<T>()` (resp. `SwappableWith<T, U>()`).

**Comment by ericniebler** [comment]
Note that `EqualityComparable` and `StrictTotallyOrdered` are *NOT* affected by this because these are non-modifying concepts that always operate on `const` lvalues of type `remove_reference_t<T>`. So no changes are needed there, AFAICT.

**Comment by ericniebler** [comment]
@CaseyCarter for your review. Give the thumbs-up before Monday and I can get an updated P0651 into John Spicer's hands for the pre-meeting mailing.

**Comment by CaseyCarter** [comment]
> Give the thumbs-up before Monday

My thumbs are up after a tiny tweak to avoid calling `tagged`'s non-member `friend swap` a member ;)

**Comment by CaseyCarter** [comment]
We have a small problem in the specification of \techterm{swappable with} in [concepts.lib.corelang.swappable]:

> 1 This subclause provides definitions for swappable types and expressions. In these definitions, let `t` denote an expression of type `T`, and let `u` denote an expression of type `U`.
>
> 2 An object `t` is *swappable with* an object `u` if and only if `Swappable<T, U>()` is satisfied. `Swappable<T, U>()` is satisfied if and only if given distinct objects `t2` equal to `t` and `u2` equal to `u`, after evaluating either `ranges::swap(t, u)` or `ranges::swap(u, t)`, `t2` is equal to `u` and `u2` is equal to `t`.

`T` and `U` are the *types* of the expressions `t` and `u`, whereas our definition of `Swappable` takes two "expression-type-and-value-category-encoded-as-type"s. Para 2 should read: "An object `t` is *swappable with* an object `u`  However, I can't imagine making people read "...if and only if `Swappable<decltype((t)), decltype((u))>()` is satisfied. `Swappable<decltype((t)), decltype((u))>()` is satisfied if and only if ...". We need a better formulation for this wording.

Also, [iterator.custpoints.iter_swap]/1.2 talks about "...if the reference type of `E1` is swappable with (\ref{concepts.lib.corelang.swappable}) the reference type of `E2`..." which doesn't make sense in the context of the swappable requirements: we say that objects/expressions/values are "swappable with" objects/expressions/values. Requirements on types like this should just require `SwappableWith` to be satisfied.

I suggest adjusting the PR as follows:

Replace the entire contents of [concepts.lib.corelang.swappable] with:

> ```c++
> template <class T, class U>
> concept bool SwappableWith =
>   CommonReference<
>     const remove_reference_t<T>&,
>     const remove_reference_t<U>&> &&
>   requires(T&& t, U&& u) {
>     ranges::swap(std::forward<T>(t), std::forward<T>(t));
>     ranges::swap(std::forward<U>(u), std::forward<U>(u));
>     ranges::swap(std::forward<T>(t), std::forward<U>(u));
>     ranges::swap(std::forward<U>(u), std::forward<T>(t));
>   };
> 
> template <class T>
> concept bool Swappable = SwappableWith<T&, T&>;
> ```
> 
> 1 Let `t` be an expression such that `decltype((t))` is `T` and `u` an expression such that `decltype((u))` is `U`. Let `t2` be a distinct object equal to `t` and `u2` a distinct object equal to `u`. `SwappableWith<T, U>()` is satisfied if and only if after evaluating either `ranges::swap(t, u)` or `ranges::swap(u, t)`, `t2` is equal to `u` and `u2` is equal to `t`.
> 
> 2 An object `t` is *swappable with* an object `u` if and only if `SwappableWith<T, U>()` is satisfied. 
> 
> 3 An rvalue or lvalue `x` is *swappable* if and only if `SwappableWith<decltype((x)), decltype((x))>()` is satisfied.

Change [iterator.custpoints.iter_swap]/1.2 as follows:
```diff
 (1.2) - Otherwise, if the types of E1 and E2 both satisfy Readable, and if 
-        the reference type of E1 is swappable with (7.3.11) the reference type of E2,
+        the reference types of E1 and E2 satisfy SwappableWith,
         then ranges::swap(*E1, *E2)
```
