### ISSUE TITLE
Simplify distance(Range)

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#177]
With the library-wide concept promotion rules in place for `Range`/`SizedRange` we no longer need two overloaded declarations for `distance(Range)` and `distance(SizedRange)`.

### Proposed Wording:

Update the synopsis of `<experimental/ranges/iterator>` in [iterator.synopsis]:
```diff
  // 6.11, range primitives:
  namespace {
    constexpr unspecified size = unspecified ;
    constexpr unspecified empty = unspecified ;
    constexpr unspecified data = unspecified ;
    constexpr unspecified cdata = unspecified ;
  }

  template <Range R>
    difference_type_t<iterator_t<R>> distance(R&& r);
- template <SizedRange R>
-   difference_type_t<iterator_t<R>> distance(R&& r);
}}}}
```

Modify [ranges.primitives] as follows:

```diff
template <Range R>
difference_type_t<iterator_t<R>> distance(R&& r);

-1 Effects: Equivalent to: return ranges::distance(ranges::begin(r), ranges::end(r));
+1 Effects:
+  - If R satisfies SizedRange, equivalent to:
+      return static_cast<difference_type_t<iterator_t<R>>>(size(r));
+  - Otherwise, equivalent to: return distance(begin(r), end(r));

-template <SizedRange R>
-difference_type_t<iterator_t<R>> distance(R&& r);
-
-2 Effects: Equivalent to: return ranges::size(r);
```

> ``` c++
> template <Range R>
> auto distance(R&& r) -> difference_type_t<iterator_t<R>>;
> ```
> 
> Effects:
> - If `R` satisfies `SizedRange`, equivalent to:<br>`static_cast<difference_type_t<iterator_t<R>>>(size(r))`.
> - Otherwise, equivalent to `distance(begin(r), end(r))`.

**Comment by ericniebler** [comment]
Fixed.
