### ISSUE TITLE
Consider relaxing the DefaultConstructible requirements

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#179]
....in the general library concepts (which would effectively replace `Semiregular` with `Copyable`) and the iterator concepts. There's concern in the community that relaxing type invariants to allow for default construction of a type that would not otherwise provide it is a horrible idea.

Relaxing the default construction requirement for iterators would also remove one of the few "breaking" differences between input and output iterators in the Standard (which do not require default construction) and Ranges (which currently do require default construction).

**Comment by ericniebler** [comment]
According to EoP, the job of the default constructor is simply to put the object into a partially formed state. It's the responsibility of the programmer to assign a well-defined value.

That's the party line. I also understand not wanting to force the introduction of an undefined state. Nevertheless, I'm against removing `DefaultConstructible` from `Semiregular`.

**Comment by CaseyCarter** [comment]
To me, requiring default construction for single-pass (input and output) iterators is a gratuitous backwards incompatibility. I could get behind the idea if there was something to gain from it, but there doesn't seem to be a benefit. None of the algorithms need to default construct single-pass iterators; there are only a handful of default constructions of *forward* iterators. The case for delayed initialization of single-pass iterators is pretty slim.

For that matter, *copying* single-pass iterators in generic code isn't a useful operation under the sentinel paradigm. It's great for concrete models of single-pass iterators so that I can use them with STL1 code, but STL2 code could easily be written to always move single-pass iterators which would hopefully reduce the incidence of use-after-invalidate bugs.

**Comment by CaseyCarter** [comment]
The recent trend of making everything in the standard library `constexpr` is in conflict with the desire to not require default construction. The traditional workaround for delayed initialization of a non-default-constructible `T` is to instead store an `optional<T>`. Changing an `optional<T>` from the empty to filled states is not possible in a constant expression per [[expr.const]/2](http://eel.is/c++draft/expr.const#2):

> 2 An expression `e` is a *core constant expression* unless the evaluation of `e`, following the rules of the abstract machine, would evaluate one of the following expressions:
> [...]
> [2.10](http://eel.is/c++draft/expr.const#2.10) an assignment expression or invocation of an assignment operator ([class.copy]) that would change the active member of a union;
> [..]
> [2.19](http://eel.is/c++draft/expr.const#2.19) a new-expression;
> [...]

In the absence of `constexpr` it's easy to see this situation as a wash: either `T` implements a default constructor and must handle the additional state in its members, or the client of `T` instead uses `optional<T>` and must handle the additional (empty) state in its members. With `constexpr` becoming more prominently a concern, it becomes more sensible to place the burden of the extra state on `T` itself instead of the users of `T`.

**Comment by CaseyCarter** [comment]
> So, are you saying this issue should be resolved "won't fix"?

I'm thinking more "NAD without prejudice." It's a shame we've gotten no engagement on this issue, but certainly you and I agree it's NAD. I'll close this pending new information.
