### ISSUE TITLE
s/IndirectCallableRelation/IndirectRelation/

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#188]
Also: IndirectCallablePredicate, IndirectCallableStrictWeakOrder.

**Comment by CaseyCarter** [comment]
This isn't insane, but I am somewhat nervous that we may eventually need to bring back the non-`Callable` function concepts and it will be challenging to do so if these names are taken.

**Comment by CaseyCarter** [comment]
There's also the question of maintaining consistency with the `is_callable` trait in the WP.

**Comment by ericniebler** [comment]
FWIW, We have "`Predicate`" in the draft and not "`CallablePredicate`". We need to go one way or the other; right now we're inconsistent. Not sure what `is_callable` has to do with it.

**Comment by CaseyCarter** [comment]
Closed via #285.
