### ISSUE TITLE
Why does `IndirectlyCopyable` refine `IndirectlyMovable`

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#197]
...instead of being defined as:

```c++
template <class In, class Out>
concept bool IndirectlyCopyable() {
  return Readable<In>() && Writable<Out, reference_t<In>>();
}
```

certainly there are no algorithms that *both* move and copy elements from their input range to their output range. I write either `*out = *in;` or `*out = iter_move(*in);`, never both.

**Comment by CaseyCarter** [comment]
and similarly for `IndirectlyCopyableStorable`.

**Comment by ericniebler** [comment]
If you can copy things, you can move them, right? Copyable refines Movable.

**Comment by CaseyCarter** [comment]
> `Copyable` refines `Movable`

Yes, but `Writable<I, const T&>` doesn't refine `Writable<I, T>`. Algorithms that are constrained with `IndirectlyCopyable` in practice are specified to never `iter_move` from their input sequence. Much like how `find_if` never mutates its input sequence even if the iterators are mutable, `copy` never evaluates `*out = iter_move(*in)`. Even if the extraneous constraints are always satisfied in sane programs, why pay the cost of checking them?

**Comment by ericniebler** [comment]
OK. 👍

**Comment by CaseyCarter** [comment]
I'm going to run with this in P0441. If I'm wrong, the worst I can do is break `unique_copy` since it is the only user of `IndirectlyCopyable`. I can't imagine that level of damage being challenging to repair.

**Comment by ericniebler** [comment]
`P0441`? FWIW, it's easy enough to test this in cmcstl2.

**Comment by CaseyCarter** [comment]
Without implementation checking, there's nothing to test when we're relaxing requirements. Stuff that worked with the stronger requirements will work with the weaker requirements. The best I can do is inspect the implementation of `unique_copy` and assure myself that it uses no operations that are not properly constrained by the relaxed requirements. (Which I did.)
