### ISSUE TITLE
We probably still need a LessThanComparable concept

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#20]

**Comment by asutton** [comment]
If we have TotallyOrdered, we should not have LessThanComparable.

Andrew Sutton

**Comment by ericniebler** [comment]
The group voted down having a named `LessThenComparable` concept, preferring instead to constrain `std::less` with an *ad hoc* constraint.

**Comment by asutton** [comment]
I think this sets a bad precedence. An ad hoc constraint admits that
people are defining operator< without considering what it actually
means.

I understand the reticence to not require more operations since > and
friends are formulaic. We should seriously consider providing
constrained defaults in the global namespace. The we can require the
right concepts for those operators.

Andrew Sutton

**Comment by ericniebler** [comment]
> I think this sets a bad precedence. An ad hoc constraint admits that
> people are defining operator< without considering what it actually
> means.

I agree. I argued for naught.

> I understand the reticence to not require more operations since > and
> friends are formulaic. We should seriously consider providing
> constrained defaults in the global namespace. The we can require the
> right concepts for those operators.

Ah! That's a very interesting suggestion. In fact, it would not need to be in the global namespace -- only in `std` if all we care about is that the standard algorithms and function objects do the "right thing". I'll float the idea in LEWG. Thanks.

**Comment by asutton** [comment]
> I understand the reticence to not require more operations since > and
> friends are formulaic. We should seriously consider providing
> constrained defaults in the global namespace. The we can require the
> right concepts for those operators.
>
> Ah! That's a very interesting suggestion. In fact, it would not need to be in the global namespace -- only in std if all we care about is that the standard algorithms and function objects do the "right thing". I'll float the idea in LEWG. Thanks.

I've been saying this for years, and we don't even need concepts. I
think we could have done it with decltype in a late-binding return and
nothing more. I'm probably missing something obvious.

The only reason I suggest global scope, is that the compiler will pick
up the appropriate operators for everybody's partially defined models
(with an appropriate #include, or should I say import?). And if people
have defined overloads, their more specialized types will be selected
anyways.

Andrew

**Comment by jyasskin** [comment]
I think defining things in the global namespace doesn't work, since they get hidden by definitions in namespaces. I can talk to Eric about details.

**Comment by asutton** [comment]
I might be overlooking some scoping issues, but I *feel* like it should
work, and compiler's can't intuit my feelings, then the language is broken
:)


Andrew Sutton

**Comment by jyasskin** [comment]
Ville just told me that EWG agreed on default comparators, so we don't need a library solution for this.

That's not going to fix the problem with upgrading the requirements on operator< from StrictWeakOrdering to TotalOrdering.

**Comment by jyasskin** [comment]
I'm not sure how the room will take a requirement for StrictWeakOrdering over LessThanComparable given the default comparisons from Core. We should ask them.

**Comment by asutton** [comment]
Generated defaults are orthogonal. What we probably want is to allow programmers to define ==, but get != for free, or at least very cheap. Same with < and its friends.

It's better to solve this problem than to start writing ad hoc constraints.

**Comment by jyasskin** [comment]
Yeah, that's what I understand http://open-std.org/JTC1/SC22/WG21/docs/papers/2015/n4475.pdf does, which got a green light in http://wiki.edg.com/twiki/bin/view/Wg21lenexa/Comparisons%2cComparisons%2cComparisonsNotes. I'm not sure it defaults in all the circumstances the "I want my weird type to work" folks want, but it could be close enough.

@chandlerc worried at me about strict-weak-ordered types, where TotallyOrdered assumes things about == that aren't true. Given your semantic vision for the library, does it make sense to use StrictWeakOrdered instead?

**Comment by asutton** [comment]
> Yeah, that's what I understand http://open-std.org/JTC1/SC22/WG21/docs/papers/2015/n4475.pdf does, which got a green light in http://wiki.edg.com/twiki/bin/view/Wg21lenexa/Comparisons%2cComparisons%2cComparisonsNotes. I'm not sure it defaults in all the circumstances the "I want my weird type to work" folks want, but it could be close enough.
>
> @chandlerc worried at me about strict-weak-ordered types, where TotallyOrdered assumes things about == that aren't true. Given your semantic vision for the library, does it make sense to use StrictWeakOrdered instead?

Oh, that's right. We generate those by default now. I haven't been
following that discussion as closely as I should.

I have a concept in Origin called WeaklyOrdered that required only <
and friends and did not require ==. That might be reasonable concept
to define.

But I'd fallen out of favor with that approach since I've never seen a
type that was designed to be weakly (but not totally) ordered.

**Comment by ericniebler** [comment]
> But I'd fallen out of favor with that approach since I've never seen a
> type that was designed to be weakly (but not totally) ordered.

... and I've never seen a type that's a weak input iterator that's not also an input iterator. But that's not how we design concepts. Or is it? A-hem. ;-)

**Comment by asutton** [comment]
> But I'd fallen out of favor with that approach since I've never seen a
> type that was designed to be weakly (but not totally) ordered.
>
> ... and I've never seen a type that's a weak input iterator that's not also
> an input iterator. But that's not how we design concepts. Or is it? A-hem.
> ;-)

Ha :) Apparently there's a reason I've kept it around.
