### ISSUE TITLE
Swappable concept description still implies ADL is being used to find "swap"

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#200]
> "User code can ensure that the evaluation of swap calls is performed in an appropriate
> context under the various conditions as follows:"

... followed by uses of `swap` that pull `ranges::swap` into scope with a using declaration, followed by an unqualified call. This should be cleaned up in light of the fact that `ranges::swap` is now a customization point object that guarantees the correct lookup context.

### Proposed Resolution

In [concepts.lib.corelang.swappable]/p3, remove the example which begins "User code can ensure that the evaluation of `swap` calls is performed in an appropriate context [...]")

**Comment by CaseyCarter** [comment]
There's going to be a new revision of P0370 - I'm making sure that all the wording therein agrees with what's in the TS document for Issaquah. It already touches `[concepts.lib.corelang.swappable]`, and thus is the ideal vehicle for any changes to the `Swappable` discussion.

**Comment by ericniebler** [comment]
Great. So, you'll make the edits?

**Comment by CaseyCarter** [comment]
Yes, will do.

**Comment by CaseyCarter** [comment]
I'm looking at this enormous example in [concepts.lib.corelang.swappable]. It exists to demonstrate the ADL 2-step, which can be complicated if you've never seen it before. With the CPO changes, calling `swap` is as simple as - if not simpler than - anything else in `std`. However I change this it seems tutorial and therefore pointless.

Why not simply remove the example?

**Comment by ericniebler** [comment]
> Why not simply remove the example?

Works for me.

**Comment by ericniebler** [comment]
On second thought, this example is the only place in the standard that shows `swap` being called with an rvalue proxy, or with asymmetrical argument types. I agree with nuking this example, but perhaps replacing it with a note that such types are OK, and perhaps adding an example specifically showing that kind of usage.

**Comment by ericniebler** [comment]
Fixed.
