### ISSUE TITLE
EqualityComparable vs WeaklyEqualityComparable

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#201]
The text has this:

> "[ Note: The distinction between EqualityComparable&lt;T, U&gt;() and WeaklyEqualityComparable&lt;T, U&gt;() is purely semantic. -- end note ]"

Really? `EqualityComparable` requires `Common<T,U>` and `WeaklyEqualityComparable` doesn't. That's more that semantic, isn't it?

**Comment by CaseyCarter** [comment]
`EqualityComparable<T>()` and `WeaklyEqualityComparable<T, T>()`, maybe, but I think we should just strike the note.

**Comment by ericniebler** [comment]
👍
