### ISSUE TITLE
Don't slurp entities from std:: into std::experimental::ranges::v1

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#203]
The Ranges TS, [function.objects]/p3 says

> Any entities declared or defined directly in namespace std in header `<functional>` that are not already defined in namespace `std::experimental::ranges` in header `<experimental/ranges/functional>` are imported with _using-declarations_ (7.3.3). [ _Example:_
> ```
> namespace std { namespace experimental { namespace ranges { inline namespace v1 {
> using std::reference_wrapper;
> using std::ref;
> // ... others
> }}}}
> ```
> &mdash;_end example_ ]

This breaks forward compatibility should we ever decide that something in `std::` needs to have a parallel, constrained implementation in `ranges::`.

### Proposed resolution

Strike paragraph 1 in [iterator.synopsis].

In [tagged.tuple]/p1, strike the text beginning with "Any entities declared or defined in namespace std in header <tuple>" and ending at the end of the example.

Strike p3 and p4 under [function.objects].

Strike p2 under [utility].

**Comment by CaseyCarter** [comment]
The original motivation for "slurping" was to enable simple programs to transition from using the Standard library to the Ranges library with `s/std/std::experimental::ranges/g`. That looks great in tiny example programs, but it's not a realistic use case for any real-world codebase that is necessarily going to have to deal with breakages and transition gradually. I agree that "slurping" is a well-intentioned idea that fails in the real world.

**Comment by cjdb** [comment]
If this hasn't been resolved yet, I can take a look at it over the weekend.
