### ISSUE TITLE
Add new header <experimental/range/range>

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#211]
Where do `enable_view`, `disable_sized_range`, and `view_base` live? Or the Range concepts? Do we need a `<experimental/ranges/range>` header?

Heck, where do the Iterator concepts live? They don't appear in the `iterator` header synopsis.

Solution description
--------------------

The problems with the concepts and iterator synopses have been handled as editorial changes in 1862bd8 and e15540b. This resolution is describes as a diff to those changes. It suggests adding a new header to hold all range-related functionality: `<experimental/ranges/range>`. This gives us a place to put the range customization points (`begin`, `end`, `size`, etc.), the range concepts, and range utilities.

It will also give us a place to put future range-related functionality, such as a view facade and adaptors, without further bloating `<experimental/ranges/iterator>`, which is quite heavy already.

The following resolution has been implemented in #328, but not merged pending LWG review.

Proposed Resolution
--------------------

To "Table 1 - Ranges TS library headers", add `<experimental/ranges/range>`.

To "Table 2 - Library categories", add a row for "Ranges library" between the "Iterators library" and the "Algorithms library".

After [library.general]/p6, add a new paragraph that reads:

> The ranges library (\ref{ranges}) describes components for dealing with ranges of
> elements.

Change [iterators.general]/1 as follows:

```diff
This Clause describes components that \Cpp programs may use to perform
iterations over containers (Clause \cxxref{containers}),
streams~(\cxxref{iostream.format}),
-stream buffers~(\cxxref{stream.buffers}),
-and ranges~(\ref{ranges}).
+and stream buffers~(\cxxref{stream.buffers}).
```

From table "Table 5 — Iterators library summary" [tab:iterators.lib.summary], delete the last line, which reads "Ranges".

From [iterator.synopsis], delete the following lines:

```diff
-  // \ref{iterator.range}, range access:
-  namespace {
-    constexpr @\unspec@ begin = @\unspec@;
-    constexpr @\unspec@ end = @\unspec@;
-    constexpr @\unspec@ cbegin = @\unspec@;
-    constexpr @\unspec@ cend = @\unspec@;
-    constexpr @\unspec@ rbegin = @\unspec@;
-    constexpr @\unspec@ rend = @\unspec@;
-    constexpr @\unspec@ crbegin = @\unspec@;
-    constexpr @\unspec@ crend = @\unspec@;
-  }
-
-  // \ref{range.primitives}, range primitives:
-  namespace {
-    constexpr @\unspec@ size = @\unspec@;
-    constexpr @\unspec@ empty = @\unspec@;
-    constexpr @\unspec@ data = @\unspec@;
-    constexpr @\unspec@ cdata = @\unspec@;
-  }
-  template <Range R>
-  difference_type_t<iterator_t<R>> distance(R&& r);
-  template <SizedRange R>
-  difference_type_t<iterator_t<R>> distance(R&& r);
```

Between Clause 6 (Iterators) and Clause 7 (Algorithms), add a new Clause "Ranges" with stable name [ranges]. Move [ranges.general] from [iterators] into the new [ranges] clause, with the following changes:

```diff
-1 This subclause describes components for dealing with
+1 This Clause describes components for dealing with
 ranges of elements.
 2 The following subclauses describe range and view
 requirements, and components for range primitives,
-predefined ranges, and stream ranges, as summarized in
+as summarized in
 Table 7.
```

In Table 7 - Ranges library summary, move "Requirements" from the first line to the last and change the header from `<experimental/ranges/iterator>` to `<experimental/ranges/range>`.

Add a subclause "Header `<experimental/ranges/range>` synopsis" with stable name [range.synopsis] with the following content:

> ```c++
> #include <experimental/ranges/iterator>
> 
> namespace std { namespace experimental { namespace ranges { inline namespace v1 {
>   // \ref{range.access}, range access:
>   namespace {
>     constexpr @\unspec@ begin = @\unspec@;
>     constexpr @\unspec@ end = @\unspec@;
>     constexpr @\unspec@ cbegin = @\unspec@;
>     constexpr @\unspec@ cend = @\unspec@;
>     constexpr @\unspec@ rbegin = @\unspec@;
>     constexpr @\unspec@ rend = @\unspec@;
>     constexpr @\unspec@ crbegin = @\unspec@;
>     constexpr @\unspec@ crend = @\unspec@;
>   }
> 
>   // \ref{range.primitives}, range primitives:
>   namespace {
>     constexpr @\unspec@ size = @\unspec@;
>     constexpr @\unspec@ empty = @\unspec@;
>     constexpr @\unspec@ data = @\unspec@;
>     constexpr @\unspec@ cdata = @\unspec@;
>   }
> 
>   template <class T>
>   using iterator_t = decltype(ranges::begin(declval<T&>()));
> 
>   template <class T>
>   using sentinel_t = decltype(ranges::end(declval<T&>()));
> 
>   template <class>
>   constexpr bool disable_sized_range = false;
> 
>   template <class T>
>   struct enable_view { };
> 
>   struct view_base { };
> 
>   // \ref{ranges.requirements}, range requirements:
> 
>   // \ref{ranges.range}, Range:
>   template <class T>
>   concept bool Range() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.sized}, SizedRange:
>   template <class T>
>   concept bool SizedRange() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.view}, View:
>   template <class T>
>   concept bool View() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.bounded}, BoundedRange:
>   template <class T>
>   concept bool BoundedRange() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.input}, InputRange:
>   template <class T>
>   concept bool InputRange() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.output}, OutputRange:
>   template <class R, class T>
>   concept bool OutputRange() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.forward}, ForwardRange:
>   template <class T>
>   concept bool ForwardRange() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.bidirectional}, BidirectionalRange:
>   template <class T>
>   concept bool BidirectionalRange() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.random.access}, RandomAccessRange:
>   template <class T>
>   concept bool RandomAccessRange() {
>     return @\seebelow@;
>   }
> 
>   // \ref{range.utilities}, range utilities:
>   template <Range R>
>   difference_type_t<iterator_t<R>> distance(R&& r);
> 
>   template <SizedRange R>
>   difference_type_t<iterator_t<R>> distance(R&& r);
> }}}}
> ```

Move [iterator.range] from [iterators] into the new [ranges] clause right after the synopsis. Change its stable name to [range.access] (and fix all references).

Add a new paragraph to [range.access]:

> 1 In addition to being available via inclusion of the `<experimental/ranges/range>`
> header, the customization point objects in \ref{range.access} are available when
> `<experimental/ranges/iterator>` is included.

Change all stable names within [range.access] from [iterator.range.\*] to [range.access.\*] (e.g. [iterator.range.begin] becomes [range.access.begin]). Fix up all references.

Move [range.primitives] from [iterators] to the [ranges] clause right after [ranges.access].

Add a new paragraph to [range.primitives]:

> 1 In addition to being available via inclusion of the `<experimental/ranges/range>`
> header, the customization point objects in \ref{range.primitives} are available when
> `<experimental/ranges/iterator>` is included.

Move section "Range requirements" [ranges.requirements] from [iterator] to the [ranges] clause, right after [range.primitives]. Promote it to a subclause; likewise, promote all its (sub)sections up one level.

From [ranges.range]/p1, remove the definitions of the `iterator_t` and `sentinel_t` template aliases. (They now live in the `<experimental/ranges/range>` synopsis.)

From [ranges.sized]/p1, remove the definition of `disable_sized_range`.

From [ranges.view]/p2, remove the definitions of `enable_view` and `view_base`.

Create a new subclause "Range utilities" ([range.utilities]) after "Range requirements" ([ranges.requirements]). Move the specification of `distance` from [range.primitives] into a new section "`distance`" ([range.distance]).

**Comment by CaseyCarter** [comment]
We also have no synopsis for `<experimental/ranges/concepts>`.

**Comment by timsong-cpp** [comment]
The organization of Clause 6 in general leaves a lot to be desired. `reference_t` and `rvalue_reference_t` are referenced on the second page (in `Readable`'s definition), but aren't defined until ~a dozen pages later.

**Comment by ericniebler** [comment]
I would say adding missing synopses and rearranging content is editorial. Would you agree @CaseyCarter and @jwakely? I'll prepare a patch.

**Comment by jwakely** [comment]
Agreed.

**Comment by CaseyCarter** [comment]
> Do we need a `<experimental/ranges/range>` header?

Adding a new header would definitely *not* be editorial, but filling in existing synopses is.

**Comment by ericniebler** [comment]
@CaseyCarter Do you agree that we should add an `<experimental/ranges/range>` header, in which the range concepts and supporting traits should live? Arguably, the "range" access functions/customization-point-objects (`begin`, `end`, `data`, etc.) should, if not move there outright, be guaranteed to be available after `#include`ing `<experimental/ranges/range>` (although I'm not yet clear on how to express that in standardese).

**Comment by CaseyCarter** [comment]
> Do you agree that we should add an `<experimental/ranges/range>` header?

For the current TS, it would be a bit light for a separate header, even after stealing `begin`, `end`, ... `size`, `data`, `empty` from `<experimental/ranges/iterator>`. I suppose the future content may be heavy enough that some users would want to include `<iterator>` without getting all of the rangey stuff.

> (although I'm not yet clear on how to express that in standardese)

By paraphrasing N4618 24.7 [iterator.range]/1 (which is basically duplicated in [iterator.container]/1):

> In addition to being available via inclusion of the `<iterator>` header, the function templates in 24.7 are available when any of the following headers are included: `<array>`, `<deque>`, `<forward_list>`, `<list>`, `<map>`, `<regex>`, `<set>`, `<string>`, `<string_view>`, `<unordered_map>`, `<unordered_set>`, and `<vector>`.

**Comment by ericniebler** [comment]
> > Do you agree that we should add an `<experimental/ranges/range>` header?
> 
> For the current TS, it would be a bit light for a separate header

So, yea or nay?

**Comment by CaseyCarter** [comment]
> So, yea or nay?

I think it will be easier to change now than later, so yea.

**Comment by ericniebler** [comment]
@jwakely Do you think that breaking part of `<experimental/ranges/iterator>` out into a new `<experimental/ranges/range>` header is editorial or not? @CaseyCarter thinks not.

**Comment by jwakely** [comment]
I agree that adding a new header is not editorial. Moving text around and adding (or removing) synopses would be editorial, as it only changes the presentation of the information. A new header would be an observable change in how users make use of the library.

**Comment by ericniebler** [comment]
Solution description
--------------------

The problems with the concepts and iterator synopses have been handled as editorial changes in 1862bd8 and e15540b. This resolution is describes as a diff to those changes. It suggests adding a new header to hold all range-related functionality: `<experimental/ranges/range>`. This gives us a place to put the range customization points (`begin`, `end`, `size`, etc.), the range concepts, and range utilities.

It will also give us a place to put future range-related functionality, such as a view facade and adaptors, without further bloating `<experimental/ranges/iterator>`, which is quite heavy already.

Proposed Resolution
--------------------

Change [iterators.general]/1 as follows:

```diff
This Clause describes components that \Cpp programs may use to perform
iterations over containers (Clause \cxxref{containers}),
streams~(\cxxref{iostream.format}),
-stream buffers~(\cxxref{stream.buffers}),
-and ranges~(\ref{ranges}).
+and stream buffers~(\cxxref{stream.buffers}).
```

From table "Table 5 — Iterators library summary" [tab:iterators.lib.summary], delete the last line, which reads "Ranges".

From [iterator.synopsis], delete the following lines:

```diff
-  // \ref{iterator.range}, range access:
-  namespace {
-    constexpr @\unspec@ begin = @\unspec@;
-    constexpr @\unspec@ end = @\unspec@;
-    constexpr @\unspec@ cbegin = @\unspec@;
-    constexpr @\unspec@ cend = @\unspec@;
-    constexpr @\unspec@ rbegin = @\unspec@;
-    constexpr @\unspec@ rend = @\unspec@;
-    constexpr @\unspec@ crbegin = @\unspec@;
-    constexpr @\unspec@ crend = @\unspec@;
-  }
-
-  // \ref{range.primitives}, range primitives:
-  namespace {
-    constexpr @\unspec@ size = @\unspec@;
-    constexpr @\unspec@ empty = @\unspec@;
-    constexpr @\unspec@ data = @\unspec@;
-    constexpr @\unspec@ cdata = @\unspec@;
-  }
-  template <Range R>
-  difference_type_t<iterator_t<R>> distance(R&& r);
-  template <SizedRange R>
-  difference_type_t<iterator_t<R>> distance(R&& r);
```

Between Clause 6 (Iterators) and Clause 7 (Algorithms), add a new Clause "Ranges" with stable name [ranges]. Move [ranges.general] from [iterators] into the new [ranges] clause, with the following changes:

```diff
-1 This subclause describes components for dealing with
+1 This Clause describes components for dealing with
 ranges of elements.
 2 The following subclauses describe range and view
 requirements, and components for range primitives,
-predefined ranges, and stream ranges, as summarized in
+as summarized in
 Table 7.
```

In Table 7 - Ranges library summary, move "Requirements" from the first line to the last and change the header from `<experimental/ranges/iterator>` to `<experimental/ranges/range>`.

Add a subclause "Header `<experimental/ranges/range>` synopsis" with stable name [range.synopsis] with the following content:

> ```c++
> #include <experimental/ranges/iterator>
> 
> namespace std { namespace experimental { namespace ranges { inline namespace v1 {
>   // \ref{range.access}, range access:
>   namespace {
>     constexpr @\unspec@ begin = @\unspec@;
>     constexpr @\unspec@ end = @\unspec@;
>     constexpr @\unspec@ cbegin = @\unspec@;
>     constexpr @\unspec@ cend = @\unspec@;
>     constexpr @\unspec@ rbegin = @\unspec@;
>     constexpr @\unspec@ rend = @\unspec@;
>     constexpr @\unspec@ crbegin = @\unspec@;
>     constexpr @\unspec@ crend = @\unspec@;
>   }
> 
>   // \ref{range.primitives}, range primitives:
>   namespace {
>     constexpr @\unspec@ size = @\unspec@;
>     constexpr @\unspec@ empty = @\unspec@;
>     constexpr @\unspec@ data = @\unspec@;
>     constexpr @\unspec@ cdata = @\unspec@;
>   }
> 
>   template <class T>
>   using iterator_t = decltype(ranges::begin(declval<T&>()));
> 
>   template <class T>
>   using sentinel_t = decltype(ranges::end(declval<T&>()));
> 
>   template <class>
>   constexpr bool disable_sized_range = false;
> 
>   template <class T>
>   struct enable_view { };
> 
>   struct view_base { };
> 
>   // \ref{ranges.requirements}, range requirements:
> 
>   // \ref{ranges.range}, Range:
>   template <class T>
>   concept bool Range() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.sized}, SizedRange:
>   template <class T>
>   concept bool SizedRange() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.view}, View:
>   template <class T>
>   concept bool View() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.bounded}, BoundedRange:
>   template <class T>
>   concept bool BoundedRange() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.input}, InputRange:
>   template <class T>
>   concept bool InputRange() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.output}, OutputRange:
>   template <class R, class T>
>   concept bool OutputRange() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.forward}, ForwardRange:
>   template <class T>
>   concept bool ForwardRange() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.bidirectional}, BidirectionalRange:
>   template <class T>
>   concept bool BidirectionalRange() {
>     return @\seebelow@;
>   }
> 
>   // \ref{ranges.random.access}, RandomAccessRange:
>   template <class T>
>   concept bool RandomAccessRange() {
>     return @\seebelow@;
>   }
> 
>   // \ref{range.utilities}, range utilities:
>   template <Range R>
>   difference_type_t<iterator_t<R>> distance(R&& r);
> 
>   template <SizedRange R>
>   difference_type_t<iterator_t<R>> distance(R&& r);
> }}}}
> ```

Move [iterator.range] from [iterators] into the new [ranges] clause right after the synopsis. Change its stable name to [range.access] (and fix all references).

Add a new paragraph to [range.access]:

> 1 In addition to being available via inclusion of the `<experimental/ranges/range>`
> header, the customization point objects in \ref{range.access} are available when
> `<experimental/ranges/iterator>` is included.

Change all stable names within [range.access] from [iterator.range.*] to [range.access.*] (e.g. [iterator.range.begin] becomes [range.access.begin]). Fix up all references.

Move [range.primitives] from [iterators] to the [ranges] clause right after [ranges.access].

Add a new paragraph to [range.primitives]:

> 1 In addition to being available via inclusion of the `<experimental/ranges/range>`
> header, the customization point objects in \ref{range.primitives} are available when
> `<experimental/ranges/iterator>` is included.

Move section "Range requirements" [ranges.requirements] from [iterator] to the [ranges] clause, right after [range.primitives]. Promote it to a subclause; likewise, promote all its (sub)sections up one level.

From [ranges.range]/p1, remove the definitions of the `iterator_t` and `sentinel_t` template aliases. (They now live in the `<experimental/ranges/range>` synopsis.)

From [ranges.sized]/p1, remove the definition of `disable_sized_range`.

From [ranges.view]/p2, remove the definitions of `enable_view` and `view_base`.

Create a new subclause "Range utilities" ([range.utilities]) after "Range requirements" ([ranges.requirements]). Move the specification of `distance` from [range.primitives] into a new section "`distance`" ([range.distance]).

**Comment by CaseyCarter** [comment]
Mini-LWG review likes the distinct range header, there's question about whether it should #include all of <iterator>,or not re-export anything from iterator, or perhaps only provide the concepts and alias templates from <iterator> that are needed to define ranges.
