### ISSUE TITLE
Should there be a range equivalent of std::uninitialized_X?

### ISSUE THREAD

**Issue by cjdb** [ericniebler/stl2#223]
I noticed this morning that there's no Ranges equivalent for uninitialized_fill, etc.
Is there a proposal for these, should I quickly write one up, or have they been excluded?

### Proposed Resolution
Adopt [P1033 "Rangify the uninitialised memory algorithms!"](http://wg21.link/p1033).

**Comment by CaseyCarter** [comment]
We don't have any coverage of the algorithms in `<numeric>` or `<memory>`. They were originally excluded because N3351 didn't cover them, and no one has been motivated enough to include them yet.

**Comment by cjdb** [comment]
I don't think I can get all of `<memory>` done by the deadline (including a draft `Allocator` concept, etc.), but I'll give it an honest try, and let you know when it's done.

**Comment by CaseyCarter** [comment]
> I don't think I can get all of <memory> done by the deadline (including a draft Allocator concept, etc.),

I guarantee you can't get all of `<memory>` done, and we wouldn't want to: it's out of the scope of the TS, and the ensuing discussion would delay the TS another 6 months to a year. If, however, you were to specify the *algorithms* in `<memory>` - uninitialized_fill etc. - then you would have a better chance of being done before the deadline and I'm confident it wouldn't derail the TS.

**Comment by cjdb** [comment]
> If, however, you were to specify the _algorithms_ in `<memory>` - uninitialized_fill etc. - then you would have a better chance of being done before the deadline and I'm confident it wouldn't derail the TS.

Will report back when it's done. Should I create a branch and demo in cmcstl2 as well?

**Comment by CaseyCarter** [comment]
Sure, if you are motivated to do so.

**Comment by CaseyCarter** [comment]
I'll even start you off with an untested may-not-even-compile implementation of `uninitialized_copy` I whipped up after Oulu that's been waiting for me to finish it:

```c++
// cmcstl2 - A concept-enabled C++ standard library
//
//  Copyright Casey Carter 2016
//
//  Use, modification and distribution is subject to the
//  Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt)
//
// Project home: https://github.com/caseycarter/cmcstl2
//
#ifndef STL2_DETAIL_ALGORITHM_UNINITIALIZED_COPY_HPP
#define STL2_DETAIL_ALGORITHM_UNINITIALIZED_COPY_HPP

#include <new>
#include <stl2/iterator.hpp>
#include <stl2/detail/fwd.hpp>
#include <stl2/detail/tagged.hpp>

STL2_OPEN_NAMESPACE {
	///////////////////////////////////////////////////////////////////////////
	// uninitialized_copy [Extension]
	//
	template <InputIterator I, Sentinel<I> S, ForwardIterator O>
	requires
		models::Constructible<value_type_t<O>, reference_t<I>> &&
		models::Same<value_type_t<O>&, reference_t<O>>
	tagged_pair<tag::in(I), tag::out(O)>
	uninitialized_copy(I first, S last, O result)
	{
		using T = value_type_t<O>;
		auto saved = result;
		try {
			for (; first != last; ++first, void(++result)) {
				::new(static_cast<void*>(&*result)) T(*first);
			}
		} catch(...) {
			for (; saved != result; ++saved) {
				(*saved).~T();
			}
			throw;
		}
		return {__stl2::move(first), __stl2::move(result)};
	}

	template <InputRange Rng, class O>
	requires
		models::ForwardIterator<__f<O>> &&
		models::Constructible<value_type_t<__f<O>>, reference_t<iterator_t<Rng>>> &&
		models::Same<value_type_t<__f<O>>&, reference_t<__f<O>>>
	tagged_pair<tag::in(safe_iterator_t<Rng>), tag::out(__f<O>)>
	uninitialized_copy(Rng&& rng, O&& result)
	{
		return __stl2::uninitialized_copy(
			__stl2::begin(rng), __stl2::end(rng), __stl2::forward<O>(result));
	}

	///////////////////////////////////////////////////////////////////////////
	// uninitialized_copy_n [Extension]
	//
	template <class I, class O>
	requires
		models::InputIterator<__f<I>> &&
		models::ForwardIterator<__f<O>> &&
		models::Constructible<value_type_t<__f<O>>, reference_t<__f<I>>> &&
		models::Same<value_type_t<__f<O>>&, reference_t<__f<O>>>
	tagged_pair<tag::in(__f<I>), tag::out(__f<O>)>
	uninitialized_copy_n(I&& first, difference_type_t<__f<I>> n, O&& out)
	{
		auto counted = __stl2::make_counted_iterator(__stl2::forward<I>(first), n);
		auto result = uninitialized_copy(__stl2::move(counted),
			default_sentinel{}, __stl2::forward<O>(out));
		return {result.in().base(), result.out()};
	}
} STL2_CLOSE_NAMESPACE

#endif
```

**Comment by cjdb** [comment]
I won't have a demo by the deadline; is it worth trying to put changes into the document for review? I've focused on getting a demo ready before writing up the proposal.

**Comment by ericniebler** [comment]
Done.
