### ISSUE TITLE
review common_type and common_reference in light of LWG#2763

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#225]
See https://cplusplus.github.io/LWG/lwg-defects.html#2763

**Comment by ericniebler** [comment]
> If any of the types computed above are ill-formed, then `COMMON_REF(A, B)` is ill-formed.

This is too sweeping. It needs to be way more precise.

**Comment by CaseyCarter** [comment]
@ericniebler: Am I crazy, or did we not review and move to ready in LWG a PR that updated the wording for `common_type` and `common_reference`? Should this be closed as a duplicate?

**Comment by ericniebler** [comment]
We mos def have `Common<void, void>` working now. At one point I believed that the language "If any of the types computed above are ill-formed," was insufficiently precise, but I don't know now what my objection was. I'm happy to close this.
