### ISSUE TITLE
Document aliases for a concept's associated types together with that concept

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#227]
In [iterator.traits]:

> WI is the name of a type that satisfies the `WeaklyIncrementable` concept (24.2.4), `R` is the
> name of a type that satisfies the `Readable` concept (24.2.2), and `II` is the name of a type that satisfies the `InputIterator` concept (24.2.9) concept, the types
> `difference_type_t<WI>`
> `value_type_t<R>`
> `iterator_category_t<II>`
> be defined as the iterator’s difference type, value type and iterator category, respectively.

But the concepts `WeaklyIncrementable`, `Readable`, and `InputIterator` are defined in terms of these type aliases, so the type aliases can't depend on the concepts.

**Comment by CaseyCarter** [comment]
This doesn't say the aliases depend on the concepts - the aliases stand alone and are defined elsewhere. *This* statement exists to provide the semantic link between the aliases and the terms "difference type," "value type," and "iterator category" used to describe iterators in the text. (We are notably missing that link for "reference type." We define `reference_t`, but I think we don't state anywhere that the "reference type" of an iterator type `I` is `reference_t<I>`.)

I think it would be an improvement to make those semantic links earlier in the document, ideally when the associated concept is introduced. E.g., "`difference_type_t<I>` is known as the "difference type" of the `WeaklyIncrementable` type `I`."

**Comment by CaseyCarter** [comment]
I am satisfied that the reorganization of [iterator] in 853222815e48dee0fc934e6eef3d8c7b008bb35c fixes this issue by moving [iteator.assoc.types] ahead of the concept definitions.
