### ISSUE TITLE
Review concept definitions for misuse of the term "rvalue"

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#230]
Rvalues can be either xvalues or prvalues. Are there cases where it matters? Do we need to be more specific anywhere?

**Comment by CaseyCarter** [comment]
After a full sweep of all of the concept definitions in the TS, the papers-in-flight, and (I think) the issues list, I'm satisfied that our uses of "rvalue" don't need to be made more specific. ("xvalue", on the other hand, is a good indicator of "things that can potentially break when they interact with proxy references," but that as they say is [a different question](https://github.com/ericniebler/stl2/issues/226).)

I'm going to close this as NAD.
