### ISSUE TITLE
Why doesn't the transform algorithm constrain its function argument with IndirectlyCallable?

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#231]
It uses `indirect_result_of_t` so it gets a sort of constraint, but shouldn't it also use the concept?

**Comment by CaseyCarter** [comment]
`indirect_result_of<F(Args...)>` has no member named `type` if `IndirectCallable<F, Args...>()` is not satisfied, so `transform` is implicitly constrained with `IndirectCallable`. Whether or not the `IndirectCallable` constraint appears directly in the `transform` declaration, it is necessary to constrain the output sequence to accept the output of the transformation with `Writable`.
