### ISSUE TITLE
Kill the Readability requirement for i++ for InputIterators.

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#232]
### Proposed Resolution

Adopt the wording in P0541.

**Comment by ericniebler** [comment]
Whoa, just noticed that `move_iterator::operator++(int)` is defined in terms of the underlying iterator's _pre_-increment operator, _and_ `move_iterator` purports to work with input iterators. This is hella broken. Not specific to STL2. Probably needs a new LWG issue.

**Comment by ericniebler** [comment]
In addition to the known problems with `InputIterator`'s postfix increment operator comes the implementation difficulty of having to implement iterator adaptors like `move_iterator` when the underlying iterator may have an `operator++(int)` that returns some unknown proxy that caches state (e.g. `istreambuf_iterator`).

**Comment by CaseyCarter** [comment]
If we do not remove the requirement for post-increment on `InputIterator`, we need to properly require that `*i++` equals the prior value of `*i`.

**Comment by ericniebler** [comment]
> If we do not remove the requirement for post-increment on `InputIterator` ...

To be clear, nobody is proposing dropping post-increment for `InputIterator`. I'm suggesting we drop the requirement that the type of `i++` satisfy `Readable`.

**Comment by tahonermann** [comment]
> I'm suggesting we drop the requirement that the type of i++ satisfy <tt>Readable</tt>

If <tt>Readable</tt> isn't satisfied for <tt>i++</tt>, does <tt>i++</tt> continue to serve any purpose for input iterators?  Currently, there are no other requirements for the post-increment result, not even that the result is convertible to the iterator type.  It looks to me like <tt>i++</tt> would just be a hobbled form of <tt>++i</tt>.

I'm looking forward to your paper on this subject (and would be happy to provide feedback on it should you care to share a draft).  I had to modify test code to work around the lack of support for <tt>operator++(int)</tt> in the range-v3 port of text_view (see the FIXME comment at https://github.com/tahonermann/text_view-range-v3/blob/master/test/test-text_view.cpp#L811) and found separating the dereference and increment to be annoying.

**Comment by ericniebler** [comment]
> If `Readable` isn't satisfied for `i++`, does `i++` continue to serve any purpose for input iterators?

Yes, for code like this:

```c++
for (auto i = x.begin(); i != x.end(); i++)
```

Lots of code like this exists in the world.

> found separating the dereference and increment to be annoying.

If your code is generic, you should avoid postfix increment on input iterators since the alternative is often more efficient. Nothing is stopping a particular iterator from supporting `Readable` `i++`, or from non-generic code from making use of it.

**Comment by tahonermann** [comment]
> Yes, for code like this:
> 
> `for (auto i = x.begin(); i != x.end(); i++)`
> 
> Lots of code like this exists in the world.

Certainly.  I meant that it serves no purpose in that all remaining uses could be trivially rewritten as pre-increment without any impact to program semantics.

> > found separating the dereference and increment to be annoying.

> If your code is generic, you should avoid postfix increment on input iterators since the alternative is often more efficient. Nothing is stopping a particular iterator from supporting Readable i++, or from non-generic code from making use of it.

Well, in this case, the code was intending to validate that post-increment actually worked :)

I agree with avoiding post-increment, or at least, avoiding gratuitous use of it as in the loop statement above.  Despite the potential for overhead, I do appreciate the expressiveness provided by post-increment:

```
if (*i++ == 'x')
    y = *i++;
```

as opposed to:

```
if (*i == 'x')
    y = *++i;
++i;
```

Not that you aren't already very familiar with such concerns, but these are the reasons I'm loathe to lose the readability requirement.
