### ISSUE TITLE
projected<I>::value_type incorrectly decaying arrays to pointers 

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#236]
The following code does not compile with `projected` as it is currently defined in the latest draft.

``` c++
int matrix[3][4] = {};
std::experimental::ranges::for_each(matrix, [](int(&)[4]){});
```

**Proposed resolution:**

The fix is to change the definition of `projected` in [projected] as follows:

``` diff
template <Readable I, IndirectRegularCallable<I> Proj>
struct projected {
-  using value_type = decay_t<indirect_result_of_t<Proj&(I)>>;
+  using value_type = remove_cv_t<remove_reference_t<indirect_result_of_t<Proj&(I)>>>;
  indirect_result_of_t<Proj&(I)> operator*() const;
};
```

**Comment by CaseyCarter** [comment]
Multidimensional arrays are the killer use case for arrays as value types. If we want `int[3][4]` to be a range, and I don't think there's a serious counterargument, we're going to have to have arrays as "value types."

This has dire consequences for #183.

**Comment by CaseyCarter** [comment]
Also, we need to define `uncvref_t` already so we can stop trying to use `decay_t` just because it's shorter to type.

**Comment by ericniebler** [comment]
See also #237

**Comment by ericniebler** [comment]
> Also, we need to define `uncvref_t` already so we can stop trying to use `decay_t` just because it's shorter to type.

https://cplusplus.github.io/LWG/lwg-active.html#1120

**Comment by CaseyCarter** [comment]
> > Also, we need to define `uncvref_t` already so we can stop trying to use `decay_t` just because it's shorter to type.

> https://cplusplus.github.io/LWG/lwg-active.html#1120

http://wg21.link/p0550
