### ISSUE TITLE
P0022 breaks `indirect_result_of`

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#238]
By removing my undocumented fix to `indirect_result_of` that `remove_reference`s the function type before passing it to `IndirectCallable`:

``` c++
template <class F, class... Is>
requires IndirectCallable<remove_reference_t<F>, Is...>()
struct indirect_result_of<F(Is...)> :
result_of<F(value_type_t<Is>...)> { };
```

Without that `remove_reference_t`, when `F` is a reference type, we require the trivially satisfiable `CopyConstructible<F>` instead of the desired `CopyConstructible<remove_reference_t<F>>`. 

`indirect_result_of` is used directly in the declarations of the `transform` algorithms, and in `projected`. As a a result, after the change, `transform` doesn't properly require the transformation function - and no algorithm properly requires its projection arguments - to be `CopyConstructible`.

### Proposed Resolution [SUPERSEDED]

Wording is relative to P0022R2. In section [indirectcallables.indirectfunc], change the definition of `indirect_result_of` to read:

``` diff
template <class F, class... Is>
-    requires IndirectCallable<F, Is...>()
+    requires IndirectCallable<decay_t<F>, Is...>()
struct indirect_result_of<F(Is...)> :
    result_of<F(reference_t<Is>...)> { };
```

(Note that this differs from the prior definition only by replacing `F` with `decay_t<F>` in the parameters of `IndirectCallable`.)

**Comment by ericniebler** [comment]
Are we certain that `remove_reference_t` is correct here? It may turn a function reference type into a function type, and passing a function type to `IndirectCallable` isn't likely to end well. I suggest we use `decay_t` here.

**Comment by CaseyCarter** [comment]
Yes I'm testing that preparatory to making the change here.

**Comment by ericniebler** [comment]
Hold off on edits to cmcstl2. I'm working on a huge diff to replace all the callable wrapper stuff with calls to `invoke`.

**Comment by CaseyCarter** [comment]
### Proposed Resolution:

Wording is relative to P0022R2. In section [indirectcallables.indirectfunc], change the definition of `indirect_result_of` to read:

> ```c++
template <class F, class... Is>
  requires IndirectCallable<decay_t<F>, Is...>()
struct indirect_result_of<F(Is...)> :
  result_of<F(reference_t<Is>...)> { };
```

(Note that this differs from the prior definition only by replacing `F` with `decay_t<F>` in the parameters of `IndirectCallable`.)

**Comment by ericniebler** [comment]
Procedural suggestion: we put proposed resolution up top by editing the initial issue description. That way we can find it quickly in committee.

**Comment by CaseyCarter** [comment]
Review discussion:

* Decaying the type passed to `IndirectCallable` but not to `result_of` results in testing the result type of differently cv-qualified function object types. Open a separate issue for this after applying 238.

**Comment by CaseyCarter** [comment]
Superseded by the resolution of #286.
