### ISSUE TITLE
Subsumption relationships for the Core Concepts

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#24]
Relationships between the Core Concepts need to reflect the rules of the core language. Specifically, if T and U are the same type, then obviously:
- T is derived from U
- T is convertible to U
- T and U share a common type T.

We need to make these facts explicit in the concept design by ensuring that `Same<T,U>` subsumes `Derived<T,U>`, `Convertible<T,U>`, and `Common<T,U>` so that users can portably rely on templates requiring `Same<T,U>` being unambiguously overloadable with templates requiring one of the preceding. Doing so is simple, it only requires prepending `Same<T,U> ||` to the definitions of Derived, Convertible, and Common.

I think `CommonType<T,T>` should also be hardwired to `T` to reflect this relationship - user overloads of `std::common_type<T,T>` to a type other than `T` should be ignored and or undefined behavior:

```
template <class T, class U>
using CommonType =
  typename std::conditional_t<std::is_same<T, U>::value, meta::id<T>,
    std::common_type<T, U>>::type;
```

There is a small problem with Same subsuming Derived: `Derived<T,T>` will be true for non-class types which is not the case for `std::is_base_of<T,T>`. I think that we should leave that discrepancy in place: the purpose of the Derived concept is to model is-a, and an int is-a int. Alternatively we could maintain the weirdness of `std::is_base_of` in the definition of Derived:

```
template <class T, class U>
concept bool Derived =
  std::is_class<T>::value &&
  std::is_class<U>::value &&
  (Same<T,U> || std::is_base_of<U, T>::value);
```

but that makes overload disambiguation extremely awkward:

```
void f(auto, auto); // unconstrained
template <class T, Same<T> U>
void f(T, U); // T and U are the same non-class type
template <class T, class U>
  requires std::is_class<T>::value && std::is_class<U>::value && Same<T,U>
void f(T, U); // T and U are the same class type
template <class T, Derived<T> U>
void f(T, U); // U is a class type different than but derived from T
```

in comparison to:

```
void f(auto,auto); // unconstrained
template <class T, Same<T> U>
void f(T, U); // T and U are the same possibly-class type
template <class T, Derived<T> U>
void f(T, U); // U is a class type different than but derived from T
```

I strongly prefer allowing `Derived<int,int>` to be true. The inconsistency with `std::is_base_of<int,int>` is somewhat justified by the different name - we could even rename Derived to IsA.

**Comment by ericniebler** [comment]
Not sure about this one. I've heard @asutton say that most of these core concepts need to be compiler intrinsics. Andrew?

**Comment by asutton** [comment]
There are a lot of implications among type traits and intrinsics that
would could model, either in the library or in the core language.

This needs a paper that fully motivates and enumerates those
relationships. It can't just be a bug report.

Andrew Sutton

**Comment by CaseyCarter** [comment]
I'll keep gathering the relationships I find implementing N4382 in gcc, and write them up in a paper. Hopefully others will note similar relationships herein that I can include as well.

**Comment by ericniebler** [comment]
The subsumption Casey talks about here (sticking `Same<T,U>() ||` in all the core concepts) would have deleterious effects on compile times, for modest (IMO) expressive gain. Closing this. @CaseyCarter shout if you disagree.
