### ISSUE TITLE
Should Writable require Semiregular, or "Move-Defaultable"

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#240]
P0022R2 changes the `Readable` concept by replacing the `Semiregular` requirement with `Movable` and `DefaultConstructible`; this allows move-only types like `unique_ptr<int>` and `optional<thread>` to model `Readable`.

P0022R2 notably does _not_ make the symmetric change to the `Writable` concept. Why should I be forbidden to write to these move-only types from which I may read?

Note that this discrepancy is exacerbated by the fact that both implementations ([cmcstl2](https://github.com/CaseyCarter/cmcstl2/blob/master/include/stl2/detail/iterator/concepts.hpp#L223), [range-v3](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/utility/iterator_concepts.hpp#L176)) of the TS have _already_ implemented the same relaxation for `Writable`.

EDIT:

### Proposed Resolution

[_Editorial note:_ Change the definition of `Writable` ([iterators.writable]) as follows: --_end note_]

```diff
template <class Out, class T>
concept bool Writable() {
-  return Semiregular<Out>() &&
+  return Movable<Out>() && DefaultConstructible<Out>() &&
    requires(Out o, T&& t) {
      *o = std::forward<T>(t); // not required to be equality preserving
    };
}
```

**Comment by ericniebler** [comment]
I think it was just an oversight.

**Comment by ericniebler** [comment]
Huh. Where do we currently require that iterators are copyable?
