### ISSUE TITLE
Customizing iter_move and iter_swap is needlessly complicated

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#242]
The specifications of `iter_move` and `iter_swap` in P0022R2 requires user customizations found via ADL to compete in overload resolution with the "default" implementations which are constrained functions that accept forwarding references. Consider the example:

``` c++
class my_iterator { /*...some input iterator...*/ };
some_type iter_move(const my_iterator& i) { /*...stuff...*/ }

int main() {
  iter_move(my_iterator{});
}
```

oops, the `iter_move` customization isn't called because the default is a better match for rvalues. Let's change the program then:

``` c++
class my_iterator { /*...some input iterator...*/ };
some_type iter_move(my_iterator&& i) { /*...stuff...*/ }

int main() {
  iter_move(my_iterator{});
}
```

Now it works. Except that I also want my customization to work for lvalues. I suppose I need to take a forwarding reference, and constrain it to have the same decayed type:

``` c++
class my_iterator { /*...some input iterator...*/ };
template<class I>
  requires ranges::Same<my_iterator, std::decay_t<I>>()
some_type iter_move(I&& i) { /*...stuff...*/ }

int main() {
  iter_move(my_iterator{});
  my_iterator i{};
  iter_move(i);
}
```

Oops: now `my_iterator` doesn't satisfy `Readable`. `iter_move` is ambiguous since it is neither more specialized nor more constrained than the default implementation (or vice versa). After consulting an expert on partial ordering of templates, I discover that I need to make my `iter_move` more constrained than the default implementation by duplicating its constraints:

``` c++
template<class I>
  requires ranges::Same<my_iterator, std::decay_t<I>>() &&
  requires(I& i) { {*i} -> auto&&; };
some_type iter_move(I&& i) { /*...stuff...*/ }
```

or make lots of implementations that are more specialized:

``` c++
some_type actually_iter_move(const my_iterator& i) { /*...stuff...*/ }
decltype(auto) iter_move(const my_iterator& i) { return actually_iter_move(i); }
decltype(auto) iter_move(my_iterator& i) { return actually_iter_move(i); }
decltype(auto) iter_move(my_iterator&& i) { return actually_iter_move(i); }
decltype(auto) iter_move(const my_iterator&& i) { return actually_iter_move(i); }
```

I leave it to the reader to demonstrate the same problem exists for `iter_swap`, except magnified by the fact that `iter_swap` has two parameters and that `iter_swap` has a "poison pill" deleted overload thrown into the mix.

### Proposed Resolution:

[_Editorial note:_ Replace the text of [iterator.utils.iter_move] with the following: --_end note_]

1\. The name `iter_move` denotes a _customization point object_ ([customization.point.object]). The effect of the expression `ranges::iter_move(E)` for some expression `E` is equivalent to the following:

2\. `iter_move(E)`, if that expression is well-formed when evaluated in a context that does not include `ranges::iter_move` but does include the lookup set produced by argument-dependent lookup ([basic.lookup.argdep]).

3\. Otherwise, if `E` is dereferenceable
> (3.1) If `*E` is an lvalue, `std::move(*E)`
> (3.2) Otherwise, `*E`

4\. Otherwise, `ranges::iter_move(E)` is ill-formed.

5\. If `ranges::iter_move(E)` does not equal `*E`, the program is ill-formed with no diagnostic required.

[_Editorial note:_ Replace the text of [iterator.utils.iter_swap] with the following: --_end note_]

1\. The name `iter_swap` denotes a _customization point object_ ([customization.point.object]). The effect of the expression `ranges::iter_swap(E1, E2)` for some expressions `E1` and `E2` is equivalent to the following:

2\. `(void)iter_swap(E1, E2)`, if that expression is well-formed when evaluated in a context that does not include `ranges::iter_swap` but does include the lookup set produced by argument-dependent lookup ([basic.lookup.argdep]) and the following declaration:

> ```c++
> void iter_swap(auto, auto) = delete;
> ```

3\. Otherwise, if the expressions `E1` and `E2` both satisfy `Readable`, and if the reference type of `E1` is swappable with ([concepts.lib.corelang.swappable) the reference type of `E2`, then `ranges::swap(*E1, *E2)`

4\. Otherwise, if the types `T1` and `T2` of `E1` and `E2` satisfy `IndirectlyMovableStorable<T1, T2>() && IndirectlyMovableStorable<T2, T1>()`, exchanges the values denoted by `E1` and `E2`.
> (4.1) `ranges::iter_swap(E1, E2)` is a constant expression if and only if `E1` and `E2` are constant expressions and the required operations of `IndirectlyMovableStorable<T1, T2>()` and `IndirectlyMovableStorable<T2, T1>()` are constant expressions.
> (4.2) `ranges::iter_swap(E1, E2)` is `noexcept` if and only if `E1` and `E2` are `noexcept` and the required operations of `IndirectlyMovableStorable<T1, T2>()` and `IndirectlyMovableStorable<T2, T1>()` are `noexcept`.

5\. Otherwise, `ranges::iter_swap(E1, E2)` is ill-formed.

6\. If `ranges::iter_swap(E1, E2)` does not swap the values denoted by the expressions `E1` and `E2`, the program is ill-formed with no diagnostic required.

**Comment by CaseyCarter** [comment]
### Suggested solution

Use a multistep specification for these customization points like that used for the others, a la:

1. If ADL succeeds in an overload set containing "poisin pill", call that.
2. Otherwise throw at the default overload set.
3. Otherwise fail.

I am also inclined to say that `iter_move` (and possibly `iter_swap` as well?) should `lvalue-ify` its argument(s) before processing (though I have no idea how to specify that concisely) so that lvalue customizations are triggered for rvalue arguments. I can't imagine wanting to define an iterator with differing behavior for these customization points depending on rvalue vs. lvalue, and I note that both implementations of `iter_move` already perform such "lvalue-ization."

**Comment by CaseyCarter** [comment]
The overload of `iter_swap` in namespace `std` has the signature:
```c++
template<class ForwardIterator1, class ForwardIterator2>
void iter_swap(ForwardIterator1 a, ForwardIterator2 b);
```
so the poison pill should be:
```c++
void iter_swap(auto, auto) = delete;
```
which also makes it a teensy bit easier to specialize than the currently specified `iter_swap(auto&&, auto&&)` poison pill.

**Comment by ericniebler** [comment]
### Proposed Resolution (incomplete):

Replace the text of [iterator.utils.iter_swap] with:

1\. The name `iter_swap` denotes a _customization point object_ (17.5.2.1.5). The effect of the expression `ranges::iter_swap(E1, E2)` for some expressions `E1` and `E2` is equivalent to the following:

2\. `(void)iter_swap(E1, E2)`, if that expression is well-formed when evaluated in a context that does not include `ranges::iter_swap` but does include the following declaration:

> ```c++
> void iter_swap(auto, auto) = delete;
> ```

3\. Otherwise, `(void)iter_swap(E1, E2)`, if that expression is well-formed when evaluated in a context that does not include `ranges::iter_swap` but does include the following `iter_swap` function templates:

> ```c++
> // exposition only
> template <class I1, class I2,
>     Readable _R1 = remove_reference_t<I1>,
>     Readable _R2 = remove_reference_t<I2>>
>     requires Swappable<reference_t<_R1>, reference_t<_R2>>()
> void iter_swap(I1&& r1, I2&& r2)
>     noexcept(is_nothrow_swappable_with_v<reference_t<_R1>, reference_t<_R2>>);
> ```
> >  (3.1) _Effects:_ Equivalent to `ranges::swap(*r1, *r2)`
>
> ```c++
> template <class I1, class I2,
>     Readable _R1 = std::remove_reference_t<I1>,
>     Readable _R2 = std::remove_reference_t<I2>>
>     requires !Swappable<reference_t<_R1>, reference_t<_R2>>() &&
>         IndirectlyMovableStorable<_R1, _R2>() &&
>         IndirectlyMovableStorable<_R2, _R1>()
> void iter_swap(I1&& r1, I2&& r2)
>     noexcept(is_nothrow_indirectly_movable_v<_R1, _R2> &&
>         is_nothrow_indirectly_movable_v<_R2, _R1>);
> ```
> > (3.2) _Effects:_ Exchanges values referred to by two `Readable` objects.
> > 
> > (3.3) [ _Example:_ Below is a possible implementation:
> > ```c++
> > value_type_t<_R1> tmp(iter_move(r1));
> > *r1 = iter_move(r2);
> > *r2 = std::move(tmp);
> > ```
> > -- _end example_ ]

4\. Otherwise, `ranges::iter_swap(E1, E2)` is not well-formed.

5\. If the `iter_swap` function selected by overload resolution does not swap the values denoted by the expressions `E1` and `E2`, the program is ill-formed with no diagnostic required.

**Comment by CaseyCarter** [comment]
> 2\. `(void)iter_swap(E1, E2)`, if that expression is well-formed when evaluated in a context that does not include `ranges::iter_swap` but does include the following declaration:

> > ```c++
> > void iter_swap(auto, auto) = delete;
> > ```

This is where the "lvalue-ification" needs to happen: I'd like `iter_move(foo&)` to work for `foo` rvalues.

> 3\. Otherwise, `(void)iter_swap(E1, E2)`, if that expression is well-formed when evaluated in a context that does not include `ranges::iter_swap` but does include the following `iter_swap` function templates:

This lookup context must also include the poison pill or use a different exposition-only name for the implementation functions so that it cannot resolve to `std::iter_swap`. We can also omit the `(void)` cast since both implementations return `void`.

**Comment by ericniebler** [comment]
I am mildly against lvalue-ification. It seems the the sort of surprising, overly-nannying monkey business that the standard library aught to steer clear of.\

If we had to do it (and I prefer we don't) we could specify the behavior in terms of behavior equivalent to:

```c++
auto _Lval(auto&& f) noexcept ->
  decltype((f)) { return f; }
```

I.e. `ranges::iter_swap(E1,E2)` is equivalent to `(void)iter_swap(_Lval(E1),_Lval(E2))` in the context blah, blah, blah.

**Comment by CaseyCarter** [comment]
> I am mildly against lvalue-ification. It seems the the sort of surprising, overly-nannying monkey business that the standard library aught to steer clear of.

I can live with that. I expect most `iter_move` and `iter_swap` overloads will accept `const&` and bind to everything, which works properly without lvalue-ification. If you need to discriminate non-`const` lvalues you're doing something "funny" and you can find an expert in template partial ordering to explain the gory details.

**Comment by ericniebler** [comment]
### Proposed Resolution (incomplete):

Replace the text of [iterator.utils.iter_swap] with:

1\. The name `iter_swap` denotes a _customization point object_ (17.5.2.1.5). The effect of the expression `ranges::iter_swap(E1, E2)` for some expressions `E1` and `E2` is equivalent to the following:

2\. `(void)iter_swap(E1, E2)`, if that expression is well-formed when evaluated in a context that does not include `ranges::iter_swap` but does include the following declaration:

> ```c++
> void iter_swap(auto, auto) = delete;
> ```

3\. Otherwise, if the expressions `E1` and `E2` both satisfy `Readable`, and if the reference type of `E1` is swappable with ([concepts.lib.corelang.swappable) the reference type of `E2`, then `ranges::swap(*E1, *E2)`

4\. Otherwise, let `FWD(X)` be `static_cast<decltype(X)&&>(X)`. If `E1` and `E2` satisfy `IndirectlyMoveStorable`, and `E2` and `E1` satisfy `IndirectlyMoveStorable`, then:

> ```c++
> {
>     auto&& e1 = E1;
>     auto&& e2 = E2;
>     value_type_t<remove_reference_t<decltype(e1)>> tmp(ranges::iter_move(FWD(e1)));
>     *FWD(e1) = ranges::iter_move(FWD(e2));
>     *FWD(e2) = std::move(tmp);
> }
> ```
> 
> (4.1) [ _Note:_ The implementation is free to perform these indirect moves in the reverse order; that is, `iter_move` from `e2` into a temporary, `iter_move` from `e1` into `*e2`, and then from the temporary into `*e1`. --_end note_ ]

5\. Otherwise, `ranges::iter_swap(E1, E2)` is ill-formed.

6\. If the `iter_swap` function selected by overload resolution does not swap the values denoted by the expressions `E1` and `E2`, the program is ill-formed with no diagnostic required.

**Comment by CaseyCarter** [comment]
> 2. (void)iter_move(E) ...

`iter_move(E)`

> (3.1) If the type of `*E` is a reference type

if `*E` is an lvalue

> 4. ...

* `IndirectlyMoveStorable` is not nasty enough: `IndirectlyMovableStorable`.
* `E1` and `E2` are expressions, `IndirectlyMovableStorable` is a concept over types.
* The implementation detail is unnecessary. With the requirements in place we can simply "exchange the values denoted by `E1` and `E2`."

Why not:

> If the types `T1` and `T2` of `E1` and `E2` satisfy `IndirectlyMovableStorable<T1, T2>() && IndirectlyMovableStorable<T2, T1>()`, exchanges the values denoted by `E1` and `E2`.

**Comment by ericniebler** [comment]
> Why not:
> 
> > If the types `T1` and `T2` of `E1` and `E2` satisfy `IndirectlyMovableStorable<T1, T2>() && IndirectlyMovableStorable<T2, T1>()`, exchanges the values denoted by `E1` and `E2`.

If `E1` is an lvalue, `T1` will still not be a reference type, right? That's fine. But this still feels underspecified. When is it `constexpr`? When is it `noexcept`?

**Comment by CaseyCarter** [comment]
> If E1 is an lvalue, T1 will still not be a reference type, right?

Right; type and value category are orthogonal until `decltype` comes into the picture and mixes them together. "The type of <expression>" is `remove_reference_t<decltype((<expression>))>`. 

> When is it `constexpr`? When is it `noexcept`?

Yes, I've gone too far and made the operation underspecified instead of overspecified. Could we get away with "<expression> shall be `noexcept` if the operations required by the constraint are `noexcept`, and a constant expression if `E1` and `E2` are constant expressions and the required operations can appear in a constant expression"?

**Comment by ericniebler** [comment]
> Could we get away with "<expression> shall be `noexcept` if the operations required by the constraint are `noexcept`, and a constant expression if `E1` and `E2` are constant expressions and the required operations can appear in a constant expression"?

Probably not.  I'm giving it some thought.

**Comment by ericniebler** [comment]
> Could we get away with [...]

I strongly suspect the committee would send us back to the drawing board with that.

### How about this:

Let `e1` and `e2` be the objects denoted by `E1` and `E2` respectively. Given a hypothetical function template `iter_exchange` equivalent to:

```c++
// exposition only
template <class X, class Y>
constexpr auto iter_exchange(X&& x, Y&& y) 
    noexcept(is_nothrow_indirectly_movable_v<remove_reference_t<X>, remove_reference_t<Y>>) {
  value_type_t<remove_reference_t<X>> old_value = iter_move((X&&)x);
  *(X&&)x = iter_move((Y&&)y);
  return old_value;
}
```

then `ranges::iter_swap(E1,E2)` is equivalent to _either_:
- `*e1 = iter_exchange(e2, e1)`, _or_
- `*e2 = iter_exchange(e1, e2)`

**Comment by ericniebler** [comment]
(Also, `iter_exchange` might be a handy thing to have. I wonder if I should propose it just so that we can use it from `iter_swap`.)

**Comment by CaseyCarter** [comment]
> I strongly suspect the committee would send us back to the drawing board with that.

Yes, I have no trouble imagining STL's reaction. "operations required by `IndirectlyMovableStorable`"  might be more acceptable. I understand that I'm stepping out of the LWG norm here, but I think we would be doing both the specifiers and the readers of the standard library specification a huge favor by introducing an idiom for "noexcept(<Expression>) is true if the operations required by <Concept> are noexcept, and <Expression> is a constant expression if the operations required by <Concept> are constexpr." That single sentence carries the same meaning as an entire paragraph of "as if by: <Implementation>" except that it's stated explicitly instead something that must be deduced from <implementation>,

**Comment by CaseyCarter** [comment]
> (Also, `iter_exchange` might be a handy thing to have. I wonder if I should propose it just so that we can use it from `iter_swap`.)

Despite the rant above, I agree with this notion.

**Comment by ericniebler** [comment]
>  I have no trouble imagining STL's reaction

Why do you have to imagine STL's reaction? Can't you, like, walk down the hall and ask him?

**Comment by CaseyCarter** [comment]
> Why do you have to imagine STL's reaction? Can't you, like, walk down the hall and ask him?

He sits 12 feet from me in the team room. I'd ask but he has been out of the office for a couple of hours.

**Comment by CaseyCarter** [comment]
> then `ranges::iter_swap(E1,E2)` is equivalent to _either_:
- `*e1 = iter_exchange(e2, e1)`, _or_
- `*e2 = iter_exchange(e1, e2)`

`ranges::iter_swap` should always be a `void` prvalue:

- `void(*e1 = iter_exchange(e2, e1))`, _or_
- `void(*e2 = iter_exchange(e1, e2))`

**Comment by ericniebler** [comment]
Does that mean you are OK with the `iter_exchange` solution, or do you still want to see if your see-the-concept-requirements-stupid verbiage will fly?

**Comment by CaseyCarter** [comment]
I'd prefer see-the-concept-requirements because I can imagine it applying to cases all through the standard library. It's a no-brainer that given
> ```c++
> template <class X, class Y>
>   requires Concept<X, Y>()
> f(X, Y);
> ```
>
> *Effects:* [...stuff...].

or

> If the types `X` and `Y` of `E1` and `E2` satisfy `Concept`, the effect of `f(E1, E2)` shall be [...stuff...]

that the implementation of `f` uses only operations required by `Concept`. It's not a huge stretch to see that `f` can be `noexcept` and/or `constexpr` if the operations required by `Concept` are `noexcept` and/or `constexpr`.

**Comment by ericniebler** [comment]
So, are you going to propose `noexcept(requires)`? :-)

**Comment by CaseyCarter** [comment]
...but Casey, if the constraints include `Constructible<T, Args...>()`, one of the required expressions is `new T{declval<Args>()...}`. `noexcept(requires)` loses a metric ton of usability.

**Comment by ericniebler** [comment]
> ...but Casey, if the constraints include `Constructible<T, Args...>()`, one of the required expressions is `new T{declval<Args>()...}`. `noexcept(requires)` loses a metric ton of usability.

Yup, and sadly the proposed wording seems to fall victim to this since `IndirectlyMovableStorable` requires `Readable`, which requires `DefaultConstructible`, which requires `new T`. So `iter_swap` is trivially `noexcept(false)`. :-(

**Comment by CaseyCarter** [comment]
Review discussion:

* STL: "dereferenceable" meaning "valid expression" is weird, we use that term to describe the runtime property. 

* "`E1` and `E2` both satisfy `Readable`" applies a concept to an expression instead of to types.

**Comment by ericniebler** [comment]
In 602e277 I opted not to take the broken wording regarding `noexcept` and `constexpr` of `iter_swap`. I actually don't recall LWG looking at that wording. Instead, I opened #284 to separately track that issue.

**Comment by ericniebler** [comment]
> ...but Casey, if the constraints include `Constructible<T, Args...>()`, one of the required expressions is `new T{declval<Args>()...}`. `noexcept(requires)` loses a metric ton of usability.

Not after P05476, if it's accepted.
