### ISSUE TITLE
difference_type of arrays

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#243]
The `is_array` specialization for `difference_type` is extraneous; the fallback/deducing specialization handles array types properly.

### Proposed Resolution
Change [iterator.traits]/4 as follows:
```diff
  [...]

template <class T>
struct difference_type<T*>
  : enable_if<is_object<T>::value, ptrdiff_t> { };

- template <class I>
-   requires is_array<I>::value
- struct difference_type<I> : difference_type<decay_t<I>> { };

template <class I>
struct difference_type<I const> : difference_type<decay_t<I>> { };

  [...]
```

**Comment by ericniebler** [comment]
I'm certain I added it for a reason. Have you tried making this edit in range-v3?

**Comment by ericniebler** [comment]
And in cmcstl2?

**Comment by CaseyCarter** [comment]
No, and yes. IIRC the array specialization existed before the "fallback," and we simply did not notice that it is obsolete.

**Comment by CaseyCarter** [comment]
range-v3 needed the array specialization because it did not have the "fallback."

**Comment by ericniebler** [comment]
👍

**Comment by ericniebler** [comment]
And can i just say that github's built-in diff syntax highlighting is
```diff
- pretty good
+ AWESOME
```
