### ISSUE TITLE
move_iterator::operator* should be defined in terms of iter_move

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#244]
### Proposed Resolution:

Change the synopsis of class `move_iterator` in [move.iterator]:
```diff
template <InputIterator I>
class move_iterator {
public:
  using iterator_type = I;
  using difference_type = difference_type_t<I>;
  using value_type = value_type_t<I>;
  using iterator_category = input_iterator_tag;
-  using reference = see below ;
+  using reference = rvalue_reference_t<I>;
  move_iterator();
  explicit move_iterator(I i);
  [...]
};
```
Delete paragraph 1:

> ```diff
> - 1 Let R be reference_t<I>. If is_reference<R>::value is true, the template
> -   specialization move_iterator<I> shall define the nested type named reference as a
> -   synonym for remove_reference_t<R>&&, otherwise as a synonym for R.
> ```

Change the description of `move_iterator::operator*` in [move.iter.op.star] as follows:
> ```diff
> - 1 Effects: Equivalent to static_cast<reference>(*current).
> + 1 Effects: Equivalent to: return iter_move(current);
> ```

**Comment by CaseyCarter** [comment]
### Proposed Resolution:

Change the synopsis of class `move_iterator` in [move.iterator]:
```diff
template <InputIterator I>
class move_iterator {
public:
  using iterator_type = I;
  using difference_type = difference_type_t<I>;
  using value_type = value_type_t<I>;
  using iterator_category = input_iterator_tag;
-  using reference = see below ;
+  using reference = rvalue_reference_t<I>;
  move_iterator();
  explicit move_iterator(I i);
  [...]
};
```
and delete paragraph 1:

> 1 Let `R` be `reference_t<I>`. If `is_reference<R>::value` is `true`, the template specialization `move_iterator<I>` shall define the nested type named `reference` as a synonym for `remove_reference_t<R>&&`, otherwise as a synonym for `R` .

Change the description of `move_iterator::operator*` in [move.iter.op.star] from:
> 1 *Effects:* Equivalent to `static_cast<reference>(*current)`.

to

> 1 *Effects:* Equivalent to `iter_move(current)`.

**Comment by ericniebler** [comment]
We forgot that `i[n]` should be changed to `return iter_move(i + n)`. Considering that the `op*` change was approved, I consider the corresponding change to `op[]` to be editorial/approved in principle. We should note the edit in the Editor's Report for Kona.

**Comment by ericniebler** [comment]
See e70a378.
