### ISSUE TITLE
The iterator adaptors should customize iter_move and iter_swap

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#245]
### Proposed resolution:

In [reverse.iterator], add declarations to the synopsis:

> ```diff
>   reference operator[](difference_type n) const
>     requires RandomAccessIterator<I>();
> +
> + friend constexpr rvalue_reference_t<I> iter_move(const reverse_iterator& i)
> +   noexcept(see below);
> + template <IndirectlySwappable<I> I2>
> +   friend void iter_swap(const reverse_iterator& x, const reverse_iterator<I2>& y)
> +     noexcept(see below);
> +
> private:
>   I current; // exposition only
> };
> ```

Add new sections before [reverse.iter.make] as follows:

> ```diff
> + 24.7.1.3.? iter_move [reverse.iter.iter_move]
> +
> + friend constexpr rvalue_reference_t<I> iter_move(const reverse_iterator& i)
> +   noexcept(see below);
> +
> + 1 Effects: Equivalent to: return ranges::iter_move(prev(i.current));
> +
> + 2 Remarks: The expression in the noexcept clause is equivalent to 
> +   noexcept(ranges::iter_move(declval<I&>())) && noexcept(--declval<I&>()) && 
> +   is_nothrow_copy_constructible<I>::value.
> +
> + 24.7.1.3.? iter_swap [reverse.iter.iter_swap]
> +
> + template <IndirectlySwappable<I> I2>
> +   friend void iter_swap(const reverse_iterator& x, const reverse_iterator<I2>& y)
> +     noexcept(see below);
> +
> + 1 Effects: Equivalent to ranges::iter_swap(prev(x.current), prev(y.current)).
> +
> + 2 Remarks: The expression in the noexcept clause is equivalent to 
> +   noexcept(ranges::iter_swap(declval<I>(), declval<I>())) && noexcept(--declval<I&>()).
> ```

In [move.iterator], add declarations to the synopsis:
> ```diff
>   reference operator[](difference_type n) const
>     requires RandomAccessIterator<I>();
>
> + friend constexpr rvalue_reference_t<I> iter_move(const move_iterator& i)
> +   noexcept(see below);
> + template <IndirectlySwappable<I> I2>
> +   friend void iter_swap(const move_iterator& x, const move_iterator<I2>& y)
> +     noexcept(see below);
> +
> private:
>   I current; // exposition only
> };
> ```

Add new paragraphs to [move.iter.nonmember] as follows:

> ```diff
> template <RandomAccessIterator I>
>   move_iterator<I>
>     operator+(
>       difference_type_t<I> n,
>       const move_iterator<I>& x);
>
> 2 Effects: Equivalent to x + n.
> +
> + friend constexpr rvalue_reference_t<I> iter_move(const move_iterator& i)
> +   noexcept(see below):
> +
> + -?- Effects: Equivalent to: return ranges::iter_move(i.current);
> +
> + -?- Remarks: The expression in the noexcept clause is equivalent to 
> +     noexcept(ranges::iter_move(i.current)).
> +
> + template <IndirectlySwappable<I> I2>
> +   friend void iter_swap(const move_iterator& x, const move_iterator<I2>& y)
> +     noexcept(see below):
> +
> + -?- Effects: Equivalent to ranges::iter_swap(x.current, y.current).
> +
> + -?- Remarks: The expression in the noexcept clause is equivalent to 
> +     noexcept(ranges::iter_swap(x.current, y.current)).
>
> template <InputIterator I>
>   move_iterator<I> make_move_iterator(I i);
>
> 3 Returns: move_iterator<I>(i).
> ```

In [common.iterator], add declarations to the synopsis:

> ```diff
>   common_iterator& operator++();
>   common_iterator operator++(int);
> +
> + friend constexpr rvalue_reference_t<I> iter_move(const common_iterator& i)
> +   noexcept(see below)
> +     requires InputIterator<I>();
> + template <IndirectlySwappable<I> I2, class S2>
> +   friend void iter_swap(const common_iterator& x, const common_iterator<I2, S2>& y)
> +     noexcept(see below)
>
> private:
>   bool is_sentinel; // exposition only
> ```

Add new sections after [common.iter.op.comp]:

> ```diff
> + 24.7.4.2.? iter_move [common.iter.op.iter_move]
> +
> + friend constexpr rvalue_reference_t<I> iter_move(const common_iterator& i)
> +   noexcept(see below)
> +     requires InputIterator<I>();
> +
> + 1 Requires: !i.is_sentinel.
> +
> + 2 Effects: Equivalent to: return ranges::iter_move(i.iter);
> +
> + 3 Remarks: The expression in the noexcept clause is equivalent to
> +   noexcept(ranges::iter_move(i.iter)).
> +
> + 24.7.4.2.? iter_swap [common.iter.op.iter_swap]
> +
> + template <IndirectlySwappable<I> I2>
> +   friend void iter_swap(const common_iterator& x, const common_iterator<I2>& y)
> +     noexcept(see below);
> +
> + 1 Requires: !x.is_sentinel && !y.is_sentinel.
> +
> + 2 Effects: Equivalent to ranges::iter_swap(x.iter, y.iter).
> +
> + 3 Remarks: The expression in the noexcept clause is equivalent to 
> +   noexcept(ranges::iter_swap(x.iter, y.iter)).
> ```

In [counted.iterator], add declarations to the synopsis:

> ```diff
>   see below operator[](difference_type n) const
>     requires RandomAccessIterator<I>();
>
> + friend constexpr rvalue_reference_t<I> iter_move(const counted_iterator& i)
> +   noexcept(see below)
> +     requires InputIterator<I>();
> + template <IndirectlySwappable<I> I2>
> +   friend void iter_swap(const counted_iterator& x, const counted_iterator<I2>& y)
> +     noexcept(see below);
> +
> private:
>   I current; // exposition only
> ```

Add new paragraphs to [counted.iter.nonmember] as follows:

> ```diff
> template <RandomAccessIterator I>
>   counted_iterator<I>
>     operator+(difference_type_t<I> n, const counted_iterator<I>& x);
>
> 5 Requires: n <= x.cnt.
>
> 6 Effects: Equivalent to x + n.
> +
> + friend constexpr rvalue_reference_t<I> iter_move(const counted_iterator& i)
> +   noexcept(see below)
> +     requires InputIterator<I>();
> +
> + -?- Effects: Equivalent to: return ranges::iter_move(i.current).
> +
> + -?- Remarks: The expression in the noexcept clause is equivalent to 
> +      noexcept(ranges::iter_move(i.current)).
> +
> + template <IndirectlySwappable<I> I2>
> +   friend void iter_swap(const counted_iterator& x, const counted_iterator<I2>& y)
> +     noexcept(see below);
> +
> + -?- Effects: Equivalent to ranges::iter_swap(x.current, y.current).
> +
> + -?- Remarks: The expression in the noexcept clause is equivalent to
> +     noexcept(ranges::iter_swap(x.current, y.current)).
>
> template <Iterator I>
>   counted_iterator<I> make_counted_iterator(I i, difference_type_t<I> n);
>
> 7 Requires: n >= 0.
>
> 8 Returns: counted_iterator<I>(i, n).
> ```

**Comment by ericniebler** [comment]
Why should they customize `iter_swap`? Is customizing `iter_move` not enough?

**Comment by CaseyCarter** [comment]
> Why should they customize `iter_swap`? Is customizing `iter_move` not enough?

For the same reason that movable types sometimes customize `swap`: it may be the case that `iter_swap` of the base iterators is more efficient than `iter_move` construction + `iter_move` assignment + `move` assignment.

**Comment by CaseyCarter** [comment]
## Preliminary wording:

In the synopsis of `<experimental/ranges/iterator>` in [iterator.synopsis], add new declarations before the declaration of `make_reverse_iterator`:

> ```diff
> template <RandomAccessIterator I>
>   reverse_iterator<I>
>     operator+(
>   difference_type_t<I> n,
>   const reverse_iterator<I>& x);
> +
> + template <class I>
> +   constexpr rvalue_reference_t<I> iter_move(const reverse_iterator<I>& i);
> + template <class I1, class I2>
> +     requires IndirectlySwappable<I1, I2>()
> +   void iter_swap(const reverse_iterator<I1>& x, const reverse_iterator<I2>& y);
>
> template <BidirectionalIterator I>
>   reverse_iterator<I> make_reverse_iterator(I i);
> ```

and before the declaration of `make_move_iterator`:

> ```diff
> template <RandomAccessIterator I>
>   move_iterator<I>
>     operator+(
>   difference_type_t<I> n,
>   const move_iterator<I>& x);
> +
> + template <class I>
> +   constexpr rvalue_reference_t<I> iter_move(const move_iterator<I>& i);
> + template <class I1, class I2>
> +     requires IndirectlySwappable<I1, I2>()
> +   void iter_swap(const move_iterator<I1>& x, const move_iterator<I2>& y);
>
> template <InputIterator I>
>   move_iterator<I> make_move_iterator(I i);
> ```

and before the declaration of `default_sentinel`:

> ```diff
> template <class I2, SizedSentinel<I2> I1, SizedSentinel<I2> S1, SizedSentinel<I1> S2>
> difference_type_t<I2> operator-(
>   const common_iterator<I1, S1>& x, const common_iterator<I2, S2>& y);
> +
> + template <InputIterator I, Sentinel<I> S>
> + rvalue_reference_t<I> iter_move(
> +   const common_iterator<I, S>& i);
> + template <class I1, class S1, class I2, class S2>
> +   requires IndirectlySwappable<I1, I2>()
> + void iter_swap(
> +   const common_iterator<I1, S1>& x, const common_iterator<I2, S2>& y);
>
> // 24.7.5 Default sentinels
> class default_sentinel;
> ```

and before the declaration of `make_counted_iterator`:

> ```diff
> template <RandomAccessIterator I>
>   counted_iterator<I>
>     operator+(difference_type_t<I> n, const counted_iterator<I>& x);
> +
> + template <InputIterator I>
> +   rvalue_reference_t<I> iter_move(
> +     const counted_iterator<I>& i);
> + template <class I1, class I2>
> +     requires IndirectlySwappable<I1, I2>()
> +   void iter_swap(
> +     const counted_iterator<I1>& x,
> +     const counted_iterator<I2>& y);
> +
> template <Iterator I>
>   counted_iterator<I> make_counted_iterator(I i, difference_type_t<I> n);
> ```

In [reverse.iterator], add declarations to the synopsis:

> ```diff
>   template <class IteratorRandomAccessIterator I>
>     reverse_iterator<IteratorI>
>       operator+(
>     difference_type_t<I> n,
>     const reverse_iterator<I>& x);
> +
> + template <class I>
> +   constexpr rvalue_reference_t<I> iter_move(const reverse_iterator<I>& i);
> + template <class I1, class I2>
> +     requires IndirectlySwappable<I1, I2>()
> +   void iter_swap(const reverse_iterator<I1>& x, const reverse_iterator<I2>& y);
>
>   template <BidirectionalIterator I>
>     reverse_iterator<I> make_reverse_iterator(I i);
> }}}}
> ```

Add new sections before [reverse.iter.make] as follows:

> ### 24.7.1.3.? Non-member function `iter_move` [reverse.iter.iter_move]
> ```c++
> template <class I>
>   constexpr rvalue_reference_t<I> iter_move(const reverse_iterator<I>& i);
> ```
> 1 Effects: Equivalent to `iter_move(prev(i.current))`.
>
> ### 24.7.1.3.? Non-member function `iter_swap` [reverse.iter.iter_swap]
> ```c++
> template <class I1, class I2>
>   requires IndirectlySwappable<I1, I2>()
>     void iter_swap(const reverse_iterator<I1>& x, const reverse_iterator<I2>& y);
> ```
> 1 Effects: Equivalent to `iter_swap(prev(x.current), prev(y.current))`.

In [move.iterator], add declarations to the synopsis:
> ```diff
>   template <RandomAccessIterator I>
>     move_iterator<I>
>       operator+(
>         difference_type_t<I> n,
>         const move_iterator<I>& x);
> +
> + template <class I>
> +   constexpr rvalue_reference_t<I> iter_move(const move_iterator<I>& i);
> + template <class I1, class I2>
> +     requires IndirectlySwappable<I1, I2>()
> +   void iter_swap(const move_iterator<I1>& x, const move_iterator<I2>& y);
> +
>   template <class IteratorInputIterator I>
>     move_iterator<IteratorI> make_move_iterator(IteratorI i);
> }}}}
> ```

Add new paragraphs to [move.iter.nonmember] as follows:

> ```c++
> template <RandomAccessIterator I>
>   move_iterator<I>
>     operator+(
>       difference_type_t<I> n,
>       const move_iterator<I>& x);
> ```
>
> 2 *Effects:* Equivalent to `x + n`.
>
> ```diff
> + template <class I>
> +   constexpr rvalue_reference_t<I> iter_move(const move_iterator<I>& i);
> ```
>
> -?- *Effects:* Equivalent to `iter_move(i.current)`.
>
> ```diff
> + template <class I1, class I2>
> +     requires IndirectlySwappable<I1, I2>()
> +   void iter_swap(const move_iterator<I1>& x, const move_iterator<I2>& y);
> ```
>
> -?- *Effects:* Equivalent to `iter_swap(x.current, y.current)`.
>
> ```c++
> template <InputIterator I>
>   move_iterator<I> make_move_iterator(I i);
> ```
> 3 *Returns:* `move_iterator<I>(i)`.

In [common.iterator], add declarations to the synopsis:

> ```diff
>   template <class I2, SizedSentinel<I2> I1, SizedSentinel<I2> S1, SizedSentinel<I1> S2>
>   difference_type_t<I2> operator-(
>     const common_iterator<I1, S1>& x, const common_iterator<I2, S2>& y);
> +
> + template <InputIterator I, Sentinel<I> S>
> + rvalue_reference_t<I> iter_move(
> +   const common_iterator<I, S>& i);
> + template <class I1, class S1, class I2, class S2>
> +   requires IndirectlySwappable<I1, I2>()
> + void iter_swap(
> +   const common_iterator<I1, S1>& x, const common_iterator<I2, S2>& y);
> }}}}
> ```

Add new sections after [common.iter.op.comp]:

> ### 24.7.4.2.6 `iter_move` for `common_iterator` [common.iter.op.iter_move]
> ```c++
> template <InputIterator I, Sentinel<I> S>
> rvalue_reference_t<I> iter_move(
>   const common_iterator<I, S>& i);
> ```
> 1 *Requires:* `!i.is_sentinel`
>
> 2 *Effects:* Equivalent to `return iter_move(i.iter);`
>
> ### 24.7.4.2.7 `iter_swap` for `common_iterator` [common.iter.op.iter_swap]
> ```c++
> template <class I1, class S1, class I2, class S2>
>   requires IndirectlySwappable<I1, I2>()
> void iter_swap(
>   const common_iterator<I1, S1>& x, const common_iterator<I2, S2>& y);
> ```
> 1 *Requires:* `!x.is_sentinel && ! y.is_sentinel`
>
> 2 *Effects:* Equivalent to `iter_swap(x.iter, y.iter)`.

In [counted.iterator], add declarations to the synopsis:

> ```diff
> template <RandomAccessIterator I>
>   counted_iterator<I>
>     operator+(difference_type_t<I> n, const counted_iterator<I>& x);
> +
> + template <InputIterator I>
> +   rvalue_reference_t<I> iter_move(
> +     const counted_iterator<I>& i);
> + template <class I1, class I2>
> +     requires IndirectlySwappable<I1, I2>()
> +   void iter_swap(
> +     const counted_iterator<I1>& x,
> +     const counted_iterator<I2>& y);
>
> template <Iterator I>
>   counted_iterator<I> make_counted_iterator(I i, difference_type_t<I> n);
> ```

Add new paragraphs to [counted.iter.nonmember] as follows:

> ```c++
> template <RandomAccessIterator I>
>   counted_iterator<I>
>     operator+(difference_type_t<I> n, const counted_iterator<I>& x);
> ```
>
> 5 *Requires:* `n <= x.cnt`.
>
> 6 *Effects:* Equivalent to `x + n`.
>
> ```diff
> + template <InputIterator I>
> +   constexpr rvalue_reference_t<I> iter_move(const counted_iterator<I>& i);
> ```
>
> -?- *Effects:* Equivalent to `iter_move(i.current)`.
>
> ```diff
> + template <class I1, class I2>
> +     requires IndirectlySwappable<I1, I2>()
> +   void iter_swap(const counted_iterator<I1>& x, const counted_iterator<I2>& y);
> ```
>
> -?- *Effects:* Equivalent to `iter_swap(x.current, y.current)`.
>
> ```c++
> template <Iterator I>
>   counted_iterator<I> make_counted_iterator(I i, difference_type_t<I> n);
> ```
> 7 *Requires:* `n >= 0`.
>
> 8 *Returns:* `counted_iterator<I>(i, n)`.

**Comment by ericniebler** [comment]
I seem to recall there being a problem with a function and an object named `iter_swap` or `iter_move` that I needed to resolve by making these friend functions in-situ within the class. Have you tried this in cmcstl2?

**Comment by CaseyCarter** [comment]
> I seem to recall there being a problem with a function and an object named `iter_swap` or `iter_move` that I needed to resolve by making these friend functions in-situ within the class. Have you tried this in cmcstl2?

The only `iter_move` and `iter_swap` overloads in cmcstl2 are for `basic_iterator`. They are currently non-member non-friend templates in a detail namespace along with an empty base class from which basic_iterator inherits. I've had to change the customization hook design so many times to workaround GCC bugs that I'd forgotten the fundamental issue of name collision with the CPO. This PR obviously cannot work. Fixing.

**Comment by CaseyCarter** [comment]
Updated wording with less pretty but more clear editing instructions.

**Comment by CaseyCarter** [comment]
> Updated wording with less pretty but more clear editing instructions.

`iter_move` and `iter_swap` *really* want to be `noexcept`.

**Comment by ericniebler** [comment]
> `iter_move` and `iter_swap` really want to be `noexcept`.

Agreed. Beyond that, these look good.

**Comment by CaseyCarter** [comment]
There's wording with `noexcept` clauses. `reverse_iterator` is a bit weird here in that the effects are equivalent to `iter_move(prev(i.current))`, but I've made the noexcept behavior depend on only `iter_move(declval<I&>())` and `--declval<I&>()`. (I want users to have a chance to make reverse_iterator nothrow-iter_move-able even if their implementation doesn't have conditional noexcept on prev.)

**Comment by ericniebler** [comment]
Understood. But `prev(i.current)` copies and moves an iterator, so we _could_ at least add `noexcept(is_nothrow_copyable_v<I>)`.

**Comment by CaseyCarter** [comment]
I've added `is_nothrow_copy_constructible`. I'm playing a little fast and loose by omitting the move requirement: It's possible to implement without using `prev` so the move isn't needed.

**Comment by ericniebler** [comment]
@CaseyCarter Why are the `iter_move` functions `constexpr` but not the `iter_swap` functions?

**Comment by CaseyCarter** [comment]
Because `std::move` is `constexpr`, but `std::swap` is not (yet). In other words, adding proxy iterator support to an existing algorithm means replacing `foo = std::move(*bar);` with `foo = ranges::iter_move(bar);`, and `using std::swap; swap(*foo, *bar);` with `ranges::iter_swap(foo, bar)`. I wanted to ensure that the replacement is at least as constexpr as the original.

That said, I would not argue against making `iter_swap` `constexpr`.
