### ISSUE TITLE
Stream iterators need constraints

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#246]
Proposed Resolution
-------------------

Add the following to the `<experimental/ranges/iterator>` synopsis ([iterator.synopsis]):

> ```
> template <class T, class charT = char, class traits = char_traits<charT>>
> concept bool StreamInsertable =
>   see-below;
> 
> template <class T, class charT = char, class traits = char_traits<charT>>
> concept bool StreamExtractable =
>   see-below;
> ```

Under section "Stream iterators" ([iterators.stream]) and before subsection "Class template `istream_iterator`" ([istream.iterator]), add a subsection "Stream iterator requirements" (stable name [iterators.stream.requirements]) with the following:

> **Stream iterator requirements**  [iterators.stream.requirements]
>
> 1. The concepts `StreamInsertable` and `StreamExtractable` define the requirements of types that can be written to and read from standard iostreams (#CXX14REF [input.output]).
> ```
> template <class T, class charT = char, class traits = char_traits<charT>>
> concept bool StreamInsertable =
>   requires (basic_ostream<charT, traits>& sout, const T& t) {
>     { s << t } -> Same<basic_ostream<charT, traits>>&;
>   };
> ```
>
> 2. Let `sout` be a non-const lvalue of type `basic_ostream<charT, traits>` and `t` be a const lvalue of type `T`. Then `StreamInsertable<T, charT, traits>` is satisfied if an only if
>
> > (2.1) -- `addressof(sout) == addressof(sout << t)`
>
> ```
> template <class T, class charT = char, class traits = char_traits<charT>>
> concept bool StreamExtractable =
>   requires (basic_istream<charT, traits>& sin, T& t) {
>     { s >> t } -> Same<basic_istream<charT, traits>>&;
>   };
> ```
> 3. Let `sin` be a non-const lvalue of type `basic_istream<charT, traits>` and `t` be a non-const lvalue of type `T`. Then `StreamExtractable<T, charT, traits>` is satisfied if an only if
>
> > (3.1) -- `addressof(sin) == addressof(sin >> t)`

Change the synopsis of [istream.iterator]/p2 as follows:

```diff
 namespace std { namespace experimental { namespace ranges { inline namespace v1 {
-  template <class T, class charT = char, class traits = char_traits<charT>,
-      class Distance = ptrdiff_t>
+  template <Semiregular T, class charT = char, class traits = char_traits<charT>,
+      SignedIntegral Distance = ptrdiff_t>
+    requires StreamExtractable<T, charT, traits>
   class istream_iterator {
     [...]
```

Change the synopsis of [ostream.iterator]/p2

```diff
 namespace std { namespace experimental { namespace ranges { inline namespace v1 {
   template <class T, class charT = char, class traits = char_traits<charT>>
+      requires StreamInsertable<T, charT, traits>
   class ostream_iterator {
     [...]
```

**Comment by CaseyCarter** [comment]
Related: [LWG DR 2878](http://cplusplus.github.io/LWG/lwg-defects.html#2878).

**Comment by ericniebler** [comment]
@CaseyCarter where should the concepts `StreamInsertable` and `StreamExtractable` live? I'm inclined to create a new header for them: `<experimental/ranges/ios>`, where we may want to eventually put generic inserters, extractors, and manipulators for ranges. (Yuk, iostreams.) But adding a new header this late in the proceedings for only two concepts feels weird.

So ... maybe `<experimental/ranges/concepts>`?

**Comment by CaseyCarter** [comment]
Puke. We need them to constrain things in `<iterator>`, I'd default to throwing them in there for now. Obviously no strong preference.

**Comment by ericniebler** [comment]
I see you constrained `charT` in cmcstl2 with MoveConstructible in places. That's not a very good constraint. The IS says this:

> In the classes of Clause 30, a template parameter with name `charT` represents a member of the set of types containing `char`, `wchar_t`, and any other implementation-defined character types that satisfy the requirements for a character on which any of the iostream components can be instantiated.

I don't think we can capture that effectively in a concept since it's implementation-defined. I'd rather we say nothing about the requirements on `charT` at this time.

**Comment by ericniebler** [comment]
@CaseyCarter ready for review

**Comment by CaseyCarter** [comment]
Thank you for not copying the experimental `DefaultConstructible<T>() and CopyConstructible<T>()` requirement from cmcstl2's `istream_iterator`.

In para 3, `StreamInsertable` should be `StreamExtractable`.

> I see you constrained `charT` in cmcstl2 with `MoveConstructible` in places.

`istreambuf_iterator::operator*` is specified to return a `charT` by value that is "obtained via the `streambuf` member `sbuf_->sgetc()`. Those effects can only be implemented in C++14 if `charT` is move constructible. C++17 is a different story.

That said, I can live with no explicit requirements for `charT` at this time. We're specifying iterators and algorithms, not iostreams.

**Comment by ericniebler** [comment]
> In para 3, `StreamInsertable` should be `StreamExtractable`.

Fixed, thanks.

> `istreambuf_iterator::operator*` is specified to return a `charT` by value that is "obtained via the `streambuf` member `sbuf_->sgetc()`.

Understood, but constraining `istreambuf_iterator`'s `charT` parameter with `MoveConstructible` tells users that the instantiation will succeed if `charT` satisfies `MoveConstructible`, and that's not true. Besides, if we're not constraining `traits` (and we're most definitely *NOT*) then leaving `charT` unconstrained is also fine.

**Comment by CaseyCarter** [comment]
> Understood, but constraining `istreambuf_iterator`'s `charT` parameter with `MoveConstructible` tells users that the instantiation will succeed if `charT` satisfies `MoveConstructible`, and that's not true.

Conversely, constraining it with nothing tells users that instantiation will always succeed; there are no requirements to satisfy. Perhaps a footnote: "Don't care - iostreams - you're on your own!"

**Comment by ericniebler** [comment]
We don't have dupe `istream_iterator` and `ostream_iterator` class templates anymore like we did in the TS. We can't add constraints to existing templates without breaking things. I'm closing this NAD.
