### ISSUE TITLE
DerivedFrom should be publicly and unambiguously 

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#255]
### Proposed Resolution

Change [concepts.lib.corelang.derived] as follows:

```diff
 template <class T, class U>
 concept bool DerivedFrom() {
-  return see below ;
+  return is_base_of<U, T>::value &&
+    is_convertible<remove_cv_t<T>*, remove_cv_t<U>*>::value; // see below
 }

-1 DerivedFrom<T, U>() is satisfied if and only if is_base_of<U, T>::value is
-  true.
+1 There need not be a subsumption relationship between DerivedFrom<T, U>() and either
+  is_base_of<U, T>::value or is_convertible<remove_cv_t<T>*, remove_cv_t<U>*>::value.
+
+2 [Note: DerivedFrom<T, U>() is satisfied if and only if T is publicly and unambiguously
+  derived from U, or T and U are the same class type ignoring cv qualifiers.-end note]
```

**Comment by ericniebler** [comment]
@CaseyCarter Comments?

**Comment by CaseyCarter** [comment]
"if and only if `is_base_of<U, T>::value && is_convertible<T*, U*>::value` is `true`" is shorter.

**Comment by ericniebler** [comment]
Resolution edited to hide the subsumption relationship with the traits.

**Comment by timsong-cpp** [comment]
`is_base_of<U, T>` ignores cv-qualification, but `is_convertible<T*, U*>` doesn't. Should `DerivedFrom` care about cv-qualifications on `T` and `U`?

**Comment by CaseyCarter** [comment]
> Should `DerivedFrom` care about cv-qualifications on `T` and `U`?

It definitely should not; PR corrected to use `is_convertible<remove_cv_t<T>*, remove_cv_t<U>*>::value`.
