### ISSUE TITLE
Add constexpr to advance, distance, next, and prev

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#256]
Also common_iterator(?).

**Comment by CaseyCarter** [comment]
My review notes were more along the lines of "Add constexpr to those things that are constexpr in the WD, notably advance, distance, next, prev." `reverse_iterator` and `move_iterator` are also heavily `constexpr` in the WD; there's a strong consistency argument that `common_iterator` and `counted_iterator` should be as well.

**Comment by ericniebler** [comment]
With the caveat that we have to be careful with `common_iterator` to not disallow a `variant`-like implementation.

**Comment by CaseyCarter** [comment]
Resolved in [P0579](https://github.com/ericniebler/stl2/blob/master/ext/constexpr/P0579.md).
