### ISSUE TITLE
Make the document consistent WRT presentation

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#257]
Don't try to match the section/subsection/para numbers in the IS. Don't show diff markings. We're not changing anything in the IS (aside from range-`for`).

**Comment by ericniebler** [comment]
Also, any reference to sections _not_ defined in the TS itself should refer explicitly to the IS.

**Comment by CaseyCarter** [comment]
This is *almost* completed. Clause 2 "Statements" needs a bit of clarification that:

1. it is meant to be modifying C++14 §6.5.4 [stmt.ranged] (no longer clear after the renumber)
2. The \ednote needs to be rephrased as an indication to the reader that the following text replaces part of C++14

**Comment by ericniebler** [comment]
OK, I think this is now done.
