### ISSUE TITLE
The Common concept and narrowing conversions

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#26]
The definition of Common in N4382 uses curly-brace conversions to the common type:

```
template <class T, class U>
concept bool Common =
  requires (T t, U u) {
    typename CommonType<T, U>;
    {CommonType<T, U>{forward<T>(t)}};
    {CommonType<T, U>{forward<U>(u)}};
  };
```
(As an aside, I'll note that per N4377 a compound-requirement with nothing after the expression `{ E };` is equivalent to a simple-requirement `E;`. The `{}` are extraneous in `{CommonType<T, U>{...}}`.) Our legacy of type promotions from C means that it's not always possible to convert to the common type without narrowing, e.g. `common_type<double,long long>`. The conversions should therefore use `()` syntax:
```
template <class T, class U>
concept bool Common =
  requires (T t, U u) {
    typename CommonType<T, U>;
    CommonType<T, U>(forward<T>(t));
    CommonType<T, U>(forward<U>(u));
  };
```

**Comment by ericniebler** [comment]
Ditto for other places where `CommonType` gets used, like `TotallyOrdered`.
