### ISSUE TITLE
Restrict alg.general changes from P0370 to apply only to the range-and-a-half algorithms

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#261]
..as directed during LWG review of P0370. LWG is uncomfortable with the uncertainty this wording introduces, and would prefer to "limit the scope of the potential damage" to only the deprecated range-and-a-half algorithms. 

Proposed resolution
--------------------
(This wording assumes the PRs of #286 and #379 have been applied)

Strike para [algorithms.general]/10 which begins: "Some algorithms declare both an overload that takes a Range and an Iterator, and an overload that takes two Range parameters."

Strike para [algorithms.general]/12 which begins, "Despite that the algorithm declarations nominally accept parameters by value [...]"

Replace the entire content of Annex A.2 [depr.algo.range-and-a-half] with:

> 1 The following algorithm signatures are deemed unsafe and are deprecated in this document.
>
> 2 Overloads of algorithms that take a `Range` argument and a forwarding reference parameter `first2_` behave as if they are implemented by calling `begin` and `end` on the `Range` and dispatching to the overload that takes separate iterator and sentinel arguments, perfectly forwarding `first2_`.
>
> ```c++
> template <InputIterator I1, Sentinel<I1> S1, class I2, class Pred = equal_to<>,
>     class Proj1 = identity, class Proj2 = identity>
>   requires InputIterator<decay_t<I2>> && !Range<I2> &&
>     IndirectPredicate<Pred, projected<I1, Proj1>, projected<decay_t<I2>, Proj2>>
>   tagged_pair<tag::in1(I1), tag::in2(decay_t<I2>)>
>     mismatch(I1 first1, S1 last1, I2&& first2_, Pred pred = Pred{},
>              Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});
>
> template <InputRange Rng1, class I2, class Pred = equal_to<>,
>     class Proj1 = identity, class Proj2 = identity>
>   requires InputIterator<decay_t<I2>> && !Range<I2> &&
>     IndirectPredicate<Pred, projected<iterator_t<Rng1>, Proj1>,
>         projected<decay_t<I2>, Proj2>>
>   tagged_pair<tag::in1(safe_iterator_t<Rng1>), tag::in2(decay_t<I2>)>
>     mismatch(Rng1&& rng1, I2&& first2_, Pred pred = Pred{},
>              Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});
> ```
>
> 3 *Effects:* Equivalent to: `return mismatch(first1, last1, std::forward<I2>(first2_), unreachable{}, pred, proj1, proj2);`, except that the underlying algorithm never increments `first2` more than `last1 - first1` times.
>
> ```c++
> template <InputIterator I1, Sentinel<I1> S1, class I2,
>     class Pred = equal_to<>, class Proj1 = identity, class Proj2 = identity>
>   requires InputIterator<decay_t<I2>> && !Range<I2> &&
>     IndirectlyComparable<I1, decay_t<I2>, Pred, Proj1, Proj2>
>   bool equal(I1 first1, S1 last1,
>              I2&& first2_, Pred pred = Pred{},
>              Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});
>
> template <InputRange Rng1, class I2, class Pred = equal_to<>,
>     class Proj1 = identity, class Proj2 = identity>
>   requires InputIterator<decay_t<I2>> && !Range<I2> &&
>     IndirectlyComparable<iterator_t<Rng1>, decay_t<I2>, Pred, Proj1, Proj2>
>   bool equal(Rng1&& rng1, I2&& first2_, Pred pred = Pred{},
>              Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});
> ```
>
> 4 *Effects:* Equivalent to: `return first1 == mismatch(first1, last1, std::forward<I2>(first2_), pred, proj1, proj2).in1();`
>
> ```c++
> template <ForwardIterator I1, Sentinel<I1> S1, class I2,
>     class Pred = equal_to<>, class Proj1 = identity, class Proj2 = identity>
>   requires ForwardIterator<decay_t<I2>> && !Range<I2> &&
>     IndirectlyComparable<I1, decay_t<I2>, Pred, Proj1, Proj2>
>   bool is_permutation(I1 first1, S1 last1, I2&& first2_, Pred pred = Pred{},
>                       Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});
>
> template <ForwardRange Rng1, class I2, class Pred = equal_to<>,
>     class Proj1 = identity, class Proj2 = identity>
>   requires ForwardIterator<decay_t<I2>> && !Range<I2> &&
>     IndirectlyComparable<iterator_t<Rng1>, decay_t<I2>, Pred, Proj1, Proj2>
>   bool is_permutation(Rng1&& rng1, I2&& first2_, Pred pred = Pred{},
>                       Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});
> ```
>
> 5 *Effects:* Equivalent to:
>
> ```c++
>   auto first2 = std::forward<I2>(first2_);
>   return is_permutation(first1, last1, first2, next(first2, distance(first1, last1)),
>                         pred, proj1, proj2);
> ```
>
> ```c++
> template <ForwardIterator I1, Sentinel<I1> S1, class I2>
>   requires ForwardIterator<decay_t<I2>> && !Range<I2> &&
>     IndirectlySwappable<I1, decay_t<I2>>
>   tagged_pair<tag::in1(I1), tag::in2(decay_t<I2>)>
>     swap_ranges(I1 first1, S1 last1, I2&& first2_);
>
> template <ForwardRange Rng, class I>
>   requires ForwardIterator<decay_t<I>> && !Range<I> &&
>     IndirectlySwappable<iterator_t<Rng>, decay_t<I>>
>   tagged_pair<tag::in1(safe_iterator_t<Rng>), tag::in2(decay_t<I>)>
>     swap_ranges(Rng&& rng1, I&& first2_);
> ```
>
> 6 *Effects:* Equivalent to:
>
> ```c++
>   auto first2 = std::forward<I2>(first2_);
>   return swap_ranges(first1, last1, first2, next(first2, distance(first1, last1)),
>                      pred, proj1, proj2);
> ```
>
> ```c++
> template <InputIterator I1, Sentinel<I1> S1, class I2, WeaklyIncrementable O,
>     class F, class Proj1 = identity, class Proj2 = identity>
>   requires InputIterator<decay_t<I2>> && !Range<I2> &&
>     Writable<O, indirect_result_of_t<F&(projected<I1, Proj1>,
>         projected<decay_t<I2>, Proj2>)>>
>   tagged_tuple<tag::in1(I1), tag::in2(decay_t<I2>), tag::out(O)>
>     transform(I1 first1, S1 last1, I2&& first2_, O result,
>               F binary_op, Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});
>
> template <InputRange Rng, class I, WeaklyIncrementable O, class F,
>     class Proj1 = identity, class Proj2 = identity>
>   requires InputIterator<decay_t<I>> && !Range<I> &&
>     Writable<O, indirect_result_of_t<F&(
>         projected<iterator_t<Rng>, Proj1>, projected<decay_t<I>, Proj2>>)>
>   tagged_tuple<tag::in1(safe_iterator_t<Rng>), tag::in2(decay_t<I>), tag::out(O)>
>     transform(Rng&& rng1, I&& first2_, O result,
>               F binary_op, Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});
> ```
>
> 7 *Effects:* Equivalent to: `return transform(first1, last1, std::forward<I2>(first2_), unreachable{}, pred, proj1, proj2);`, except that the underlying algorithm never increments `first2` more than `last1 - first1` times.

**Comment by ericniebler** [comment]
What wording is this issue specifically referring to? Is it this:

> "Despite that the algorithm declarations nominally accept parameters by value, it is unspecified when and if the argument expressions are used to initialize the actual parameters....

? If so, then conforming implementations cannot forward their ~~callables~~invocables?

**Comment by CaseyCarter** [comment]
Yes. IIRC, there were no issues with the number and order of template parameters paragraph. Only the (admittedly somewhat vague) wording about unspecified sequencing in /12 was frightening to people. It maybe needs to move to Annex A.2 so as to only apply to those deprecated algorithms.

> If so, then conforming implementations cannot forward their invocables?

I think the intent of [algorithms.general]/9:

> 9 Overloads of algorithms that take `Range` arguments behave as if they are implemented by calling
`begin` and `end` on the `Range` and dispatching to the overload that takes separate iterator and sentinel
arguments.

is that range overloads should *forward* their other arguments to the corresponding iterator+sentinel overload, although that isn't completely clear from "as if....by...dispatching." I think we could editorially clarify that paragraph.

**Comment by ericniebler** [comment]
I'm unclear why the deprecated algorithms deserve special treatment in this respect, and I can't recall the discussion. Do you?

I'm also not comfortable with an editorial change that permits forwarding the invocables from the range overloads. There are very few places in the standard where invocables taken by forwarding reference (`std::thread` constructor, `std::invoke`, `std::function::operator=` (but not the `std::function` constructor, for some reason). It also wasn't my intent when I wrote [algorithms.general]/9. We may need to ask the LEWG for more guidance here, unless you remember more of the LEWGs original intent than I do.

**Comment by CaseyCarter** [comment]
> I'm unclear why the deprecated algorithms deserve special treatment in this respect, and I can't recall the discussion. Do you?

The critical motivation for paragraph 12 is to give implementations the leeway necessary to implement the behavior specified in para 10 to disambiguate (Range, Iterator) from (Range, Range) overloads when the second parameter is an array. Such overload sets only occur when one of the deprecated overloads in Annex A.2 is involved. LWG feedback was to somehow constrain the allowances in paragraph 12 to only affect those overload sets, ideally so that we could remove the allowances altogether if and when those deprecated overloads are removed.

**Comment by ericniebler** [comment]
> Such overload sets only occur when one of the deprecated overloads in Annex A.2 is involved.

Ah there. Thank you.

My preferred resolution is to simply remove the allowance currently granted for perfectly forwarding arguments nominally taken by value. The range-based overloads should `std::move` the functions.

@CaseyCarter LMK if you object.

Proposed resolution
--------------------

Change 

```diff
9 Overloads of algorithms that take Range arguments (6.9.2.2)
  behave as if they are implemented by calling begin and end
  on the Range and dispatching to the overload that takes
- separate iterator and sentinel arguments.
+ separate iterator and sentinel arguments, moving all
+ arguments taken by value.
```

Strike para [alg.general]/12 which begins, "Despite that the algorithm declarations nominally accept parameters by value [...]"

This change also requires `transform` to constrain its function with `CopyConstructible`. See the resolution of #286.

**Comment by CaseyCarter** [comment]
> My preferred resolution is to simply remove the allowance currently granted for perfectly forwarding arguments nominally taken by value.

Yes, this is workable. From an implementation point of view, that requires the "weird" overloads that accept parameters by forwarding reference which the TS depicts as accepted by value to sequence the initialization of the nominal parameter objects before any other user-visible effects.

For example, range-and-a-half `equal` is declared:
```c++
template <InputIterator I1, Sentinel<I1> S1, InputIterator I2,
    class Pred = equal_to<>, class Proj1 = identity, class Proj2 = identity>
  requires IndirectlyComparable<I1, I2, Pred, Proj1, Proj2>()
  bool equal(I1 first1, S1 last1, I2 first2, Pred pred = Pred{},
             Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});
```
and can be implemented to conform with algorithm.general/10 as:
```c++
template <class T>
  requires Constructible<std::decay_t<T>, T>()
using decayed = std::decay_t<T>;

template <InputIterator I1, Sentinel<I1> S1, class I2_,
    class Pred = equal_to<>, class Proj1 = identity, class Proj2 = identity>
  requires InputIterator<decayed<I2_>() &&
    IndirectlyComparable<I1, decayed<I2_>, Pred, Proj1, Proj2>()
  bool equal(I1 first1, S1 last1, I2_&& first2_, Pred pred = Pred{},
             Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{})
  {
    auto first2 = std::forward<I2_>(first2_);
    // ...
  }
```

**Comment by timsong-cpp** [comment]
Not sure if this wording allows enough leeway to not move the arguments and pass them by reference instead, as (presumably) we want to allow for at least the invocables.

Also, I believe the standard allows users to depend on non-member function signatures being the same as depicted in the standard (unlike member functions), so we may need some additional wording providing an exemption.

**Comment by CaseyCarter** [comment]
> Not sure if this wording allows enough leeway to not move the arguments and pass them by reference instead, as (presumably) we want to allow for at least the invocables.

I think that you and I are both being overly defensive. The exact number of moves or copies the library performs on parameters passed by value isn't significant under as-if. The original wording of alg.general/9 is sufficient and we shouldn't bother to change it.

> I believe the standard allows users to depend on non-member function signatures being the same as depicted in the standard

This is only an issue for the deprecated range-and-a-half algorithms in Annex A.2, since algorithms.general/10 really only applies to them. How do folks feel about striking algorithm.general/10 "Some algorithms declare both an overload that takes a Range and an Iterator..." as well, and changing the declarations in Annex A.2 too explicitly disambiguate them as I did for `equal` above?

**Comment by ericniebler** [comment]
I think I should strike "moving all arguments taken by value" from the proposed resolution. I would like it to be conforming for an implementation to "forward" function object by `std::reference_wrapper`.

> I believe the standard allows users to depend on non-member function signatures being the same as depicted in the standard

Reference?

> How do folks feel about striking algorithm.general/10 "Some algorithms declare both an overload that takes a Range and an Iterator..." as well, and changing the declarations in Annex A.2 too explicitly disambiguate them as I did for `equal` above?

I prefer our current solution.

**Comment by timsong-cpp** [comment]
>>  I believe the standard allows users to depend on non-member function signatures being the same as depicted in the standard

>Reference?

Hard to find an explicit one, since this is more of a "nothing says it doesn't work". For member functions, [member.functions]/2 allows their signatures to be mangled at will, but there's nothing comparable in [global.functions].

**Comment by CaseyCarter** [comment]
> Also, I believe the standard allows users to depend on non-member function signatures being the same as depicted in the standard (unlike member functions), so we may need some additional wording providing an exemption.

Ranges has [algorithms.general]/11:

> The number and order of template parameters for algorithm declarations is unspecified, except where explicitly stated otherwise.

Without the capability to explicitly specify template parameters, users cannot take the address of a Ranges algorithm to detect whether it takes a particular parameter by value or forwarding reference. I can't think of any other variation of "A call to a non-member function signature" ([global.functions/2) that this PR breaks. Pending any future developments, I think this PR is good.

**Comment by ericniebler** [comment]
> users cannot take the address of a Ranges algorithm to detect whether it takes a particular parameter by value or forwarding reference. 

Users could certainly pass a function object that detects whether its copy/move constructor was called when the object was passed to an algorithm, could they not?

**Comment by timsong-cpp** [comment]
> Without the capability to explicitly specify template parameters, users cannot take the address of a Ranges algorithm to detect whether it takes a particular parameter by value or forwarding reference.

`static_cast` to a signature?

**Comment by CaseyCarter** [comment]
> Users could certainly pass a function object that detects whether its copy/move constructor was called when the object was passed to an algorithm, could they not?

Yes they can, and an implementation of an algorithm that accepts an expression that references an object for a nominally by-value parameter must move/copy that argument into an object as specified.

> `static_cast` to a signature?

*This* I agree is broken: the function template will not convert into a function reference / pointer of the appropriate type.

**Comment by CaseyCarter** [comment]
Updated PR with the drop-back-and-punt solution: stop trying to be eloquent and simply specify these overloads directly.

**Comment by CaseyCarter** [comment]
Updated PR to also strike [algorithms.general]/10, the "Implementations make these Range/Iterator algorithm overloads work somehow" paragraph. It's no longer necessary now that we have explicitly disambiguated all such overloads.
