### ISSUE TITLE
Use expression-equivalent in definitions of CPOs

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#262]
...which is not part of the general library meaning of "Effects: Equivalent to." We need to document this explicitly at each occurrence, or introduce blanket wording that covers the different usage in 
CPO descriptions, or introduce a new term (e.g. "expression-equivalent-to").

[*NOTE:* C++14's *`DECAY_COPY`* pseudo-macro is defined in terms of a `decay_copy` function which is *not* `constexpr` or `noexcept`, so nowhere can we say that something is *expression-equivalent to* an expression involving *`DECAY_COPY`* if we want to retain `constexpr`- and `noexcept`-ness ... unless we define our own *`DECAY_COPY`* that preserves `constexpr`- and `noexcept`-ness. -- *end note*]

Proposed Resolution
--------------------

After [iterator.requirements.general], add a new subsection "decay_copy" (stable name [iterator.decaycopy]), with the following contents:

> **`decay_copy`** [iterator.decaycopy]
> 1 Several places in this Clause use the expression <tt><i>DECAY_COPY</i>(x)</tt>, which is equivalent
> to `decay_t<decltype((x))>(x)`.

Change [iterator.range.begin]/p1 to read:

```diff
 The name begin denotes a customization point object ([customization.point.object]).
 The effect of the expression ranges::begin(E) for some expression E is
-equivalent to:
+expression-equivalent to:
```

Change [iterator.range.end]/p1 to read:

```diff
 The name end denotes a customization point object ([customization.point.object]).
 The effect of the expression ranges::end(E) for some expression E is
-equivalent to:
+expression-equivalent to:
```

Change [iterator.range.cbegin]/p1 to read:

```diff
 The name cbegin denotes a customization point object ([customization.point.object]).
 The effect of the expression ranges::cbegin(E) for some expression E of type T is
-equivalent to ranges::begin(static_const<const T&>(E)).
+expression-equivalent to ranges::begin(static_const<const T&>(E)).
```

Change [iterator.range.cend]/p1 to read:

```diff
 The name cend denotes a customization point object ([customization.point.object]).
 The effect of the expression ranges::cend(E) for some expression E of type T is
-equivalent to ranges::end(static_const<const T&>(E)).
+expression-equivalent to ranges::end(static_const<const T&>(E)).
```

Change [iterator.range.rbegin]/p1 to read:

```diff
 The name rbegin denotes a customization point object ([customization.point.object]).
 The effect of the expression ranges::rbegin(E) for some expression E is
-equivalent to:
+expression-equivalent to:
```

Change [iterator.range.rend]/p1 to read:

```diff
 The name rend denotes a customization point object ([customization.point.object]).
 The effect of the expression ranges::rend(E) for some expression E is
-equivalent to:
+expression-equivalent to:
```

Change [iterator.range.crbegin]/p1 to read:

```diff
 The name crbegin denotes a customization point object ([customization.point.object]).
 The effect of the expression ranges::crbegin(E) for some expression E of type T is
-equivalent to ranges::rbegin(static_cast<const T&>(E)).
+expession-equivalent to ranges::rbegin(static_cast<const T&>(E)).
```

Change [iterator.range.crend]/p1 to read:

```diff
 The name crend denotes a customization point object ([customization.point.object]).
 The effect of the expression ranges::crend(E) for some expression E of type T is
-equivalent to ranges::rend(static_cast<const T&>(E)).
+expession-equivalent to ranges::rend(static_cast<const T&>(E)).
```

Change [range.primitives.size]/p1 to read:

```diff
 The name size denotes a customization point object ([customization.point.object]).
 The effect of the expression ranges::size(E) for some expression E with type T is
-equivalent to:
+expression-equivalent to:
-(1.1) - extent<T>::value if T is an array type (ISO/IEC 14882:2014 §3.9.2).
+(1.1) - DECAY_COPY(extent<T>::value) if T is an array type (ISO/IEC 14882:2014 §3.9.2).
```

Change [range.primitives.empty]/p1 to read:

```diff
 The name empty denotes a customization point object ([customization.point.object]).
 The effect of the expression ranges::empty(E) for some expression E is
-equivalent to:
+expression-equivalent to:
```

Change [range.primitives.data]/p1 to read:

```diff
 The name data denotes a customization point object ([customization.point.object]).
 The effect of the expression ranges::data(E) for some expression E is
-equivalent to:
+expression-equivalent to:
```

Change [range.primitives.cdata]/p1 to read:

```diff
 The name cdata denotes a customization point object ([customization.point.object]).
 The effect of the expression ranges::cdata(E) for some expression E of type T is
-equivalent to ranges::data(static_cast<const T&>(E)).
+expression-equivalent to ranges::data(static_cast<const T&>(E)).
```

**Comment by ericniebler** [comment]
Smallest change would be to change what "equivalent to" means in the context of CPOs. I find that somewhat distasteful. We should examine what breaks when we change "Effects: equivalent to" across the whole library to include `constexpr` and `noexcept`.

**Comment by jwakely** [comment]
I believe it's because those are part of the function declarator, not the effects. i.e. they're part of the C++ description of the function, not the English prose description. That's not a very helpful answer though.

**Comment by CaseyCarter** [comment]
We need to formulate other CPOs in terms of expression-equivalence as #284 does for `iter_move` and `iter_swap`.

**Comment by CaseyCarter** [comment]
LWG Kona review suggested making a sweep of the TS wording for other occurrences that could be simplified with the application of "expression-equivalent to."

**Comment by ericniebler** [comment]
@CaseyCarter for your review

**Comment by CaseyCarter** [comment]
The `decay_copy` wording is awkward (and in C++14 as well). Why not simply:

> 1 Several places in this Clause use the expression `DECAY_COPY(x)`, which is equivalent to `decay_t<decltype((x))>(x)`.

**Comment by ericniebler** [comment]
I prefer to keep it close to the (admittedly awkward) C++14 formulation.

**Comment by CaseyCarter** [comment]
I'm mildly concerned that the `noexcept` clause uses `is_nothrow_constructible` whereas the return is actually performing an implicit conversion. I *think* that our uses of `DECAY_COPY` only apply it to `CopyConstructible` types - iterators, sentinels, and integers - so the difference is moot for the TS.

**Comment by ericniebler** [comment]
> I'm mildly concerned that the `noexcept` clause uses `is_nothrow_constructible` whereas the return is actually performing an implicit conversion.

OK, how about now?

> Several places in this Clause use the expression `DECAY_COPY(x)`, which is equivalent to `decay_t<decltype((x))>(x)`.

And I was mildly concerned that this could be a C-style cast, although I have a hard time imagining a situation where it could matter.

**Comment by CaseyCarter** [comment]
I believe it is now as correct as `decay_t<decltype((E))>(E)`, albeit significantly longer ;)

[`decay_t<decltype((E))>(E)` is equivalent to `static_cast<decay_t<decltype((E))>>(E)`, since there is always an implicit conversion sequence (the identity conversion) from `decay_t<decltype((E))>` to `decltype((E))`.]

**Comment by ericniebler** [comment]
OK, fine. ;-)

**Comment by CaseyCarter** [comment]
Looking at [range.primitives.size]: it's anomalous that the `extent` bullet for array types in the PR uses `size_t(extent<T>::value)` when all of the other bullets are `DECAY_COPY(...things...)`. I'm altering the PR to `DECAY_COPY(extent<T>::value)` for consistency. Shout if you disagree.

**Comment by ericniebler** [comment]
> it's anomalous that the `extent` bullet for array types in the PR uses `size_t(extent<T>::value)` when all of the other bullets are `DECAY_COPY(...things...)`. I'm altering the PR to `DECAY_COPY(extent<T>::value)` for consistency.

Should you also change `bool((E).empty())` to `DECAY_COPY((E).empty())` in [range.primitives.empty]? Likewise for `bool(ranges::begin(E) == ranges::end(E))`? I would say no, but then again, I thought there was nothing wrong with `size_t(extent<T>::value)`.

**Comment by CaseyCarter** [comment]
> Should you also change `bool((E).empty())` to `DECAY_COPY((E).empty())` in [range.primitives.empty]? Likewise for `bool(ranges::begin(E) == ranges::end(E))`?

No: those expressions could return a model of `Boolean` that we must convert to `bool`. The anomaly is *good* in those cases: it really does indicate something special is happening.

**Comment by CaseyCarter** [comment]
Needs a note describing the difference between our `DECAY_COPY` and IS `DECAY_COPY`.
