### ISSUE TITLE
Should ValueType<R> default to uncvref<ReferenceType<R>>?

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#28]
For the vast majority of iterators, the value type is the reference type with references and cv-qualifiers stripped. Defaulting `ValueType` would (a) be a convenience for iterator implementors, and (b) allow the removal of the special cases for pointer and array types from the definition of `value_type`. I propose that `value_type<T>` should be:
* User-defined specialization, if any.
* Otherwise if `T::value_type` is a type, `{ using type = T::value_type; }`
* Otherwise if `T::element_type` is a type, `{ using type = T::element_type; }`
* Otherwise if `ReferenceType<T>` is a type, `{ using type = ReferenceType<T>; }`
* Otherwise `{}`.

`ValueType<T>` would then be `value_type<T>::type` with references and cv-qualifiers stripped if `value_type<T>::type` exists and is a non-void type, and result in a substitution failure otherwise.

I've implemented this with GCC as:
```
template <class T>
using ReferenceType =
  decltype(*std::declval<T>());

namespace detail {
template <class T>
using uncvref =
  std::remove_cv_t<std::remove_reference_t<T>>;

template <class T>
struct nonvoid { using type = T; };
template <class T>
  requires std::is_void<T>::value
struct nonvoid<T> {};

template <class T>
concept bool HasValueType =
  requires { typename T::value_type; };

template <class T>
concept bool HasElementType =
  requires { typename T::element_type; };

template <class T>
concept bool HasReferenceType =
  requires { typename ReferenceType<T>; };
}

template <class>
struct value_type {};

template <detail::HasValueType T>
struct value_type<T> { using type = typename T::value_type; };

template <detail::HasElementType T>
  requires !detail::HasValueType<T>
struct value_type<T> { using type = typename T::element_type; };

template <detail::HasReferenceType T>
  requires !detail::HasElementType<T> && !detail::HasValueType<T>
struct value_type<T> { using type = ReferenceType<T>; };

template <class T>
using ValueType =
  detail::uncvref<meta::eval<detail::nonvoid<meta::eval<value_type<T>>>>>;
```

**Comment by CaseyCarter** [comment]
Note that there's also a drive-by fix here that prefers `T::value_type` over `T::element_type` if both exist.

**Comment by ericniebler** [comment]
> Note that there's also a drive-by fix here that prefers `T::value_type` over `T::element_type` if both exist.

Noted, but I'm not sure whether that's a fix or not. It is rightly(?) ambiguous if a type has both `value_type` and `element_type`. The user can resolve the ambiguity by specializing the `value_type` struct.

Also, I considered defaulting `value_type` the way you suggest, and may yet, but it's not completely obvious to me that it's the right thing. Consider the `zip` view that has `pair<X&,Y&>` as a reference type and `pair<X,Y>` as a value type. And proxy iterators as a general class. Defaulting `value_type` gives the wrong answer. That's not necessarily an argument against doing it, but it's something to consider.

**Comment by CaseyCarter** [comment]
> Noted, but I'm not sure whether that's a fix or not. It is rightly(?) ambiguous if a type has both value_type and element_type. The user can resolve the ambiguity by specializing the value_type struct.

I think `element_type` is only relevant here for backwards compatibility with smart pointers; it's essentially a historical mistake. As such, I'd like to minimize its impact on the Iterator design. I'll point out that an STL1 iterator type `T` that contains both `value_type` and `element_type` members has no ambiguity - `std::iterator_traits<T>::value_type` resolves to its `value_type` member - so this is a breaking change. That said, I'm not completely married to the idea although it would be nice to at least support the case when `T::value_type` and `T::element_type` are the same without requiring specialization of `std::value_type`.

> proxy iterators

That's why I said "vast majority" - the default is almost certainly incorrect for proxy iterators. My thought was that the vast majority of iterators will continue to be non-proxy iterators in the future as they have been in the past, in which case the convenience of the default would outweigh the relatively minor danger of inadvertently using that default with a proxy iterator. Given that we hope to end up with a library design in which proxy iterators will actually *work*, my belief may be unfounded.

There is historical quasi-precedent in that `std::iterator<tag, T>` defaults the type of `reference` to `T&`, but I don't find that a terribly convincing argument either. I'll change the issue title to a question instead of an imperative and we'll see if anyone else wants to comment.

**Comment by CaseyCarter** [comment]
No one else seems to think so.
