### ISSUE TITLE
iter_move and iter_swap need to say when they are noexcept and constexpr

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#284]
The proposed wording of #242 takes a stab at it but gets it wrong.

Proposed Resolution
-----------------------

Add two new paragraphs to [intro.defs] that read:

> -?-
> **constant subexpression**
> expression whose evaluation as subexpression of a conditional-expression `CE` (ISO/IEC 14882:2014 §5.16) would not prevent `CE` from being a core constant expression (ISO/IEC 14882:2014 §5.19)
>
> -?-
> **expression-equivalent**
> relationship that exists between two expressions `E1` and `E2` such that
> - `E1` and `E2` have the same effects,
> - `noexcept(E1) == noexcept(E2)`, and
> - `E1` is a constant subexpression if and only if `E2` is a constant subexpression

[_Editor's note:_ the definition of "constant subexpression" is taken from the latest C++17 draft.]

Change [iterator.utils.iter_move]/1 as follows:

```diff
 1 The name iter_move denotes a customization point
-  object (3.3.2.3). The effect of the expression
+  object (3.3.2.3). The expression
   ranges::iter_move(E) for some expression E is
-  equivalent to the following:
+  expression-equivalent to the following:
-(1.1) — iter_move(E), if that expression is well-formed
+(1.1) — static_cast<decltype(iter_move(E))>(iter_move(E)),
+      if that expression is well-formed
       when evaluated in a context that does not include
       ranges::iter_move but does include the lookup set
       produced by argument-dependent lookup (ISO/IEC
       14882:2014 §3.4.2).
-(1.2) — Otherwise, if the expression *E is well-formed
-(1.2.1) — If *E is an lvalue, std::move(*E).
-(1.2.2) — Otherwise, *E.
+(1.2) — Otherwise, if the expression *E is well-formed:
+(1.2.1) — if *E is an lvalue, std::move(*E);
+(1.2.2) — otherwise, static_cast<decltype(*E)>(*E).
 (1.3) — Otherwise, ranges::iter_move(E) is ill-formed.
```

Change [iterator.utils.iter_swap]/1 as follows:

```diff
 1 The name iter_swap denotes a customization point
-  object (3.3.2.3). The effect of the expression
+  object (3.3.2.3). The expression
   ranges::iter_swap(E1, E2) for some expressions E1
-  and E2 is equivalent to the following:
+  and E2 is expression-equivalent to the following:
 (1.1) - (void)iter_swap(E1, E2), if that expression is well-
       formed when evaluated in a context that does not
       include ranges::iter_swap but does include the
       lookup set produced by argument-dependent lookup
       (ISO/IEC 14882:2014 §3.4.2) and the following
       declaration:
         void iter_swap(auto, auto) = delete;
 (1.2) - Otherwise, if the types of E1 and E2 both satisfy
       Readable, and if the reference type of E1 is swappable
       with (4.2.11) the reference type of E2, then
       ranges::swap(*E1, *E2).
 (1.3) - Otherwise, if the types T1 and T2 of E1 and E2
       satisfy IndirectlyMovableStorable<T1, T2>() &&
       IndirectlyMovableStorable<T2, T1>(),
-      exchanges the values denoted by E1 and E2.
+      (void)(*E1 = iter_exchange_move(E2, E1)), except
+      that E1 is evaluated only once.
+
+2 iter_exchange_move is an exposition-only function specified as:
+
+    template <class X, class Y>
+      constexpr value_type_t<remove_reference_t<X>> iter_exchange_move(X&& x, Y&& y)
+        noexcept(see below);
+
+(2.1) Effects: Equivalent to:
+
+        value_type_t<remove_reference_t<X>> old_value(iter_move(x));
+        *x = iter_move(y);
+        return old_value;
+
+(2.2) The expression in the noexcept is equivalent to:
+
+        NE(remove_reference_t<X>, remove_reference_t<Y>) &&
+        NE(remove_reference_t<Y>, remove_reference_t<X>)
+
+      Where NE(T1, T2) is the expression:
+
+        is_nothrow_constructible<value_type_t<T1>, rvalue_reference_t<T1>>::value &&
+        is_nothrow_assignable<value_type_t<T1>&, rvalue_reference_t<T1>>::value &&
+        is_nothrow_assignable<reference_t<T1>, rvalue_reference_t<T2>>::value &&
+        is_nothrow_assignable<reference_t<T1>, value_type_t<T2>>::value> &&
+        is_nothrow_move_constructible<value_type_t<T1>>::value &&
+        noexcept(ranges::iter_move(declval<T1&>()))
```

**Comment by ericniebler** [comment]
_This resolution is incomplete._

Proposed resolution
-------------------

Change [iterator.synopsis] as follows:

```diff
namespace std { namespace experimental { namespace ranges { inline namespace v1 {
// 6.6, primitives:
// exposition only
template <class T> concept bool _Dereferenceable
  = requires(T& t) { {*t} -> auto&&; };

// 6.6.1, utilities:
namespace {
  // 6.6.1.1, iter_move:
  constexpr unspecified iter_move = unspecified ;
  // 6.6.1.2, iter_swap:
  constexpr unspecified iter_swap = unspecified ;
}

+// REF, iter_exchange
+template <class X, class Y>
+     requires see below
+constexpr value_type_t<remove_reference_t<X>> iter_exchange(X&& x, Y&& y) 
+    noexcept(see below);
```

After subsection [iterator.utils.iter_swap], add a new subsection titled "**iter_exchange**" [iterator.utils.iter_exchange] with the following:

>```c++
> template <class X, class Y>
>     requires see below
> constexpr value_type_t<remove_reference_t<X>> iter_exchange(X&& x, Y&& y)
>   noexcept(see below);
> ```
> 1 In the below, let `A` be `remove_reference_t<X>` and let `B` be `remove_reference_t<Y>`.
> 2 _Effects:_
> > ```c++
> > value_type_t<A> old_value = ranges::iter_move((X&&)x);
> > *(X&&)x = iter_move((Y&&)y);
> > return old_value;
> > ```
>
> 3 The `requires` expression is equivalent to `Readable<A>() && Readable<B>() && Constructible<value_type_t<A>, rvalue_reference_t<A>>() && Writable<A, rvalue_reference_t<Y>>() && MoveConstructible<value_type_t<A>>()`

noexcept(is_nothrow_indirectly_movable_v<remove_reference_t<X>, remove_reference_t<Y>> && is_nothrow_move_constructible<value_type_t<remove_reference_t<X>>>::value) {

**Comment by ericniebler** [comment]
@CaseyCarter Rip this to shreds.

**Comment by timsong-cpp** [comment]
Not Casey (obviously), but some comments:

"is a constant expression" definitely doesn't work (that means `void f(int *p) { constexpr auto&& i = ranges::iter_move(p); }` must work, which is obviously nonsensical.)

I think what this need is some variant of the wording used for `assert` and `addressof` (see [LWG 2296](https://timsong-cpp.github.io/lwg-issues/2296) and [2234](https://timsong-cpp.github.io/lwg-issues/2234)), i.e., define *constant subexpression* and use that.

"expression is noexcept" is also not a defined concept; we can say "`noexcept(expression)` is `true`".

**Comment by CaseyCarter** [comment]
> define *constant subexpression* and use that.

i.e., steal 17.3.6 from the C++17 WP. This would conveniently give us a "Terms and Definitions" clause, as required by the ISO/IEC directives part 2 §6.4.

**Comment by CaseyCarter** [comment]
All of the repetition here is reminding me that Lisa Lippincot suggested in LWG that we define a new term for expression equivalence that includes `noexcept` and constant subexpression-ness so we can avoid saying "`E1` is equivalent to `E2`; `noexcept(E1)` is `noexcept(E2)`; `E1` is a constant subexpression if `E2` is." over and over.

**Comment by CaseyCarter** [comment]
I hate the note in [iterator.utils.iter_swap]/1.3; it seems tutorial and/or over-specified.

Perfect-forwarding is wrong for `x` and `y` in the effects of `iter_exchange`. We aren't using `&&` here to perfect forward, we're using it because we don't care if the caller passes us lvalues or rvalues. It's also odd that these effects use `iter_move` both qualified and unqualified:
```c++
value_type_t<A> old_value = iter_move(x);
*x = iter_move(y);
return old_value;
```

**Comment by ericniebler** [comment]
> define a new term for expression equivalence that includes `noexcept` and constant subexpression-ness

Naming suggestions? "Super ultra equivalent to"? ;-) I guess we could be boring and say "noexcept-constexpr equivalent to".

**Comment by CaseyCarter** [comment]
>  Naming suggestions?

Bear in mind you're asking the person who named "cmcstl2"and "BikeshedEqualityComparable." Why not ask Twitter?

**Comment by ericniebler** [comment]
> This would conveniently give us a "Terms and Definitions" clause, as required by the ISO/IEC directives part 2 §6.4.

I can't figure out what this means. 6.4 doesn't refer to anything called "Terms and Definitions".

**Comment by CaseyCarter** [comment]
> I can't figure out what this means. 6.4 doesn't refer to anything called "Terms and Definitions".

Table 2 "Overview of the major subdivisions of a document and their arrangement in the text" includes a mandatory "Terms and definitions" section immediately after the normative references.

**Comment by CaseyCarter** [comment]
I suppose I should point out that I'm looking at http://www.iec.ch/members_experts/refdocs/iec/isoiecdir-2%7Bed7.0%7Den.pdf, the part 2 v 7, which I believe is the most recent.

**Comment by ericniebler** [comment]
We already have a definitions clause: 3.2.

**Comment by ericniebler** [comment]
I added definitions of "constant subexpression" and "noexcept constexpr equivalent to" (but haven't used them yet). Comments welcome.

**Comment by CaseyCarter** [comment]
> 2 Whenever the _Effects:_ element specifies that the semantics of some function `F` are _Noexcept-constexpr equivalent to_ some code sequence, then the description elements have the same interpretation as if the _Effects:_ element had specified that `F` were _Equivalent to_ that code sequence, with the addition that, when called with arguments `args...`

We want to specify the semantics of *expressions* rather than functions. `ranges::iter_move`, for example, is not a function: it's name that denotes a CPO. We want to specify the semantics of the expression `ranges::iter_move(E)` for some subexpression `E` as being equivalent to <stuff>.

Maybe *expression-equivalent* would be a reasonable name? I think that may have been the original suggestion in LWG, and "Foo is expression-equivalent to bar" is reasonably distinct from "foo is equivalent to bar."

Do we actually need the power of entire code sequences? I think all of the CPO specifications are purely expression-to-expression mappings. Without full code sequences, that majority of this specification complexity goes away. Also, there's a lot of C++ syntax missing here that needs to be either characterized (`T t{a...}`, `T t = {a...}` came to mind just looking at the "local variable" bullets) or somehow ruled out.

**Comment by CaseyCarter** [comment]
> Do we actually need the power of entire code sequences?

I see you've used noexcept-constexpr-equivalence of a function with a code sequence in the definition of `iter_exchange`. This doesn't make sense to me, given that `iter_exchange` is in fact an actual function, and it already has `constexpr` and conditional `noexcept` specified in its declaration. A function declared `constexpr` *should* be a constant subexpression when the expressions in the code sequence specified in its *Effects:* element meet the requirements in [expr.const]; I'm inclined to leave that problem alone until [LWG2833](http://cplusplus.github.io/LWG/lwg-active.html#2833) is resolved.

**Comment by ericniebler** [comment]
> Do we actually need the power of entire code sequences? I think all of the CPO specifications are purely expression-to-expression mappings.

My thinking is that the notion of noexcept-constexpr equivalence is going to be handy outside the definitions of CPOs. But scaling this back for now certainly would make the change simpler and easier to swallow.

> I hate the note in [iterator.utils.iter_swap]/1.3; it seems tutorial and/or over-specified.

If we are to use _expression-equivalent-to_, we need to say what an equivalent expression is. I think our best bet is to just pick one; say, `void(*e1 = ranges::iter_exchange(e2, e1))`.

**Comment by CaseyCarter** [comment]
> But scaling this back for now certainly would make the change simpler and easier to swallow.

This. I can see us spending a week on this fixing corners and plugging holes, and still have to go through LWG 3 times to make everyone happy.

> If we are to use _expression-equivalent-to_, we need to say what an equivalent expression is. I think our best bet is to just pick one

+1

**Comment by CaseyCarter** [comment]
We should send this to EWG and threaten to specify `noexcept(auto)` by hand in the library if they won't give it to us in the language. ;)

**Comment by ericniebler** [comment]
I can't find a definition of the library term "equivalent to" except where is meaning in _Effects:_ clauses is described. I can't use that to define _expression-equivalent-to_ since that will appear outside _Effects:_ clauses. Suggestions?

**Comment by CaseyCarter** [comment]
How about:

In some cases, the behavior of library components in expressions is specified as being *expression-equivalent* to some other expression. When an expression `E1` is expression-equivalent to another expression `E2`, the effects are as if `E1` were replaced with `E2` in the original program. [ *Note:* This is similar to "Effects: Equivalent to" (\ref) used in the description of function semantics, but additionally implies that `noexcept(E1) == noexcept(E2)`, and that `E1` is a constant subexpression if and only if `E2` is a constant subexpression.---*end note*]

**Comment by CaseyCarter** [comment]
> In some cases,

Dead words. "The behavior of library components in expressions is sometimes specified as..."

**Comment by CaseyCarter** [comment]
> as being *expression-equivalent* to some other expression.

Replace "some other expression" throughout with "a replacement expression."

**Comment by CaseyCarter** [comment]
> effects are as if `E1` were replaced with `E2` in the original program

as if `E1` were replaced *by* `E2`

**Comment by ericniebler** [comment]
I simplified a bit. Take a look.

**Comment by CaseyCarter** [comment]
I like this *a lot* - it's approaching elegance.

Nitpicks:

> After [definitions]/1, add two new paragraphs that read:

Needs a blank line between the two paragraphs.

> `(void)(*e1 = ranges::iter_exchange(E2, e1))`, where `e1` is the `Readable` object referenced by the expression `E1`.

For a similar case in another CPO (I forget which) I used the original expression directly and tacked on a "except that `E1` is only evaluated once."

**Comment by ericniebler** [comment]
W00t. Let's run with it.

**Comment by ericniebler** [comment]
@jwakely, could you weigh in here on the definition of "expression-equivalent to" in the Proposed Resolution and its use in the specification of the `iter_move` and `iter_swap` customization point objects? TIA.

**Comment by jwakely** [comment]
Why the `static_cast<decltype(X)>(X)` expressions? Doesn't `X` already have that type?

**Comment by ericniebler** [comment]
Because without guaranteed copy elision, a function cannot behave exactly like the equivalent expression without a move, if that expression is a prvalue.

**Comment by CaseyCarter** [comment]
LWG: After applying this, consider making a sweep to see where "expression-equivalent" could be used to simplify the existing wording.

**Comment by CaseyCarter** [comment]
Potential rework for exposition-only `iter_exchange`. (The use-before-definition of `ITER_EXCHANGE(X,Y)` is awkward, but not unprecedented: `INVOKE` is used 104 pages before its definition in the Standard.) I've made the conditional `noexcept` symmetric as well.

> -?-
> **constant subexpression**
> expression whose evaluation as subexpression of a conditional-expression `CE` (ISO/IEC 14882:2014 §5.16) would not prevent `CE` from being a core constant expression (ISO/IEC 14882:2014 §5.19)
>
> -?-
> **expression-equivalent**
> relationship that exists between two expressions `E1` and `E2` such that
> - `E1` and `E2` have the same effects,
> - `noexcept(E1) == noexcept(E2)`, and
> - `E1` is a constant subexpression if and only if `E2` is a constant subexpression

[_Editor's note:_ the definition of "constant subexpression" is taken from the latest C++17 draft.]

Change [iterator.utils.iter_move]/1 as follows:

```diff
 1 The name iter_move denotes a customization point
-  object (3.3.2.3). The effect of the expression
+  object (3.3.2.3). The expression
   ranges::iter_move(E) for some expression E is
-  equivalent to the following:
+  expression-equivalent to the following:
-(1.1) iter_move(E), if that expression is well-formed
+(1.1) static_cast<decltype(iter_move(E))>(iter_move(E)),
+      if that expression is well-formed
       when evaluated in a context that does not include
       ranges::iter_move but does include the lookup set
       produced by argument-dependent lookup (ISO/IEC
       14882:2014 §3.4.2).
 (1.2) — Otherwise, if the expression *E is well-formed
 (1.2.1) — If *E is an lvalue, std::move(*E).
-(1.2.2) — Otherwise, *E.
+(1.2.2) — Otherwise, static_cast<decltype(*E)>(*E).
 (1.3) — Otherwise, ranges::iter_move(E) is ill-formed.
```

Change [iterator.utils.iter_swap]/1 as follows:

```diff
 1 The name iter_swap denotes a customization point
-  object (3.3.2.3). The effect of the expression
+  object (3.3.2.3). The expression
   ranges::iter_swap(E1, E2) for some expressions E1
-  and E2 is equivalent to the following:
+  and E2 is expression-equivalent to the following:
 (1.1) - (void)iter_swap(E1, E2), if that expression is well-
       formed when evaluated in a context that does not
       include ranges::iter_swap but does include the
       lookup set produced by argument-dependent lookup
       (ISO/IEC 14882:2014 §3.4.2) and the following
       declaration:
         void iter_swap(auto, auto) = delete;
 (1.2) - Otherwise, if the types of E1 and E2 both satisfy
       Readable, and if the reference type of E1 is swappable
       with (4.2.11) the reference type of E2, then
       ranges::swap(*E1, *E2).
 (1.3) - Otherwise, if the types T1 and T2 of E1 and E2
       satisfy IndirectlyMovableStorable<T1, T2>() &&
       IndirectlyMovableStorable<T2, T1>(),
-      exchanges the values denoted by E1 and E2.
+      (void)(*E1 = ITER_EXCHANGE(E2, E1)), except
+      that E1 is evaluated only once.
+
+2 ITER_EXCHANGE(A, B) is a call to the exposition-only function `iter_exchange` defined as:
+
+    template <class X, class Y>
+      constexpr value_type_t<remove_reference_t<X>> iter_exchange(X&& x, Y&& y)
+        noexcept(see below);
+
+(2.1) Let T1 be remove_reference_t<X> and let T2 be remove_reference_t<Y>.
+
+(2.2) Effects: Equivalent to:
+
+        value_type_t<T1> old_value(iter_move(x));
+        *x = iter_move(y);
+        return old_value;
+
+(2.3) The expression in the `noexcept` is equivalent to:
+
+        is_nothrow_indirectly_movable_v<T1, T2> &&
+        is_nothrow_indirectly_movable_v<T2, T1> &&
+        is_nothrow_move_constructible<value_type_t<T1>>::value &&
+        is_nothrow_move_constructible<value_type_t<T2>>::value
```

[_Editor's note:_ the above `noexcept` clause depends on the resolution of #317 for correctness.]

**Comment by ericniebler** [comment]
This reformulation loses the fix to `is_nothrow_indirectly_movable` in #317. `iter_move` might not be `noexcept`.

Also,

```diff
+(2.2) Let XXX(T1, T2) be the expression:
+
+        is_nothrow_constructible<value_type_t<T1>, rvalue_reference_t<T1>>::value &&
+        is_nothrow_assignable<value_type_t<T1> &, rvalue_reference_t<T1>>::value &&
+        is_nothrow_assignable<reference_t<T1>, rvalue_reference_t<T2>>::value &&
+        is_nothrow_assignable<reference_t<T1>, value_type_t<T2>>::value> &&
+        is_nothrow_move_constructible<value_type_t<T1>>::value &&
```

Drop the trailing `&&`.

**Comment by CaseyCarter** [comment]
Updated in-place:
* rename noexcept "macro" `XXX` to `NE`
* tack `noexcept(ranges::iter_move(declval<T1&>()))` onto the noexcept "macro"

Better?

**Comment by ericniebler** [comment]
Better. Maybe rename to `ITER_EXCHANGE_MOVE` and `iter_exchange_move` because the committee didn't like the `iter_exchange` name.

**Comment by ericniebler** [comment]
I move the PR to the top.

**Comment by CaseyCarter** [comment]
> I move the PR to the top.

I really wish github markdown had a "windowshade" tag that would abbreviate/collapse a section of text until clicked.
