### ISSUE TITLE
"regular function" != `RegularInvocable`

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#288]
Per the discussion in ericniebler/range-v3#499. `f` is an "operand" of the expression `invoke(f, args...)`, and both an "input" and (if mutable) an "output" thereof. `RegularInvocable`'s requirement that "The `invoke` function call expression shall be equality-preserving" is therefore not sufficient to ensure that the result of invoking `f` with `args...` depends only on the value of `args...`.

This fundamentally breaks equational reasoning in the algorithms, e.g., I cannot prove that the result of calling `sort(range, comp)` on a sequence is a sorted sequence if the comparator can be stateful. We need to restore the equivalence of regular functions and `RegularInvocable`s.

### Proposed Resolution:

Modify [concepts.lib.callable.regularinvocable] to read:

```diff
 1 The invoke function call expression shall be equality-preserving
+  and shall not modify the function object or the arguments.
   (4.1.1). [ Note: This requirement supersedes the annotation in the definition of
   Invocable. —end note ]
```

**Comment by CaseyCarter** [comment]
Actually, is there any reason not to require that the `invoke` expression required for `RegularInvocable` not modify *any* of its operands?

**Comment by ericniebler** [comment]
That would be a departure from how we've been defining "regular function" and an expression's inputs and outputs (the latter of which permit out parameters if I remember correctly). So... why?

**Comment by CaseyCarter** [comment]
Equational reasoning. The postcondition of e.g. `sort(rng, comp)` is `is_sorted(rng, comp)`. That postcondition isn't achievable if `comp` can accumulate state or mutate its operands. The meaning of `comp(a, b)` becomes something like "Was `a` less than `b` before I invoked `comp`?"

**Comment by ericniebler** [comment]
Make it so!

**Comment by ericniebler** [comment]
I have amended the proposed resolution accordingly.
