### ISSUE TITLE
[iterator, count) ranges

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#289]
> * [alg.copy]  Does copy_n need a “Requires:” element stating that [result, result + n) is a valid range?
>
> * same concern for fill_n and generate_n.

We have "The result of the application of functions in the library to invalid ranges is undefined." in [iterator.requirements.general]/10 where "range" is defined: "A range is an iterator and a sentinel that designate the beginning and end of the computation." Instead of adding a requirement to every `_n` algorithm, we should expand the blanket wording to cover [iterator, count) ranges as well.

Proposed Resolution
--------------------

Change  [iterator.requirements.general] as follows:

```diff
  7 Most of the library’s algorithmic templates that operate on data structures have interfaces
    that use ranges. A range is an iterator and a sentinel that designate the beginning and end
    of the computation
+   , or an iterator and a count that designate the beginning and the number of elements to which
+   the computation is to be applied.

  8 An iterator and a sentinel denoting a range are comparable. 
-   A sentinel denotes an element when it compares equal to an iterator i, and i points to that
-   element.
    The types of a sentinel and an iterator that denote a range must satisfy Sentinel (9.3.9). A
    range [i,s) is empty if i == s; otherwise, [i,s) refers to the elements in the data 
    structure starting with the element pointed to by i and up to but not including the element
    pointed to by the first iterator j such that j == s.

  9 A sentinel s is called reachable from an iterator i if and only if there is a finite sequence
    of applications of the expression ++i that makes i == s. If s is reachable from i,
-   they denote a range.
+   [i,s) denotes a range.

+ ? A counted range [i,n) is empty if n == 0; otherwise, [i,n) refers to the n elements in the
+   data structure starting with the element pointed to by i and up to but not including the
+   element pointed to by the result of incrementing i n times.

 10 A range [i,s) is valid if and only if s is reachable from i.
+   A counted range [i,n) is valid if and only if n == 0; or n is positive, i is
+   dereferenceable, and [++i,--n) is valid.
    The result of the application of functions in the library to invalid ranges is unspecified.
```

Change [alg.fill]/p1 as follows:

```diff
 1. Effects: fill assigns value through all the iterators in the range [first,last).
-   fill_n assigns value through all the iterators in the range [first,first + n) if n is
+   fill_n assigns value through all the iterators in the counted range [first,n) if n is
    positive, otherwise it does nothing.
```

Change [alg.generate]/p1-2 as follows:

```diff

-1. Effects: Assigns the value of invoke(gen) through successive iterators in the 
-   range [first,last), where last is first + max(n, 0) for generate_n.
+1. Effects: The generate algorithms invoke the function object gen and assign the return value
+   of gen through all the iterators in the range [first, last). The generate_n algorithm invokes
+   the function object gen and assigns the return value of gen through all the iterators in
+   the counted range [first, n) if n is positive, otherwise it does nothing.
 
-2. Returns: last
+2. Returns: last, where last is first + max(n, 0) for generate_n
 
-3. Complexity: Exactly last - first evaluations of invoke(gen) and assignments.
+3. Complexity: Exactly last - first or n evaluations of invoke(gen) and assignments,
+   respectively.
```

**Comment by CaseyCarter** [comment]
Should be addressed together with #352 to avoid merge conflicts.

**Comment by ericniebler** [comment]
@CaseyCarter How about this?

Proposed Resolution
--------------------

To [algorithms.general], add a new paragraph that reads:

> 13. Counted versions of certain algorithms are provided. Counted algorithms accept a range as an iterator and a integral count, `[i,n)`, denoting the `n` elements starting at `i`. When such a version is provided for *algorithm* it is called *algorithm_n*. The requirements on the range `[i,n)` are the same as those specified for the range `[i,i+n)` ([iterator.requirements.general]).

**Comment by CaseyCarter** [comment]
`[i, i+n)` is not always the same range as `[i, n)`. Counted ranges are not in general equivalent to bounded ranges when iterators can have cyclic values. (For posterity: range-v3's `view::repeat` is the obvious example: a `repeat` view has a singular iterator value such that `i == ++i`, so `[i, i+42) == [i,i) != [i,42)`.)

I think we need to update the definition of valid range to resolve this.

**Comment by CaseyCarter** [comment]
...or:

> 13. Counted versions of certain algorithms are provided. Counted algorithms accept an iterator and a integral count, denoting the `n` elements starting at `i`. When such a version is provided for *algorithm* it is called *algorithm_n* and behaves as if it is implemented by dispatching to the overload that takes separate iterator and sentinel arguments with `counted_iterator<decltype(i)>{i, n}` and `default_sentinel{}`.

**Comment by CaseyCarter** [comment]
> `[i, i+n)` is not always the same range as `[i, n)`.

Blech, this affects the existing specifications of the `_n` algorithms. `fill_n`, for example, "assigns `value` through all the iterators in the range `[first,first + n)`...". Those will need cleanup, or removal if we can get the blanket behavior paragraph right. Ironically the return values are fine: `[i,n)` is not always the same range as `[i,i+n)`, but the end iterator values of both ranges are provably equal.

**Comment by ericniebler** [comment]
Can we define a range as and iterator/sentinel `[i,s)` *or* and iterator/count `[i,n)`? If so, we can say that for `[i,s)` it's what we know now, and for `[i,n)` it is the `n` elements starting at `i`. Then we can define the counted algorithms as operating on range `[i,n)` instead of `[i,i+n)`.

**Comment by ericniebler** [comment]
How's this?

Proposed Resolution
-----------------

After [iterator.requirements.general]/p8, add:

> 8. Some of the library’s algorithmic templates that operate on data structures have interfaces that use *counted ranges*. A counted range is an iterator and integer that designate the beginning of the sequence and the number of elements in the sequence.
> 9. A counted range `[i,n)` is empty if `n == 0`; otherwise, `[i,n)` refers to the `n` elements in the data structure starting with the element pointed to by `i` and up to but not including the element pointed to by the result of incrementing `i` `n` times.

Change [alg.fill]/p1 as follows:

```diff
 1. Effects: fill assigns value through all the iterators in the range [first,last).
-fill_n assigns value through all the iterators in the range [first,first + n) if n is
+fill_n assigns value through all the iterators in the counted range [first,n) if n is
 positive, otherwise it does nothing.
```

Change [alg.generate]/p1-2 as follows:

```diff
 1. Effects: Assigns the value of invoke(gen) through successive iterators in the 
-   range [first,last), where last is first + max(n, 0) for generate_n.
+   range [first,last) for generate or the counted range [first,n) for generate_n
-2. Returns: last
+2. Returns: last, where last is first + max(n, 0) for generate_n
-3. Complexity: Exactly last - first evaluations of invoke(gen) and assignments.
+3. Complexity: Exactly last - first or n evaluations of invoke(gen) and assignments, respectively.
```

**Comment by CaseyCarter** [comment]
I'd like to incorporate counted ranges a bit more into the descriptive paragraphs:
```diff
  7 Most of the library’s algorithmic templates that operate on data structures have interfaces
    that use ranges. A range is an iterator and a sentinel that designate the beginning and end
    of the computation
+   , or an iterator and a count that designate the beginning and the number of elements to which
+   the computation shall be applied.

  8 An iterator and a sentinel denoting a range are comparable. 
-   A sentinel denotes an element when it compares equal to an iterator i, and i points to that
-   element.
    The types of a sentinel and an iterator that denote a range must satisfy Sentinel (9.3.9). A
    range [i,s) is empty if i == s; otherwise, [i,s) refers to the elements in the data 
    structure starting with the element pointed to by i and up to but not including the element
    pointed to by the first iterator j such that j == s.

  9 A sentinel s is called reachable from an iterator i if and only if there is a finite sequence
    of applications of the expression ++i that makes i == s. If s is reachable from i,
-   they denote a range.
+   [i,s) denotes a range.

+ ? A counted range [i,n) is empty if n == 0; otherwise, [i,n) refers to the n elements in the
+   data structure starting with the element pointed to by i and up to but not including the
+   element pointed to by the result of incrementing i n times.

 10 A range [i,s) is valid if and only if s is reachable from i.
+   A range [i,n) is valid if and only if n == 0 or i is dereferenceable and [++i,--n) is valid.
    The result of the application of functions in the library to invalid ranges is unspecified.
```

**Comment by ericniebler** [comment]
Why did you delete "A sentinel denotes an element when it compares equal to an iterator i, and i points to that element"?

**Comment by CaseyCarter** [comment]
> Why did you delete "A sentinel denotes an element when it compares equal to an iterator i, and i points to that element"?

I don't think it adds anything useful to "up to and not including the element pointed to by the first iterator `j` such that `j == s`." It feels like an artifact of the "sentinels are positions" design.

**Comment by ericniebler** [comment]
That's fine. Please review the proposed resolution at the top.
