### ISSUE TITLE
Where is `projected`?

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#296]
Assuming that `projected` is not exposition only, where does it live?

**Comment by CaseyCarter** [comment]
[projected] - section 6.3.3 in N4620.

**Comment by CaseyCarter** [comment]
...unless you actually meant "In which header is it declared?" To which the answer is "probably `<experimental/ranges/iterator>`." Like the iterator concepts themselves, `projected` fails to appear in any of the header synopses. #211 is all about the disconnect between the text and the synopses.
