### ISSUE TITLE
std::optional is not a thing in C++14

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#297]
Annex C references `std::optional`, but that doesn't exist in C++14.

**Comment by CaseyCarter** [comment]
### Proposed Resolution:

Replace occurrences of `std::optional` in [diff.cpp.defaultconstruct] (§C.1.4) with "something like `optional` as specified in the C++17 Working Draft" and reference N4618 §20.6 at the first such occurrence.

**Comment by CaseyCarter** [comment]
Closed by #333.
