### ISSUE TITLE
Is it intended that an aggregate with a deleted or nonexistent default constructor satisfy DefaultConstructible?

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#300]
For example, given

    struct A{
        A(const A&) = default;
    };

The following expressions are all valid:

    A{};
    new A{};
    new A[5]{};

which would seem to mean that `A` meets `DefaultConstructible` as defined in [concepts.lib.object.defaultconstructible], unless I missed something.

If this is intended, then the note in [concepts.lib.object.defaultconstructible] is incorrect.

Proposed Resolution
----------
See [P0547R1](http://wg21.link/p0547).

**Comment by CaseyCarter** [comment]
Close enough to intended, though I'm interested to get feedback from users on our choice of list-initialization for `Constructible` et al.

### Proposed Resolution:
Modify the note in [concepts.lib.object.defaultconstructible]/1 as follows:
```diff
 1 [ Note: The array allocation expression new T[n]{} implicitly requires that T 
-  has a non-explicit
+   does not have an explicit
   default constructor. —end note ]
```

**Comment by CaseyCarter** [comment]
Committee discussion of this issue needs to consider the fact that this implies the existence of `DefaultConstructible` types `T` for which the declaration `T foo;` is ill-formed. This is enough of a freakish corner case that I'm happy to leave it ill-formed and let the fix be "don't do that."

**Comment by ericniebler** [comment]
As with `std::is_constructible`, we can require `DefaultConstructible` to check the well-formed-ness of the statement `T tmp;`. That will require a compiler intrinsic, which makes it harder to implement the TS, but that may be a price worth paying. From googling around, I'll note the `__is_constructible` intrinsic already exists on MSVC 2013 and clang.
