### ISSUE TITLE
`insert_iterator` and `ostreambuf_iterator` don't properly support `*o++ = t;`

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#302]
See the discussion at https://github.com/CaseyCarter/cmcstl2/pull/60#issuecomment-265629745. Both iterators internally store state that must be updated on each write. We made a blanket change to have output iterators' `operator++(int)` return a copy instead of a reference after the discussion in #137 (and IIRC discussion with LWG at Kona) we broke `insert_iterator` and `ostreambuf_iterator`. The expression `*o++ = t` results in updating the state of the temporary immediately before throwing it on the floor. Later use of the iterator sees the "old" state and does terrible things.

The fix is to change the postfix increment of at least `insert_iterator` and `ostreambuf_iterator`, if not all of the output iterators specified in the TS, to again return by reference as in Standard C++.

### Proposed Resolution

Adopt [P0541](http://wg21.link/P0541).

**Comment by ericniebler** [comment]
Will be addressed by P0541. See https://github.com/ericniebler/stl2/blob/master/ext/post_inc/post_inc.md for wording.

**Comment by ericniebler** [comment]
P0541 was moved to ready in Kona.
