### ISSUE TITLE
Table 5 is missing many subclauses

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#308]
It only has 6.2 and 6.6-6.9.  6.3-6.5 along with 6.10-11 are missing.

I guess this is another "Clause 6 is disorganized" issue (cf. #211).

**Comment by ericniebler** [comment]
The analogous table in the IS (Table 88 — Iterators library summary) is also missing subclauses. I'm not sure if this is par for the course or not, but I'm not overly concerned.

I can add separate table elements for the Iterator, Indirect callable, and common algorithm requirements. That's clearly editorial.
