### ISSUE TITLE
Common and CommonReference should use ConvertibleTo to test for implicit convertibility

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#311]
**Issue # 1:** the expressions `common_type_t<T, U>(t())` and `common_reference_t<T, U>(t())` in the `Common` and `CommonReference` concepts could potentially be interpreted as function-style casts depending on the types involved, which could amount to `reinterpret_cast`s. That was not the intention.

The intention was to test that expressions of type `T` and `U` can be converted to the common type (or the common reference). The fix is to simply test that requirement instead with `ConvertibleTo`.

**Issue # 2:** One of the potential uses for `common_`(`type`|`reference`) is to have a way to declare monomorphic functions that satisfy e.g., `IndirectRelation` for use with the std:: algorithms. Indeed, `IndirectReference` requires the invocable to be callable with common-reference parameters. Consider:

```c++
auto rng = view::zip(vec1, vec2); // from range-v3
using R = iter_common_reference_t<iterator_t<decltype(rng)>>;
// Note: R might be different than decltype(*begin(rng)) for, e.g. a proxy iterator.
auto pred = [](R a, R b) { return a < b; };
ranges::sort( rng, pred );
```

Right now all the higher order functions are more or less broken because they just do `pred(*here, *there)`. For an iterator whose reference type is explicitly-but-not-implicitly convertible to the common reference type, the call will pass the concept check but fail to instantiate. That's Bad.

As above, the fix is to change `Common` and `CommonReference` to use `ConvertibleTo`. That requires _implicit_ convertibility, rather than the explicit convertibility that was being checked with the function-style cast.

_Note:_ The underlying traits `common_type` and `common_reference` only require explicit convertibility. We think it's fine, indeed essential for generic code, for the concepts to be more strict than the underlying type traits.

### Proposed Resolution

Change the definition of `CommonReference` in [concepts.lib.corelang.commonref]/1 as follows:

```diff
 template <class T, class U>
 concept bool CommonReference() {
-  return requires(T (&t)(), U (&u)()) {
-    typename common_reference_t<T, U>;
-    typename common_reference_t<U, T>;
-    requires Same<common_reference_t<T, U>, common_reference_t<U, T>>();
-    common_reference_t<T, U>(t());
-    common_reference_t<T, U>(u());
-  };
+  return
+    Same<common_reference_t<T, U>, common_reference_t<U, T>>() &&
+    ConvertibleTo<T, common_reference_t<T, U>>() &&
+    ConvertibleTo<U, common_reference_t<T, U>>();
 }
```

*Note:* this removes the `typename common_reference_t...` constraints since they are superfluous.

Change the definition of `Common` in [concepts.lib.corelang.common]/1 as follows:

```diff
 template <class T, class U>
 concept bool Common() {
-   return CommonReference<const T&, const U&>() &&
-    requires(T (&t)(), U (&u)()) {
-    typename common_type_t<T, U>;
-    typename common_type_t<U, T>;
-    requires Same<common_type_t<U, T>, common_type_t<T, U>>();
-    common_type_t<T, U>(t());
-    common_type_t<T, U>(u());
-    requires CommonReference<add_lvalue_reference_t<common_type_t<T, U>>,
-                             common_reference_t<add_lvalue_reference_t<const T>,
-                                                add_lvalue_reference_t<const U>>>();
- };
+ return
+   Same<common_type_t<T, U>, common_type_t<U, T>>() && 
+   ConvertibleTo<T, common_type_t<T, U>>() &&
+   ConvertibleTo<U, common_type_t<T, U>>() &&
+   CommonReference<add_lvalue_reference_t<const T>,
+                   add_lvalue_reference_t<const U>>() &&
+   CommonReference<add_lvalue_reference_t<common_type_t<T, U>>,
+                   common_reference_t<add_lvalue_reference_t<const T>,
+                                      add_lvalue_reference_t<const U>>>()
}
```

*Note:* this removes the `typename common_type_t...` constraints since they are superfluous. It also fixes a bug where the original `Common` definition was trying to form the types `const T&` and `const U&`. That fails for _cv_ `void`. We would like `Common<void, void>()` to be `true`.

**Comment by ericniebler** [comment]
@CaseyCarter for your review.

**Comment by ericniebler** [comment]
see also #301

**Comment by CaseyCarter** [comment]
> requires(T (&t)(), U (&u)()) {

These parameters are no longer ... "required".

> Note: This changes the requirement from an explicit conversion to an implicit conversion.

Despite that *I* suggested using implicit conversion, I am now uncomfortable. I vaguely recall that we had good reason to admit explicit-only conversions. (`chrono`?) The wording in [the latest revision of Walter's `common_type` paper](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0435r1.pdf) requires that "each of the argument types in such a specialization [of `common_type`] be explicitly convertible to the common type," and LWG has seen that at least once.

If the problem with functional cast notation is that if can `reinterpret_cast` and `reinterpret_cast` is too strong, maybe `static_cast<common_type_t<T, U>>(t())` (resp. `u()`) is the right answer? That does at least preserve the `Common<void, void>` case.

**Comment by CaseyCarter** [comment]
[concepts.lib.corelang.commonref]/1 uses `ConvertibleTo<T, C>()` and `ConvertibleTo<U, C>()` in its definition of *common reference type*, but `common_reference_t<T, U>(t())` (resp. `u()`) in the concept definition. Our resolution to this issue should ensure that the text agrees with the specification.

**Comment by CaseyCarter** [comment]
What was the motivation for this issue again? Why do I care of someone defines `common_type<int, my_type>` to something stupid that requires a `reinterpret_cast` to satisfy `Common`?

**Comment by ericniebler** [comment]
FWIW, the `chrono::duration` and `chrono::time_point` converting constructors are implicit.

One of the potential uses for `common_`(`type`|`reference`) is to have a way to declare monomorphic functions that satisfy e.g., `IndirectRelation` for use with the std:: algorithms. Indeed, `IndirectReference` requires the invocable to be callable with common-reference parameters. Consider:

```c++
using R = iter_common_reference_t<I>;
auto pred = [](R&& a, R&& b) { return a < b; };
ranges::sort( view::zip(vec1, vec2), pred );
```

Right now all the higher order functions are more or less broken because they just do `pred(*here, *there)`. For an iterator whose reference type is explicitly-but-not-implicitly convertible to the common reference type, the call will pass the concept check but fail to instantiate. That's Bad.

I _think_ it's fine that the trait only requires explicit convertibility but the concepts require implicit convertibility. Otherwise, I'm unsure how to write the algorithms.

**Comment by CaseyCarter** [comment]
> I *think* it's fine that the trait only requires explicit convertibility but the concepts require implicit convertibility. Otherwise, I'm unsure how to write the algorithms.

I agree this is our best answer; I am concerned that we will stomp on this wording when we redefine `ConvertibleTo` to require both implicit and explicit conversion in #167. Maybe:

```diff
 template <class T, class U>
 concept bool CommonReference() {
-  return requires(T (&t)(), U (&u)()) {
+  return requires {
       typename common_reference_t<T, U>;
       typename common_reference_t<U, T>;
+    } &&
-    requires Same<common_reference_t<T, U>, common_reference_t<U, T>>();
-    common_reference_t<T, U>(t());
-    common_reference_t<T, U>(u());
+    Same<common_reference_t<T, U>, common_reference_t<U, T>>() &&
+    std::is_convertible<T, common_reference_t<T, U>>::value &&
+    std::is_convertible<U, common_reference_t<T, U>>::value;
-  };
 }

 template <class T, class U>
 concept bool Common() {
   return CommonReference<const T&, const U&>() &&
-    requires(T (&t)(), U (&u)()) {
+    requires {
       typename common_type_t<T, U>;
       typename common_type_t<U, T>;
+    } &&
-    requires Same<common_type_t<U, T>, common_type_t<T, U>>();
-    common_type_t<T, U>(t());
-    common_type_t<T, U>(u());
-    requires CommonReference<add_lvalue_reference_t<common_type_t<T, U>>,
+    Same<common_type_t<U, T>, common_type_t<T, U>>() &&
+    std::is_convertible<T, common_type_t<T, U>>::value &&
+    std::is_convertible<U, common_type_t<T, U>>::value &&
+    CommonReference<add_lvalue_reference_t<common_type_t<T, U>>,
                     common_reference_t<add_lvalue_reference_t<const T>,
                                        add_lvalue_reference_t<const U>>>();
- };
}
```

**Comment by ericniebler** [comment]
> I am concerned that we will stomp on this wording when we redefine ConvertibleTo to require both implicit and explicit conversion

Why would that stop on this resolution? I think it strengthens it. If we want implicit convertibility, it would certainly be surprising to generic code that does an explicit conversion to get a different answer or to fail to instantiate.

**Comment by ericniebler** [comment]
Also, let's drop the ad hoc `requires { typename common_...; }` constraints since that's implicit by the `Same` constraints. Less code is better, right?

**Comment by CaseyCarter** [comment]
> Less code is better, right?

I have been preferring `requires { typename foo<T>; } && stuff<foo<T>>...` to `stuff<foo<T>>` in the hopes that it will eventually give "better" diagnostics when `foo<T>` results in substitution failure. That's obviously an implementation concern with no bearing on the spec. So yes, we should use the shorter and clearer of the equivalent forms.

**Comment by CaseyCarter** [comment]
> Why would that stomp on this resolution? 

I'm trying too hard to minimize requirements; I've forgotten that types that have implicit conversion but not explicit conversion to `T` *deserve* to be broken.

**Comment by ericniebler** [comment]
FWIW, I don't think minimizing requirements should be the goal. That way lies the C++0x concepts like `HasPlus` and madness. I know you know this already. Just sayin' for posterity.
