### ISSUE TITLE
MoveConstructible<T>() != std::is_move_constructible<T>()

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#313]
...when `T` is `const some_move_only_type` due to the use of `remove_cv_t` in the definition of `MoveConstructible`. This is sensible if `MoveConstructible` means "Can I construct a `T` object from an rvalue expression with `T`'s value type?" but becomes *very* surprising if we align the other `structibles with the meaning of the standard type traits.

`CopyConstructible` needs to change similarly for consistency.

Proposed Resolution
----------
See [P0547](https://github.com/ericniebler/stl2/blob/master/ext/constructible/constructible.md)

**Comment by CaseyCarter** [comment]
### Suggested resolution:

Change [concepts.lib.object.moveconstructible] as follows:

```diff
 template <class T>
 concept bool MoveConstructible() {
-  return Constructible<T, remove_cv_t<T>&&>() &&
-    ConvertibleTo<remove_cv_t<T>&&, T>();
+  return Constructible<T, T>() &&
+    ConvertibleTo<T, T>();
 }

-    1 Let rv be an rvalue of type remove_cv_t<T>. Then MoveConstructible<T>() is satisfied if
-(1.1) — After the definition T u = rv;, u is equal to the value of rv before the construction.
-(1.2) — T{rv} or *new T{rv} is equal to the value of rv before the construction.
-    2 rv’s resulting state is unspecified. [ Note: rv must still meet the requirements of the
-      library component that is using it. The operations listed in those requirements must work
-      as specified whether rv has been moved from or not.—end note ]
+    1 MoveConstructible<T>() is satisfied if and only if
+(1.1) — `T` is a non-object type, or
+(1.2) — `T` is an object type and the result of constructing a new object of type `T` from an
+         rvalue `rv` of type `T` is equal to `rv`'s original value, leaving `rv` in an
+         unspecified state. [ Note: rv must still meet the requirements of the library component
+         that is using it. The operations listed in those requirements must work as specified
+         whether rv has been moved from or not.—end note ]
```

**Comment by ericniebler** [comment]
Surely the _semantic_ constraints on `CopyConstructible` must change, too. IMO it should get the same treatment as `MoveConstructible` wrt non-object types.

**Comment by ericniebler** [comment]
> +    1   MoveConstructible<T>() is satisfied if and only if
> +(1.1) — T is a non-object type, or

Nope. `void` and function types are not move constructible. What I have done in the paper I'm working on is:

> 1 <ins>If `T` is an object type, then</ins>
>
> > &#8203;<ins>(1.1)</ins> Let `rv` be an rvalue of type <del>`remove_cv_t<`</del>`T`<del>`>`</del>. Then `MoveConstructible<T>()` is satisfied if and only if
> >
> > > (<ins>1.</ins>1.1) -- After the definition `T u = rv;`, `u` is equal to the value of `rv` before the construction.
> > > 
> > > (<ins>1.</ins>1.2) -- `T{rv}` <del>or `*new T{rv}`</del> is equal to the value of `rv` before the construction.
> > 
> > <ins>(1.</ins>2<ins>) If `T` is not `const`,</ins> `rv`'s resulting state is unspecified<ins>; otherwise, it is unchanged</ins>. [ _Note:_ `rv` must still meet the requirements of the library component that is using it. The operations listed in those requirements must work as specified whether `rv` has been moved from or not. --_end note_ ]

I don't bother saying, "Otherwise, `MoveConstructable` adds no further semantic constraints on its argument," but that's the gist.

**Comment by CaseyCarter** [comment]
> Surely the semantic constraints on CopyConstructible must change, too.

Yes, WIP. Distracted integrating cmcstl2 pulls.

> Nope. void and function types are not move constructible.

They fail in `Constructible`, and hence need no semantic requirements here.

**Comment by ericniebler** [comment]
So text which reads, "MoveConstructible() is satisfied if and only if T is a non-object type, or..." is wrong. I guess I'm confused about what you're suggesting.

**Comment by CaseyCarter** [comment]
The prose requirements are implicitly in addition to the syntactic requirements, here as in all of the other concepts.

**Comment by ericniebler** [comment]
But they should not be in contradiction of it.
