### ISSUE TITLE
Should Constructible<A,B> require ConvertibleTo<B,A>?

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#315]
It would be surprising to generic code if this works:

```c++
T t(a);
```

but this didn't:

```c++
T t = a;
```

**Comment by ericniebler** [comment]
@CaseyCarter ?

**Comment by CaseyCarter** [comment]
I agree, but I have doubts about implementability. Recall that at one time we had something similar, when we tried to make `Constructible<T, Args...>` require `sizeof...(Args) != 1 || ExplicitlyConvertible<Args..., T>` which ran afoul of template parameter kind problems. Trying to split `Constructible` into overloads by arity:

```c++
template<class T>
concept bool Constructible() { /*...*/ }
template<class T, Class Arg>
concept bool Constructible() { return ConvertibleTo<Arg, T>() && /*...*/ }
template<class T, class First, class... Rest>
concept bool Constructible() { /*...*/ }
```
simply pushes the template parameter kind problem into the users of `Constructible`.

**Comment by ericniebler** [comment]
It could be:

```c++
namespace detail {
	template <class...>
	struct front {
		using type = void;
	};
	template <class T>
	struct front<T> {
		using type = T;
	};
}

template <class T, class... Args>
concept bool Constructible() {
	return Destructible<T>() && _Is<T, is_constructible, Args...> &&
		!(sizeof...(Args) == 1 && !ConvertibleTo<meta::_t<detail::front<Args...>>, T>());
}
```

But now that I think about it, I don't think it's such a great idea. Pretty much every style guide out there tells people to avoid implicit converting constructors. If `Constructible` _requires_ implicit conversion, folks won't know what to do.

**Comment by CaseyCarter** [comment]
`DefaultConstructible` is still a question mark for me.  I know I want `Copy/MoveConstructible` to require conversion, so that copy-initialization is always usable. I don't have enough experience with the newly-changed rules for explicit default constructors to have formed an opinion on whether `DefaultConstructible` should require implicit construction.

**Comment by ericniebler** [comment]
How would you test for it?

**Comment by CaseyCarter** [comment]
> How would you test for it?
Maybe:
```c++
template <class T> struct S { static void f(T); };

/* ... */
requires { S<T>::f({}); }
```

**Comment by ericniebler** [comment]
I was just thinking that!

**Comment by ericniebler** [comment]
`[](T){}({})`

**Comment by CaseyCarter** [comment]
I'm unsure of lambdas  in unevaluated contexts these days.
```c++
#include <type_traits>

template <class T, class... Args>
concept bool Constructible = std::is_constructible<T, Args...>::value;

template <class T> struct S { static void f(T); };

template <class T>
concept bool DefaultConstructible = Constructible<T> && requires { S<T>::f({}); };

struct A {};
static_assert(Constructible<A> && DefaultConstructible<A>);

struct B { explicit B() = default; };
static_assert(Constructible<B> && !DefaultConstructible<B>);
```

**Comment by CaseyCarter** [comment]
Capturing discussion: The distinction seems to be insignificant to generic code. Uses like `T t = {};` and `return {};` have perfectly usable alternatives `T t{};` and `return T{};`. There doesn't seem to be any benefit to justify the trouble of specifying and enforcing implicit default constructibility.
