### ISSUE TITLE
Common concept and "unambiguously convertible"

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#32]
For two types `A` and `B` to model `Common`, the Palo Alto report requires that there be a third type `C` to which both `A` and `B` are "unambiguously convertible", which it defines as follows:

> We say that two types `T` and `U` are *unambiguously convertible* if there exists a unique, explicit
conversion from `T` to `U`, or from `U` to `T`, but not both.

This is a problem for `Common<int, unsigned>`. The common type as determined by `std::common_type_t<int, unsigned>` will not have unambiguous conversions from `int` and `unsigned`. Conversions to and from signed and unsigned integers can go in both directions.

@asutton , thoughts?

**Comment by ericniebler** [comment]
... or are we OK with `int` and `unsigned` not modeling `Common`? That would be a little weird.

**Comment by asutton** [comment]
> ... or are we OK with int and unsigned not modeling Common? That would be a
> little weird.

The intent of the description was to say that there are rules for
picking an unambiguous conversion (I'm pretty sure that true ? 0 : 0u
is well formed).

Today, I don't think I'd write it that way. I'd simply say, there
exists some type C such that T and U can be converted to C.

Andrew

**Comment by ericniebler** [comment]
> I'm pretty sure that `true ? 0 : 0u` is well formed

It is. But the current wording doesn't stop there.

> Today, I don't think I'd write it that way. I'd simply say, there exists some type C such that T and U can be converted to C.

Right. I'll rip out the "unambiguously convertible" wording.

Thanks.
