### ISSUE TITLE
ranges::exchange should be constexpr and conditionally noexcept 

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#322]
Resolved by [P0579](https://wg21.link/P0579).

**Comment by ericniebler** [comment]
Proposed Resolution
---------------------

Change [utility.exchange] as follows:

```diff
 template <MoveConstructible T, class U=T>
   requires Assignable<T&, U>()
-T exchange(T& obj, U&& new_val);
+constexpr T exchange(T& obj, U&& new_val) noexcept(see below);

 1 Effects: Equivalent to:
      T old_val = std::move(obj);
      obj = std::forward<U>(new_val);
      return old_val;
+2 The expression in the `noexcept` is equivalent to:
+     is_nothrow_move_constructible<T>::value &&
+     is_nothrow_assignable<T&, U>::value
```

Make the same change to the signature of `exchange` in the `<experimental/ranges/utility>` header synopsis ([utility]).

**Comment by CaseyCarter** [comment]
Related to US NB comment 108 on the C++17 WP:

> Adopt the changes to the `<utility>` header proposed in p0202r1, i.e., only bullets C, D, and E.
In addition, mark the swap functions of pair and tuple as constexpr, and consider doing the same for optional and variant.

P0202r1 makes `std::exchange` `constexpr`.
