### ISSUE TITLE
Destructible should disallow overloaded comma operator

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#323]
It already disallows weird address-of operators. We should outlaw types with overloaded comma operators too. Open bike-shed discussion about whether `Destructible` is the right place for this or not.

cc @StephanTLavavej

**Comment by timsong-cpp** [comment]
I've always found it weird that the disallowance of overloaded address-of is grouped under `Destructible`.

**Comment by CaseyCarter** [comment]
> We should outlaw types with overloaded comma operators too. Open bike-shed discussion about whether Destructible is the right place for this or not.

I've been waffling on forbidding comma, given that there's no general way to enforce it syntactically. The best I can come up with is:

> T satisfies `CommaSanity` if and only if for some `T` of type `t` and `u` of any type `U`, `(t, u)` is equal to `u` and `(u, t)` is equal to `t`, and in both cases every value computation and side effect associated with the left expression is sequenced before every value computation and side effect associated with the right expression. 

I suppose we *could* usefully require `{ (t, u) } -> Same<U>; { (u, t) } -> Same<T>;' applied pairwise on the types of iterators passed to algorithms, which I think is the 90% use case anyway:

> ```c++
> template <class T, class U>
> concept bool __CommaSane = requires(T&& t, U&& u) {
>   { (t, u) } -> Same<U>;
>   { (u, t) } -> Same<T>;
> };
>
> template <class...Ts>
> concept bool CommaSanity() { return see below; }
> ```
>
> `__CommaSane` is satisfied if and only if every value computation ...[stuff above].
>
>`CommaSanity()` is satisfied if and only if `__CommaSane<T, U>` is satisfied for all types `T` and `U` in `Ts...`.
>

**Comment by CaseyCarter** [comment]
> I've always found it weird that the disallowance of overloaded address-of is grouped under `Destructible`.

`Destructible` is the base of a refinement hierarchy, so properties that we want to apply to everything in the hierarchy end up there. The obvious shortcoming is that we now have no way to, e.g., forbid crazy overloading of `&` on a type that the library refers to but does not create or destroy. This is of course balanced against the *strong* encouragement from the committee to minimize the number of concepts and avoid the insane proliferation of tiny meaningless concepts that happened in C++0x.

I expect that at some point in the development of STL2 we'll decide that we need a distinct concept for just these requirements and it will be factored out of `Destructible`.

**Comment by cjdb** [comment]
> `Destructible` is the base of a refinement hierarchy, so properties that we want to apply to everything in the hierarchy end up there.

Is banning the comma operator for all types the right move though? Unless the idea is to eventually deprecate and remove overloaded commas (and this is a way to force people to stop using it early), I feel this might be a bit restrictive. If we're not ever going to deprecate the comma operator, what about making it a requirement of `Semiregular`, as an alternative?

**Comment by StephanTLavavej** [comment]
I believe that overloaded commas are far rarer and more pathological than overloaded address-of, which is unfortunately somewhat common.

Supporting both is a headache, but it falls purely on the implementer (and we currently don't have compiler warnings of the form "hey this could be hijacked"; with such warnings it would be far easier). I vaguely recall that Old Concepts had the ability to remap operations, although I doubt we'll get that again. A simpler approach, making it easy to support overloaded operators, would be some block-scope directive saying "I want operators to be sane for now".

Note that algorithms may want sane operators even when they don't destroy anything. I'm not sure that Destructible is the right place, without doing a full audit of every algorithm.

**Comment by ericniebler** [comment]
> I've been waffling on forbidding comma, given that there's no general way to enforce it syntactically. The best I can come up with is:
>
> > T satisfies `CommaSanity` if and only if for some `T` of type `t` and `u` of any type `U`, `(t, u)` is equal to `u` and `(u, t)` is equal to `t`, and in both cases every value computation and side effect associated with the left expression is sequenced before every value computation and side effect associated with the right expression.

That doesn't work if you let `U` be _any_ type. It could be a type with an overloaded comma operator that makes the requirements fail through no fault of `T`'s.

**Comment by CaseyCarter** [comment]
> That doesn't work if you let U be any type. It could be a type with an overloaded comma operator that makes the requirements fail through no fault of T's.

How else do we constrain the behavior of `n` things in an expression with `>n` operands, if not by universally qualifying over the operands that are missing? It fundamentally makes no sense to ask if `T` has an overloaded comma operator: comma operators have two operands.

> Supporting both is a headache, but it falls purely on the implementer (and we currently don't have compiler warnings of the form "hey this could be hijacked"; with such warnings it would be far easier)

If we eventually get checked template implementations, then *everyone* will become an implementor and be the lucky recipient of "error: operator ',' is unconstrained in expression '++i, ++j'". If we can eliminate those errors for a large class of future programs by adding the right constraints to some of the standard concepts, we'll be helping more future programmers than just standard library implementors.
