### ISSUE TITLE
Change _Name and __name exposition only to italics, lower, hypenated

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#325]
The current working draft has the following in the `<cstdlib>` header synopsis:

<tt><i>// Exposition-only function type aliases</i></tt>
<tt>extern "C" using <i>c-atexit-handler</i> = void(); <i>// exposition only</i></tt>
<tt>extern "C++" using <i>atexit-handler</i> = void(); <i>// exposition only</i></tt>
<tt>extern "C" using <i>c-compare-pred</i> = int(const void* , const void*); <i>// exposition only</i></tt>
<tt>extern "C++" using <i>compare-pred</i> = int(const void* , const void*); <i>// exposition only</i></tt>

Arguably, this is how we should be doing it. So, I suggest replacing `_Destructible` with <tt>_destructible_</tt>, and likewise for the other exposition-only gunk in the synopses.

**Comment by timsong-cpp** [comment]
_`atexit-handler`_ and the like has the benefit that it's obviously not a valid C++ identifier (because of the hyphen). _`destructible`_ doesn't have that benefit and may cause confusion with `Destructible` being a different concept in its own right.

**Comment by CaseyCarter** [comment]
"dereferenceable" is the only exposition-only name we have in a header synopsis, and you formatted it in this style in e15540b17427724af926455e951b0cf53f4594cc. Are you suggesting we use this style for exposition-only names that occur *outside* synopses as well? Or is this issue not a request for change so much as a request that we maintain this stylistic choice in future edits?

**Comment by ericniebler** [comment]
Not feeling the need any longer to make this change. I think the *`c-atexit-handler`* style is good for exposition-only things in synopses, but that `__name` and `_Name` works well for things not in synopses (e.g. `__iterator_traits`). There is some precedent for this in the IS.
