### ISSUE TITLE
concept UniformRandomNumberEngine

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#334]
...can syntactically require `G::min()` and `G::max()` to be constant expressions.

### Proposed Resolution

Change [rand.req.urng] as follows:

```diff
 namespace std { namespace experimental { namespace ranges { inline namespace v1 {
   template <class G>
   concept bool UniformRandomNumberGenerator() {
     return requires(G g) {
       { g() } -> UnsignedIntegral; // not required to be equality preserving
       { G::min() } -> Same<result_of_t<G&()>>;
+      requires (G::min(), true);
       { G::max() } -> Same<result_of_t<G&()>>;
+      requires (G::max(), true);
     };
   }
 }}}}

     1   A uniform random number generator g of type G is a function object returning unsigned
         integer values such that each value in the range of possible results has (ideally) equal
         probability of being returned. [ Note: The degree to which g’s results approximate the
         ideal is often determined statistically. —end note ]
     2   Let g be any object of type G. Then UniformRandomNumberGenerator<G>() is satisfied if
        and only if

-(2.1) — Both G::min() and G::max() are constant expressions (ISO/IEC 14882:2014 §5.19).

 (2.2) — G::min() < G::max().
```

**Comment by ericniebler** [comment]
What is the failure mode if the functions are not constexpr?

**Comment by CaseyCarter** [comment]
> What is the failure mode if the functions are not constexpr?

The wording is a bit messy. The definition of predicate constraint in [temp.constr.pred] says "A *predicate constraint* is a constraint that evaluates **a constant expression** `E` (5.19). ... After substitution, `E` shall have type `bool`." [emphasis mine]. If `E` is dependent, there's no way to know *a priori* if it is a constant expression, so I can only assume the intent is to determine at substitution time whether or not an expression forms a valid predicate constraint.

In practice, gcc emits a hard error. This would be better as an issue against the concepts TS to clarify the behavior than against our TS to depend on that behavior.

**Comment by CaseyCarter** [comment]
> This would be better as an issue against the concepts TS to clarify the behavior than against our TS to depend on that behavior.

[This is Concepts TS 18](http://cplusplus.github.io/concepts-ts/ts-active.html#18). Andrew apparently agrees with me ;)
