### ISSUE TITLE
Should `Proj` be `Invocable`?

### ISSUE THREAD

**Issue by cjdb** [ericniebler/stl2#337]
I'm wondering if `class Proj` should be more tightly constrained, to say `Invocable<value_type_t<I>> Proj = identity`?

Even if this is redundant thanks to the constraints on `Pred`/`Comp` in the next parameter, it'll at least communicate that `Proj` ought to be invocable, and not any type `T`.

**Comment by ericniebler** [comment]
`Proj` is constrained by using it together with the iterator in `projected<Proj, I>`, which is a constrained template. It needs no further constraint. We try to keep requires clauses to a minimum to reduce verbosity.
