### ISSUE TITLE
After P0547R0, const-qualified iterator types are not Readable or Writable

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#339]
`Readable` requires `Movable`. `const`-qualified types are not `Movable` after P0547R0. Ouch.

Proposed Resolution
-------------------
Accept the revised wording in P0547R1.

**Comment by ericniebler** [comment]
@CaseyCarter for your review.

**Comment by CaseyCarter** [comment]
The requires expression in `Readable` no longer needs any parameters. (There's also something funky with the indentation, but the Editor can fix that.)

**Comment by ericniebler** [comment]
Fixed by P0547, LWG wants to see the paper again.
