### ISSUE TITLE
CH 1 (003): Adopt the Concepts TS

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#342]
### General Comment

Consider adoption of the Concepts TS to ISO/IEC 14882:2014, given its relevance to other TSes. Building a house of cards of possibly volatile TSes is a disservice to the community and risks relevance and adoption of this TS.

### Proposed change

Consider adoption of the Concepts TS to ISO/IEC 14882:2014.

**Comment by ericniebler** [comment]
No consensus to change.

**Comment by CaseyCarter** [comment]
> No consensus to change.

Are you doing NB comment resolution somewhere? Or is this a "the authors' recommendation" comment?

**Comment by ericniebler** [comment]
Yes, lewg had 10 minutes to kill, so we looked a a few Ranges NB comments.
