### ISSUE TITLE
US 3 (007): 3.3.2.3/3: What does "equal" mean for CPOs?

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#346]
### Technical Comment

What does it mean for two customization point objects to be “equal”?  Are they required to provide an overload for operator==?  The note on the Semiregular concept suggests otherwise: “[ Note: The Semiregular concept is satisfied by types that behave similarly to built-in types like int,
except that they may not be comparable with ==.—end note ]”

### Proposed Change

Provide a more nuanced wording that two such objects shall have identical behavior when used as described in their customization contract.  Clarify if, for example, two objects can hold logging information tracking which one is called, as long as the logging info does not interfere with contractual behavior.

**Comment by ericniebler** [comment]
LEWG: Include forward reference to [concepts.lib.general.equality].
