### ISSUE TITLE
Forward return type of operator< in diamond less

### ISSUE THREAD

**Issue by tomaszkam** [ericniebler/stl2#35]
In the document N4382 the signatures of call operator for diamond less (and other comparison operators) was changed to return hard-coded `bool` instead of faithfully passing result of `operator<`:
```c++
template <class T, class U>
  requires TotallyOrdered<T, U>()
constexpr bool operator()(T&& t, U&& u) const;
```

This change limits the usability of diamond comparison wrappers in the context outside of standard library when the access to the actual return type of `operator<` is needed. However I believe that this change is not necessary for comparators to meet algorithms requirement (`Relation`), because use of the  `TotallyOrdered<T, U>` (or `EqualityComparable<T,U>`) guarantees that the return type of `operator<` (and any other comparison operator)  fulfills `Boolean` concept that is required for binary function to meet the `Relation` requirement. Given above I would recommend leaving return type unchanged.

**Comment by ericniebler** [comment]
Good point.
