### ISSUE TITLE
GB 2 (012): 4.2.2: Same <T, const T>

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#351]
### Technical Comment

Is 'const' part of the type?
In 4.2.2 Concept Same [concepts.lib.corelang.same] we read:
"Same<T, U>() is satisfied if and only if T and U denote the same type."
is the intention that Same<const T, T>() is true or false?

### Proposed Resolution

Clarify the meaning - perhaps in terms of std::is_same or using the same wording ("T and U name the same type with the same cv-qualifications")

**Comment by CaseyCarter** [comment]
2017-03-01 LEWG triage: LWG (LIkely NAD).

**Comment by CaseyCarter** [comment]
C++14 [basic.type.qualifier]/1 says "The cv-qualified or cv-unqualified versions of a type are distinct types." "distinct types" are clearly not "the same type."

**Comment by ericniebler** [comment]
I believe this is handled now by the resolution for #321, which strikes the wording GB2 is objecting to. #321 is in ready status, so closing this.
