### ISSUE TITLE
GB 5 (016): 7.1/10: Missing "shall"

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#355]
### Editorial Comment

Missing 'shall' in 7.1p10 "Implementations provide a mechanism to resolve this ambiguity in favor of the overload that takes two ranges."

### Proposed Change

Add 'shall' after 'Implementations'

**Comment by CaseyCarter** [comment]
2017-03-01 LEWG triage: LWG.

**Comment by CaseyCarter** [comment]
I observe that adding a "shall" here would be counter to typical LWG usage. We typically use "shall" to impose requirements on users, and simply make factual statements about conforming implementations. "Implementations do X" vs. "implementations shall do X".

**Comment by CaseyCarter** [comment]
Note that the paragraph in question ([algorithms.general]/10) is now numbered 10.1/10. Note also that the PR of #261 suggests striking this paragraph.

**Comment by ericniebler** [comment]
There is no consensus for change at this time.
