### ISSUE TITLE
US 7 (019): 8: Add <numeric> algorithms

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#358]
### General Comment

No range-based overloads for the algorithms in the `<numeric>` header.  There is no obvious reason to omit this latter part of the C++14 algorithms collection.

### Proposed Change

Add range overloads in `<experimental/ranges/numeric>` for: `accumulate`, `inner_product`, `partial_sum`, `adjacent_different`, and `iota`.

**Comment by CaseyCarter** [comment]
2017-03-01 LEWG triage: This is a large feature request; no consensus for change.

**Comment by cjdb** [comment]
Is the reason for no change the same as (or similar to)  Eric's reasoning in https://github.com/CaseyCarter/cmcstl2/pull/61?

**Comment by CaseyCarter** [comment]
Yes. This comment requests a new feature. It's not as simple as "oops, we missed an overload of equal" - the numeric algorithms have some fundamentally different sorts of requirements that need to be studied carefully.
