### ISSUE TITLE
US 8 (020): A.2: Move deprecated algorithms entirely into the Annex

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#359]
### Editorial Comment

Library convention is to document deprecated features entirely in the deprecated annex, rather than in the normative section, with a reference from the deprecated annex.

### Proposed Change

Move the specification of the deprecated forms of `mismatch`, `equal`, `is_permutatation`, `swap_ranges`, and `transform` algorithms directly into Annex A.

**Comment by CaseyCarter** [comment]
2017-03-01 LEWG triage: Editorial.

**Comment by cjdb** [comment]
Is this just removing deprecated declarations from `algorithms.tex`, or does this involve copying the semantics across to `deprecated.tex` as well?

**Comment by ericniebler** [comment]
Do we also need to move the deprecated parts of `ranges::begin` and `ranges::end`? It's not clear how that should look.

**Comment by CaseyCarter** [comment]
Considering that (1) the NB comment does not ask for that, and (2) I think splitting the specification of a single component across clauses would be irretrievably confusing, I believe we should not split `begin` and `end` at this time.

**Comment by CaseyCarter** [comment]
> Is this just removing deprecated declarations from `algorithms.tex`, or does this involve copying the algorithm semantics across to `deprecated.tex` as well?

From a quick look at `mismatch`, there's a little more involved than simply cutting and pasting the declarations. For example, `mismatch` has a Remarks element to the effect that `last2` is `first2 + (last1 - first1)` for the overloads with no argument `last2` which is no longer sensible if no such overloads appear in that section. That Remark needs to be moved into the Annex and rephrased a la "In the specifications of the <stuff> elements in [citation needed], `last2` is `first2 + (last1 - first1)` for these overloads."

I expect there are similar occurrences in the other algorithms that will need to be cleaned up.

**Comment by cjdb** [comment]
Do we want to format them like in the Algorithms section?

```
A.2 Range-and-a-half algorithms                             [depr.algo.range-and-a-half]
// declarations here, like in S7.1...
A.2.1 Mismatch                                                      [depr.algo.mismatch]
//...
```
