### ISSUE TITLE
P0541 is missing semantics for OutputIterator's writable post-increment result

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#361]
[P0541](http://wg21.link/P0541) changes the definition of `OutputIterator` to:

```c++
template <class I, class T>
concept bool OutputIterator() {
  return Iterator<I>() && Writable<I, T>() &&
    requires(I i, T&& t) {
      *i++ = std::forward<T>(t); // not required to be equality preserving
    };
}
```

It notably fails to add any semantic constraints on the expression `*i++ = std::forward<T>(t)`. What does it do? Who knows?

Proposed Resolution
--------------------

After [iterators.output]/p1 and before p2, add the following:

> x. Let `E` be an expression such that `decltype((E))` is `T`, and let `i` be a dereferenceable object of type `I`. Then `OutputIterator<I, T>()` is satisfied only if `*i++ = E;` has effects equivalent to:
> ```c++
> *i = E;
> ++i;
> ```

**Comment by ericniebler** [comment]
@CaseyCarter for your review

**Comment by CaseyCarter** [comment]
Counter proposal:

> x. Let `E` be an expression such that `decltype((E))` is `T`, and let `i` be a dereferenceable object of type `I`. Then `OutputIterator<I, T>()` is satisfied if and only if `*i++ = E;` has effects equivalent to:
> ```c++
> *i = E;
> ++i;
> ```

**Comment by ericniebler** [comment]
Toronto 2017:
s/if and only if/only if/
