### ISSUE TITLE
tagged<user-defined type> does not work

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#364]
Since tagged getters use qualified `std::get` to access the fields of `Base` and users are forbidden to overload `std::get`. A possible solution is to use ADL to find `get` function templates in the user's namespace(s) as implemented in [range-v3's `tagged`](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/utility/tagged_pair.hpp).

Proposed Resolution
-------------------
This issue is resolved by the PR for #363.

**Comment by CaseyCarter** [comment]
@ericniebler PR for your review.

**Comment by ericniebler** [comment]
Looks good.

**Comment by timsong-cpp** [comment]
> This issue is resolved by the PR for #364.

Infinite recursion.

**Comment by CaseyCarter** [comment]
LEWG has killed `tagged` for C++20 - closing this as NAD.
