### ISSUE TITLE
common_iterator::operator-> is underconstrained

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#366]
As specified in #318. The "proxy case" constructs an object of type `value_type_t<I>` from `reference_t<I>` but does not require `Constructible<value_type_t<I>, reference_t<I>>()`.

Proposed Resolution
---------------------

Change the class synopsis of `common_iterator` ([common.iterator]) as follows (includes part of the resolution of #368):

```diff
 see below operator*();
 see below operator*() const requires dereferenceable<I const>;
-see below operator->() const requires Readable<I const>();
+see below operator->() const requires see below;
```

To [common.iter.op.ref], add a p3 that reads:

> 3. The expression in the `requires` clause is equivalent to:
> ```c++
> Readable<I const>() &&
>   (requires (const I& i) { i.operator->(); } ||
>    is_reference<reference_t<I>>::value ||
>    Constructible<value_type_t<I>, reference_t<I>>())
> ```

**Comment by ericniebler** [comment]
@CaseyCarter for your review
