### ISSUE TITLE
common_iterator's and counted_iterator's const operator* need to be constrained

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#368]
Some iterators (e.g., `insert_iterator`) don't have a `const`-qualified `operator*`. When wrapping such an iterator, `counted_iterator` and `common_iterator` also should not have such an overload of `operator*`.

Proposed Resolution
--------------------

1. Change the `common_iterator` class synopsis [common.iterator] as follows:

```diff
 see below operator*();
-see below operator*() const;
-see below operator->() const requires Readable<I>();
+see below operator*() const requires dereferenceable<I const>;
+see below operator->() const requires Readable<I const>();

common_iterator& operator++();
common_iterator operator++(int);
```

2. Change `common_iterator::operator*` [common.iter.op.star] as follows:

```diff
 decltype(auto) operator*();
-decltype(auto) operator*() const;
+decltype(auto) operator*() const requires dereferenceable<I const>;
 1 Requires: !is_sentinel
 2 Effects: Equivalent to: return *iter;
```

3. Change `common_iterator::operator->` [common.iter.op.ref] as follows:

```diff
-see below operator->() const requires Readable<I>();
+see below operator->() const requires Readable<I const>();
 1 Requires: !is_sentinel
 2 Effects: Given an object i of type I
...
```

4. Change the `counted_iterator` class synopsis [counted.iterator] as follows:

```diff
 see below operator*();
-see below operator*() const;
+see below operator*() const requires dereferenceable<I const>;

counted_iterator& operator++();
counted_iterator operator++(int);
```

5. Change `counted_iterator::operator*` [counted.iter.op.star] as follows:

```diff
 decltype(auto) operator*();
-decltype(auto) operator*() const;
+decltype(auto) operator*() const requires dereferenceable<I const>;
 1 Effects: Equivalent to: return *current;
```

**Comment by ericniebler** [comment]
Actually, it can't be `Readable<I const>()` because `common_iterator` and `counted_iterator` can wrap output iterators, which are not `Readable`. It also can't be `Iterator<I const>` because const things are not `WeaklyIncrementable`. Maybe an ad hoc constraint would work here?

**Comment by ericniebler** [comment]
@CaseyCarter for your review.

**Comment by CaseyCarter** [comment]
`Readable<I>()` requires `*` to be valid for a `const I`, so `common_iterator::operator->` is already properly constrained.

The ad-hoc constraint on the other operators is exactly `dereferenceable<const T>`; we should re-use the exposition-only concept and think about making it a real boy.

**Comment by ericniebler** [comment]
> `Readable<I>()` requires `*` to be valid for a `const I`

Not after the resolution of #339.

> The ad-hoc constraint on the other operators is exactly `dereferenceable<const T>`; we should re-use the exposition-only concept

Done.

> and think about making it a real boy.

Decline (for now). More important fish.
