### ISSUE TITLE
common_iterator needs some help to interface STL2 code to STL1 code.

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#37]
`common_iterator` is presented as a facility for interfacing "new" code that uses STL2 iterator/sentinel pairs with "old" code that accepts iterator pairs. There are a couple of shortcomings in this design:
1. Converting to `common_iterator` is not always the most efficient way to derive an iterator pair from an iterator/sentinel pair. The fact that `common_iterator` requires the iterator and sentinel types to be different is a nod to the fact that using a `common_iterator` is less efficient than using the original type directly in this case. That requirement unfortunately makes `common_iterator` impossible to use directly in generic code. Additionally, if the iterator models `RandomAccessIterator` and together with the sentinel models `SizedIteratorRange`, it is possible to convert the sentinel to the iterator type in constant time resulting in a more efficient common type than `common_iterator`.
2. Given the differences in the iterator models of STL2 and STL1 - particularly the STL1 requirement that the reference type of a `ForwardIterator` be a true reference which is not the case for STL2 - an STL2 iterator may not model the STL1 iterator category that is identified by the same iterator category tag.

I think we have a duty to ease the STL1 to STL2 transition as much as possible, so it is important to facilitate interfacing "new" iterator code to "old" iterator code for codebases in transition. I propose a design for two facilities to address the above problems. First, a family of function templates `make_common_iterator` that converts an iterator or sentinel in constant time into a common type that models the most refined iterator concept supportable by that iterator and sentinel, and second a family of function templates `decay_iterator` that adapts an STL2 iterator into the most refined STL1 iterator concept that its type models.
### `make_common_iterator` family

```
// make_common_iterator<S>(I) transforms the given InputIterator into a common
// type of S and I that models the most refined iterator concept supportable by
// S and I with no more than constant time conversion complexity.

// Base iterator template
template <class S, InputIterator I>
    requires Sentinel<S, I>
auto make_common_iterator(I i) {
    return common_iterator<I, S>{i};
}

// If S and I are the same type, they are already Common.
template <class S, InputIterator I>
    requires Same<S, I>
auto make_common_iterator(I i) {
    return i;
}

// If S and I model SizedIteratorRange and I models RandomAccessIterator, we
// can convert the sentinel to I in constant time - so we need not convert i.
template <class S, RandomAccessIterator I>
    requires SizedIteratorRange<I, S>
auto make_common_iterator(I i) {
    return i;
}

// make_common_iterator<S>(I, S) transforms the given Sentinel into a common
// type of S and I that models the most refined iterator concept supportable by
// S and I with no more than constant time conversion complexity.
// Post-condition:
//   Same<make_common_iterator<S>(I), make_common_iterator<S>(I, S)>
// Note: S is in a non-deduced context to force the user to specify it
//   explicitly for consistency with make_common_iterator<S>(I).

// Base sentinel template
template <class S, InputIterator I>
    requires Sentinel<S, I>
auto make_common_iterator(I, typename identity<S>::type s) {
    return common_iterator<I, S>{s};
}

// Same therefore Common
template <InputIterator S>
auto make_common_iterator(typename identity<S>::type /* unused */,
                          typename identity<S>::type last) {
    return last;
}

// S and I model SizedIteratorRange and I models RandomAccessIterator,
// convert the sentinel to I in constant time.
template <class S, RandomAccessIterator I>
    requires SizedIteratorRange<I, S>
auto make_common_iterator(I i, typename identity<S>::type s) {
    return i + (s - i);
}
```
### `decay_iterator` family

Bikeshed: `old_style_iterator`, `stl1_iterator`, ...

```
// class decayed_iterator<ForwardIterator>: iterator adaptor that restricts
// IteratorCategory of a ForwardIterator to InputIterator.
template <ForwardIterator I>
class decayed_iterator {
    I base_; // expo
public:
    using iterator_category = input_iterator_tag;
    // ..."inherit" value_type, difference_type, reference, etc.

    decayed_iterator() = default;
    decayed_iterator(I i) : base_(i) {}

    I base() const;

    // ...Delegate input iterator operations to base_...
    // operator-> could be problematic.
};

// decay_iterator(I) transforms an STL2 iterator into an STL1 iterator. The
// result of decay_iterator(I) models the most refined STL1 iterator concept
// supportable by I.

// STL2 InputIterators are STL1 input iterators. (Again, operator-> is an issue)
auto decay_iterator(InputIterator i) {
    return i;
}

// Assume any WeakIterator that does not model WeakInputIterator
// is an STL1 Output iterator.
// (This needs more design review)
template <WeakIterator O>
    requires !WeakInputIterator<O>
auto decay_iterator(O o) {
    return o;
}

// STL2 ForwardIterators that don't satisfy the reference requirement are STL1
// input iterators.
auto decay_iterator(ForwardIterator i) {
    return decayed_iterator<decltype(i)>{i};
}

// STL2 ForwardIterators that DO satisfy the reference requirement are STL1
// iterators. (Problem: operator->)
template <ForwardIterator I>
    requires Same<ReferenceType<I>, ValueType<I>&> ||
             Same<ReferenceType<I>, const ValueType<I>&>
auto decay_iterator(I i) {
    return i;
}
```
### Use case

```
template<class ForwardIterator>
void oldfun(ForwardIterator begin, ForwardIterator end);

template <class InputIterator>
void oldfun(InputIterator i,
            typename std::iterator_traits<InputIterator>::difference_type n);

template <InputIterator I>
void newfun(I i, DifferenceType<I> n) {
    oldfun(decay_iterator(i), n);
}

template<InputIterator I, Sentinel<I> S>
void newfun(I i, S s) {
    oldfun(decay_iterator(make_common_iterator<S>(i)),
           decay_iterator(make_common_iterator<S>(i, s)));
}
```
### Design Alternatives
1. Provide a precomposed `decay_common_iterator` facility to ease the common (pun intended) use case:
   
   ```
   template<InputIterator I, Sentinel<I> S>  
   void newfun(I i, S s) {  
       oldfun(decay_common_iterator<S>(i), decay_common_iterator<S>(i, s));  
   }
   ```
2. Same as (1), but drop `make_common_iterator`; I'm not sure there are interesting use cases for `common_iterator` that don't involve decaying to an STL1 iterator concept.

**Comment by ericniebler** [comment]
```c++
// operator-> could be problematic
```

Can't it simply return `base_`?

**Comment by ericniebler** [comment]
> I'm not sure there are interesting use cases for `common_iterator` that don't involve decaying to an STL1 iterator concept

Consider specializations of `common_type`.

**Comment by ericniebler** [comment]
Regarding `decay_iterator`, I feel that a better(?) way would be to modify `std::v1::iterator_traits` to detect `v2` iterators and report the iterator tag appropriately. That way, users don't need to do anything (except maybe build a `common_iterator`), and there's no chance for them to forget and get weird behavior.

You're right about the need for `make_common_iterator` though. I need to think more about the interface, though.

**Comment by ericniebler** [comment]
My instinct tells me that `make_common_iterator` is too low-level, error-prone, and verbose. I'd rather see something like range-v3's `view::bounded`, which could be used like this:

```c++
template<class It>
It v1_algo(It first, It last) {
    return last;
}

int main() {
    Range rng = /* make some range*/;
    // Call a legacy algorithm:
    auto res = rng | takes_bounded([](auto first, auto last){
        return v1_algo(first, last);
    });
}
```

...where `takes_bounded` is something like:

```c++
template<class Fun>
auto takes_bounded(Fun fun) {
    return make_pipeable([=](auto && rng) {
        using Rng = decltype(rng);
        auto bounded = std::forward<Rng>(rng) | view::bounded;
        return fun(begin(bounded), end(bounded));
    }
}
```

**Comment by CaseyCarter** [comment]
> Can't it simply return base_?

I simple meant that if `base_` doesn't have an lvalue ReferenceType and doesn't implement `operator->`, it is more challenging than my blanket "forward the operations" claim. Not insurmountable, but non-trivial.

> Consider specializations of `common_type`.

I meant to constrain that statement contingent on the removal of the `Common` requirements. If a `common_iterator` specialization isn't required to satisfy `Sentinel` then I believe there are few/no use cases except passing to STL1 code.

> My instinct tells me that `make_common_iterator` is too low-level, error-prone, and verbose.

`bounded_range` itself makes gradual transition easier. Updating from
```
template <class InputIterator, class T>
void f(InputIterator first, InputIterator last, T foo) {
    // ...
    auto bar = // ...;
    auto baz = // ...;
    auto res = oldfun(first, last, foo, bar, baz);
    // ...
}
```
to
```
template <InputIterator I, Sentinel<I> S, class T>
void f(I first, S last, T foo) {
    // ...
    auto bar = // ...;
    auto baz = // ...;
    auto rng = make_bounded_range(first, last);
    auto res = oldfun(begin(rng), end(rng), foo, bar, baz);
    // ...
}
```
is simple. It should be possible to move slowly to the new Sentinel universe with minimal code disruption and without having to understand views and actions and piping. Wrapping in a lambda is a significant barrier for entry.

> I feel that a better(?) way would be to modify `std::v1::iterator_traits` to detect v2 iterators and report the iterator tag appropriately.

Yes, modulo the absence of `operator->` in v2 iterators which is a requirement for v1 input iterators.

**Comment by ericniebler** [comment]
I like `make_bounded_range`. I understand the need for something like `decay_iterator`, but I feel like it's something that can be added later. There are bigger fish to fry, like proxy iterators and infinite ranges.

**Comment by ericniebler** [comment]
Depends on #49

**Comment by ericniebler** [comment]
As of 98ed39c, `common_iterator` has `operator->`.

**Comment by CaseyCarter** [comment]
The landscape has changed somewhat since I first filed this issue: I think the compatibility story has improved. I'll review this discussion and make a determination of whether there's more we should do for TS1 or if this should wait for a view adapter to provide improved back-compat in TS2.

**Comment by ericniebler** [comment]
I've reviewed this issue. The only thing left here that I like is the suggestion to add `make_bounded_range`. However, it's too late in the proceedings to be adding new features, and I couldn't justify `make_bounded_range` as a bug-fix for interoperability issues that haven't been shown to exist.

Regarding `operator->` ... to be honest, I'm not overly concerned about that issue. I feel that relatively little generic code uses that operator, and `common_iterator` has `operator->` anyhow. The specialization of `std::iterator_traits` handles the vast majority of the interoperability problems.

I'm bumping this to the IS, unless we add `view::bounded` in a TS2.

**Comment by ericniebler** [comment]
We have `view::common` to address the issues brought up here. Closing.
