### ISSUE TITLE
WeaklyIncrementable => Iterator

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#370]
Many algorithms constrain an output iterator by requiring `WeaklyIncrementable` in conjunction with `Writable`, e.g.:

```c++
template <InputIterator I, Sentinel<I> S, WeaklyIncrementable O>
    requires IndirectlyCopyable<I, O>()
  tagged_pair<tag::in(I), tag::out(O)> copy(I first, S last, O result);
```
(`IndirectlyCopyable<I, O>()` requires `Writable<O, reference_t<I>>()`.) While this is sufficient, I think that replacing these uses with `Iterator` (a) more clearly shows intent, and (b) is less frightening to those unfamiliar with the concepts. `WeaklyIncrementable` has a *lot* of syllables. Note that `Iterator` refines `WeaklyIncrementable` with a "dereferenceability" requirement `{ *i } -> auto&&;`, which all feasible models of `Writable` must necessarily meet in order to satisfy `Writable`'s expression requirement `*o = std::forward<T>(t)`.

Proposed Resolution
-----------------------
Replace uses of `WeaklyIncrementable` to constrain template parameters with `Iterator` in the declarations of algorithms `copy`, `copy_n`, `copy_if`, `remove_copy`, `remove_copy_if`, `unique_copy`, `reverse_copy`, `rotate_copy`, `partition_copy` (`IndirectlyCopyable` provides the `Writable` constraint); `move` and the example in [move.sentinel]/2 (`IndirectlyMovable` provides the `Writable` constraint); `transform` (used directly with `Writable`); and `merge`, `set_union`, `set_intersection`, `set_difference`, and `set_symmetric_difference` (`Mergeable` provides the `Writable` constraint).

**Comment by CaseyCarter** [comment]
(Was caseycarter/stl2#25.)

**Comment by timsong-cpp** [comment]
Should we turn them into `OutputIterator` instead (to permit the algorithms to do `*r++ = meow;`)?

**Comment by ericniebler** [comment]
Superseded by #496.
