### ISSUE TITLE
Algorithm std::foo is more specialized than ranges::foo

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#371]
This function:
```c++
using namespace std::experimental::ranges;

template<InputIterator I, Sentinel<I> S>
auto find_42(I i, S s) {
    return find(i, s, 42);
}
```
confusingly prefers to call `std::find` over `std::experimental::ranges::find` when `I` and `S` are the same type and `std` is an associated namespace of `I`. The algorithms in `ranges` are more constrained, but the algorithms in `std` are more specialized since they only accept same-type `[begin, end)` pairs. This could cause hardship for stl2 users.

Our best guidance right now is to always qualify names in `std::experimental::ranges`, ideally via a namespace alias:
```c++
namespace ranges = std::experimental::ranges;

template<ranges::InputIterator I, ranges::Sentinel<I> S>
auto find_42(I i, S s) {
    return ranges::find(i, s, 42);
}
```
which avoids this problem by requiring many more keystrokes, or to enclose names in parentheses to disable ADL: `return (find)(i, s, 42);`.

Some design alternatives to address this issue:

1. Require symmetric-type overloads of the algorithms in the `ranges` namespace which will be equally-specialized and more constrained than those in namespace `std` and therefore preferred by overload resolution

2. "kill" ADL by implementing the algorithms in the `ranges` namespace as function objects with overloaded call operators rather then overloaded function templates. This is the design used in range-v3.

(Was caseycarter/cmcstl2#12.)

**Comment by viboes** [comment]
Have you considered any alternative solution as explicit namespaces (n1691)?

**Comment by ericniebler** [comment]
Casey wrote:

> Some design alternatives to address this issue:
>
> 1. Require symmetric-type overloads of the algorithms in the ranges namespace which will be equally-specialized and more constrained than those in namespace std and therefore preferred by overload resolution
> 
> 2. "kill" ADL by implementing the algorithms in the ranges namespace as function objects with overloaded call operators rather then overloaded function templates. This is the design used in range-v3.

3. Require implementors to solve the problem, but leave it up to them to solve it as they see fit. They may decide to change the algorithm signatures in namespace `std` to:

```c++
template <class I, class V, class S = I>
enable_if_t<is_same<I, S>::value, I> find(I, S, V const&);
```

I *think* that would be conforming. Heck, they could even make the algorithms work with sentinels. It effects SFINAE, but no other conforming programs AFAICT (not thinking too hard).

> Have you considered any alternative solution as explicit namespaces (n1691)?

The Ranges TS isn't the appropriate vehicle for a language change of this magnitude, especially considering that there is a simple library work-around.

**Comment by ericniebler** [comment]
> I *think* that would be conforming.

I think that would be an ABI-breaking change, so few implementors would go that route. But the point remains. We don't need to specify this.

**Comment by CaseyCarter** [comment]
> They may decide to change the algorithm signatures in namespace `std` to:
> 
> ```c++
> template <class I, class V, class S = I>
> enable_if_t<is_same<I, S>::value, I> find(I, S, V const&);
> ```
> 
> I *think* that would be conforming. 

`find(istream_iterator<int>(some_stream), {}, 42);` has to work. Defaulting the second template parameter to the same type as the first fixes this example, but then `find({}, some_iterator{some_expression}, 42)` won't work.

> I think that would be an ABI-breaking change, so few implementors would go that route. But the point remains: we don't need to specify this.

For the TS, we can ignore the issue altogether and tell people to qualify names. For STL2 in the IS, I'm less happy with that solution and breaking ABI is a non-starter.

**Comment by ericniebler** [comment]
Deferring this until the IS.

**Comment by ericniebler** [comment]
This was fixed by turning all algorithms in `std::ranges::` into _niebloids_.
