### ISSUE TITLE
Should the Ranges TS have a feature test macro?

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#383]
Probably not, users could just `__has_include(<experimental/ranges/range>)` or some such, but I just thought I'd ask.

Under the assumption that there will one day be a Ranges TS 2, it may prove useful to have a macro to tell what level of ranges support the implementation offers.

Proposed Resolution
------------------

After section "Namespaces, headers, and modifications to standard classes" ([intro.namespaces]), add a section "Feature-testing recommendations (Informative)" with the stable name [intro.feature.test] as follows:

> 4.3 **Feature-testing recommendations (Informative)** [intro.feature.test]
>
> 1. For the sake of forward compatibility with future versions of this Technical Specification, WG21 (the ISO technical committee for the C++ programming language) recommends that implementers provide `__cpp_lib_experimental_ranges` as a feature-test macro with the value `201707`.
>
> 2. Implementers of this Technical Specification should define the macro such that it is available after the inclusion of any header in Table 2.

**Comment by CaseyCarter** [comment]
If we end up having a TS2, `__cpp_lib_ranges` could come in handy. It's not hard to do now or later, I have no strong feelings either way.

**Comment by cjdb** [comment]
> Probably not, users could just `__has_include(<experimental/ranges/range>)` or some such

Isn't Ranges based off C++14? 

On an unrelated note, this seems like an easy way to massage code that can flit between a range-v3 release and a conforming implementation (not sure how easy it is to interchange the two without regressions).

**Comment by CaseyCarter** [comment]
> Isn't Ranges based off C++14?

Yes, but without `__has_include`, you need external configuration in the build system whether or not the ranges headers define a macro. (The SD-6 feature detection macros for *language* features are predefined by the compiler, those for *library* features are defined in library headers.)

**Comment by ericniebler** [comment]
@CaseyCarter Any suggestions for improvements?

**Comment by CaseyCarter** [comment]
Why not put this in the front matter in [intro]? It will probably even fit in the blank space on that page ;)

**Comment by ericniebler** [comment]
How about now?

**Comment by CaseyCarter** [comment]
LGTM

**Comment by ericniebler** [comment]
C++20 has `__cpp_lib_ranges`, and the TS is old news.
