### ISSUE TITLE
Change the name of "implicit expression variants"

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#384]
As defined in [concepts.lib.general.equality]/6:

> Where a requires-expression declares an expression that is non-modifying for some constant lvalue operand, additional variants of that expression that accept a non-constant lvalue or (possibly constant) rvalue for the given operand are also required except where such an expression variant is explicitly required with differing semantics. Such implicit expression variants must meet the semantic requirements of the declared expression. The extent to which an implementation validates the syntax of these implicit expression variants is unspecified.

LWG in Kona was concerned that the term is confusing now that C++ has `std::variant`.

While we're at it, define the new name as a term-of-art since it is used as such elsewhere in [concepts.lib].

Proposed Resolution
-----------------------
Change [concepts.lib.general.equality]/6 as follows:
```diff
 Where a requires-expression declares an expression that is non-modifying for some constant
 lvalue operand, additional
-variants
+variations
 of that expression that accept a non-constant lvalue or (possibly constant) rvalue for the
 given operand are also required except where such an expression
-variant
+variation
 is explicitly required with differing semantics.
-Such implicit expression variants
+These \techterm{implicit expression variations}
 must meet the semantic requirements of the declared expression. The extent to which an
 implementation validates the syntax of
-these implicit expression variants
+the variations
 is unspecified.
```
Replace other occurrences of "variant(s)" in this paragraph with "variation(s)."

Replace "implicit expression variants" with "implicit expression variations (\ref{concepts.lib.general.equality})" in:
* [concepts.lib.object.destructible]/2
* [ranges.range]/2.2

**Comment by CaseyCarter** [comment]
"implicit expression variations"?

**Comment by ericniebler** [comment]
Sure I guess.
