### ISSUE TITLE
P0541: basic exception guarantee in counted_iterator's postincrement

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#386]
Comment from LWG Kona review:

> basic guarantee in `counted_iterator`'s postincrement and postdecrement. (If that results in inconsistently ordered operations, STL wants a note to explain why.)

These operators are specified to update the count member and then directly return the result of postincrementing/postdecrementing the iterator member. My concern was that the count and iterator members could become desynchronized of the iterator operation throws. We've avoided the issue in the past by updating the count after updating the iterator.

The real issue here is that we would like for adaptors to preserve whatever exception guarantee the adapted type provides. This is trivially the case for `reverse_iterator`, `move_iterator`, and I think `common_iterator`, but `counted_iterator` needs to try a little harder or explicitly warn users that `counted_iterator`'s postincrement operation for single-pass iterators doesn't maintain the guarantee of the adapted iterator.

### Proposed Resolution

Wording relative to D0541R1. Change the specification of `operator++(int)`:
```diff
 decltype(auto) operator++(int);

 4 Requires: cnt > 0.
 5 Effects: Equivalent to:

 --cnt
-return current++;
+try { return current++; }
+catch(...) { ++cnt; throw; }
```

**Comment by CaseyCarter** [comment]
Possible solution:

Change the effects-equivalent-to:
```diff
 --cnt;
-return current++;
+try { return current++; }
+catch(...) { ++cnt; throw; }
```

**Comment by ericniebler** [comment]
I think that's good enough for the spec, so long as "equivalent to" permits an implementation such as:

```c++
using _P = decltype(declval<I&>()++);
_P operator++(int) {
  if constexpr (is_void_v<_P>) {
    current++;
    --cnt;
  } else {
    _P&& tmp = current++;
    --cnt;
    return static_cast<_P&&>(tmp);
  }
}
```

I think it does.
