### ISSUE TITLE
Writable should work with rvalues

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#387]
During LWG Kona review of D0547R1. `Writable` is defined therein as:
```c++
template <class Out, class T>
concept bool Writable() {
  return requires(Out& o, T&& t) {
    *o = std::forward<T>(t);
  };
}
```
The concept only requires writability for lvalues, but it seems reasonable to require that writability is oblivious to value category.

### Proposed Resolution
Accept the wording in P0547R1.

**Comment by ericniebler** [comment]
We need to combine this resolution with the one from #381.
