### ISSUE TITLE
When can a model of a weaker concept be promoted to a stronger concept?

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#39]
We need to establish requirements that describe the interaction between user code and the library in respect to concepts. For example it is obvious - although it wouldn't hurt to make the fact explicit - that passing a type/types/parameters that meet the syntactic requirements, but not the semantic/prose requirements, of concept `Foo` to a standard library component that requires `Foo` should be forbidden/result in UB. What is less obvious and harder to specify is when a library component with a weaker requirement should be allowed to assume that a type/types/parameters that happen to meet the syntactic requirements of a stronger concept do in fact model that concept. (I refer to this as "promoting" a model to the stronger concept.)

For example, we certainly want a library component that requires `InputIterator` to have the freedom to assume that a type that meets the syntactic requirements of `RandomAccessIterator` does in fact model that concept and optimize appropriately. Conversely, a library component that requires `Function` must never assume that a given type actually models `RegularFunction` despite meeting the syntactic requirements of `RegularFunction` since both concepts have identical syntactic requirements and differ only in their semantic requirements.

I see two alternative approaches:
1. Syntax is king. It is forbidden to pass types that meet only the syntactic requirements of any standard concept to any standard library component (presumably with an exception for standard concepts that differ only in semantic requirements). This maximizes implementor freedom but is dangerous for users that do not have a thorough knowledge of every standard concept. This model makes it impossible to use types with the standard library in any way if they meet only the syntax of any concept, e.g., you may not declare a `unique_ptr` to a type that has `==`/`!=` but does not model `EqualityComparable`.
2. Syntax means nothing. The contract between a library component and the user is limited to exactly those requirements that are specified explicitly. A library component that requires some type to be EqualityComparable cannot assume that the type is in fact TotallyOrdered simply because it meets the syntactic requirements of TotallyOrdered. Similarly, a library component that requires an InputIterator cannot assume that the parameter is in fact a RandomAccessIterator simply because it meets the pertinent syntactic requirements.

I don't think we want to introduce any kind of duck typing into STL2; the second approach is the only tenable solution for providing a "conceptified" standard library. Library components that want to "promote" a model of a weaker concept to a stronger one will necessarily need to build that property into the semantic requirements of the weaker concept.

Returning to the specific example of the family of iterator concepts, there must be an additional requirement imposed on iterator models to enable promotion. That requirement could be as generic as "no model of an iterator concept may meet the syntactic requirements of any iterator concept it does not model" or something specific like "`IteratorCategory<I>` must not be derived from a category tag corresponding to an iterator concept not modeled by `I`."

**Comment by ericniebler** [comment]
> For example, we certainly want a library component that requires `InputIterator` to have the freedom to assume that a type that meets the syntactic requirements of `RandomAccessIterator` does in fact model that concept and optimize appropriately.

Iterators declare the concept they model via `IteratorCategory`. There's no need to guess.

> Conversely, a library component that requires `Function` must never assume that a given type actually models `RegularFunction` despite meeting the syntactic requirements of `RegularFunction` since both concepts have identical syntactic requirements and differ only in their semantic requirements.

Right, you can't create an overload set with concept-based overload-resolution when there is no subsumption relationship between the concepts. 

> e.g., you may not declare a `unique_ptr` to a type that has `==`/`!=` but does not model `EqualityComparable`.

Why does `unique_ptr` care at all if the underlying type is `EqualityComparable` or not?

> I see two alternative approaches:
> 1. Syntax is king. [...]
> 2. Syntax is nothing [...]

\3. The users are king. They are assumed to be smart enough to pass objects that, if they syntactically model the stronger concept, do in fact model that concept. We as designers of STL2 are responsible enough to define concepts that do not create these kinds of syntactic ambiguities in the first place. (Where we can't, like with `Function` and `RegularFunction`, we cannot responsibly create functions that overload on the concepts; rather we create differently named functions, and again the user is responsible for calling the right one.)

> or something specific like "`IteratorCategory<I>` must not be derived from a category tag corresponding to an iterator concept not modeled by `I`."

It hardly seems necessary to me. It should be obvious enough to everybody that if you lie to the concepts system about the capabilities of your type, you're going to get garbage behavior.

**Comment by asutton** [comment]
> I see two alternative approaches:
> 1. Syntax is king. [...]
> 2. Syntax is nothing [...]
>
> \3. The users are king. They are assumed to be smart enough to pass objects that, if they syntactically model the stronger concept, do in fact model that concept. We as designers of STL2 are responsible enough to define concepts that do not create these kinds of syntactic ambiguities in the first place. (Where we can't, like with Function and RegularFunction, we cannot responsibly create functions that overload on the concepts; rather we create differently named functions, and again the user is responsible for calling the right one.)


+1.

We do occasionally create concepts that are not syntactically
differentiable, but we get around that with traits.

Dropping RegularFunction might not be a bad thing. If we strike
StrictWeakOrder and EquivalenceRelation, we should drop
RegularFunction too.

There is something to be said for people making the mistake of trying
to overload on those concepts, but I think that the people writing
constrained templates generally know how they're related, so this is a
non-issue for me.

Plus, we can't guard against every potential misuse or abuse out
there. We should aim for consistent and sensible interfaces, without
over-engineering them to accommodate potentially bad or broken code.
Let that be a quality of implementation issue.

**Comment by CaseyCarter** [comment]
> Iterators declare the concept they model via IteratorCategory. There's no need to guess.

I missed the requirement in [iterator.assoc]/1 "...it is required that if...`WeakInputIterator` is the name of a type that models the WeakInputIterator (24.2.13) concept, the types ... `IteratorCategory<WeakInputIterator>` ... be defined as the iterator’s ... iterator category," I was expecting it to be in [iterator.requirements]. Absent that requirement, it would be possible to create a pathological type that models FooIterator and meets the syntactic requirements of RandomAccessIterator. To enable promotion, the spec needs to forbid passing such a type to a component that requires FooIterator - which it does.

> Why does `unique_ptr` care at all if the underlying type is EqualityComparable or not?

I can't imagine, and it's not important - it's simply an example of the kind of silliness that results from duck typing. If the library is free to assume that types that model the syntax of a concept also model the semantics, every concept effectively becomes a customization point.

> The users are king. They are assumed to be smart enough to pass objects that, if they syntactically model the stronger concept, do in fact model that concept.

There's an important distinction to make here. If the library specifies an overload set:
```
void f(EqualityComparable);
void f(TotallyOrdered);
```
There's an implicit precondition that a user not pass to this overload set a type that models EqualityComparable but looks like TotallyOrdered. Despite not being immediately obvious to users unfamiliar with concepts I believe that implicit precondition is clear enough not to need specification.

Conversely if the library defines a single function:
```
void g(EqualityComparable);
```
The implementation of `g` cannot assume that a parameter that meets the syntax of TotallyOrdered in fact models TotallyOrdered - its postconditions would not be derivable from its preconditions.
