### ISSUE TITLE
Replace indirect_result_of with indirect_(invoke_)?result

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#390]
C++17 deprecates `result_of` and adds `invoke_result`. We should get in front of this change and replace `indirect_result_of<F(Args...)>` with `indirect_result<F, Args...>`. (Insert bikeshed about whether it should be called `indirect_invoke_result`. I prefer not.)

**Comment by CaseyCarter** [comment]
It would be exceedingly weird to use `result_of<F(Args...)>` from `std` and `indirect_result_of<F, Args...>` from `ranges`. If we make this change - and I see no reason not to do so - we should steal `invoke_result` from the WP as well and replace all uses of `result_of` in the TS with uses of `invoke_result`.

**Comment by morinmorin** [comment]
Oh, farewell to `result_of` ;)

I think `result_of` can be adapted to behave like `invoke_result` (in a backward compatible way):

```
template <typename F, typename... Args>
struct result_of : __invoke_result<F, Args...> {};

template <typename F, typename... Args>
struct result_of<F(Args...)> : __cxx14_result_of<F(Args...)> {};
```

But yeah, offering new traits `invoke_result` would be less confusing for users.


Just-reminiscing-about-boost-result_of-ly yours,
Michel Morin

**Comment by CaseyCarter** [comment]
> I think `result_of` can be adapted to behave like `invoke_result`

This results in ambiguity for function types: is `invoke_result_t<F(Args..)>` asking for `decltype(declval<F>()(declval<Args>()...))` (the result of calling an `F` with `Args...`) or `decltype(declval<F(Args...)>()())` (the result of calling a function that returns `F` and accepts `Args...` with no arguments)?

**Comment by morinmorin** [comment]
> This results in ambiguity for function types

Right!

Stupidly, I referred to a too old Spec (C++11) which says
```
result_of<Fn(ArgTypes...)>
Fn shall be a callable type (20.8.1), reference to function, 
or reference to callable type.
```
and I wrongly assumed that `F` in `invoke_result<F, Args>` should not be a function type. This was wrong.

Sorry for the noise.

**Comment by CaseyCarter** [comment]
> Sorry for the noise.

It's not noise; someone brought up the exact same suggestion when we discussed replacing `result_of` with `invoke_result` in LWG in Kona. It's subtle that there's an intersection in the inputs of the two traits which has differing behavior. Had you not brought it up in this thread it's likely that someone else would have done so later.

**Comment by morinmorin** [comment]
Thanks for the kind words, Casey,

> It's subtle that there's an intersection in the inputs of the two traits which has differing behavior.

Yeah, unfortunate intersection.

**Comment by ericniebler** [comment]
I feel like this is a change best deferred. The Ranges TS is based on C++14, which has `result_of` and not `invoke_result`. If and when the Ranges TS gets rebased on C++17 or merged into the IS, this change would be appropriate.

**Comment by ericniebler** [comment]
Fixed.
