### ISSUE TITLE
CommonReference informally requires ConvertibleTo, but doesn't formally require it

### ISSUE THREAD

**Issue by cjdb** [ericniebler/stl2#394]
From 7.3.5:

> For two types `T` and `U`, if `common_reference_t<T, U>` is well-formed and denotes a type `C` such that both `ConvertibleTo<T, C>()` and `ConvertibleTo<U, C>()` are satisfied, then `T` and `U` share a _common reference type_, `C`. 
[Note: `C` could be the same as `T`, or `U`, or it could be a different type. `C` may be a reference type. `C` need not be unique.]
```cpp
template <class T, class U>
concept bool CommonReference() {
  return requires(T (&t)(), U (&u)()) {
    typename common_reference_t<T, U>;
    typename common_reference_t<U, T>;
    requires Same<common_reference_t<T, U>,
                  common_reference_t<U, T>>();
    common_reference_t<T, U>(t());
    common_reference_t<T, U>(u());
  };
}
```

I can't see anyone implying that `ConvertibleTo` is required in the code.

**Comment by cjdb** [comment]
FWIW cmcstl2's `models::CommonReference` does require `ConvertibleTo`.

**Comment by ericniebler** [comment]
I'm certain we fixed that in Kona, didn't we?

**Comment by cjdb** [comment]
> I'm certain we fixed that in Kona, didn't we?

Ah, found it! NFI how I missed this #311. I'll make a PR for it later today as penance.
