### ISSUE TITLE
SizedRange should not require size() to be callable on a const qualified object

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#396]
See discussion of ericniebler/range-v3#385 and [discussion on Slack](https://cpplang.slack.com/archives/C4Q3A3XB8/p1490824988630435).

Motivating example: range-v3 `drop_while`. `begin` must determine and cache the initial iterator value to satisfy the amortized O(1) complexity requirement, and so needs to mutate non-observable state inside the view object. If the adapted view has iterators that satisfy `SizedSentinel`, `drop_while` could implement `size` by calling `begin` and `end` and returning their difference. Transitively, doing so would require `size` to be a non-`const` member as well.

### Proposed Resolution

```diff
 template <class T>
 concept bool SizedRange() {
   return Range<T>() &&
     !disable_sized_range<remove_cv_t<remove_reference_t<T>>> &&
-    requires(const remove_reference_t<T>& t) {
+    requires(T& t) {
       { ranges::size(t) } -> ConvertibleTo<difference_type_t<iterator_t<T>>>;
     };
 }

    2    Given an lvalue t of type remove_reference_t<T>, SizedRange<T>() is satisfied if and
         only if:
-(2.1) — size(t) returns the number of elements in t.
+(2.1) — ranges::size(t) is O(1), does not modify t, and is equal to ranges::distance(t).
```

**Comment by CaseyCarter** [comment]
@ericniebler PR for your review.

**Comment by ericniebler** [comment]
```diff
-    requires(remove_reference_t<T>& t) {
+    requires(T& t) {
```

**Comment by ericniebler** [comment]
Also, is it just me or is "the number of elements in `t`" weird? Shouldn't we say something like `size(t) == distance(begin(t), end(t))`, or something. And is it enough for p1 to say "a Range type that knows its size in constant time with the `size` function," or do we need to say specifically that the expression `ranges::size(t)` is O(1)?

**Comment by CaseyCarter** [comment]
`distance` and `size` are not always the same in cyclic-iterator world:
```c++
auto rng = view::take_exactly(view::repeat(42), 7);
assert(ranges::size(rng) == 7);
assert(ranges::distance(rng) == 0);
```

**Comment by CaseyCarter** [comment]
Bah, [that example fails](https://wandbox.org/permlink/PcR0UyJPEOngMdIK). I remain concerned.

**Comment by ericniebler** [comment]
What's wandbox, and what version of range-v3 does it have?

**Comment by ericniebler** [comment]
And any view which cannot guarantee that size and distance return the same result should probably not satisfy SizedRange.

**Comment by CaseyCarter** [comment]
Wandbox was previously melpon.org/wandbox, handy online compiler with daily updates for clang and gcc trunk. RANGE_V3_VERSION is 0.2.1.

We have plenty of infinite ranges with finite distance. I can find no cases where both are finite and different, but I cannot prove no such ranges exist either. It's probably ok to simply forbid such a thing.

**Comment by ericniebler** [comment]
> We have plenty of infinite ranges with finite distance.

We do?

**Comment by CaseyCarter** [comment]
> That. Is. Awesome.

Yeah, I did't realize they had range-v3 until today. I've been linking coliru examples, but coliru's range-v3 is as old as the Microsoft version.

> We do?

No, I'm deluding myself into believing that it's possible to somehow extract a finite sequence that includes a cycle from an infinite range - a la `auto rng = take_exactly(repeat(42), 7)` - such that its `distance` is equal to the `distance` between the iterators from the base range that would be adapted into its `begin` and `end` iterators. `size(rng) == distance(rng) && distance(rng) == 7`, but `distance(begin(rng).base(), next(begin(rng), end(rng)).base()) == 0`. This fact, however, does not demonstrate a range with differing `size` and `distance` so much as prove once again that there might not be any iterator `j` such that the counted range `[i, n)` is equivalent to he bounded range `[i, j)` in a design with cyclic iterators.

**Comment by CaseyCarter** [comment]
PR updated.
