### ISSUE TITLE
Assignable semantic constraints contradict each other for self-assign

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#398]
As of P0547, we have this for the post-conditions on `Assignable`'s `t = std::forward<U>(u)` expression:

> (1.2.1) – `t` is equal to `u2`.
> (1.2.2) – If `u` is a non-const xvalue, the resulting state of the object to which it refers is unspecified.

If `&t == &u` and `u` is a non-const xvalue, is the resulting state `u2` or unspecified?

Proposed Resolution
--------------------

This wording is relative to [D0547R1](http://wiki.edg.com/pub/Wg21kona2017/LibraryWorkingGroup/D0547R1.html).

Change paragraph 1 of [concepts.lib.corelang.assignable] (7.3.10) as follows:

```diff
 1. Let t be an lvalue
-   which
+   that
    refers to an object o such that decltype((t)) is T, and u an expression
    such that decltype((u)) is U. Let u2 be a distinct object that is equal to
    u. Then Assignable<T, U>() is satisfied if and only if
 (1.1) – std::addressof(t = u) == std::addressof(o).
 (1.2) – After evaluating t = u:
-(1.2.1)   – t is equal to u2.
+(1.2.1)   – t is equal to u2, unless u is a non-const xvalue that refers to o.
 (1.2.2)   – If u is a non-const xvalue, the resulting state of the object to which it
-            refers is unspecified. [ Note: the object must still meet the requirements of
-            the library component that is using it. The operations listed in those
-            requirements must work as specified. – end note ]
+            refers is valid but unspecified ([lib.types.movedfrom]).
 (1.2.3)   – Otherwise, if u is a glvalue, the object to which it refers is not modified.

-2. There is no 
+2. There need not be a 
    subsumption relationship between Assignable<T, U>() and is_lvalue_reference<T>::value.

+3. [Note: Assignment need not be a total function ([structure.requirements]); in particular,
+   if assignment to an object x can result in a modification of some other object y, then
+   x = y is likely not in the domain of =. -- end note]
```

**Previous Proposed Resolution [SUPERSEDED]**
(Kept for historical reasons, and in case we need to move back to a normative formulation.)

~~Two distinct objects x and y need not be in the domain of `=` if the expression `MODIFY(x), y` is not equality preserving or if it is not equal to the expression `y`, for any equality-preserving, modifying operation MODIFY ([concepts.lib.general.equality]). [Note: MODIFY is permitted to destroy x. -- end note]~~

**Comment by ericniebler** [comment]
Suggestion:

> (1.2.1) - `t` is equal to `u2`, unless `addressof(t) == addressof(u)` and `u` is a non-`const` xvalue.

???

**Comment by ericniebler** [comment]
The issue is larger than self-assignment. Anytime the rhs of an assignment (even a _copy_ assignment) is owned directly or indirectly by the lhs, such that changing the value of the lhs could have the effect of invalidating the rhs, then the assignment invokes undefined behavior _unless the copy-and-swap idiom is used_ (or in the case of move, move-and-swap). This can happen trivially with smart pointers to nodes in node-based data structures.

It can also happen with `vector<any>`: an element of the vector could contain another `vector<any>`. If the element is made the rhs of an assignment to the containing vector, UB results. `std::vector` does not use copy-and-swap for its copy assignment operator, and so it suffers from this problem. Changing to copy-and-swap would be a huge performance hits, to guard against what is admittedly a corner case.

My suggestion is to come up with wording that says basically that assignment is UB if mutating the lhs can invalidate the rhs.

**Comment by ericniebler** [comment]
@CaseyCarter Please review the proposed wording.

**Comment by timsong-cpp** [comment]
>     Then Assignable<T, U>() is satisfied if and only if
>    
>     +(1.x) – u is not lifetime-dependent-on o, or u refers to o.

This really doesn't make sense here. It should go into the "Let" clause, saying that you needn't handle the "mutating the lhs can invalidate the rhs" case to satisfy `Assignable`.

Then we need separate wording to make it actually UB to perform the assignment, perhaps by saying something along the lines that implementations may assume that no assignment operation on an `Assignable` type has a "mutating the lhs can invalidate the rhs" case.

**Comment by ericniebler** [comment]
@timsong-cpp wrote:
> This really doesn't make sense here. It should ...

Agreed. I'll word-smith.

**Comment by ericniebler** [comment]
@timsong-cpp wrote:
> This really doesn't make sense here. It should go into the "Let" clause, saying that you needn't handle the "mutating the lhs can invalidate the rhs" case to satisfy `Assignable`.

Done.

> Then we need separate wording to make it actually UB to perform the assignment

I think not. Some types are able to make assignment well-defined in the presence of lifetime-dependence. For example, if a type does copy-construct-and-swap for copy assignment and move-construct-and-swap for move assignment, it's always safe. Also, `std::shared_ptr` skirts the problem with fancy footwork. If we say UB for *all* lifetime-dependent assigns, then we make valid programs invalid.

Rather, I think it's satisfactory to define the guaranteed semantics for the non-lifetime-dependent case and say nothing about the lifetime-dependent case. Types are allowed to offer stronger guarantees.

**Comment by timsong-cpp** [comment]
> I think not. Some types are able to make assignment well-defined in the presence of lifetime-dependence. 

True, but don't we still need something to say that anything that takes an `Assignable` type need not behave correctly when given things that will cause lifetime-dependent assignments - unless that is well-defined in addition to `Assignable` - or something along those lines?

That is to say, normally ` void f(MeowConcept x);` will only use operations defined by `MeowConcept` with `x`, but that's not true with the new `Assignable` because the code that actually performs the assignment can't check for lifetime-dependency, but must assume that either there is no lifetime-dependence or that lifetime-dependent assignment is well defined.

**Comment by CaseyCarter** [comment]
What does "made invalid by" mean?

I think we're going down a rathole here because of "distinct objects." What we really want here is "objects with distinct values" or "independent objects" `a` and `b` such that no modification of `a` ever results in a modification of `b`.

I think we are equipped to handle assignment between objects with distinct values, and self-assignments, but this attempt to characterize what happens when we assign objects with overlapping values to each other seems doomed.

**Comment by ericniebler** [comment]
> What does "made invalid by" mean?

Not valid. Invariants not satisfied. See [defns.valid].

> I think we're going down a rathole here because of "distinct objects." What we really want here is "objects with distinct values" or "independent objects" `a` and `b` such that no modification of `a` ever results in a modification of `b`.

So far I've been thinking about lifetime, not modification. If an assignment operator tries an in-place mutation (like `std::vector::operator=` when the capacity is large enough to hold the result), and the mutation can accidentally result in the rhs becoming invalid (because it was destroyed prematurely as a result of the in-place mutation), then we're in UB-land.

You are describing something stronger: *any* modification of one object affecting the value of another. That may be what we want. Can you describe a situation where `a` and `b` are *not* lifetime-dependent, but where an assignment can land us in UB-land?

**Comment by ericniebler** [comment]
> don't we still need something to say that anything that takes an `Assignable` type need not behave correctly when given things that will cause lifetime-dependent assignments - unless that is well-defined in addition to `Assignable` - or something along those lines?

Let's back up. We already require:

> 6 Required operations of any concept defined in this document need not be total functions; that is, some arguments to a required operation may result in the required semantics failing to be satisfied. [ Example: The required < operator of the StrictTotallyOrdered concept (7.4.4) does not meet the semantic requirements of that concept when operating on NaNs.—end example ] This does not affect whether a type satisfies the concept.
> 7 A declaration may explicitly impose requirements through its associated constraints (Concepts TS [temp.constr.decl]). When the associated constraints refer to a concept (Concepts TS [dcl.spec.concept]), additional semantic requirements are imposed on the use of the declaration.
> 8 If the semantic requirements of a declaration are not satisfied at the point of use, the program is ill-formed, no diagnostic required.

Here's what I'm thinking: lifetime-dependent objects are outside the domain of assignment in much the same way that NaN is outside the domain of `<`. We don't need total functions for a type to satisfy a concept. That's nothing special. So, instead of trying to carefully carve out a set of values over which assignment is defined, can we get away with a (non-normative) note stating that objects that are value-dependent are outside the domain of op= ?

**Value dependent** (strawman definition):
`y` is *value-dependent* on `x` if a modification of `x` could result in a modification of `y` (where "modification" here could mean "changes the value", "invalidates", or "destroys").

**Comment by CaseyCarter** [comment]
```diff
 If x and y are distinct objects such that
-y is made invalid by the destruction of x, 
+destruction of x would invalidate y,
 then y is \techterm{lifetime-dependent-on} x.
```

**Comment by CaseyCarter** [comment]
> So, instead of trying to carefully carve out a set of values over which assignment is defined, can we get away with a (non-normative) note stating that objects that are value-dependent are outside the domain of op= ?

This feels like a more achievable direction, except for the "non-normative" part. I think a normative statement that "value-dependent pairs of objects need not be in the domain of `=`" would work.

**Comment by timsong-cpp** [comment]
But preferably with something other than *value-dependent*. Core already gave it an (unrelated) meaning.

**Comment by ericniebler** [comment]
OK, but we need to make an exception for self-assignment, which must not be UB, and except in the case of self-move must give the lhs the value of the rhs.

**Comment by ericniebler** [comment]
How about this?

> Two distinct objects `x` and `y` need not be in the domain of `=` if the expression <tt><i>MODIFY</i>(x), y</tt> is not equality preserving, for any equality-preserving, modifying operation *`MODIFY`*.

**Comment by ericniebler** [comment]
Updated, needs eyeballs. I would like to circulate this among a select group of experts after you sign off on this. My blog post about post-conditions on self-move made waves which haven't settled yet.

**Comment by timsong-cpp** [comment]
We should probably cast `MODIFY(x)` to void.

**Comment by CaseyCarter** [comment]
I am happy with the intent of the change. I do think the wording would be improved by naming the property (e.g., ) and using it as a precondition for the semantic requirements of `Assignable`:
```diff
 Let `t` be an lvalue that refers to an object `o` such that `decltype((t))` is `T`, and `u` an
 expression such that `decltype((u))` is `U` 
+that either (a) does not refer to an object, (b) refers to `o`, or (c) refers to an object `x`
+such that `p(o, x)` holds.
 Let u2 be a distinct object that is equal to u
+such that `p(o, u2)` and `p(x, u2)` - if `u` refers to an object `x` - holds.
```

Discussion with my officemate reveals that we may be working too hard to define the domain of assignment, and I'm starting to agree. It feels like we've just discovered `NaN`, and we're trying really hard to say that `NaN == NaN` does not matter, when we already have global wording that says operations need not be total. I strongly suspect that there are other special cases that we haven't yet run across that we would need to characterize as well in order to precisely characterize the domain of assignment. This feels more like an avenue for research than a "tweak this wording" issue.

**Comment by ericniebler** [comment]
> Discussion with my officemate reveals that we may be working too hard to define the domain of assignment, and I'm starting to agree. It feels like we've just discovered NaN, and we're trying really hard to say that NaN == NaN does not matter, when we already have global wording that says operations need not be total.


That's exactly why I originally suggested a non-normative note. I do think this issue warrants at least that much.

**Comment by ericniebler** [comment]
> This feels more like an avenue for research than a "just tweak this wording a bit" issue.

I disagree and would prefer we say something since there has been a lot of confusion and discussion about this issue, even among top experts. This is our line in the sand.

**Comment by CaseyCarter** [comment]
How about:
```latex
\enternote
If assignment to an object \tcode{x} can result in a modification of some other object
\tcode{y}, then \tcode{x = y} is likely not in the domain of \tcode{=}.
\exitnote
```
which makes the point in a way that non-mathematicians can understand?

**Comment by ericniebler** [comment]
The phrase "likely not in the domain" is awfully weak. How about "not required to be in the domain"?

**Comment by CaseyCarter** [comment]
I could live with "not required to be in the domain," although I suspect it will create confusion since nothing is currently required to be *in* the domain.
