### ISSUE TITLE
Should implicit Destructible requirements be made explicit?

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#40]
I was about to submit a pull request adding `Destructible<T>` to the requirements of `std::swap(T&,T&)` and `std::exchange(T&, U&&)` in [utility] and [utility.swap], when it occurred to me that every standard library function that may destroy an object implicitly requires `Destructible`. Do we want to make those requirements explicit in STL2?

**Comment by ericniebler** [comment]
Ugh. Yes it belongs on `std::swap` and `std::exchange`. `Destructible` is implied by `Semiregular`, so it should be already required in most of the algorithms, but it's clearly missing in many places. If you make a pull request, I'll gladly merge it.

**Comment by asutton** [comment]
> Ugh. Yes it belongs on std::swap and std::exchange. Destructible is implied by Semiregular, so it should be already required in most of the algorithms, but it's clearly missing in many places. If you make a pull request, I'll gladly merge it.


Apparently, assuming everything is Regular is not a bad thing...

If we ever have to write Destructible as a constraint on algorithm,
we've done something wrong. Let's over-constrain wherever we would
need to do this. If there are legitimate reasons to relax those
constraints, then we should require something more than a Github issue
discussion.

Andrew
