### ISSUE TITLE
for_each requirements strengthened vs. C++14

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#401]
`std::for_each` only requires its function argument to be `MoveConstructible`, whereas `ranges::for_each` requires its function argument to be `CopyConstructible`. Is this strengthening of requirements intentional?

We should either relax the requirement to agree with `std::for_each` or add a note to specifically point out that the requirement is stronger than that of C++14.

**Comment by ericniebler** [comment]
I'm personally OK with leaving it as-is, possibly with a note. I don't like special-casing one algorithm -- it complicates the concept checking. If people complain, we can fix it later.

I'll note that `for_each` from the Parallelism TS requires `CopyConstructible`.
