### ISSUE TITLE
Normative content in informative subclause

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#404]
The entire subclause 6.2 [description] is informative, but it contains things like `[customization.point.object]` and the last few paragraphs of `[structure.requirements]` that are clearly intended to be normative rather than informative.

Proposed Resolution
--------------------

Strike [structure.requirements]/p8, which states "If the semantic requirements of a declaration are not satisfied at the point of use, the program is ill-formed, no diagnostic required."

Add a new subsubsection after "Requires paragraph" ([res.on.required]) called "Semantic requirements" (stable name [res.on.requirements]) with the following:

> 6.3.4.7 **Semantic requirements** [res.on.requirements]
> 1 If the semantic requirements of a declaration's constraints~(\ref{structure.requirements}) are not satisfied at the point of use, the program is ill-formed, no diagnostic required.

Move subsubsection "Customization Point Objects" ([customization.point.object]) to a new subsubsection under "Conforming implementations" ([conforming]).

**Comment by ericniebler** [comment]
Would it make sense to move [structure.requirements]/p6-8 under [conforming]? And [customization.point.object] to a new subsection after [conforming]?

**Comment by CaseyCarter** [comment]
> Would it make sense to move [structure.requirements]/p6-8 under [conforming]?

I think 6 and 7 actually fit here as an informative clarification of how the remainder of the document formulates its normative requirements. 8 "If the semantic requirements of a declaration are not satisfied at the point of use, the program is ill-formed, no diagnostic required." is a constraint on programs and should therefore go in [constraints] perhaps with a link back here to make it clear what "semantic requirements" means.

> And [customization.point.object] to a new subsection after [conforming]?

CPO places requirements on the implementation - I would think a  subsubwhatever *in* conforming makes sense.

**Comment by ericniebler** [comment]
@CaseyCarter done
