### ISSUE TITLE
[intro.defs] doesn't conform to ISO directives

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#405]
The introductory text doesn't match the directives. Additionally, the directives says that

> The definition shall be written in such a form that it can replace the term in its context. It shall not start with an article (“the”, “a”) nor end with a full stop.

The definition of the only term, "projection", doesn't meet this requirement.

**Comment by ericniebler** [comment]
Looks like the following applies:

> If terms and definitions are provided in Clause 3, in addition to a reference to an external document, use the following introductory text:
> 
>> For the purposes of this document, the terms and definitions given in [external document reference xxx] and the following apply.
>> 
>> ISO and IEC maintain terminological databases for use in standardization at the following addresses:
>> IEC Electropedia: available at http://www.electropedia.org/
>> ISO Online browsing platform: available at http://www.iso.org/obp
