### ISSUE TITLE
istreambuf_iterator::operator->

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#407]
[LWG 2790](http://cplusplus.github.io/LWG/lwg-defects.html#2790) recently removed `istreambuf_iterator::operator->` from C++17. Should it be removed here as well?

**Comment by ericniebler** [comment]
Proposed Wording
-----------------

1. Remove the note in paragraph 1 of 9.8.3 [istreambuf.iterator]:

> The class template `istreambuf_iterator` defines an input iterator (9.3.11) that reads successive _characters_ from the streambuf for which it was constructed. `operator*` provides access to the current input character, if any. ~~[Note: operator-> may return a proxy. — end note]~~ Each time `operator++` is evaluated, the iterator advances to the next input character. […]

2. Remove the member from the class synopsis in 9.8.3 [istreambuf.iterator]:

```diff
 charT operator*() const;
-pointer operator->() const;
 istreambuf_iterator& operator++();
 proxy operator++(int);
```
