### ISSUE TITLE
find_first_of and mismatch should use IndirectRelation instead of Indirect(Binary)Predicate

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#411]
Why do `find_first_of` and `mismatch` use `Indirect(Binary)Predicate` instead of `IndirectRelation`?

According to [cppreference.com](http://en.cppreference.com/w/cpp/concept/BinaryPredicate), there are many algorithms that merely expect a BinaryPredicate and not a so-called Compare ... which is the current standard's name for Relation. In the Ranges TS, only `find_first_of` and `mismatch` expect Predicates; all the others expect Relations. Why?

I believe we picked this up from the Palo Alto report. Was the change intentional? Are the changed algorithms now over-constrained by requiring Relations whereas they could make do with Predicates?

@CaseyCarter thoughts? Maybe @asutton can give us the backstory on why N3351 strengthened the requirements of some algorithms, but mysteriously not `find_first_of` and `mismatch`.

Proposed Resolution
--------------

Change `<experimental/ranges/algorithm>` synopsis ([algorithms.general]) as follows:

```diff
 template <InputIterator I1, Sentinel<I1> S1, ForwardIterator I2, Sentinel<I2> S2,
     class Proj1 = identity, class Proj2 = identity,
-    IndirectPredicate<projected<I1, Proj1>, projected<I2, Proj2>> Pred = equal_to<>>
+    IndirectRelation<projected<I1, Proj1>, projected<I2, Proj2>> Pred = equal_to<>>
   I1
     find_first_of(I1 first1, S1 last1, I2 first2, S2 last2,
                   Pred pred = Pred{},
                   Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});
 
 template <InputRange Rng1, ForwardRange Rng2, class Proj1 = identity,
     class Proj2 = identity,
-    IndirectPredicate<projected<iterator_t<Rng1>, Proj1>,
+    IndirectRelation<projected<iterator_t<Rng1>, Proj1>,
       projected<iterator_t<Rng2>, Proj2>> Pred = equal_to<>>
   safe_iterator_t<Rng1>
     find_first_of(Rng1&& rng1, Rng2&& rng2,
                   Pred pred = Pred{},
                   Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});

[...]

 template <InputIterator I1, Sentinel<I1> S1, InputIterator I2, Sentinel<I2> S2,
     class Proj1 = identity, class Proj2 = identity,
-    IndirectPredicate<projected<I1, Proj1>, projected<I2, Proj2>> Pred = equal_to<>>
+    IndirectRelation<projected<I1, Proj1>, projected<I2, Proj2>> Pred = equal_to<>>
   tagged_pair<tag::in1(I1), tag::in2(I2)>
     mismatch(I1 first1, S1 last1, I2 first2, S2 last2, Pred pred = Pred{},
              Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});
 
 template <InputRange Rng1, InputRange Rng2,
     class Proj1 = identity, class Proj2 = identity,
-    IndirectPredicate<projected<iterator_t<Rng1>, Proj1>,
+    IndirectRelation<projected<iterator_t<Rng1>, Proj1>,
       projected<iterator_t<Rng2>, Proj2>> Pred = equal_to<>>
   tagged_pair<tag::in1(safe_iterator_t<Rng1>),
               tag::in2(safe_iterator_t<Rng2>)>
     mismatch(Rng1&& rng1, Rng2&& rng2, Pred pred = Pred{},
              Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});
 ```

Make the same changes to the signatures of `find_first_of` and `mismatch` in sections "Find first of" ([alg.find.first.of]) and "Mismatch" ([mismatch]).

Make the following change to section "Range-and-a-half algorithms" ([depr.algo.range-and-a-half]) in Annex A:

```diff
 template <InputIterator I1, Sentinel<I1> S1, InputIterator I2,
     class Proj1 = identity, class Proj2 = identity,
-    IndirectPredicate<projected<I1, Proj1>, projected<I2, Proj2>> Pred = equal_to<>>
+    IndirectRelation<projected<I1, Proj1>, projected<I2, Proj2>> Pred = equal_to<>>
   tagged_pair<tag::in1(I1), tag::in2(I2)>
     mismatch(I1 first1, S1 last1, I2 first2, Pred pred = Pred{},
              Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});
 
 template <InputRange Rng1, InputIterator I2,
     class Proj1 = identity, class Proj2 = identity,
-    IndirectPredicate<projected<iterator_t<Rng1>, Proj1>,
+    IndirectRelation<projected<iterator_t<Rng1>, Proj1>,
       projected<I2, Proj2>> Pred = equal_to<>>
   tagged_pair<tag::in1(safe_iterator_t<Rng1>), tag::in2(I2)>
     mismatch(Rng1&& rng1, I2 first2, Pred pred = Pred{},
              Proj1 proj1 = Proj1{}, Proj2 proj2 = Proj2{});
 ```

**Comment by CaseyCarter** [comment]
`Compare` requires the function to induce a strict weak ordering, so it corresponds more precisely to our `StrictWeakOrder` than `Relation`.

**Comment by ericniebler** [comment]
The question remains. Why do we single out `find_first_of` and `mismatch`? Shouldn't those use `IndirectRelation` instead of `Indirect(Binary)Predicate`?

**Comment by CaseyCarter** [comment]
> The question remains.

Yes, sorry - my comment was meant to inform the discussion, not as a response. I see no reason for those two particular algorithms to avoid `Relation`.

**Comment by ericniebler** [comment]
@CaseyCarter For your review.

**Comment by ericniebler** [comment]
I amended the proposed resolution with the required changes to Annex A.
