### ISSUE TITLE
accessors of tagged getters should be conditionally noexcept

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#418]
[taggedtup.tagged]/p4 says:

> A tagged getter class with DerivedCharacteristic D , ElementIndex N , and ElementName name shall provide the following interface:
> ```
> struct __TAGGED_GETTER {
>   constexpr decltype(auto) name() & { return get<N>(static_cast<D&>(*this)); }
>   constexpr decltype(auto) name() && { return get<N>(static_cast<D&&>(*this)); }
>   constexpr decltype(auto) name() const & { return get<N>(static_cast<const D&>(*this)); }
> };
> ```

The *`name`* accessors should be `noexcept` if the `return` expression is `noexcept` and if initializing the return value cannot throw (likely since `get` for `pair` and `tuple` are `noexcept` and return references).

Proposed Resolution
-----------------------

This issue is resolved by the proposed resolution of #364.

**Comment by CaseyCarter** [comment]
LEWG has killed `tagged` foor C++20 - closing this as NAD.
