### ISSUE TITLE
[istream.iterator] para 1 and 2 are horrible

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#419]
The specification and design of `istream_iterator` have some problems. First, the specification in the Standard begins with two paragraphs ([istream.iterator]/1 and /2) that intermix semi-normative description with actual normative requirements. This results in requirements that are either redundant, or are far from the entity whose behavior they are intended to describe. These normative requirements should be in the specification of the individual member functions. The current situation is both confusing and inconsistent with the specification of other library components.

Second, the semantics of exactly when an `istream_iterator` performs a read from its underlying input stream are unclear. The specification purports to allow an implementation to delay reading the initial value from the stream, which has been a source of confusion in the past ([LWG 245 “Which operations on istream_iterator trigger input operations?”](http://wg21.link/lwg245)). This program, for example:
```c++
istream_iterator<int>{cin};
istream_iterator<int>{cin};
istream_iterator<int>{cin};
istream_iterator<int>{cin};
istream_iterator<int>{cin};
```
is specified to read between zero and five integers from the standard input. Some analysis shows that an implementation that delays reading the initial value from the stream cannot, in fact, conform to the input iterator requirements.

Proposed Resolution
-----------------------
Adopt the wording in [P0738 "I Stream, You Stream, We All Stream for `istream_iterator`"](http://wg21.link/p0738).

**Comment by ericniebler** [comment]
Fixed.
