### ISSUE TITLE
Harmonize common_type with C++17's [meta.trans.other]/p4 

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#420]
Looks like the language drifted since we lifted it for the PR of #235. C++17's [meta.trans.other]/p4 now reads:

> Note B: Notwithstanding the provisions of (\cxxref{meta.type.synop}), and pursuant to \cxxref{namespace.std}, a program may specialize `common_type<T1, T2>` for types `T1` and `T2` such that `is_same_v<T1, decay_t<T1>>` and `is_same_v<T2, decay_t<T2>>` are each `true`. [ *Note:* Such specializations are needed when only explicit conversions are desired between the template arguments. —*end note* ] Such a specialization need not have a member named `type`, but if it does, that member shall be a *typedef-name* for an accessible and unambiguous cv-unqualified non-reference type `C` to which each of the types `T1` and `T2` is explicitly convertible. Moreover, `common_type_t<T1, T2>` shall denote the same type, if any, as does `common_type_t<T2, T1>`. No diagnostic is required for a violation of this Note’s rules.

This is much better, IMO.

Proposed Resolution
---------------------

Replace our Note B (see #235) with the one in the current IS draft, quoted above.

In addition, make the following change to the (newly added) paragraph about `basic_common_reference` (see #235):

```diff
-A program may specialize the basic_common_reference trait for
-two cv-unqualified non-reference types if at least one of them depends on a
-user-defined type. Such a specialization need not have a member named
-type.
+Notwithstanding the provisions of \cxxref{meta.type.synop}, and pursuant to
+\cxxref{namespace.std}, a program may specialize
+basic_common_reference<T, U, TQual, UQual> for types T and U such that
+is_same_v<T, decay_t<T>> and is_same_v<U, decay_t<U>> are each true.
+[ Note: Such specializations are needed when only explicit conversions are
+desired between the template arguments. —end note ] Such a specialization
+need not have a member named type, but if it does, that member shall be a
+typedef-name for an accessible and unambiguous type C to which each of the
+types TQual<T> and UQual<U> is convertible. Moreover,
+basic_common_reference<T, U, TQual, UQual>::type shall denote the same type,
+if any, as does basic_common_reference<U, T, UQual, TQual>::type. A program
+may not specialize basic_common_reference on the third or fourth parameters,
+TQual or UQual. No diagnostic is required for a violation of these rules.
```

**Comment by ericniebler** [comment]
@CaseyCarter for your review

**Comment by CaseyCarter** [comment]
> explicitly convertible

#311 Changes `Common` and `CommonReference` to require `ConvertibleTo`; this should simply be "convertible" rather than "explicitly convertible."
