### ISSUE TITLE
With common_type, the Ranges TS requires vendors to break conformance

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#421]
The Ranges TS requires changes to `common_type` *in namespace `std`*. This is a bad idea. It requires vendors to break conformance in order to support the Ranges TS. Reformulate things so that we can move the `Common[Reference]` machinery out of namespace `std` and into namespace `std::experimental::ranges`.

This moves the last piece of the Ranges TS out of namespace `std`, making the TS a pure extension.

Proposed Resolution
--------------------

[*Editorial:* Issue #259 moves the `is_swappable` traits out of namespace `std` and into namespace `std::experimental::ranges`. This PR does the same for the `common_type` traits, leaving nothing left in [meta.type.synop]. This wording assumes the wording in (ready) issue #259.]

Remove section "Header `<type_traits>` synopsis" ([meta.type.synop]).

Give section "Header `<experimental/ranges/type_traits>` synopsis ([meta.type.synop.rng]) the stable name [meta.type.synop] and make the following change to the synopsis:

```diff
 namespace std { namespace experimental { namespace ranges { inline namespace v1 {
 // (REF), type properties:
 template <class T, class U> struct is_swappable_with;
 template <class T> struct is_swappable;
 
 template <class T, class U> struct is_nothrow_swappable_with;
 template <class T> struct is_nothrow_swappable;

+// (REF), other transformations
+template <class... T> struct common_type;
+template <class T, class U, template <class> class TQual, template <class> class UQual>
+  struct basic_common_reference { };
+template <class... T> struct common_reference;
 
+template <class... T>
+  using common_type_t = typename common_type<T...>::type;
+template <class... T>
+  using common_reference_t = typename common_reference<T...>::type;

 template <class T, class U> constexpr bool is_swappable_with_v
     = is_swappable_with<T, U>::value;
 template <class T> constexpr bool is_swappable_v
     = is_swappable<T>::value;
 
 template <class T, class U> constexpr bool is_nothrow_swappable_with_v
     = is_nothrow_swappable_with<T, U>::value;
 template <class T> constexpr bool is_nothrow_swappable_v
     = is_nothrow_swappable<T>::value;
 }}}}
```

Rename section "Additional type properties" ([meta.unary.prop.rng], #259) to "Type properties" with the stable name [meta.unary.prop].

Move section "Other transformations" ([meta.trans.other]) after "Type properties".

Strike the editorial notes in [meta.trans.other] that read "Change Table 57 – “Other Transformations” in ISO/IEC 14882:2014 as follows", and "Delete [meta.trans.other]/p3 from ISO/IEC 14882:2014 and replace it with the following."

Remove all the diff markings from [meta.trans.other].

Renumber Table 57 (since it is no longer referring to a table in another document).

Change the description of `common_type` in [meta.trans.other] as follows (includes resolutions of #235 and #420):

 ```diff
   2. Note A: For the common_type trait applied to a parameter pack [...]
   [...]
   (2.3)     — Otherwise, if sizeof...(T) is two, let T1 and T2 denote the
               two types in the pack T, and let D1 and D2 be decay_t<T1> and
               decay_t<T2> respectively. Then
   (2.3.1)        — If D1 and T1 denote the same type and D2 and T2 denote
                    the same type, then
- (2.3.1.-?-)             — If COND_RES(T1, T2) is well-formed, then the
+ (2.3.1.-?-)             — If std::common_type_t<T1, T2> is well-formed, then the
                             member typedef type denotes
-                           decay_t<COND_RES(T1, T2)>.
+                           std::common_type_t<T1, T2>.
   (2.3.1.1)               — If COMMON_REF(T1, T2) is well-formed, then the
                             member typedef type denotes that type.
   (2.3.1.2)               — Otherwise, there shall be no member type
   [...]
   (2.4.2)        — Otherwise, there shall be no member type.
  -?-. Note B: Notwithstanding the provisions of (\cxxref{meta.type.synop}),
       and pursuant to [...].
  ```

**Comment by CaseyCarter** [comment]
Background:
* [LWG DR 2465 "SFINAE-friendly common_type is nearly impossible to specialize correctly and regresses key functionality"](http://cplusplus.github.io/LWG/lwg-defects.html#2465)

and 

* [LWG DR 2763 "common_type_t<void, void> is undefined"](http://cplusplus.github.io/LWG/lwg-defects.html#2763)

are both marked as "Resolved by [P0435R1 [ed: "Resolving LWG Issues re common_type"]](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0435r1.pdf)." Since these are defect resolutions, they apply to C++14, the base document for the Ranges TS. For all intents, the current wording of "C++14 `common_type`" is the wording specified in [P0435R1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0435r1.pdf).

The effective difference between the wording in P0435R1 and N4671 (the current Ranges WP) is that bullet 3.3.2 from P0435R1:

> (3.3.2) — Otherwise, let `C` denote the same type, if any, as `decay_t<decltype(false ? declval<D1>() :  declval<D2>())>`. [Note: This will not apply if there is a specialization `common_type<D1, D2>`. — end note]

is replaced by two bullets:

> (2.3.1.1) — If `COMMON_REF(T1, T2)` is well-formed, then the member typedef `type` denotes that type.
> (2.3.1.2) — Otherwise, there shall be no member `type`.

Where `COMMON_REF` (N4671 [meta.trans.other]/1) is substantially more complicated than the simple ternary expression from P0435.

**Comment by timsong-cpp** [comment]
Note that P0435R1's wording is further adjusted by [P0548R1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0548r1.pdf). 

Since we are talking about `COMMON_REF` of two decayed types, only the final bullet is relevant and produces `decay_t<COND_RES(CREF(A), CREF(B))>`. The difference is that the conditional expression uses const lvalues rather than non-const xvalues. Note that #235's PR will check `decay_t<COND_RES(T1, T2)>` first - i.e., with non-const xvalues, so with that the only difference is when `COND_RES(T1, T2)` is ill-formed but `COND_RES(CREF(A), CREF(B))` is well-formed.

**Comment by ericniebler** [comment]
> Note that #235's PR will check `decay_t<COND_RES(T1, T2)>` first - i.e., with non-const xvalues, so with that the only difference is when `COND_RES(T1, T2)` is ill-formed but `COND_RES(CREF(A), CREF(B))` is well-formed.

Right. My suggestion is to move `common_type` (and friends) into `std::experimental::ranges`, and instead of first checking the well-formed-ness of `decay_t<COND_RES(T1, T2)>` -- as suggested by the PR of #235 -- we should check the well-formed-ness of `std::common_type_t<T1, T2>`.

**Comment by CaseyCarter** [comment]
>Note that P0435R1's wording is further adjusted by P0548R1.

Sadly, only for the C++17 WP. Intentional or not, WG21 applied P0548R1 to the C++17 WP via LWG motion  22. That paper has not been applied to resolve a defect in prior standards. (The difference is largely academic, but it's worth pointing out here.) 

In any case, the clarifications that P0548R1 applies to the `common_type` wording don't have significant normative effect. Most of its normative changes were to `chrono::duration`.

**Comment by timsong-cpp** [comment]
> That paper has not been applied to resolve a defect in prior standards. 

Well, it's applied (in part) to resolve a defect in a paper applied to resolve a defect in prior standards :) It makes little sense to say that `duration`-like `common_type` specializations cause undefined behavior in C++14.

As relevant to `common_type`, the impact is primarily in the `common_type<T0>` case, which may now dispatch to a user specialization.

**Comment by CaseyCarter** [comment]
> It makes little sense to say that `duration`-like `common_type` specializations cause undefined behavior in C++14.

I have certainly never accused WG21 of making sense.

**Comment by timsong-cpp** [comment]
> This happens for `common_type_t<NonMovableType, NonMovableType>`.

I'm not sure I understand. `true? declval<NonMovableType>() : declval<NonMovableType>()` is a perfectly well-formed xvalue expression...?

**Comment by ericniebler** [comment]
> > This happens for `common_type_t<NonMovableType, NonMovableType>`.
>
> I'm not sure I understand. `true? declval<NonMovableType>() : declval<NonMovableType>()` is a perfectly well-formed xvalue expression...?

Dang, it was something like that. I'll note that the following doesn't compile today, and will with the tweak we're proposing:

```c++
using Y = std::common_type_t<std::reference_wrapper<int>, int>;
```

This is actually a peculiarity with `reference_wrapper`, which has the following constructor:

```c++
// What could possibly go wrong?
reference_wrapper(T &&) = delete;
```

When checking convertibility, the compiler seems to think this is viable. (!!!) Since a `reference_wrapper` can be converted to a prvalue `int`, and since (it thinks) an xvalue `int` can be converted to a prvalue `reference_wrapper`, the conversion is ambiguous, so `std::common_type` gives up.

Srsly, WTF? This is a major PITA. I had hoped that we could just drop the extra bullet and be happy with C++14's `common_type`, but when I try to change the reference implementation accordingly, I see lots of test breakages. It's too late for risky changes. We have to keep the extra bullet and move our `common_type` into our own namespace.

I'll write up a PR.

**Comment by timsong-cpp** [comment]
>    using Y = std::common_type_t<std::reference_wrapper<int>, int>;

That's a nice example, but even with the tweak `using Z = std::common_type_t<std::reference_wrapper<const int>, const int>;` still breaks as far as I can see.

**Comment by ericniebler** [comment]
> even with the tweak `using Z = std::common_type_t<std::reference_wrapper<const int>, const int>;` still breaks

I don't deny it. `reference_wrapper` might need a `common_type` specialization.

**Comment by timsong-cpp** [comment]
> `reference_wrapper` might need a `common_type` specialization.

And/or its constructors need to be adjusted so that it doesn't have an ICS at all from rvalue `T`s, rather than having an ICS that is ill-formed when actually used.

**Comment by ericniebler** [comment]
> > `reference_wrapper` might need a `common_type` specialization.
> 
> And/or its constructors need to be adjusted so that it doesn't have an ICS at all from rvalue `T`s, rather than having an ICS that is ill-formed when actually used.

I've msg'ed the lwgchair about this. (Hi, @mclow!)

**Comment by CaseyCarter** [comment]
> And/or its constructors need to be adjusted so that it doesn't have an ICS at all from rvalue `T`s

This is hard to accomplish for e.g. `reference_wrapper<const int>` given that `const int&&` converts to `const int&`.

**Comment by CaseyCarter** [comment]
> This is hard to accomplish for e.g. `reference_wrapper<const int>` given that `const int&&` converts to `const int&`.

Perhaps:

```c++
template<class T>
struct reference_wrapper {
  template<class U>
    requires std::is_lvalue_reference_v<U> &&
      std::is_convertible_v<U, T&>
    reference_wrapper(U&&);
};
```

**Comment by ericniebler** [comment]
Better IMO:

```c++
template <class T>
struct reference_wrapper_ {
  reference_wrapper_(T&);
  reference_wrapper_(T&&) = delete;
  reference_wrapper_(const reference_wrapper_& x) noexcept;
};

template <class T>
struct reference_wrapper {
  template <class U>
    requires std::is_constructible_v<reference_wrapper_<T>, U>
  reference_wrapper(U&& u);
  reference_wrapper(const reference_wrapper& x) noexcept;

  operator T& () const noexcept;
};

using T = std::common_type_t<reference_wrapper<int>, int>;

static_assert(std::is_constructible<reference_wrapper<int>, int&>::value, "");
static_assert(std::is_constructible<reference_wrapper<int const>, int const&>::value, "");
static_assert(!std::is_constructible<reference_wrapper<int>, int>::value, "");
static_assert(!std::is_constructible<reference_wrapper<int const>, int const>::value, "");
```

**Comment by CaseyCarter** [comment]
[C++17](https://godbolt.org/g/7upxYz):
```c++
#include <type_traits>

template<class T> void f(T&);
template<class T> void f(T&&) = delete;

template <class T>
struct reference_wrapper {
  template <class U,
    std::void_t<decltype(f(std::declval<U>()))>* = nullptr>
  constexpr reference_wrapper(U&& u);

  constexpr operator T& () const noexcept;
};

using T = std::common_type_t<reference_wrapper<int>, int>;

static_assert(std::is_constructible<reference_wrapper<int>, int&>::value, "");
static_assert(std::is_constructible<reference_wrapper<int const>, int const&>::value, "");
static_assert(!std::is_constructible<reference_wrapper<int>, int>::value, "");
static_assert(!std::is_constructible<reference_wrapper<int const>, int const>::value, "");
```

**Comment by timsong-cpp** [comment]
> `f(std::declval<U>())` 

`f<T>`?

**Comment by ericniebler** [comment]
This PR is ready for review.

**Comment by ericniebler** [comment]
And for posterity, [here is a gist](https://gist.github.com/ericniebler/7cff48607b44a949f5cc7e86ff17cecf) of a `reference_wrapper` that has exactly(?) the same behavior as `std::reference_wrapper` minus the ICS that offendeth thyne sensibilities.

**Comment by timsong-cpp** [comment]
>>> This happens for` common_type_t<NonMovableType, NonMovableType>`.
>>
>>I'm not sure I understand. `true? declval<NonMovableType>() : declval<NonMovableType>()` is a perfectly well-formed xvalue expression...?
>
> Dang, it was something like that. 

Maybe you were thinking about #338's change to the definition of `COND_RES`?
