### ISSUE TITLE
Constrain return types in IndirectInvocable

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#424]
Both range-v3 and cmcstl2 constrain the return types of the required expressions of the `IndirectInvocable` concepts to share a common reference. The concepts in STL2 don't seem to do that. Was this just an oversight?

A polymorphic function `F` that has wildly unrelated return types when invoked with a `value_type_t<I>&` vs. a `reference_t<I>` should not be accepted by the STL algorithms because of the havoc it would cause.

Proposed Resolution
--------------------
 
This resolution assumes the switch to variable-style concepts suggested by [P0651](http://wg21.link/P0651).

Change `IndirectUnaryInvocable` ([indirectcallable.indirectinvocable]) as follows:

```diff
 template <class F, class I>
 concept bool IndirectUnaryInvocable =
   Readable<I> &&
   CopyConstructible<F> &&
   Invocable<F&, value_type_t<I>&> &&
   Invocable<F&, reference_t<I>> &&
-  Invocable<F&, iter_common_reference_t<I>>;
+  Invocable<F&, iter_common_reference_t<I>> &&
+  CommonReference<
+    result_of_t<F&(value_type_t<I>&)>,
+    result_of_t<F&(reference_t<I>&&)>>;
```

Change `IndirectRegularUnaryInvocable` ([indirectcallable.indirectinvocable]) as follows:

```diff
 template <class F, class I>
 concept bool IndirectRegularUnaryInvocable =
   Readable<I> &&
   CopyConstructible<F> &&
   RegularInvocable<F&, value_type_t<I>&> &&
   RegularInvocable<F&, reference_t<I>> &&
-  RegularInvocable<F&, iter_common_reference_t<I>>;
+  RegularInvocable<F&, iter_common_reference_t<I>> &&
+  CommonReference<
+    result_of_t<F&(value_type_t<I>&)>,
+    result_of_t<F&(reference_t<I>&&)>>;
```

**Comment by ericniebler** [comment]
@CaseyCarter for your review.

**Comment by CaseyCarter** [comment]
LGTM. I'd prefer if you move the rationale into the second post: I think it helps readers triage issues if we keep the first post simply a problem statement and PR, with the rest of the thread as discussion.

**Comment by ericniebler** [comment]
For this to be truly useful, there should be a way to get a value type directly from a reference type. But that's [another can of worms](https://github.com/ericniebler/stl2/issues/226).
