### ISSUE TITLE
What header declares the tag specifiers?

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#425]
We say they exist, and refer to them throughout the algorithm specifications, but we never specify the exact set of tag specifiers, or the header which users must include in order to name the tag specifiers.

**Comment by CaseyCarter** [comment]
Probably in `<utility>`, where `tagged` is defined. `<algorithm>` wouldn't be crazy either.

**Comment by timsong-cpp** [comment]
Um, 
> [Header `<experimental/ranges/algorithm>` synopsis](https://timsong-cpp.github.io/cppwp/ranges-ts/algorithms#general-2)
>     
>     #include <initializer_list>
>     
>     namespace std { namespace experimental { namespace ranges { inline namespace v1 {
>       namespace tag {
>         // [alg.tagspec], tag specifiers (See [taggedtup.tagged]):
>         struct in;
>         struct in1;
>         struct in2;
>         struct out;
>         struct out1;
>         struct out2;
>         struct fun;
>         struct min;
>         struct max;
>         struct begin;
>         struct end;
>       }

Or did I misunderstand the issue?

**Comment by ericniebler** [comment]
Yes, I specified them in `<experimental/ranges/algorithms>` because that's where they are used.

**Comment by CaseyCarter** [comment]
> Or did I misunderstand the issue?

No, you do not. I should not use the issue list to remind myself to check something later.

It's a bit unfortunate that I cannot use `tagged` without including the heavy-weight `<algorithm>` since there's currently no way for users to define their own tag specifiers. This is not a bridge we need to burn now, though.
