### ISSUE TITLE
tagged<const pair<int, int>, /* specifiers */>

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#426]
I don't see any wording that says `Base` must be cv-unqualified, but the behavior as specified here seems to be "ignore the cv-qualification in element access but consider it in special member functions", which is nonsensical.

**Comment by CaseyCarter** [comment]
`tagged<const pair<int, int>>, Tags...>` requires `sizeof...(Tags) <= tuple_size<const pair<int, int>>::value` which is ill-formed since `tuple_size<const pair<int, int>>` has no definition. 

The root problem here seems to be that the phrase "tuple-like types" lacks a proper normative definition.

**Comment by timsong-cpp** [comment]
> `tuple_size<const pair<int, int>>` has no definition

It does, via the `template <class T> class tuple_size<const T>;` specialization

**Comment by CaseyCarter** [comment]
LEWG has killed `tagged` foor C++20 - closing this as NAD.
