### ISSUE TITLE
Using a function type for TaggedType leads to result_of-esque problems

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#427]
This is well-formed because function type adjustment silently drops the `const`:

```c++
tagged_tuple<tag::in(const int)> x; 
x.in() = 1;
```

which seems rather unfortunate.

**Comment by ericniebler** [comment]
Indeed. We could permit the use of abominable function types as an alternate syntax:

```c++
tagged_tuple<tag::in(int) const> x; 
```

That's WEIRD and violates the Principle of Least Surprise. We could also permit the use of a special wrapper:

```c++
tagged_tuple<tag<tag::in, int const>> x; 
```

or

```c++
struct const_; // undefined
tagged_tuple<tag::in(const_(int))> x; 
```

or

```c++
template <class> struct exactly; // undefined
tagged_tuple<tag::in(exactly<int const>)> x; 
```

The use of function types here was arguably a mistake. We'll have a chance to fix it when we merge to the IS (and I'm tagging this appropriately).

**Comment by ericniebler** [comment]
I'll note here that users have a simple work-around: use `tagged` directly.

**Comment by timsong-cpp** [comment]
Or

```c++
tagged_tuple<const int(tag::in)> x;
```

**Comment by CaseyCarter** [comment]
I think I'd prefer to have tag specifiers be class templates instead of classes a la `tagged_pair<tag::in<int>, tag::out<float const>>`.

**Comment by ericniebler** [comment]
> Or
> 
> ```c++
> tagged_tuple<const int(tag::in)> x;
> ```

Nope, that's just `int(tag::in)`.

**Comment by timsong-cpp** [comment]
> Nope, that's just `int(tag::in)`.

[It's not](http://coliru.stacked-crooked.com/a/d8b797924aecc884) :)

**Comment by ericniebler** [comment]
> > Nope, that's just `int(tag::in)`.
> 
> [It's not](http://coliru.stacked-crooked.com/a/d8b797924aecc884) :)

Whaaaaat? I don't understand C++ at all.

**Comment by timsong-cpp** [comment]
> Whaaaaat? I don't understand C++ at all.

The crazy type adjustments apply only to parameter types, not return types - recall the C++03-era advice about returning `const`-qualified stuff.

Now, given `const int f();`, `decltype(f())` is `int`, but that's [expr]/6 at work on the type of the function call expression and doesn't affect the function type itself.

One thing I like about the structure of `const int (tag::in)` is that one can think of the parens as parenthetical annotations.

**Comment by ericniebler** [comment]
... or:

```c++
tagged_tuple<const int tag::in::*> x;
```

@CaseyCarter wrote:
> I think I'd prefer to have tag specifiers be class templates instead of classes a la `tagged_pair<tag::in<int>, tag::out<float const>>`. 

This is the least awful I've heard so far.

**Comment by timsong-cpp** [comment]
>> I think I'd prefer to have tag specifiers be class templates instead of classes a la `tagged_pair<tag::in<int>, tag::out<float const>>`.
>
>This is the least awful I've heard so far.

I like that too, though I'm slightly worried about template template parameter matching in the presence of alias templates. See CWG 1286.

**Comment by CaseyCarter** [comment]
LEWG has killed `tagged` foor C++20 - closing this as NAD.
