### ISSUE TITLE
Consider removing support for rvalue ranges from range access CPOs

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#429]
Currently all of:
* `begin`
* `end`
* `cbegin`
* `cend`
* `rbegin`
* `rend`
* `crbegin`
* `crend`
* `data`
* `cdata`

accept rvalue ranges of type `T` and treat them like lvalue ranges of type `const T` because that's how the standard versions (unintentionally?) handle rvalues. This support is deprecated because I was afraid to straight-up remove support for something that works in Standard C++.

Now I know better. Support for rvalue ranges in these CPOs should be burned out with fire and sword.

**Comment by cjdb** [comment]
## Proposed resolution

**Change to [iterator.range.begin]/1.1**
```diff
-\tcode{ranges::begin(static_cast<const T\&>(E))} if \tcode{E} is an rvalue of
-type \tcode{T}. This usage is deprecated.
-\enternote This deprecated usage exists so that
-\tcode{ranges::begin(E)} behaves similarly to \tcode{std::begin(E)}
-as defined in ISO/IEC 14882 when \tcode{E} is an rvalue. \exitnote
+\tcode{ranges::begin(E)} is ill-formed if \tcode{E} is an rvalue.
```

**Change to [iterator.range.end]/1.1**

```diff
-\tcode{ranges::end(static_cast<const T\&>(E))} if \tcode{E} is an rvalue of
-type \tcode{T}. This usage is deprecated.
-\enternote This deprecated usage exists so that
-\tcode{ranges::end(E)} behaves similarly to \tcode{std::end(E)}
-as defined in ISO/IEC 14882 when \tcode{E} is an rvalue. \exitnote
+\tcode{ranges::end(E)} is ill-formed if \tcode{E} is an rvalue.
```

**Change to [iterator.range.cbegin]/2**

```diff
-Use of \tcode{ranges::cbegin(E)} with rvalue \tcode{E} is deprecated.
-\enternote This deprecated usage exists so that \tcode{ranges::cbegin(E)}
-behaves similarly to \tcode{std::cbegin(E)} as defined in ISO/IEC 14882 when
-\tcode{E} is an rvalue. \exitnote
+Use of tcode{ranges::cbegin(E)} with rvalue \tcode{E} is ill-formed.
```

**Change to [iterator.range.cend]/2**

```diff
-Use of \tcode{ranges::cend(E)} with rvalue \tcode{E} is deprecated.
-\enternote This deprecated usage exists so that \tcode{ranges::cend(E)}
-behaves similarly to \tcode{std::cend(E)} as defined in ISO/IEC 14882 when
-\tcode{E} is an rvalue. \exitnote
+Use of \tcode{ranges::cend(E)} with rvalue \tcode{E} is ill-formed.
```

**Change to [iterator.range.rbegin]/1.1**

```diff
-\tcode{ranges::rbegin(static_cast<const T\&>(E))} if \tcode{E} is an rvalue of
-type \tcode{T}. This usage is deprecated.
-\enternote This deprecated usage exists so that
-\tcode{ranges::rbegin(E)} behaves similarly to \tcode{std::rbegin(E)}
-as defined in ISO/IEC 14882 when \tcode{E} is an rvalue. \exitnote
+\tcode{ranges::rbegin(E)} is ill-formed if \tcode{E} is an rvalue.
```

**Change to [iterator.range.rend]/1.1**

```diff
-\tcode{ranges::rend(static_cast<const T\&>(E))} if \tcode{E} is an rvalue of
-type \tcode{T}. This usage is deprecated.
-\enternote This deprecated usage exists so that
-\tcode{ranges::rend(E)} behaves similarly to \tcode{std::rend(E)}
-as defined in ISO/IEC 14882 when \tcode{E} is an rvalue. \exitnote
+`ranges::rend(E)` is ill-formed if `E` is an rvalue.
```

**Change to [iterator.range.crbegin]/2**

```diff
-Use of \tcode{ranges::crbegin(E)} with rvalue \tcode{E} is deprecated.
-\enternote This deprecated usage exists so that \tcode{ranges::crbegin(E)}
-behaves similarly to \tcode{std::crbegin(E)} as defined in ISO/IEC 14882 when
-\tcode{E} is an rvalue. \exitnote
+Use of `ranges::crbegin(E)` with rvalue `E` is ill-formed.
```

**Change to [iterator.range.crend]/2**

```diff
-Use of \tcode{ranges::crend(E)} with rvalue \tcode{E} is deprecated.
-\enternote This deprecated usage exists so that \tcode{ranges::crend(E)}
-behaves similarly to \tcode{std::crend(E)} as defined in ISO/IEC 14882 when
-\tcode{E} is an rvalue. \exitnote
+Use of \tcode{ranges::crend(E)} with rvalue \tcode{E} is ill-formed.
```

**Change to [range.primitives.data]/1.1**

```diff
-\tcode{ranges::data(static_cast<const T\&>(E))} if \tcode{E} is an rvalue of
-type \tcode{T}. This usage is deprecated. \enternote
-This deprecated usage exists so that \tcode{ranges::data(E)} behaves
-similarly to \tcode{std::data(E)} as defined in the \Cpp Working
-Paper when \tcode{E} is an rvalue. \exitnote
+\tcode{ranges::data(E)} is ill-formed if \tcode{E} is an rvalue.
```

**Change to [range.primitives.cdata]/2**

```diff
-Use of \tcode{ranges::cdata(E)} with rvalue \tcode{E} is deprecated.
-\enternote This deprecated usage exists so that \tcode{ranges::cdata(E)}
-has behavior consistent with \tcode{ranges::data(E)} when \tcode{E} is
-an rvalue. \exitnote
+Use of \tcode{ranges::cdata(E)} with rvalue \tcode{E} is ill-formed.
```
## Note

I've noticed that there are two different opening sentences: one for non-`const`, and one for `const`:

```
\tcode{ranges::data(static_cast<const T\&>(E))} if \tcode{E} is an rvalue of type \tcode{T}. This usage is deprecated.
```
```
Use of \tcode{ranges::cdata(E)} with rvalue \tcode{E} is deprecated.
```

I've kept the wording the same, but it feels a bit awkward. Should the wording be changed for one of them so that they remain consistent?

**Comment by timsong-cpp** [comment]
The cleanest fix seems to me to be striking the first bullet entirely for the non-const variants, then adding a new paragraph with "Use of ... with rvalue `E`..." after the whole list.

**Comment by CaseyCarter** [comment]
> I've noticed that there are two different opening sentences: one for non-const, and one for const

The non-`const` CPOs define rvalue-specific behavior: they transform the rvalues into const lvalues. The `const` CPOs don't need rvalue-specific behavior since they transform everything into const lvalues. Take `cbegin`, for example: `ranges::cbegin(E)` is expression-equivalent to `ranges::begin(static_cast<const remove_reference_t<decltype((E))>&>(E))` which works regardless of the value category of `E`. 

> The cleanest fix seems to me to be striking the first bullet entirely for the non-const variants, then adding a new paragraph with "Use of ... with rvalue E..." after the whole list.

I don't like non-local effects. If I'm trying to determine the behavior of `foo(2)` and the specification says:

> `foo(x)` returns:
> * If `x > 0`, `x + 3`
> * Otherwise, if ...
> * Otherwise, if ...
> * ...

I should be able to stop reading at the first bullet rather then needing to ensure that a later bullet doesn't say "Except when `x` is even, in which case foo(x) returns -1."

What about a middle-of-the-road solution? Change the specifications to:

> `ranges::foo(E)` for an lvalue expression E is equivalent to:
> * ...
> * ...
> * Otherwise, or when `E` is an rvalue, `ranges::foo(E)` is ill-formed.

**Comment by timsong-cpp** [comment]
I'm not a big fan of having "rvalue" in a bullet list introduced by "lvalue expression". To borrow your argument, I should be able to skip the entire list when I read "for an lvalue expression `E`" in its introduction. How about:

> The expression `ranges::foo(E)` for some expression `E` is ill-formed if `E` is an rvalue. Otherwise, the expression is equivalent to:
>
> * ...
> * ...

**Comment by CaseyCarter** [comment]
How about "The expression `ranges::foo(E)` is ill-formed for rvalue `E`. For lvalue `E`, it is equivalent to:"?

**Comment by cjdb** [comment]
Updated PR in ++OP.

**Comment by ericniebler** [comment]
Fixed.
