### ISSUE TITLE
`ostream_iterator` doesn't support `string_view`

### ISSUE THREAD

**Issue by cjdb** [ericniebler/stl2#430]
Seems like an issue for the IS, but I'm documenting it now, as it just came up.

# Motivation

Gives people an incentive to (seamlessly) move from `const char*` to `string_view`.

Right now, we need to use `ostream_iterator<T>{o, delimiter.data()}`, which isn't an issue, but some might argue that `.data()` is 'ugly' or 'confusing'. AFAICT there's no impact beyond eliminating the need for the `.data()` member function call.

# Proposed resolution

Change to [ostream.iterator]/2:

```diff
-ostream_iterator(ostream_type& s, const charT* delimiter) noexcept
+ostream_iterator(ostream_type& s, const string_view delimiter) noexcept
```

**Comment by timsong-cpp** [comment]
No. `string_view` isn't necessarily null-terminated, unlike the current interface.

I also question the idea of storing and persisting a non-owning view of a (possibly temporary) string.

**Comment by cjdb** [comment]
> I also question the idea of storing and persisting a non-owning view of a (possibly temporary) string.

Yes, I didn't consider the temporary case.
