### ISSUE TITLE
Do chrono types satisfy the comparison concepts?

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#431]
Many types `T` and `U` in chrono are *explicitly* but not *implicitly* convertible to `common_type_t<T, U>`. Does this make it impossible or merely challenging for those types to satisfy the comparison concepts?

We need to develop a common vision for the future of `Common` in C++.

**Comment by ericniebler** [comment]
Challenging but not impossible, I would say. We would need to specialize `common_type` for the chrono types and pick some unspecified type to which both types are implicitly convertible. Demoting the priority.

**Comment by JohelEGP** [comment]
By definition, `duration`s and `time_point`s are implicitly convertible to their common type. This issue predates the standardization of [Extending <chrono> to Calendars and Time Zones](http://wg21.link/P0355) ([Adopted 2018-03](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/#mailing2018-04)), but might you be referring to the types it introduced?

**Comment by CaseyCarter** [comment]
In any case, this became a non-issue after the application of [LWG3153](https://wg21.link/lwg3153) to the working draft. `Common` now requires only explicit conversions.
