### ISSUE TITLE
Consider removing the _n algorithm overloads

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#432]
Since `foo_n(i, n)` is equivalent to `foo(counted_iterator{i, n}, default_sentinel{})`, the `_n` algorithms are largely extraneous. Yes, it requires more keystrokes, but future work on view adapters will simplify the usage to `foo(view::counted(i, n))` which is only slightly more keystrokes but nicely explicit.

It's notable that there are not `_n` overloads for every algorithm. At the very least, we need a consistent guideline for when we add an `_n` and when we do not. Between the two trivial alternatives, I prefer "never" to "always." There may be other reasonable guidelines that haven't occurred to me.

**Comment by cjdb** [comment]
What's the rationale behind this?

**Comment by CaseyCarter** [comment]
Updated with some description. I personally don't hate the `_n` overloads enough to remove them; it hurts our transition story absent `view::counted` in the TS.

**Comment by ericniebler** [comment]
And even now that we have `view::counted` in the IS, I don't feel strongly motivated to remove the `_n` algorithms. I'm fine leaving them as a shorthand and an historical artifact. I'm closing this since it seems unlikely anything will come of it.
