### ISSUE TITLE
CPOs should be inline constexpr variables

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#435]
instead of "constexpr reference in an unnamed namespace."

**Comment by timsong-cpp** [comment]
This doesn't compile:

```c++
namespace X {
    struct rv { friend void meow(rv) {} };
    inline constexpr auto meow = 1;
}
```

The custom `iter_move`/`iter_swap` overloads added to iterator adaptors will conflict with the CPOs.

**Comment by CaseyCarter** [comment]
@timsong-cpp Could you please file that as a distinct bug against the TS? It's unrelated to whether CPOs are constexpr references inside an unnamed namespace vs. inline constexpr variables.

**Comment by timsong-cpp** [comment]
@CaseyCarter Actually they are; it's not a problem when they are constexpr references inside an unnamed namespace, since the CPO and the hidden friend functions are members of different namespaces and so don't conflict.

**Comment by CaseyCarter** [comment]
Yes, you are of course correct - I was thinking of a closely related name lookup problem we had with customization points in range-v3. The problem here is that we (WG21) overspecify operators that are intended to be found by ADL by declaring functions that implement those operators, when we should instead be specifying expressions required to be valid and their semantics, leaving the exact implementation to implementors. (See the ongoing "Hiding operator overloads" thread on the Lib-Ext reflector for more discussion.)

We (the Ranges TS) should be specifying e.g. that `ranges::iter_move(i)` where `i` is a constant lvalue `reverse_iterator<I>` is expression-equivalent to `ranges::iter_move(ranges::prev(i.current))` and not bothering to specify how that requirement is implemented.

**Comment by CaseyCarter** [comment]
This issue is resolved in the wording of P0896R1.

**Comment by ericniebler** [comment]
Fixed.
