### ISSUE TITLE
Predicate & Relation concepts

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#44]
I believe the `Predicate` requirement `Convertible<ResultType<F, Args...>, bool>` should in fact be `Boolean<ResultType<F, Args...>>`. If there's a good reason for that specific requirement that I'm missing, then the requirement in `Relation<R, T, U>`:
```
requires (R r, T a, U b) {
  { r(a, b) } -> Boolean;
  { r(b, a) } -> Boolean;
}
```
should be changed to be consistent.

Actually, that requirement in `Relation` needs to be replaced outright with `Predicate<R, T, U> && Predicate<R, U, T>` to not only ensure consistency with the definition of `Predicate`, but to properly require `R` to be regular when applied to `T` and `U`.

**Comment by ericniebler** [comment]
Fixed
