### ISSUE TITLE
noexcept clause of reverse_iterator's iter_move and iter_swap are inconsistent with the Effects clause

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#457]
Issue #443 states the following for `reverse_iterator`'s `iter_move`:

```diff
+\begin{itemdescr}
+\pnum
+\effects Equivalent to: \tcode{return ranges::iter_move(prev(i.current));}
+
+\pnum
+\remarks The expression in \tcode{noexcept} is equivalent to:
+\begin{codeblock}
+   noexcept(ranges::iter_move(declval<I&>())) && noexcept(--declval<I&>()) &&
+     is_nothrow_copy_constructible<I>::value
```

But If we're really permitting this to be implemented in terms of `prev`, then the `noexcept` is wrong. It should be testing `ranges::iter_move(declval<I>())` (rvalue, not lvalue), and also checking `is_nothrow_move_constructible<I>::value` (for returning from `prev`).

Also, it says the following for `iter_swap`:

```diff
+\begin{itemdescr}
+\pnum
+\effects Equivalent to \tcode{ranges::iter_swap(prev(x.current), prev(y.current))}.
+
+\pnum
+\remarks The expression in \tcode{noexcept} is equivalent to:
+\begin{codeblock}
+  noexcept(ranges::iter_swap(declval<I>(), declval<I>())) && noexcept(--declval<I&>())
```

This `noexcept` expression looks wrong to me. The _Effects:_ clause requires a copy of both `I` and `I2`, and that is not dealt with here. Also, the `iter_swap` expression swaps two `I` rvalues, but the second one should be `I2`.

**Comment by CaseyCarter** [comment]
Reclassifying from IS to TS: this is a bug in the TS itself, as opposed to a problem to be fixed upon integration into the IS.

**Comment by ericniebler** [comment]
Looks fixed in the IS to me.
