### ISSUE TITLE
Normative requirement of swap_ranges is superfluous

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#458]
[alg.swap]/p2 says (in part):
> `*(first1 + n)` shall be swappable with (REF) `*(first2 + n)`

I think that's covered by the algorithm constraints, which require `IndirectlySwappable<I1, I2>`.

**Comment by CaseyCarter** [comment]
Reclassifying this as a bug in the TS, as opposed to an integration problem with the IS.

**Comment by CaseyCarter** [comment]
The PR is incorporated into P0896R2.
