### ISSUE TITLE
Even more constexpr

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#478]
P0579R1 "`constexpr` for `<experimental/ranges/iterator>`" sprinkled `constexpr` specifiers throughout the header, including the non-member function overloads that accept `move_sentinel`, but not the *member* functions of `move_sentinel`. This was purely an oversight.

Proposed Resolution
-----------------------
Modify the synopsis of class `move_sentinel` in [move.sentinel]/2 as follows:
```diff
 template <Semiregular S>
 class move_sentinel {
 public:
   constexpr move_sentinel();
-  explicit move_sentinel(S s);
+  explicit constexpr move_sentinel(S s);
-  move_sentinel(const move_sentinel<ConvertibleTo<S>>& s);
+  constexpr move_sentinel(const move_sentinel<ConvertibleTo<S>>& s);
-  move_sentinel& operator=(const move_sentinel<ConvertibleTo<S>>& s);
+  constexpr move_sentinel& operator=(const move_sentinel<ConvertibleTo<S>>& s);

-  S base() const;
+  constexpr S base() const;

 private:
   S last; // exposition only
 };
```
Change the declarations of the member functions in their detailed specifications to agree.

**Comment by CaseyCarter** [comment]
This PR is incorporated into P0896R1.

**Comment by ericniebler** [comment]
Fixed.
