### ISSUE TITLE
range-and-a-half equal in A.2 is broken

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#479]
Thanks to a typo in the PR for #261, equal is specified to return `first1 == mismatch(first1, last1, /* ... */).in1()`, which is `true` only if the two sequences differ at the first position, instead of `last1 == mismatch(first1, last1, /* ... */).in1()`, which is `true` when the two sequences are equal.

Proposed Resolution
-----------------------
Modify [dep.algo.range-and-a-half]/4 as follows:

```diff
 4 Effects: Equivalent to: return
-first1
+last1
  == mismatch(first1, last1, std::forward<I2>(first2_), comp, proj1, proj2).in1();
```

**Comment by ericniebler** [comment]
Should we be filing bugs with lwg-chair now that the TS is final?

**Comment by CaseyCarter** [comment]
> Should we be filing bugs with lwg-chair now that the TS is final?

I haven't received any instruction to do so; my intent is to continue maintaining the issues list here. We *should* probably stop hand-prioritizing bugs without LWG input, though.

**Comment by CaseyCarter** [comment]
This is sort-of fixed in P0896: it does not propose the range-and-a-half algorithms for standardization.

**Comment by ericniebler** [comment]
Fixed, closing.
