### ISSUE TITLE
Move everything out of namespace std and into some new namespace (TBD) for the TS

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#49]

**Comment by ericniebler** [comment]
Decisions need to be made about what stays in namespace `std` and what gets forked. Type traits like `common_type`? Probably stays put. Iterator tags? Undecided. The algorithms should be forked, obviously. Others?

**Comment by ericniebler** [comment]
Following the example of the Library Fundamentals TSs, I'm going with `std::experimental::ranges_v1` for now.

**Comment by asutton** [comment]
I'd lose the v1 and use a feature test macro to indicate the version. Grab
a fresh copy of the concepts TS a  copy the wording out of the intro. It's
the recommended wording by sg10.

**Comment by ericniebler** [comment]
@asutton, you refer to [this](https://github.com/cplusplus/concepts-ts/blob/master/src/intro.tex#L102)? I don't see much there that would help me here. Version'ing library components brings problems that core language changes don't have to solve, like side-by-side delivery of version'ed library components. I'll stick with what I've got, since that seems to be how LWG is doing things these days.

**Comment by asutton** [comment]
>
> @asutton <https://github.com/asutton>, you refer to this
> <https://github.com/cplusplus/concepts-ts/blob/master/src/intro.tex#L102>?
> I don't see much there that would help me here. Version'ing library
> components brings problems that core language changes don't have to solve,
> like side-by-side delivery of version'ed library components. I'll stick
> with what I've got, since that seems to be how LWG is doing things these
> days.
>
> I am. Don't inline namespaces help with that? I thought that was their
purpose.

**Comment by ericniebler** [comment]
It is and I expect ultimately we'll be using inline namespaces. But not for
a TS. We'll just have a regular namespace and if people want the new stuff
they have to ask for it. We can't make experimental stuff look like it's in
namespace std.

**Comment by asutton** [comment]
This is actually a really good question for L[E]WG. What do they expect for
libraries that may go thru multiple revisions in a TS?


Andrew Sutton

**Comment by ericniebler** [comment]
Oh, you meant a versioning inline namespace within `std::experimental::range`? That is a possibility, but I don't expect we'll try to support previous versions as components evolve. It's Just A TS(tm).

I'll raise the issue in the next telecon.
