### ISSUE TITLE
[rand.req.urng] has redundant comment and namespace wrapping

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#492]
It starts with
```c++
// defined in <experimental/ranges/random>

namespace std { namespace experimental { namespace ranges { inline namespace v1 {
```
Given the synopsis immediately above, I don't see the value of this duplication.

**Comment by CaseyCarter** [comment]
I'm tempted to suggest that this is future-proofing: when more content is added to the Clause [rand.req.urng] could move further from the synopsis, and the back-link has more value. That said, we don't do this elsewhere else in the TS where it might actually be useful. For consistency I think it should be removed:

```diff
-// defined in <experimental/ranges/random>
-
-namespace std { namespace experimental { namespace ranges { inline namespace v1 {
   template <class G>
   concept bool UniformRandomNumberGenerator =
     Invocable<G&> &&
     UnsignedIntegral<result_of_t<G&()>> &&
     requires {
        { G::min() } -> Same<result_of_t<G&()>>&&;
        { G::max() } -> Same<result_of_t<G&()>>&&;
     };
-}}}}
```
