### ISSUE TITLE
Common<nonmovable,nonmovable>

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#50]
Intuitively, `Foo<T>()` should imply `Foo<T, T>()` for `Foo` in `{ EqualityComparable, TotallyOrdered, Swappable, Relation<R> }`. `EqualityComparable<T>()` for example, tells me I can compare a `T` with a `T`, and my expectation is that `EqualityComparable<T, T>()` has the same meaning. However, for a non-movable type `T`, `Common<T, T>()` is `false` despite the fact that `CommonType<T,T>` is `T` since `T` cannot be explicitly converted to `T`.

It would seem that `Same<T, U>` should subsume `Common<T, U>` to avoid this problem. However, we then lose the guarantee that `Common<T, U>()` implies both `CommonType<T, U>(t)` and `CommonType<T, U>(u)` are syntactically valid - the cross-type concept definitions are broken completely.

I see two reasonable alternatives to address this problem:
* Ignore it and declare that non-movable types are pathological,
* Reformulate cross-type concepts to not require `Common<T, U>` when `Same<T, U>`, E.g.
```
template <class T, class U>
concept bool EqualityComparable() {
  return EqualityComparable<T>() &&
    (Same<T, U>() ||
      (/* current definition of EqualityComparable<T, U>
         without EqualityComparable<T>() requirement */));
}
```
* Reformulate the cross-type concepts, but additionally `Same<T, U>` subsumes `Common<T, U>`:
```
template <class T, class  U>
concept bool Common() {
  return Same<T, U>() || (/* current definition of Common */);
}
```
  Concepts that depend on `Common<T,U>` can't rely on the conversion syntax when `Same<T, U>` holds, so future cross-type concepts can't inadvertently introduce similar incompatibilities with their single-type variants. They must address the issue directly.

**Comment by ericniebler** [comment]
Good issue! I find one of the best things about my common_type
implementation is that it works with pathological cases like this. I didn't
think that the Common concept was dropping the ball. I'll give it thought.

**Comment by CaseyCarter** [comment]
As additional food for thought, N3351 says (§3.2.1):
> As a relation on types, the `Common` concept is both reflexive (`Common<T, T>`) is true) and
symmetric (`Common<T, U>` is the same as `Common<U, T>`).

So the authors apparently prefer the third solution variant ;)

We should also explicitly require that user specializations of `common_type` maintain those invariants by forbidding specializations of `common_type<T,T>` whose member `type` is not `T` (should probably be ill-formed NDR so that we don't have to instantiate it to check). We explicitly require symmetry now in `Common`, but that could also be declared ill-formed NDR to save an instantiation.

**Comment by ericniebler** [comment]
I can (and should) write a whole paper on `common_type`. If you read my blog posts about proxy iterators[*], you know how important this is, and how insufficient `std::common_type` is today.

[*]: Especially [this one](http://ericniebler.com/2015/02/13/iterators-plus-plus-part-2/)

**Comment by CaseyCarter** [comment]
Seems like I read that years ago - I can't believe it was actually February. I've been meaning to read over the series again ever since you added the `Common` requirement to `Swappable<T, U>`, which doesn't feel precisely right to me. `common_type<int&,double&>` is `double`, `Common<int&,double&>()` is true, so `Swappable<int&,double&>()` would (hypothetically) be true if someone were to add appropriate overloads of `swap` to the `std` namespace. This conflicts with the intuitive notion that  `swap` transposes the values of the inputs because such a `swap` would not be invertible.

Mind you, I haven't yet figured how to to specify those semantics. But eventually I'll come up with wording to require that "after `swap(a, b), swap(a, b)` the values of `a` and `b` are unchanged."

**Comment by ericniebler** [comment]
Making `Swappable` require `Common` isn't quite right, but it's better than the *zilch* that was there before. Really, just about the only sort of heterogeneous swap we'd like to permit (IMO) is something like swapping an `int &` with a `reference_wrapper<int>`. In other words, it's the proxy reference problem again. It would be really, really great to have a solution for this. Maybe my suggested `common_reference` trait could be used here. Sean's suggested language fix feels right-er in this case.

**Comment by CaseyCarter** [comment]
> Really, just about the only sort of heterogeneous swap we'd like to permit (IMO) is something like swapping an int & with a reference_wrapper<int>.

Using the terminology of EoP, I think the proper requirement for swap to be sound is that the two types represent the same species. This is vacuously true when the two types are the same. It's true of `int&` and `reference_wrapper<int>`,  and `bool&` and `vector<bool>::reference`. It's also true for types that differ by more than being "different kind of reference to the same thing" like references to `struct point { int x,y,z; }` and `using coords = int[3]`, or `struct { int a, b; }` and `pair<int, int>` and `tuple<int, int> and int[2] and std::array<int, 2>` which are all different ways to spell "ordered pair of int".

This even allows swapping a range of integers with a range of rounded doubles - since rounded doubles and integers have the same species - if someone were to write the appropriate overload. Not that I would recommend we put such a thing in the standard, the potential to misuse swap(int&, double&) is too high for my taste.

> Types U and T are Swappable if after evaluating swap(t, u), t denotes the entity that u denoted before, and u denotes the entity that t denoted before. [ Note: this necessarily requires that values of U and T have the same species. ]

Of course that means we would have to define "species" and "entity" which already is a term of art in the Standard.

**Comment by ericniebler** [comment]
Regarding the original issue, what do you think of the solution chosen by range-v3? It defines a `CommonReference` concept in terms of a new `common_reference` type trait, and it changes `Common` to be more or less:

```c++
template <class T, class U>
concept bool Common() {
  return Same<remove_cv_t<remove_reference_t<T>>,
              remove_cv_t<remove_reference_t<U>>> ||
    CommonReference<const T&, const U&> &&
    requires {
        typename CommonType<T, U>;
        requires CommonReference<
          CommonType<T, U> &,
          CommonReferenceType<const T&, const U&>>;
    };
}
```

The problem I see with this is that `Common` doesn't seem to model anything useful beyond what `CommonReference` does. And from the POV of equational reasoning, it doesn't seem to me to require anything more than the ability to bind or explicitly convert a `t` or a `u` to a common reference type `R` (allowing for the fact that `R` may not in fact be a reference at all).

I'm toying with the idea of respecifying `Common` to use `common_reference` in its implementation, rather than `common_type`. I wonder what breaks when `CommonType<T,U>` returns a reference.

(Disclaimer: I'm tired and haven't thought very hard about this.)

**Comment by ericniebler** [comment]
This issue is fixed by the Proxy Iterators extension, which is set to be merged into the Ranges TS in the new year. Closing it out.
