### ISSUE TITLE
Consider allowing single-access InputIterators

### ISSUE THREAD

**Issue by NicolBolas** [ericniebler/stl2#500]
InputIterators are a good model for most input scenarios. But they have one issue: you can access the value at the same position more than once.

If the iterator has backing store for its data, that's fine; the iterator just returns a (possibly `const`) reference to the value. And if the data is being manufactured out of whole cloth (like a counting-range iterator), that's also fine; the iterator just returns a value.

The problem comes when the iterator is creating data from some other InputIterator. Consider an `istream_iterator<T>`. The iterator reads a `T` from the `istream`. There is no backing storage for that `T`. And since `istream` is (conceptually, at least) an InputRange, you can't just back up and read the data from the stream again.

Because of this, `istream_iterator<T>` has no choice but to hold an actual `T` object within itself. That way, its `operator*` can return a reference to the `T` which has been read; if no `T` has been read yet, then it reads it from the stream.

This imposes overhead on `istream_iterator<T>` and similar iterators, in that it must hold (at least) an object of type `T`. This overhead would not be necessary if InputIterator was not explicitly required to allow multiple accesses of the current object.

**Comment by CaseyCarter** [comment]
In the past, we've argued to relax requirements on the basis that the operations were unnecessary and/or dangerous (I.e., op == and post-increment for input iterators). It was easy to argue the operations were extraneous because algorithms did not use them. This is not the case for repeated read. 

Do you have any motivation other than to eliminate the need for buffering? Note that buffering is less significant for input ranges than for input iterators - the range provides a convenient location for a buffer, helping to keep iterators small.

**Comment by NicolBolas** [comment]
> Do you have any motivation other than to eliminate the need for buffering? Note that buffering is less significant for input ranges than for input iterators - the range provides a convenient location for a buffer, helping to keep iterators small.

This keeps the iterator small, but the range itself still needs the overhead of a `T`. The motivating example that led to this concern was line-based reading from a file. So you'd have some `line_range` that takes a stream.

In a single-access world, `line_range` would only store a stream reference. As a multi-access InputRange, it has to store a full `string` as well. Also, the range has to store information about when a new line has been read, so that it can know to return the existing object or to read from the stream, then return the object.

While this may seem fairly trivial in terms of overhead, consider the intersection of "coroutine" generators and ranges. If someone has a coroutine-based generator function, it might be very useful to build an InputRange out of that. The problem is that this now requires lots of overhead.

The coroutine has its own overhead: the promise object which stores a return value object. The generator coroutine, on each resume, will yield a new value, which gets stored and a copy/move is returned to the caller. A generator InputRange adaptor would have to store a _copy_ of that return value object, so that it can return a reference to it, just in case the user wants to get the same value without incrementing the iterator.

So now, we have two instances of `T`: one in the coroutine's promise object and one in the InputRange. This seems like entirely unnecessary overhead, especially if most uses of such things will look like this:

    for(auto val: generator_range(some_coroutine)) {...}

**Comment by ericniebler** [comment]
> In a single-access world, `line_range` would only store a stream reference.

That's not a good design. A better design is for `line_range` to store a `string` and read a line into the string at each iteration. After a few iterations, the string will have enough capacity to no longer require _any_ allocations. Dereferencing the iterator will return a `const` reference to the string stored in the range. For more information, see http://ericniebler.com/2013/10/13/out-parameters-vs-move-semantics/.

> The coroutine has its own overhead: the promise object which stores a return value object. The generator coroutine, on each resume, will yield a new value, which gets stored and a copy/move is returned to the caller.

Not necessary. The generator can yield a reference to the value stored in the promise, like with `lines_range`.

**Comment by NicolBolas** [comment]
> That's not a good design. [...]

That's a really good point. Reading into the same object will require fewer allocations than reading into new objects.

> The generator can yield a reference to the value stored in the promise, like with lines_range.

Can the coroutine TS actually do that?

**Comment by CaseyCarter** [comment]
To make it clear that this discussion isn't purely theoretical:

* [range-v3's getlines range](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/getlines.hpp#L29)

* [range-v3's coroutine generator](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/experimental/utility/generator.hpp) which actually "does that."
