### ISSUE TITLE
Requirements of begin and end on a value-initialized View

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#501]
The `View` concept places no semantic requirements on the result of calling `begin` or `end` on a value-initialized view. However, for ForwardIterators, we require that value-initialized iterators compare equal. It seems reasonable to require that for a value-initialized forward view, `begin` and `end` are well-defined and compare equal.

Note: this would make cmcstl2's `ref_view` non-conforming.

**Comment by CaseyCarter** [comment]
> Note: this would make cmcstl2's ref_view non-conforming.

and [`view::c_str`](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/view/c_str.hpp), as any view with a sentinel whose predicate depends on the value of the element denoted by iterators to which it is compared.

**Comment by ericniebler** [comment]
This issue is garbage. Closing.
