### ISSUE TITLE
RandomAccessIterator needs constraints relating the comparison ops to the difference op

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#502]
If `(a - b) > 0`, then `b < a`. Etc.

### Proposed Resolution
Modify [iterators.random.access] as follows:
```diff
  2       Let a and b be valid iterators of type I such that b is reachable from a. Let n be the
          smallest value of type difference_type_t<I> such that after n applications of ++a, then
          bool(a == b). RandomAccessIterator<I> is satisfied only if:
 
 [...]

 (2.10) — (b - n) is equal to (b -= n).
 (2.11) — If b is dereferenceable, then a[n] is valid and is equal to *b.
+(2.??) — bool(a <= b)
```

**Comment by ericniebler** [comment]
First thought, best thought. The following should be added to the itemized list in [iterators.random.access] (in which `b` is reachable from `a` in `n` steps):

> `a < b || (n == 0 && a == b)`.

**Comment by CaseyCarter** [comment]
If the types of `x` and `y` satisfy `SizedSentinel` - which is the case for two random access iterators of the same type - then it's easy to show that `x == y`, `x - y == 0`, and `y - x == 0` are all equivalent. Consequently `a < b || (n == 0 && a == b)` is equivalent to `a < b || a == b`. From the definition of `StrictTotallyOrdered`, `a < b || a == b` is equivalent to `a <= b`.

It suffices to add `a <= b` as a semantic requirement to `RandomAccessIterator`. See PR in the first post.

**Comment by CaseyCarter** [comment]
The PR for this issue has been incorporated into P0896R1.

**Comment by ericniebler** [comment]
Fixed.
