### ISSUE TITLE
[meta.trans.other] Simplifying the specification of common_reference and common_type

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#506]
`common_reference` and `common_type` both uses `COMMON_REF`, but:

- `common_type` only uses it with decayed types, so it can only ever use the last bullet.
- `common_reference` only uses it on reference types, and only if the result is also a reference type, hence the last bullet, which always returns a decayed, non-reference type, is useless to it.

It would probably be cleaner to split the last bullet into its own macro, or even inline it directly into the only place it is used in `common_type`'s specification.

If we do that, then `COMMON_REF` is only used by `common_reference`, and only when the result is a reference type. Thus, if the result would not be a reference type, we might as well just make `COMMON_REF` fail. If we tweak the first bullet to fail if the result of `COND_RES` is not a reference, then we can simplify `RREF_RES` by removing the conditional, and easily inline it at its single use site if desired. 

[This](http://en.cppreference.com/w/cpp/experimental/ranges/type_traits/common_reference) basically sketches what I have in mind. My "simple common reference type" is `COMMON_REF`.

**Comment by CaseyCarter** [comment]
This PR was incorporated into P0898R0, which was moved into the C++20 WP as P0898R3 by LWG motion 28 in Rapperswil.
