### ISSUE TITLE
unreachable's comparison ops should require WeaklyIncrementable, not Iterator

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#507]
There's nothing Iterator-ish about `unreachable`. It can easily be generalized so that it is useful, e.g., in `view::iota`.

Proposed Resolution
------------------
In [unreachable.sentinel], make the following changes:

```diff
-template <Iterator I>
+template <WeaklyIncrementable I>
   constexpr bool operator==(const I&, unreachable) noexcept;
-template <Iterator I>
+template <WeaklyIncrementable I>
   constexpr bool operator==(unreachable, const I&) noexcept;
-template <Iterator I>
+template <WeaklyIncrementable I>
   constexpr bool operator!=(const I&, unreachable) noexcept;
-template <Iterator I>
+template <WeaklyIncrementable I>
   constexpr bool operator!=(unreachable, const I&) noexcept;
```

Make the same change in [unreachable.sentinel.ops] and [iterator.synopsis].

**Comment by CaseyCarter** [comment]
Why `WeaklyIncrementable`? Why not everything?
```c++
constexpr bool operator==(unreachable, unreachable) noexcept {
  return true;
}
template<class T>
  constexpr bool operator==(const T&, unreachable) noexcept {
    return false;
  }
/* ... */
```
If we can compare `nullopt_t` for equality with an `optional<T>` for any type `T`, I don't see why we cannot do the same for `unreachable`.

**Comment by timsong-cpp** [comment]
What happens if you compare an `optional<unreachable>` with an `unreachable`?

**Comment by ericniebler** [comment]
Reachability is fundamentally about a successor function. If it can be compared to anything, then `unreachable`  is the wrong name.

**Comment by ericniebler** [comment]
Another consideration, sling the lines of what @timsong-cpp is getting at. If `unbounded` is comparable to anything, then it is comparable to itself, and it reports that it is not equal to itself. Looking at `EqualityComparable` that doesn't seem to violate the letter of the concept but it does IMO violate the spirit. I don't like it when equal things compare unequal. (`EqualityComparable` should require that things compare equal to themselves, IMO.)

**Comment by CaseyCarter** [comment]
This PR was integrated into P1037R0.

**Comment by CaseyCarter** [comment]
Resolved by incorporation of P0896R4 into the C++ Working Draft in San Diego.
