### ISSUE TITLE
Do value-initialized forward iterator/sentinel pairs compare equal?

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#508]
In [iterators.forward], we require that value-initialized forward iterators compare equal to other value-initialized iterators of the same type. Do we want to say anything about iterator/sentinel pairs? What could we say?

**Comment by CaseyCarter** [comment]
```c++
template<class T>
struct delimiter_sentinel {
  T delimiter_;

  template<InputIterator I>
  requires EqualityComparable<value_type_t<I>, T>
  friend bool operator==(I i, delimiter_sentinel s) {
    return *i == s.delimiter_;
  }
  /* ... */
};

using I = char const*;

struct c_string_view {
  char const* ptr_;

  char const* begin() const { return ptr_; }
  delimiter_sentinel<char> end() const { return {}; }
};
```

Both `ranges::empty(c_string_view{})` and `I{} == delimiter_sentinel<char>{}` have undefined behavior. Should `char const*` / `delimiter_sentinel<char>` / `c_string_view` be a valid iterator / sentinel / view?
