### ISSUE TITLE
ranges::common_type_t<T> doesn't match C++17 std::common_type_t<T>

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#510]
The former is `std::decay_t<T>`, the latter `std::common_type_t<T, T>`. This is different if there's a user specialization for the latter case, or if `T` is an abominable function type.

**Comment by ericniebler** [comment]
Do we really want to allow people to override the common type of `T` and `T`? When is that ever a good thing?

**Comment by timsong-cpp** [comment]
For `T = duration<int, ratio<10,10>>`, `common_type_t<T, T>` is `duration<int, ratio<1,1>>`.

**Comment by CaseyCarter** [comment]
This is fixed in the `common_type` integration in P0898R3, moved into the C++20 WP by LWG motion 28 in Rapperswil.
