### ISSUE TITLE
rename `iterator_range` to `subrange`?

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#511]
Another possibility is to add an extra (Boolean) template parameter to make `subrange` mean "sized". Then we could write some deduction guides to make it possible for users to just say `subrange{rng}` and get a sized subrange if `rng` satisfies `SizedRange`, or a regular subrange otherwise.

E.g.:

```c++
template <Iterator I, Sentinel<I> S = I, bool Sized = SizedSentinel<S, I>>
struct subrange {
....
};

template <Iterator I, Sentinel<I> S>
struct subrange<I, S, true> {
   ...
    auto size() const { ... }
};

template <Range R>
subrange(R&) -> subrange<iterator_t<R>, sentinel_t<R>>;

template <SizedRange R>
subrange(R&) -> subrange<iterator_t<R>, sentinel_t<R>, true>;
```

**Comment by CaseyCarter** [comment]
```c++
template <SizedRange R>
subrange(R&) -> subrange<iterator_t<R>, sentinel_t<R>, true>;
```
`SizedRange R` does not imply `SizedSentinel<sentinel_t<R>, iterator_t<R>>`, despite that the reverse is true.

**Comment by ericniebler** [comment]
I never said it does. What is your point?

**Comment by CaseyCarter** [comment]
> I never said it does. What is your point?

You constrained the subrange specialization with `SizedSentinel<S, I>`, and the deduction guide selects it for `SizedRange`s. Instantiation presumably will fail when `SizedRange` holds and `SizedSentinel` does not.

**Comment by timsong-cpp** [comment]
That's not a constraint. It's just a default template argument.

**Comment by CaseyCarter** [comment]
> Instantiation presumably will fail when SizedRange holds and SizedSentinel does not.

There's the fallacy in my argument. The specialization presumably constrains its constructors:
```c++
template<SizedRange R>
subrange(R&);
template<class I, SizedSentinel<I> s>
subrange(I, S);
```
And all is well, modulo slight potential for confusion that `subrange{r}` and `subrange{begin(r), end(r)}` may have different types.

**Comment by ericniebler** [comment]
I can't precisely remember if concepts are now usable wherever a constant expression is allowed. If not, replace `bool Sized = SizedSentinel<S, I>` with `bool Sized = models::SizedSentinel<S, I>` for an appropriately defined `bool` variable template `SizedSentinel`.

**Comment by CaseyCarter** [comment]
I consider this issue effectively closed by [P0789R1](https://wg21.link/p0789r1) which includes both the rename from `iterator_range` to `subrange` and a third template parameter indicating sized-ness.

**Comment by CaseyCarter** [comment]
> I can't precisely remember if concepts are now usable wherever a constant expression is allowed.

http://eel.is/c++draft/expr.prim.id#3:

> An *id-expression* that denotes the specialization of a concept ([temp.concept]) results in a prvalue of type `bool`. The expression is `true` if the concept's normalized *constraint-expression* is satisfied ([temp.constr.constr]) by the specified template arguments and `false` otherwise.
