### ISSUE TITLE
iterator_range is not usable with safe_iterator

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#512]
Since `iterator_range<I, S>` requires `Iterator<I>` and `Sentinel<S, I>`, it cannot be used as the return type of the range-based overloads of the algorithms. Those return pairs of `dangling<iterator_t<Rng>>`, which doesn't model the concept.

Arguably, any `iterator_range` we design should be usable as the algorithm's return type. (I could argue the other way, too.)

**Comment by CaseyCarter** [comment]
The "obvious" solution: return a `dangling<subrange>`.

**Comment by ericniebler** [comment]
That's slightly inconsistent with the other algorithms, which return tagged pairs and tuples of `safe_iterator`s.

**Comment by CaseyCarter** [comment]
I propose that's not an inconsistency so much as a reflection of the differing underlying semantics. 

Algorithm `foo` nominally returns an iterator `I`; if the iterator may be invalidated, it returns `dangling<I>`. If `foo` has multiple return values, we apply this rule to each of them individually and return a `tagged_tuple` with pretty names.

Algorithm `bar` nominally returns a range `R`; if the range may be invalidated, it returns `dangling<R>`. If `bar` has multiple return values, ...

The fundamental distinction here is that all of our range-returning algorithms only return a single range. If we had an algorithm that returned a range and an `int`, its return type would be something like `tagged_pair<tag::range(safe_range_t<R>), tag::n(int)>`.

**Comment by CaseyCarter** [comment]
LEWG has chosen to kill `dangling` for C++20. Calls that previously would have returned a specialization of `dangling` will instead be ill-formed.
