### ISSUE TITLE
The range-returning algorithms should return subrange

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#526]
* `equal_range`
* `rotate`
and potentially `find_end`, `search` and `search_n` if #180 is accepted.

For the range-accepting overloads, this would be simplified by defining a `safe_subrange_t` alias in the same vein as `safe_iterator_t` (See #512):
```c++
template<Range R>
using safe_subrange_t = conditional_t<
  is_lvalue_reference_v<R>,
  subrange<iterator_t<R>>,
  dangling<subrange<iterator_t<R>>>;
```

**Comment by CaseyCarter** [comment]
The PR for this issue has been incorporated into P0896R2.

**Comment by ericniebler** [comment]
I'm loving that you're closing out so many of our old issues as "fixed". 😊

**Comment by CaseyCarter** [comment]
We *really* need to make a full audit of the issues and reprioritize for C++20. (LEWG did us a favor killing `tagged` - that was half a dozen issues in one swipe.)

**Comment by CaseyCarter** [comment]
Resolved by incorporation of P0896R4 into the C++ Working Draft in San Diego.
