### ISSUE TITLE
DefaultConstructible and explicit default constructors

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#529]
`CopyConstructible` and `MoveConstructible` both require implicit construction since the Standard Library considers `explicit` copy/move constructors to be pathological. [`DefaultConstructible` currently admits types with `explicit` default constructors](https://godbolt.org/g/kvM81a):
```c++
#include <type_traits>
#include <experimental/ranges/concepts>

namespace ranges = std::experimental::ranges;

struct S { explicit S() = default; };

int main() {
    // All fine
    { S s; }
    { S s{}; }
    S{};
    S();
    static_assert(std::is_constructible_v<S>);
    static_assert(std::is_default_constructible_v<S>);
    static_assert(ranges::DefaultConstructible<S>);
    // ill-formed
    []() -> S { return {}; };
}
```
`explicit` default constructors are useful for tag types, but not much else. I'm inclined to call them pathological and add a requirement to `DefaultConstructible` to forbid them.

**Comment by timsong-cpp** [comment]
I'd say that the vast majority of explicit default constructors are of the `explicit Foo(Bar = ...);` category, including 30+ in the standard library that probably should be fixed (I tried to do it via an issue, but Daniel & Marshall wanted a paper...which I haven't gotten time to write yet). These may be arguably pathological but are also likely widespread.

**Comment by CaseyCarter** [comment]
This is [LWG 3149](https://wg21.link/lwg3149).
