### ISSUE TITLE
View<T>'s enable_view check ignores accessibility

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#530]
> If `enable_view<T>` has a member type `type`, `enable_view<T>::type::value`;

This branch is taken (and presumably causes an error) if there's a private member type named `type`, but not if there is a private data member with that name. Is that intended or do we want the usual "if the qualified-id `enable_view<T>::type` is valid and denotes a type" wording?

### Proposed Resolution
Modify [range.view] as follows:
```diff
 For a type T, the value of view-predicate<T> shall be:
 (4.1) — If 
+the qualified-id
 enable_view<T>
+::type
-has a member type type,
+is valid and denotes a type ([temp.deduct]),
 enable_view<T>::type::value;
 (4.2) — Otherwise, if 
+DerivedFrom<
 T
+, view_base>
 is
+true,
-derived from view_base,
 true;
```

**Comment by timsong-cpp** [comment]
Don't forget to cross-reference [temp.deduct].

**Comment by ericniebler** [comment]
Fixed.
