### ISSUE TITLE
Concept ConvertibleTo has wrong parameter names

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#533]
The TS definition of concept `ConvertibleTo`:

```c++
template <class T, class U>
concept bool ConvertibleTo =
  is_convertible<From, To>::value && // see below
  requires(From (&f)()) {
    static_cast<To>(f());
  };
```

declares the template parameters `T` and `U` but refers to them in the body as `From` and `To`, respectively.

### Proposed Resolution
Change the definition of the concept in [concepts.lib.corelang.convertibleto] as follows:
```diff
-template <class T, class U>
+template <class From, class To>
 concept bool ConvertibleTo =
   is_convertible<From, To>::value && // see below
   requires(From (&f)()) {
     static_cast<To>(f());
   };
```

**Comment by timsong-cpp** [comment]
This looks like editorial: the resolution of #167 in P0740R0 was misapplied.

(Oddly enough, I got it right in cppreference. Was I writing straight from P0740?)

**Comment by CaseyCarter** [comment]
The PR for this issue was incorporated in P0898R0, and moved into the C++20 WP as part of P0898R3 in Rapperswil.
