### ISSUE TITLE
`Swappable` issues

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#534]
FIrst, we have "let `t` denote an expression of type `T`", which doesn't work if `T` has reference type, as it usually does. I think we want the usual "`decltype((t))` is `T`"

Second, we don't seem to have any requirement on `Swappable` (as opposed to _swappable_), only `SwappableWith`.

**Comment by CaseyCarter** [comment]
This issue was resolved by the reformulation of `Swappable` and `SwappableWith` in terms of `std::ranges::swap` with its attendant semantic requirements in P0896R4.
