### ISSUE TITLE
tagged::swap has problematic exception specification

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#535]
In `noexcept(swap(declval<Base&>(), declval<Base&>()))`, unqualified lookup for `swap` will find the member function (this is part of the motivation for `is_nothrow_swappable`).

We should either use the trait or qualify the swap. And perhaps make clear that we are calling `ranges::swap` instead of just `swap` in the rest of the text.

**Comment by CaseyCarter** [comment]
Although I think that [[intro.namespaces]/5](https://timsong-cpp.github.io/cppwp/ranges-ts/intro.namespaces#5) *just barely* makes that `swap` be `std:experimental::ranges::swap`, I agree the usage is bad and it should be fixed editorially.

**Comment by CaseyCarter** [comment]
LEWG has killed `tagged` for C++20 (and the TS won't be maintained after merging to IS) so I'm closing this as NAD.
