### ISSUE TITLE
XREF is underspecified

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#538]
[[meta.trans.other]/1](https://timsong-cpp.github.io/cppwp/ranges-ts/meta.trans.other#1) defines 
the "specification macro" `XREF(A)`:

> ... Let `XREF(A)` denote a unary template `T` such that `T<UNCVREF(A)>` denotes the same type as `A`. ...

Given:
```c++
template<class A> struct derp {
  template <class> using T = A;
};
```
`derp<A>::template T` meets the requirements for `XREF(A)` (`derp<A>::template T<A>` denotes the same type as `A`), but is insufficient for the uses to which `XREF` is put in specializations of `basic_common_reference` in the Ranges implementations (range-v3 and cmcstl2). Indeed, if the only purpose of `XREF(A)` was to provide a facility to "reconstitute" `A` from `remove_cvref_t<A>`, it would be far simpler to simply pass `A` to `basic_common_reference` than go through the `template <class> class TQual` rigmarole.

range-v3 and cmcstl2 implementations of `common_reference` actually implement `XREF(A)` as a unary template that applies the cv and ref-qualifiers from `A`'s type to its type parameter. This design intent was lost somewhere along the way.

### Proposed Resolution
Change [meta.trans.other]/1 as follows:
```diff
 [...]
 Let XREF(A) denote a unary template T such that
-T<UNCVREF(A)> denotes the same type as A.
+T<U> denotes the type U with the addition of A's cv and reference qualifiers, for a type U
+such that is_same<U, UNCVREF(U)>::value is true.
 [...]
```

**Comment by timsong-cpp** [comment]
There's no such thing as "reference qualifier".

**Comment by CaseyCarter** [comment]
The PR for this was incorporated into P0898R0 and moved into the C++20 WP as part of P0898R3 in Rapperswil.
