### ISSUE TITLE
Add class template deduction guides

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#544]
... when merging the Ranges TS to the IS.

**Comment by CaseyCarter** [comment]
...and consider removing `make_foo` functions.

**Comment by cjdb** [comment]
> ...and consider removing `make_foo` functions.

I seem to recall @CaseyCarter and Matt Calabrese explaining why that's not necessarily desirable on Slack, but I can't remember why (and it is forever lost in the archives now).

**Comment by ericniebler** [comment]
Pretty sure this is done now.
