### ISSUE TITLE
Invocable requirement for CPOs is incorrect

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#546]
[customization.point.object]/4 states:

> The type of a customization point object `T` shall satisfy `Invocable<const T, Args...>` (7.6.2) when the
types of `Args...` meet the requirements specified in that customization point object’s definition. Otherwise, `T` shall not have a function call operator that participates in overload resolution.

This requires `const` *rvalue* `T` to have such a function call operator, instead of `const` *lvalue* `T` as intended. The wording should *require* the call operator for lvalue `T`, ideally without forbidding the presence of equivalent call operators for rvalue (or non-`const`, or `volatile, or ...) `T`.

### Proposed Resolution
Modify [customization.point.object]/4 as follows:
```diff
 The type of a customization point object T shall satisfy
-Invocable<const T, Args...>
+Invocable<const T&, Args...>
 (22.6.2) when the types of Args... meet the requirements specified in that customization point
 object’s definition.
-Otherwise,
+When the types of Args... do not meet the customization point object’s requirements,
 T shall not have a function call operator that participates in overload resolution.
```

**Comment by CaseyCarter** [comment]
Note that this PR has already been applied to the CPO wording in D0898R0.

**Comment by timsong-cpp** [comment]
There seems to be another problem here: the type of an object includes its cv-qualification, if any, but for something like the `Semiregular` requirement (and this `Invocable`) presumably we want to remove the cv-qualification.

**Comment by ericniebler** [comment]
I've moved the issue with the `Semiregular`-ness of CPOs to #621. Closing this one.
