### ISSUE TITLE
Merging the Ranges TS

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#553]
- [x] Rethink iterator traits:
  - Play nicely with code that specializes `std::iterator_traits`.
- [x] Rethink iterator tags:
  - Parallel set of tags, like the Ranges TS?
  - One set of tags with a "is-new-style" trait?
  - One set of tags, and no nested `::iterator_category` means "is-new-style" (dispatch with concept-based overloading)?
- [x] Make existing standard iterators and iterator adaptors satisfy the new concepts:
  - Default constructible
  - More?
- [x] ~~Rethink `tagged`:~~
  - ~~Merge functionality with `pair` and `tuple`?~~
  - ~~Simply remove functionality (because structured bindings)?~~
  - ~~Each algorithm returns an unspecified tuple-like type with named accessors?~~
- [x] Customization point redesign (if feasible):
  - [ ] ~~Make namespace-scoped overloads of `swap` hidden friends instead.~~
  - [x] Attempted redesign of `begin`, `end`, et.al. if it doesn't make the world blow up.
- [ ] Make old algorithms work with new iterators and `iter_swap`/`iter_move` (insofar as it's possible)
- [ ] Rethink function objects:
  - Rename `ranges::less` to `std::ordered_less` and remove the others?
  - Keep them as-is?
- [ ] Propose changes to `pair` and `tuple` to make them work as-is with `view::zip`.
- [ ] Investigate possibility of deprecating `move_iterator` and propose `move_into_iterator` (output iterator adaptor).

ATTN @CaseyCarter we have some work to do.

**Comment by CaseyCarter** [comment]
Resolved by P0896R4. Feel free to open a new issue for "Make old algorithms work with new iterators and `iter_swap`/`iter_move` (insofar as it's possible)" or deprecating `move_iterator`.
