### ISSUE TITLE
Decide if we care about copying vs. moving iterators

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#555]
The TS copies iterators all over the place even when a move is safe. For example, the constructors of `dangling` and the iterator adapters all take iterators by value and then copy it to the member.

This came up during discussion of the `uninitialized_meow` paper, which requires the relevant iterator operations to not throw. The range overload may wrap the returned iterator in `dangling`, and  `uninitialized_meow_n` may use `counted_iterator`.

**Comment by CaseyCarter** [comment]
LEWG has chosen to kill `dangling` for C++20. Calls that previously would have returned a specialization of `dangling` will instead be ill-formed. (TLDR: No, we don't care about copying vs. moving iterators.)
