### ISSUE TITLE
[P0898] Hanging paragraph in [concepts.lib.object]

### ISSUE THREAD

**Issue by johelegp** [ericniebler/stl2#567]
https://github.com/ericniebler/stl2/blob/bf5f6d836d844444f843f50bf35c89cf8e16e505/ext/stdconcepts/concepts.tex#L1061 is missing `\rSec2[concepts.lib.object.general]{General}` after it.

**Comment by CaseyCarter** [comment]
I'll eat my hat if this is the only hanging paragraph in the Ranges TS ;)

**Comment by CaseyCarter** [comment]
It does seem to be the only occurrence in P0898, however. Fixed in caseycarter/draft@470488d835dcce56caae80d38e8aa3c8327140c4.
