### ISSUE TITLE
IndirectlySwappable concept only tests that iter_swap is callable with lvalue iterators

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#578]
It should be valid to pass rvalue iterators to `ranges::iter_swap`.

Proposed Resolution
===============

[Change [alg.req.ind.swap] as follows:]{.ednote}

```diff
template<class I1, class I2 = I1>
  concept indirectly_swappable =
    readable<I1> && readable<I2> &&
-  requires(I1& it, I2& i2) {
+  requires(const I1 it, const I2 i2) {
      ranges::iter_swap(i1, i1);
      ranges::iter_swap(i2, i2);
      ranges::iter_swap(i1, i2);
      ranges::iter_swap(i2, i1);
    };
```

**Comment by ericniebler** [comment]
I like the formulation with the implicit expression variants.

> I have a hunch, which I haven't done archaeology to verify, that we got from P0022 to Batavia by realizing that we want to allow `iter_swap` to modify the iterators so it can e.g. exchange values "stashed" in the iterator such as `istream_iterator`s values.

I suspect it was to support `std::optional`-like types, but f*** that. And I don't have huge sympathy for the stashing input iterator scenario. There would be nothing wrong with making the cache mutable. (I'll note that `istream_iterator` isn't going to satisfy `indirectly_swappable` no matter what we do.)

UPDATE: I guess one thing to worry about is whether we care in general about readable iterator types for which `operator*` is not `const`-qualified.

UPDATE 2: After making this change in range-v3, all tests pass.

**Comment by CaseyCarter** [comment]
Resolved by the merge of P1878R1 into the working draft in Belfast.
