### ISSUE TITLE
Fix prose description of ConvertibleTo in light of guaranteed copy elision

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#618]
From http://lists.isocpp.org/lib/2019/02/10129.php :

> Following the addition of guaranteed copy elision, prvalues of a type T can always be implicitly converted to that type. is_convertible_v<T, T> for non-copyable/movable types will, however, be false. The description of ConvertibleTo appears to indicate that is_convertible_v is meant to be a query for implicit convertibility in the core language sense.

... and:

>>>> is_convertible is not that core language sense thing:
>>>> is_convertible_v<void, void> is true.
>>>> As a general matter, the traits don't consider the special cases for
>>>> prvalues C++17 introduced. Changing it now would break lots of stuff,
>>>> starting from our own specifications.
>>>
> > > Is is_convertible_v the wrong thing to use in ConvertibleTo?
> >
> > Presumably we didn't mean for the ConvertibleTo<T, T> part of
> > MoveConstructible to be vacuous, so I think the use of
> > is_convertible_v is fine.
> 
> It seems the prose description of ConvertibleTo does not match its code version.

**Comment by CaseyCarter** [comment]
This is [LWG 3194](https://wg21.link/lwg3194).
