### ISSUE TITLE
Clean up specification of customization point objects

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#619]
From http://lists.isocpp.org/lib/2019/02/10122.php

> > OK, different example: iter_move is not specified to have any such poisoning, so it looks like I'm allowed to define `::iter_move(T*)`, and then `ranges::iter_move` has to use it in preference to the built-in `std::move(*E)` semantics. 
>
> We should clarify the wording to say that it only performs ADL (or  equivalently, that unqualified lookup finds nothing or only a non-viable function). That seems orthogonal to whether we call 
iter_move a "designated customization point". The global namespace is not std or a namespace within namespace std, so I don't see how [namespace.std]/7 would change anything here. 

Thanks to @timsong-cpp

**Comment by CaseyCarter** [comment]
This issue is now [lwg 3247](https://wg21.link/lwg3247).
