### ISSUE TITLE
Why does take_view::[begin|end]() [non-const] require (!simple-view<V>) ?

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#628]
The current draft of `take_view` ([range.take.view]) has:

> ```c++
> constexpr auto begin() requires (!simple-view <V>)
> ```

What is the purpose of the constraint here? It seems unnecessary.

**Comment by cjdb** [comment]
I think @CaseyCarter's reasoning is that it prevents unnecessary instantiations.

**Comment by ericniebler** [comment]
I think this is the answer.
