### ISSUE TITLE
For ranges, require that IteratorType<Rng> is convertible to IteratorType<const Rng>

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#64]

**Comment by CaseyCarter** [comment]
This should probably be:
> If `Range<const T&>() && Range<T&>()`, then `ConvertibleTo<IteratorType<T&>, IteratorType<const T&>>() && ConvertibleTo<SentinelType<T&>, SentinelType<const T&>>()`."

Since `Range<T&>()` does not imply `Range<const T&>()` because we allow mutable-only ranges.

I'll add in that we should require:
> If `Range<T&>() && Range<U>() && Same<T, uncvref_t<U>>()` then `Same<DifferenceType<IteratorType<T&>>, DifferenceType<IteratorType<U>>>()`

i.e., a `Range` has a unique difference type that is insensitive to cv/ref qualification.

**Comment by ericniebler** [comment]
Agree with all that.

**Comment by ericniebler** [comment]
Actually, I'm not sure how to harmonize this with the proposed resolution of #71. If someone asks if "`const T&`" is a `Range`, does that mean we also have to test for `Range<T&>` and additionally test for the convertibility of the iterators? Perhaps not. I'm inclined to leave this well enough alone until I have a stronger reason.

**Comment by ericniebler** [comment]
I don't see a compelling reason why we should disallow `R&` and `R const&` from being unrelated ranges. Closing.
