### ISSUE TITLE
Unsafe views that are actually safe

### ISSUE THREAD

**Issue by JohelEGP** [ericniebler/stl2#640]
Is it okay that `view`s known to be `safe_range`s in principle don't even satisfy it?

Consider http://eel.is/c++draft/range.dangling#2 and https://godbolt.org/z/jGgJng which makes it compilable. Calling `find` with a prvalue `drop_view` whose iterators are not tied to its lifetime returns `dangling` because it doesn't specialize `enable_safe_range`, even thought its base range is a `safe_range`.

This would be solved with an specialization like
```C++
template <class V>
constexpr bool enable_safe_range<drop_view<V>> = enable_safe_range<V>;
```
and similar for `view`s with iterators equal to the base range or known not to have a `parent_` pointer or anything that ties its validity to a particular view object.

**Comment by johelegp** [comment]
I can't find how this worked for `view`s before the application of http://wg21.link/P1870, so I can't be sure whether range-v3 was compliant before. But now that it's opt-in, why not do it?

**Comment by johelegp** [comment]
I don't understand why it still doesn't return `dangling`.

**Comment by johelegp** [comment]
The problem was that range-v3's `views::drop(r, x)` actually returns a `subrange` when `r` is a `random_access_range`.

**Comment by brevzin** [comment]
Here's another example I ran into recently, trying to implement an eager `trim` (didn't realize range-v3 had one at the time):

```cpp
auto trim(std::string const& s) {
    auto isalpha = [](char c) { /* ... */ };
    auto b = ranges::find_if(s, isalpha);
    auto e = ranges::find_if(s | views::reverse, isalpha).base();
    return subrange(b, e);
}
```

The declaration of `b` is fine, but the declaration of `e` is ill-formed because this `find_if` returns `dangling` - because `reverse_view` is never a `safe_range`. But in this example it would be perfectly safe (and, I think, a fairly nice way to implement this).

One way to get this to compile would be:

```cpp
template <class V>
constexpr bool enable_safe_range<reverse_view<V>> = enable_safe_range<V>;
```

**Comment by BRevzin** [comment]
> Note that before the application of http://wg21.link/P1870, this didn't result in `dangling`. So why not opt-in so that it isn't again?

P1870 didn't change this. `drop_view` wasn't a _`forwarding-range`_ before either.

**Comment by johelegp** [comment]
You're right. I'll remove that bit.
