### ISSUE TITLE
Traits that determine when a set of parameters model the syntax of a concept

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#68]
As [Eric recently commented in issue 67](https://github.com/ericniebler/stl2/issues/67#issuecomment-125709312):

> Traits are usable in contexts where concepts are not.

Most notably in my experience unit testing a concept design all but requires a predicate to test if a set of parameters meets the syntactic requirements of a concept. In the Concepts TS, `C<Args...>` isn't usable as a boolean expression in contexts other than a requires expression, so we can't use e.g. `static_assert(ForwardIterator<my_iterator>());` in a unit test.

Unless and until a future revision of the Concepts TS enables usage of concept-names as general boolean expressions, I think STL2 could do its users a favor by providing traits that serve this purpose. In cmcstl2 I've been defining `constexpr bool` functions in a namespace `models` with snake_case names to do so:
```
namespace models {
  template <class>
  constexpr bool forward_iterator() { return false; }
  template <ForwardIterator>
  constexpr bool forward_iterator() { return true; }
}
```
although I think that CamelCase `constexpr bool` variable templates would provide a better user experience, maybe `isForwardIterator<I>` or `models::ForwardIterator<I>`.

Any thoughts on specifying concept predicate traits for the concepts in the ranges proposal, and/or the naming thereof?

**Comment by W-E-Brown** [comment]
> On Jul 28, 2015, at 3:42 PM, Casey Carter <notifications@github.com> wrote:
> 
> As Eric recently commented in issue 67:
> 
> Traits are usable in contexts where concepts are not.
> 
> Most notably in my experience unit testing a concept design all but requires a predicate to test if a set of parameters meets the syntactic requirements of a concept. In the Concepts TS, C<Args...> isn't usable as a boolean expression in contexts other than a requires expression, so we can't use e.g. static_assert(ForwardIterator<my_iterator>()); in a unit test.
> 
> Unless and until a future revision of the Concepts TS enables usage of concept-names as general boolean expressions, I think STL2 could do its users a favor by providing traits that serve this purpose. In cmcstl2 I've been defining constexpr bool functions in a namespace models with snake_case names to do so:
> 
> namespace models {
>   template <class>
>   constexpr bool forward_iterator() { return false; }
>   template <ForwardIterator>
>   constexpr bool forward_iterator() { return true; }
> }
> 
> although I think that CamelCase constexpr bool variable templates would provide a better user experience, maybe isForwardIterator<I> or models::ForwardIterator<I>.
> 
> Any thoughts on standardizing concept predicate traits, and or the naming thereof?

I tried.  See section 4 of my paper N4434.  — WEB

**Comment by CaseyCarter** [comment]
> I tried.  See section 4 of my paper N4434.  — WEB

I have seen it, and I agree. I was there in Lenexa when they tried to mis-attribute the similar US NB comment to you. I think Andrew agrees in principle, his concerns were mostly about implementation requiring a compiler to perform SFINAE in an arbitrary expression context. I hope we'll see a change in the next TS revision, but if not / until that happens it would be very convenient to have predicates for the STL2 concepts.

**Comment by ericniebler** [comment]
I prefer to leave predicates/traits out of the draft for now. I suspect this capability will be added to concepts eventually. Let's wait and see.

**Comment by CaseyCarter** [comment]
>  Let's wait and see.

This happened a while ago - I think in Kona? Closing.
