### ISSUE TITLE
as_function is exposition only

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#73]
Despite `FunctionType` and `Projected` having public names, users cannot utilize callables and projections in user-written algorithms without implementing `as_function` by hand.

**Comment by tomaszkam** [comment]
FWIW, In C++11 we have alternate solution for invoking any callable with given set of arguments: ```std::invoke``, so instead of using ```pf=as_function(f); pf(args...)``` the user-written algorithms can use ```std::invoke(f, args...)```.

**Comment by CaseyCarter** [comment]
> Use `std::invoke` from C++17

Yes, this is an ideal solution for users. The algorithms are even explicitly specified in terms of `INVOKE(...)`.

**Comment by CaseyCarter** [comment]
Just to tie up this issue, b5dc238bfb03aa934d9d1a69e26bdb18381e69d7 adds `invoke` to the TS so users will have no problems writing algorithms that use callables.
