### ISSUE TITLE
[iterator.stdtraits]

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#74]
* The rules for mapping from `C = experimental::ranges_v1::IteratorCategory<In>` to `std::iterator_traits<In>::iterator_category` in para 7 are inconsistent with the mappings specified in [iterator.assoc]/8. Specifically 7.1:
> If `C` is the same as or inherits from `std::input_iterator_tag` or `std::output_iterator_tag`...

  This condition is weird: If `In` satisfies `InputIterator` then `IteratorCategory<In>` must be derived from `::std::experimental::ranges_v1::input_iterator_tag` which does not derive from either `std::input_iterator_tag` or `std::output_iterator_tag`. The only way this condition could be satisfied is if a user defines a custom iterator and specifies its member `iterator_category` to be a type that multiply inherits `ranges_v1::input_iterator_tag` and one of the two specified `std` tags. I think this paragraph can simply be removed.
  
* In 7.2:
> If `experimental::ranges_v1::Reference<In>` is not a reference type, `std::iterator_traits<In>::
iterator_category` is `std::input_iterator_tag`.

  `Reference<In>` here should be `ReferenceType<In>`.

* Due to the mapping from `std` tags to `ranges_v1` tags in [iterator.assoc]/8, the partial specializations specified for `std::iterator_traits` apply to "old" iterators as well as "new" iterators. This presents implementation difficulties since the definitions of the partial specializations must occur before instantiation of any specialization of `std::iterator_traits` to which they apply, or the program is ill-formed. For an implementation of the TS external to the implementation of the standard library, it is impossible to guarantee that ordering of definitions.

  Since the entire point of this section is to provide backwards compatibility by providing specializations of `std::iterator_traits` for "new" iterators, it's possible to both provide that feature and avoid the implementability issue with additional constraints that ensure the specializations only apply to "new" iterators:
  * The partial specialization for (possibly weak) output iterators can be constrained to apply only to iterators with no member `iterator_category` as is the case for STL2 (possibly weak) output iterators.
  * The partial specialization for weak input iterators can be constrained to only apply to iterators whose member `iterator_category` derives from `weak_input_iterator_tag` but not from `input_iterator_tag`. (`!DerivedFrom<..., input_iterator_tag>()` seems to be necessary here to ensure this partial specialization doesn't overlap with the specialization for input iterators.)
  * The partial specialization for input iterators can be constrained to only apply to iterators whose member `iterator_category` derives from `input_iterator_tag`.

**Comment by ericniebler** [comment]
> If `In` satisfies `InputIterator` then `IteratorCategory<In>` must be derived from `::std::experimental::ranges_v1::input_iterator_tag` which does not derive from either `std::input_iterator_tag` or `std::output_iterator_tag`. The only way this condition could be satisfied is if a user defines a custom iterator and specifies its member `iterator_category` to be a type that multiply inherits `ranges_v1::input_iterator_tag` and one of the two specified std tags. I think this paragraph can simply be removed.

I anticipate users will try to define iterators that work with both the old algorithms and the new. And Boost.Iterators plays games with multiply-inheriting iterator tags. In other words, I don't expect this condition to be as weird as you are suggesting. We have to allow for it. Whether the current text correctly captures that subtlety is another thing. I don't have the time to completely think this through right now, but at least now you know what I had in mind when I wrote this.

> Due to the mapping from std tags to `ranges_v1` tags in [iterator.assoc]/8, the partial specializations specified for `std::iterator_traits` apply to "old" iterators as well as "new" iterators. This presents implementation difficulties since the definitions of the partial specializations must occur before instantiation of any specialization of `std::iterator_traits` to which they apply, or the program is ill-formed.

I was aware of this when I wrote it. It certainly requires some help from stdlib vendors to at the least forward-declare the partial specializations under a feature-test macro. I won't believe it's impossible until I hear it from a stdlib vendor. If the forward declarations are present in `<iterator>` when compiling as `defined(__ranges_extensions)`, then there is no ordering problem.

**Comment by ericniebler** [comment]
Also, keep in mind that *no* iterators, old or new, need a member `iterator_category`.

**Comment by CaseyCarter** [comment]
> Also, keep in mind that no iterators, old or new, need a member `iterator_category`.

Which is a critical flaw of my approach. I suppose this part of the spec just can't be supported well by an implementation that does not modify the standard library.

**Comment by ericniebler** [comment]
> I suppose this part of the spec just can't be supported well by an implementation that does not modify the standard library.

That's always been the case. At the very least, we need to add constraints to `std::swap`.
