### ISSUE TITLE
reverse_iterator

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#78]
The binary operator declarations have a lot of redundant constraints that could be simplified:
```
EqualityComparable{I1, I2}
bool operator==(const reverse_iterator<I1>& x,
                const reverse_iterator<I2>& y);

EqualityComparable{I1, I2}
bool operator!=(const reverse_iterator<I1>& x,
                const reverse_iterator<I2>& y);

TotallyOrdered{I1, I2}
bool operator<(const reverse_iterator<I1>& x,
               const reverse_iterator<I2>& y);

TotallyOrdered{I1, I2}
bool operator>(const reverse_iterator<I1>& x,
               const reverse_iterator<I2>& y);

TotallyOrdered{I1, I2}
bool operator<=(const reverse_iterator<I1>& x,
                const reverse_iterator<I2>& y);

TotallyOrdered{I1, I2}
bool operator>=(const reverse_iterator<I1>& x,
                const reverse_iterator<I2>& y);

SizedIteratorRange{I2, I1}
DifferenceType<I2> operator-(const reverse_iterator<I1>& x,
                             const reverse_iterator<I2>& y);

template <class I>
reverse_iterator<I> operator+(DifferenceType<I> n,
                              const reverse_iterator<I>& x);
```
since `reverse_iterator<T>` cannot be so much as referred to unless `T` satisfies the associated constraints of `reverse_iterator`, i.e., is a `BidirectionalIterator`.

* [reverse.iter.cons]/1:

  > *Effects:* Value initializes `current`. Iterator operations applied to the resulting iterator have defined behavior if and only if the corresponding operations are defined on a value-initialized iterator of type `I`. If `I` is a literal type, then this constructor shall be a trivial constructor.

  Since `I` is the type of `current`, it is not possible to satisfy both "value initializes `current`" and "If `I` is literal this constructor is trivial."

  I'm a huge fan of default initialization since I think it makes bugs more apparent than value-initialization, so I would favor declaring this constructor as explicitly defaulted. That said, I know most people don't agree with me so we should probably strike the sentence " If `I` is a literal type, then this constructor shall be a trivial constructor."

* [reverse.iter.op.star]:

  > *Effects:*
  ```
I tmp = current;
return *--tmp;
```

  could be simplified to "Effects: `return *prev(current);`

* [reverse.iter.opref]:

  > Returns: `current`.

  Should be "Returns: `prev(current)`"

**Comment by ericniebler** [comment]
That text is taken directly from the current draft standard. And the Lenexa draft had `= default ` and they made me change it back. If you have an issue with it, you should file a DR.

**Comment by ericniebler** [comment]
> Should be "`Returns: prev(current)`"

I've tried to minimize the superfluous diffs from the current draft standard. If it doesn't need to be changed, I say leave it.

**Comment by CaseyCarter** [comment]
[reverse.iter.cons]/1 from N4527 is:

> Effects: Value initializes current. Iterator operations applied to the resulting iterator have defined behavior if and only if the corresponding operations are defined on a value-initialized iterator of type
Iterator.

It notably does not have the "If `I` is a literal type..." sentence since it's a contradiction for a trivial constructor to value-initialize a subobject: you can't both do something and do nothing. I think that sentence is a vestige of the `reverse_iterator() = default;` formulation.

> > Should be "Returns: prev(current)"

> I've tried to minimize the superfluous diffs from the current draft standard. If it doesn't need to be changed, I say leave it.

N4527 has "Returns: `std::addressof(operator*())`." which won't work for us since our `BidirectionalIterator` isn't required to have a true reference for its `ReferenceType`. "Returns: `current`" is off-by-one since the element denoted by a reverse iterator is `*prev(current)`.

I'll push wording to fix these two correctness issues and leave the redundant constraints in place.
