### ISSUE TITLE
CommonType<void,void>?

### ISSUE THREAD

**Issue by W-E-Brown** [ericniebler/stl2#80]
[concepts.lib.corelang.common]/2 now says:

Let C be `CommonType<T, U>`. Let t1 and t2 be objects of type T, and u1 and u2 be objects of type U.
`Common<T, U>()` is satisfied if and only if
— C(t1) equals C(t2) if and only if t1 equals t2.
— C(u1) equals C(u2) if and only if u1 equals u2.

This suggests that `CommonType<void,void>` is intended to be ill-formed, as there can be no such objects t1, etc.  Such an interpretation seems confirmed by Common's requirements that the following be well-formed:

    CommonType<T, U>( STD::forward<T>(t) );
    CommonType<T, U>( STD::forward<U>(u) );

This seems an important corner case, and I want to be certain this interpretation corresponds to the intended design.  If so, what's the rationale?

**Comment by asutton** [comment]
Define them to be expressions T() and U()?


Andrew Sutton

**Comment by ericniebler** [comment]
If you consider that the primary purpose of the concepts is to constrain generic code -- principally the algorithms -- this doesn't seem surprising or wrong to me. I think of `Common<X,Y>` as answering the question: what can generic code do with two objects of type `X` and `Y`? In that sense, `Common<void,void>` doesn't make sense and should not be satisfied.

> This seems an important corner case

Why do you think so? What algorithm requires this to work?

Meta-discussion: Concepts are different than type traits, which are principally useful in meta-programming -- which along with `static_assert` has until now been used as a poor-man's way of doing concept checking. It creates a false expectation that the concepts behave like type traits would.

A more interesting question is what `common_type_t<void,void>` should be and why. That's a question to be put to LWG.

**Comment by ericniebler** [comment]
EDIT: I now see you're asking specifically about `CommonType`, which is exactly `common_type_t`. So apologies. The fact that `Common`'s syntactic constraints are not satisfied when either `T` or `U` are `void` does not place any constraints on the `common_type` type trait. It's still an issue for LWG to say what `common_type_t<void,void>` should be. But whether it's ill-formed or `void`, the result is the same for `Common<void,void>`: it will not be satisfied.

Sorry for the answer above. You know all that already.

**Comment by ericniebler** [comment]
Closing this. If you still have questions, feel free to reopen.
