### ISSUE TITLE
Possible typos

### ISSUE THREAD

**Issue by W-E-Brown** [ericniebler/stl2#89]
1) There are numerous unnumbered (typically introductory) paragraphs; have a look at the sections specifiying the concepts Constructible, Incrementable, Sentinel, SizedIteratorRange, WeakIterator,  WeaklyIncrementable, as well as the template tagged.  You may want to audit for this throughout.
2) in [output.iterators]/2:  s/algoritm/algorithm/
3) something seems wrong in the para numbering in [alg.tagspec]; shouldn't the para numbers restart with 1?
4) also in [alg.tagspec]:  s/tag::N/tag::X/

**Comment by W-E-Brown** [comment]
5) Also, something seems amiss in [tagged.astuple]; the specialization of tuple_element twice uses N w/out declaring any N.

**Comment by ericniebler** [comment]
Thanks, Walter!
