### ISSUE TITLE
Decomposition rationale is out of sync with the current concept definitions

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#91]
This led to lots of confusion on the last telecon, with people wondering about how the concepts should behave WRT reference types, and whether these were in fact "object" concepts, like the section name seems to suggest.

**Comment by ericniebler** [comment]
I will have to remove the decomposition rationale for the mailing since it no longer accurately reflects the current design.

**Comment by CaseyCarter** [comment]
@CaseyCarter: update the decomposition rationale after the pre-meeting mailing. It doesn't need to be pretty, but it needs to be accurate.

**Comment by ericniebler** [comment]
The decomposition rationale appendix is defunct.
