### ISSUE TITLE
tagged_{pair,tuple}

### ISSUE THREAD

**Issue by W-E-Brown** [ericniebler/stl2#92]
1) Should [tagged.pairs] become [tagged.pair] for symmetry with [tagged.tuple]?  (If so, then [tagged.pairs.creation] ought become [tagged.pair.creation]).

2) Should there be a synopsis subheading at the start of [tagged.pairs]?  I note that [tagged.tuple] has a synopsis subheading, but it is unnumbered and unlabeled. I recommend parallel treatment.

3) Notation such as `tag::min(int)` and `Tag1(V1)` is used several times in these sections, but I am puzzled by this syntax.  For example, section [alg.tagspec] specifies `tag::min` to be a struct with implementation-defined members, yet the parenthesis syntax suggests that it is instead some sort of callable that takes a type argument.  Can the intent of the parenthesized type be clarified, and/or alternate syntax provided?  Or what am I missing?

**Comment by W-E-Brown** [comment]
3') Never mind.  I overlooked that these are intended to be function *types*, rather than the function *calls* I was trying to shoehorn them into. I have a heretical thought: instead of using prose wording such as [tagged.pairs]/1 "Types T1 and T2 shall be tagged types (20.15.2)", how about suitably constraining the corresponding `tagged_pair` template? (And analogously in [tagged.tuple], and perhaps in other places that promulgate requirements in prose rather than in code.  Possibly we should similarly reconsider each unconstrained template.)  Any way, sorry for the noise.

**Comment by CaseyCarter** [comment]
> I have a heretical thought: instead of using prose wording such as [tagged.pairs]/1 "Types `T1` and `T2` shall be tagged types (20.15.2)", how about suitably constraining the corresponding `tagged_pair` template? (And analogously in [tagged.tuple], and perhaps in other places that promulgate requirements in prose rather than in code. Possibly we should similarly reconsider each unconstrained template.)

In principle, I could not agree more: any requirement that can possibly be syntactic should be so. In practice, "tag specifier" and "tagged type" concepts aren't going to be widely useful given the current absence of a specified mapping mechanism from tag specifier to tag getter type - there's currently no way for users to create their own tags. Practicality aside it is [quite simple to implement concepts for `TagSpecifier` and `TaggedType`](https://github.com/CaseyCarter/cmcstl2/compare/master@%7B2%7D...master) and the [necessary wording changes are straightforward as well](https://github.com/ericniebler/stl2/compare/master...CaseyCarter:tag_constraints). @ericniebler, do you think it's useful enough to specify?

**Comment by ericniebler** [comment]
> do you think it's useful enough to specify?

I do. I was probably being too conservative by not specifying the mapping mechanism. It's important for users to be able to define their own tags. Thanks for doing this work Casey. I'll look more closely when I have a sec. (I'm in Russia all week to give a couple of talks.)

**Comment by CaseyCarter** [comment]
To complete the discussion here: direction from LWG during the 20150910 teleconference was to leave the mapping unspecified for now to allow for implementor freedom and possible innovation.
